import { requireConnectorUser } from '../../utils/connectorFabric'
import { organizationContext } from '../../utils/adaptiveFabric'
import { serviceClient } from '../../utils/fleetSupabase'
import { createProofShareToken, hashProofShareToken, proofShareExpiry } from '../../utils/proofShare'

export default defineEventHandler(async event => {
  const user = await requireConnectorUser(event); const context = await organizationContext(user); const sb = serviceClient(); const body = await readBody<any>(event); const action=String(body?.action||''); const values=body?.values||{}; const organizationId=context.membership.organization_id
  if(action==='shadow_experiment') { const {data,error}=await sb.from('outcome_shadow_experiments').insert({organization_id:organizationId,user_id:user.id,app:String(values.app||'portfolio'),capability:String(values.capability||'operate'),objective:String(values.objective||'Improve verified outcomes'),proposal:values.proposal||{},projected_outcome:values.projected_outcome||{},status:'shadow'}).select().single(); if(error)throw createError({statusCode:500,message:'shadow_experiment_failed'}); return {experiment:data,production_changed:false} }
  if(action==='drift_snapshot') { const {data,error}=await sb.from('outcome_drift_snapshots').insert({organization_id:organizationId,user_id:user.id,app:String(values.app||'portfolio'),capability:String(values.capability||'operate'),sources:values.sources||['production','tokens','components','brand','motion','connected-tools'],findings:values.findings||[],status:'queued'}).select().single(); if(error)throw createError({statusCode:500,message:'drift_snapshot_failed'}); return {snapshot:data} }
  if(action==='proof_share') { const proofId=String(values.proof_id||''); const {data:proof}=await sb.from('execution_proof_envelopes').select('id').eq('id',proofId).eq('organization_id',organizationId).maybeSingle(); if(!proof)throw createError({statusCode:404,message:'proof_not_found'}); const token=createProofShareToken(); const token_hash=hashProofShareToken(token); const expiresAt=proofShareExpiry(values.days); const {data,error}=await sb.from('proof_share_links').insert({organization_id:organizationId,proof_id:proofId,token_hash,audience:String(values.audience||'authorized reviewer').slice(0,120),scopes:['proof:read'],expires_at:expiresAt,created_by:user.id}).select('id,expires_at,audience').single(); if(error)throw createError({statusCode:500,message:'proof_share_failed'}); return {share:data,url:`${getRequestURL(event).origin}/proof/${token}`} }
  throw createError({statusCode:400,message:'unsupported_outcome_intelligence_action'})
})
