<script setup lang="ts">
const supabase = useSupabaseClient<any>()
const state = ref<any>(null), loading = ref(false), error = ref('')
async function load() {
  loading.value = true; error.value = ''
  try { const { data: { session } } = await supabase.auth.getSession(); state.value = await $fetch('/api/connectors/optimize', { headers: session?.access_token ? { authorization: `Bearer ${session.access_token}` } : {} }) }
  catch (e: any) { error.value = e?.data?.message || e?.message || 'Connector value could not be calculated.' }
  finally { loading.value = false }
}
onMounted(load)
</script>
<template><section class="optimizer"><div class="optimizer-copy"><span>Autonomous portfolio optimization</span><h2>Connect less. Route better.</h2><p>Madeus continuously scores realized reliability, quality, marginal cost, access readiness, and policy incidents. Recommendations never grant or revoke access without confirmation.</p><div v-if="state" class="summary"><b>{{state.summary.prefer}} preferred</b><b>{{state.summary.observe}} observing</b><b>{{state.summary.deprioritize}} below threshold</b></div></div><div class="rankings"><div class="rankings-head"><b>Highest-value routes</b><button @click="load">{{loading?'Scoring…':'Refresh evidence'}}</button></div><p v-if="error" class="error">{{error}}</p><div v-else-if="!state" class="loading">Calculating portfolio value…</div><article v-for="item in state?.recommendations?.slice(0,5) || []" :key="item.provider"><div><b>{{item.provider}}</b><span>{{item.recommendation}}</span></div><strong>{{item.score}}</strong><i><b :style="{width:`${item.score}%`}"/></i><small>{{Math.round(item.reliability*100)}}% reliable · {{Math.round(item.averageQuality*100)}}% quality · ${{item.averageCostUsd.toFixed(3)}}/run</small></article><NuxtLink to="/orchestrators/optimize-orchestrator">Open routing intelligence →</NuxtLink></div></section></template>
<style scoped>.optimizer{display:grid;grid-template-columns:1fr 1fr;gap:28px;margin:18px 0 28px;padding:25px;border:1px solid #dedbea;border-radius:16px;background:linear-gradient(120deg,#fff 50%,#f7f6fc)}.optimizer-copy>span{font-size:9px;font-weight:750;letter-spacing:.14em;text-transform:uppercase;color:#6557d8}.optimizer-copy h2{margin-top:7px;font-size:23px;letter-spacing:-.04em}.optimizer-copy p{max-width:560px;margin-top:9px;font-size:11px;line-height:1.65;color:#666}.summary{display:flex;gap:6px;flex-wrap:wrap;margin-top:17px}.summary b{padding:6px 8px;border-radius:99px;background:#f0eeff;font-size:8px;color:#594db8}.rankings{padding:14px;border:1px solid #e4e4e4;border-radius:12px;background:#fff}.rankings-head{display:flex;align-items:center;justify-content:space-between;font-size:10px}.rankings-head button{border:1px solid #ddd;border-radius:7px;padding:7px 9px;background:#fff;font-size:8px}.rankings article{display:grid;grid-template-columns:1fr auto;gap:5px;padding:9px 0;border-bottom:1px solid #eee}.rankings article div b,.rankings article div span{display:block;font-size:9px}.rankings article div span{margin-top:2px;color:#6557d8;font-size:7px;text-transform:uppercase}.rankings article strong{font-size:16px}.rankings article i{grid-column:1/-1;height:3px;border-radius:99px;background:#eee;overflow:hidden}.rankings article i b{display:block;height:100%;background:#6557d8}.rankings article small{grid-column:1/-1;font-size:7px;color:#999}.rankings>a{display:block;margin-top:10px;color:#5549b7;font-size:9px;text-decoration:none}.error,.loading{padding:20px 0;text-align:center;font-size:9px;color:#999}.error{color:#a63d3d}@media(max-width:800px){.optimizer{grid-template-columns:1fr}}</style>
