import { createHash } from 'node:crypto'
import { createError } from 'h3'
import { organizationContext, requireOrgAdmin } from './adaptiveFabric'
import { serviceClient } from './fleetSupabase'

export type AutonomyMode='observe'|'prepare'|'execute_reversible'|'exception_only'
export type OperatingDomain='workforce'|'finance'|'tax'|'security'|'procurement'|'crm'|'renewal'|'payment'|'legal'
export type CompiledOperatingAction={domain:OperatingDomain;action_type:string;title:string;payload:Record<string,any>;dependency_keys:string[];risk:'low'|'medium'|'high'|'critical';reversible:boolean;external_effect:boolean;status:'planned'|'ready'|'approval_required';due_at:string|null;owner_role:string;idempotency_key:string;evidence:Record<string,any>}
const ALWAYS_GATED=new Set(['send_payment','file_tax_return','change_bank_details','sign_contract','issue_contract','hire_employee','terminate_employee','change_compensation','provision_privileged_access','send_legal_notice'])
const normalize=(value:unknown)=>String(value||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
function stable(value:any):string{if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;if(value&&typeof value==='object')return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stable(value[k])}`).join(',')}}`;return JSON.stringify(value)}
export function fabricDigest(value:any){return createHash('sha256').update(stable(value)).digest('hex')}
function date(value:any){if(!value)return null;const parsed=new Date(value);return Number.isNaN(parsed.getTime())?null:parsed.toISOString()}
function key(contractId:string,version:number,domain:string,type:string,payload:any){return fabricDigest({contractId,version,domain,type,payload})}
function safeStatus(type:string,external:boolean,reversible:boolean,mode:AutonomyMode){if(ALWAYS_GATED.has(type)||external||!reversible)return'approval_required' as const;return['execute_reversible','exception_only'].includes(mode)?'ready' as const:'planned' as const}
function clauseText(content:any){return(content?.clauses||[]).map((c:any)=>`${c.id||''} ${c.heading||''} ${c.text||''}`).join('\n').toLowerCase()}
function add(out:CompiledOperatingAction[],base:Omit<CompiledOperatingAction,'idempotency_key'|'status'|'evidence'>,contractId:string,version:number,mode:AutonomyMode,source:string[]){
 const idempotency_key=key(contractId,version,base.domain,base.action_type,base.payload);out.push({...base,idempotency_key,status:safeStatus(base.action_type,base.external_effect,base.reversible,mode),evidence:{contract_id:contractId,version,source_clauses:source,compiler:'contract-ops-v1'}})
}
export function compileContractOperations(input:{contract:any;version:any;mode?:AutonomyMode}){
 const {contract,version}=input,mode=input.mode||'prepare';const text=clauseText(version?.content);const facts=contract?.matter_data||{};const clauses=version?.content?.clauses||[];const ids=(...terms:string[])=>clauses.filter((c:any)=>terms.some(t=>`${c.id} ${c.heading} ${c.text}`.toLowerCase().includes(t))).map((c:any)=>String(c.id));const actions:CompiledOperatingAction[]=[];const cid=String(contract.id),v=Number(version.version||contract.current_version||1)
 const starts=date(facts.start_date||facts.effective_date),ends=date(facts.end_date||facts.expiration_date),paymentDue=date(facts.payment_due||facts.invoice_due)
 if(/employ|employee|worker|onboard|compensation|salary/.test(text+` ${contract.category}`)){
  add(actions,{domain:'workforce',action_type:'prepare_onboarding',title:'Create role and onboarding case',payload:{person:facts.party_b||contract.counterparty_name,role:facts.role_title,start_date:starts},dependency_keys:[],risk:'medium',reversible:true,external_effect:false,due_at:starts,owner_role:'accountable_people_owner'},cid,v,mode,ids('employ','services','term'))
  add(actions,{domain:'workforce',action_type:'change_compensation',title:'Authorize payroll and compensation terms',payload:{compensation:facts.compensation||facts.fees||null,currency:facts.currency||null},dependency_keys:[],risk:'critical',reversible:false,external_effect:true,due_at:starts,owner_role:'compensation_authority'},cid,v,mode,ids('compensation','fees','payment'))
  add(actions,{domain:'security',action_type:'provision_privileged_access',title:'Authorize least-privilege access package',payload:{role:facts.role_title,starts_at:starts,ends_at:ends},dependency_keys:[],risk:'high',reversible:true,external_effect:true,due_at:starts,owner_role:'security_authority'},cid,v,mode,ids('confidential','security','services'))
 }
 if(/fee|payment|invoice|compensation|revenue|royalt|consideration/.test(text)){
  add(actions,{domain:'finance',action_type:'create_receivable_schedule',title:'Create revenue and invoice schedule',payload:{amount:facts.fees||facts.compensation||facts.amount||null,currency:facts.currency||'USD',due_at:paymentDue},dependency_keys:[],risk:'medium',reversible:true,external_effect:false,due_at:paymentDue,owner_role:'finance_control_owner'},cid,v,mode,ids('fee','payment','invoice','royalt'))
  add(actions,{domain:'payment',action_type:'send_payment',title:'Authorize payment only when due and evidenced',payload:{amount:facts.fees||facts.compensation||facts.amount||null,currency:facts.currency||'USD',counterparty:contract.counterparty_name,due_at:paymentDue,bank_details_from_contract:false},dependency_keys:[],risk:'critical',reversible:false,external_effect:true,due_at:paymentDue,owner_role:'payment_authority'},cid,v,mode,ids('payment','fee','invoice'))
  add(actions,{domain:'tax',action_type:'prepare_tax_treatment',title:'Prepare jurisdictional tax treatment and evidence pack',payload:{jurisdiction:contract.jurisdiction,amount:facts.fees||facts.compensation||facts.amount||null,filing_disabled:true},dependency_keys:[],risk:'high',reversible:true,external_effect:false,due_at:paymentDue,owner_role:'qualified_tax_reviewer'},cid,v,mode,ids('tax','payment','fee'))
 }
 if(/confidential|privacy|personal data|security|breach|data protection/.test(text))add(actions,{domain:'security',action_type:'create_security_control_plan',title:'Apply data, confidentiality, and incident controls',payload:{jurisdiction:contract.jurisdiction,counterparty:contract.counterparty_name,access:'least_privilege'},dependency_keys:[],risk:'high',reversible:true,external_effect:false,due_at:starts,owner_role:'security_control_owner'},cid,v,mode,ids('confidential','privacy','security','data'))
 if(/vendor|supplier|service|deliverable|statement of work|procure/.test(text+` ${contract.category}`)){
  add(actions,{domain:'procurement',action_type:'create_supplier_record',title:'Create governed supplier and deliverables record',payload:{counterparty:contract.counterparty_name,services:facts.services||null},dependency_keys:[],risk:'medium',reversible:true,external_effect:false,due_at:starts,owner_role:'procurement_control_owner'},cid,v,mode,ids('service','deliverable','vendor'))
  add(actions,{domain:'crm',action_type:'sync_relationship_commitments',title:'Sync relationship commitments and success milestones',payload:{counterparty:contract.counterparty_name,services:facts.services||null},dependency_keys:[],risk:'low',reversible:true,external_effect:false,due_at:starts,owner_role:'relationship_owner'},cid,v,mode,ids('service','deliverable','term'))
 }
 if(/term|renew|expire|termination|notice/.test(text))add(actions,{domain:'renewal',action_type:'monitor_renewal_and_notice',title:'Monitor renewal, termination, and notice windows',payload:{effective_at:starts,expires_at:ends,notice_period:facts.notice_period||null,auto_renewal:facts.auto_renewal||null},dependency_keys:[],risk:'medium',reversible:true,external_effect:false,due_at:ends,owner_role:'contract_owner'},cid,v,mode,ids('term','renew','termination','notice'))
 add(actions,{domain:'legal',action_type:'verify_execution_finality',title:'Verify identity, authority, signature, delivery, timestamp, and archive receipts',payload:{content_digest:version.content_digest,required:['identity','authority','signature','delivery','timestamp','archive']},dependency_keys:[],risk:'high',reversible:true,external_effect:false,due_at:null,owner_role:'legal_control_owner'},cid,v,mode,ids('signature','entire agreement'))
 const compiler_digest=fabricDigest({contract_id:cid,version:v,content_digest:version.content_digest,mode,actions:actions.map(a=>({domain:a.domain,type:a.action_type,key:a.idempotency_key}))})
 return{compiler_digest,actions,summary:{total:actions.length,ready:actions.filter(a=>a.status==='ready').length,approval_required:actions.filter(a=>a.status==='approval_required').length,domains:[...new Set(actions.map(a=>a.domain))],missing_operational_facts:[!starts&&'effective_date',!ends&&/term|renew|expire/.test(text)&&'expiration_date',!paymentDue&&/payment|invoice/.test(text)&&'payment_due'].filter(Boolean)},controls:{no_silent_external_effects:true,no_bank_details_from_contract:true,professional_roles_preserved:true,privilege_scoped:true,idempotent:true}}
}

export function simulateNegotiationTwin(contract:any,version:any){const base=compileContractOperations({contract,version,mode:'observe'});const critical=base.actions.filter(a=>a.risk==='critical').length;const missing=base.summary.missing_operational_facts.length;const scenarios=[{name:'base',operational_actions:base.actions.length,exceptions:base.summary.approval_required},{name:'counterparty_favorable',operational_actions:base.actions.length+Math.ceil(critical/2),exceptions:base.summary.approval_required+critical},{name:'early_termination',operational_actions:base.actions.filter(a=>['renewal','payment','legal'].includes(a.domain)).length,exceptions:critical+1}];return{scenarios,affected_operations:base.summary.domains,recommendation:{resolve_missing_facts:base.summary.missing_operational_facts,retain_authority_gates:critical>0,compare_total_obligation_cost:true},lower_confidence:Math.max(.2,Math.min(.9,.9-missing*.15-critical*.05)),run_digest:fabricDigest({contract:contract.id,version:version.version,scenarios})}}
export function analyzeClauseGenome(contract:any,version:any){const clauses=version?.content?.clauses||[];return clauses.map((c:any)=>({clause_type:normalize(c.heading||c.id).slice(0,80),structural_features:{word_band:Math.ceil(String(c.text||'').split(/\s+/).length/50)*50,has_dates:/\b\d{4}\b|days|months|years/i.test(c.text||''),has_money:/\$|usd|fee|payment/i.test(c.text||''),has_discretion:/sole discretion|may determine/i.test(c.text||''),status:c.status||'draft'},raw_text_exported:false,pattern_digest:fabricDigest({organization_scope:true,heading:normalize(c.heading),features:String(c.text||'').replace(/[A-Za-z]+/g,'w').slice(0,500)})}))}
export function detectContractConflicts(contract:any,version:any){const entities=[contract.counterparty_name,contract.matter_data?.party_a,contract.matter_data?.party_b].filter(Boolean).map(normalize);const text=clauseText(version.content);const findings:any[]=[];if(!/authority|authorized|power/.test(text))findings.push({type:'signer_authority_not_expressed',severity:'attention'});if(!contract.jurisdiction)findings.push({type:'governing_law_missing',severity:'blocked'});return{normalized_entities:[...new Set(entities)],authority_findings:findings,obligation_collisions:[],status:findings.some(x=>x.severity==='blocked')?'blocked':findings.length?'attention':'clear',check_digest:fabricDigest({entities:[...new Set(entities)],findings,contract:contract.id,version:version.version})}}

export async function autonomyDashboard(user:any){const context=await organizationContext(user),org=context.membership.organization_id,sb=serviceClient();const [contracts,workflows,actions,twins,conflicts,finality]=await Promise.all([sb.from('legal_contracts').select('id,title,lifecycle,current_version,jurisdiction,counterparty_name,updated_at').eq('organization_id',org).order('updated_at',{ascending:false}).limit(100),sb.from('autonomous_operating_workflows').select('*').eq('organization_id',org).order('created_at',{ascending:false}).limit(50),sb.from('autonomous_operating_actions').select('*').eq('organization_id',org).order('created_at',{ascending:false}).limit(300),sb.from('negotiation_twin_runs').select('*').eq('organization_id',org).order('created_at',{ascending:false}).limit(20),sb.from('legal_conflict_checks').select('*').eq('organization_id',org).order('created_at',{ascending:false}).limit(20),sb.from('execution_finality_receipts').select('*').eq('organization_id',org).order('created_at',{ascending:false}).limit(100)]);const rows=(x:any)=>x.error?[]:(x.data||[]),a=rows(actions);return{organization:context.membership.organization,role:context.membership.role,contracts:rows(contracts),workflows:rows(workflows),actions:a,twins:rows(twins),conflicts:rows(conflicts),finality:rows(finality),summary:{workflows:rows(workflows).length,ready:a.filter((x:any)=>x.status==='ready').length,exceptions:a.filter((x:any)=>['approval_required','blocked'].includes(x.status)).length,completed:a.filter((x:any)=>x.status==='completed').length,external_gated:a.filter((x:any)=>x.external_effect&&x.status==='approval_required').length},controls:{external_actions:'explicit_authority_required',safe_execution:'idempotent_reversible_only',professional_review:'retained_when_required',privilege:'matter_scoped_no_training'}}}

export async function executeAutonomyAction(user:any,input:any){const context=await organizationContext(user),org=context.membership.organization_id,sb=serviceClient(),action=String(input?.action||''),values=input?.values||{};if(action==='compile_operations'){
  requireOrgAdmin(context);const {data:contract}=await sb.from('legal_contracts').select('*').eq('id',values.contract_id).eq('organization_id',org).maybeSingle();if(!contract)throw createError({statusCode:404,message:'contract_not_found'});if(!['signed','active'].includes(contract.lifecycle)&&!values.allow_pre_signature_simulation)throw createError({statusCode:409,message:'signed_or_active_contract_required'});const {data:version}=await sb.from('legal_contract_versions').select('*').eq('contract_id',contract.id).eq('version',contract.current_version).single();const mode:AutonomyMode=['observe','prepare','execute_reversible','exception_only'].includes(values.mode)?values.mode:'prepare';const compiled=compileContractOperations({contract,version,mode});const {data:workflow,error}=await sb.rpc('compile_contract_operations',{p_organization_id:org,p_contract_id:contract.id,p_source_version:contract.current_version,p_compiler_digest:compiled.compiler_digest,p_autonomy_mode:mode,p_controls:compiled.controls,p_actions:compiled.actions,p_created_by:user.id});if(error)throw createError({statusCode:500,message:'contract_operations_compile_failed'});await sb.from('matter_information_barriers').upsert({organization_id:org,contract_id:contract.id,classification:'confidential',allowed_roles:['organization_owner','legal_control_owner','contract_owner'],selective_disclosure:{operations_receive:'minimum_necessary_fields',raw_contract:false},created_by:user.id},{onConflict:'organization_id,contract_id'});await sb.from('capability_activation_proofs').upsert({capability:'business_os:contract_to_operations',invocation_key:`${org}:${compiled.compiler_digest}`,invoked:true,effect:compiled.actions.length>0,outcome:mode==='observe'?'graph_observed':'operating_graph_materialized',metrics:{contract_id:contract.id,version:contract.current_version,domains:compiled.summary.domains,actions:compiled.summary.total,approval_required:compiled.summary.approval_required,mode}},{onConflict:'capability,invocation_key'});return{workflow,compiled}}
 if(['simulate_negotiation','check_conflicts','learn_clause_genome'].includes(action)){const {data:contract}=await sb.from('legal_contracts').select('*').eq('id',values.contract_id).eq('organization_id',org).maybeSingle();if(!contract)throw createError({statusCode:404,message:'contract_not_found'});const {data:version}=await sb.from('legal_contract_versions').select('*').eq('contract_id',contract.id).eq('version',contract.current_version).single();if(action==='simulate_negotiation'){const twin=simulateNegotiationTwin(contract,version);const {data,error}=await sb.from('negotiation_twin_runs').upsert({organization_id:org,contract_id:contract.id,version:version.version,...twin,created_by:user.id},{onConflict:'contract_id,version,run_digest'}).select().single();if(error)throw createError({statusCode:500,message:'negotiation_twin_failed'});return{twin:data}}if(action==='check_conflicts'){const check=detectContractConflicts(contract,version);const {data,error}=await sb.from('legal_conflict_checks').insert({organization_id:org,contract_id:contract.id,...check,created_by:user.id}).select().single();if(error)throw createError({statusCode:500,message:'conflict_check_failed'});return{check:data}}const patterns=analyzeClauseGenome(contract,version);for(const p of patterns)await sb.from('clause_genome_patterns').upsert({organization_id:org,...p,approved_positions:{},fallback_ladder:[],aggregated_outcomes:{},sample_size:1},{onConflict:'organization_id,clause_type,pattern_digest'});return{patterns}}
 if(action==='activate_workflow'){requireOrgAdmin(context);const {data,error}=await sb.from('autonomous_operating_workflows').update({state:'active',updated_at:new Date().toISOString()}).eq('id',values.workflow_id).eq('organization_id',org).select().single();if(error)throw createError({statusCode:404,message:'workflow_not_found'});return{workflow:data}}
 if(action==='execute_safe_action'){requireOrgAdmin(context);const {data:row}=await sb.from('autonomous_operating_actions').select('*').eq('id',values.action_id).eq('organization_id',org).maybeSingle();if(!row)throw createError({statusCode:404,message:'operating_action_not_found'});if(row.external_effect||!row.reversible||ALWAYS_GATED.has(row.action_type))throw createError({statusCode:403,message:'explicit_external_authority_required'});if(!['ready','approved'].includes(row.status))throw createError({statusCode:409,message:'action_not_ready'});const evidence={executor:'autonomous_business_fabric',effect:'internal_control_record_materialized',idempotency_key:row.idempotency_key,completed_at:new Date().toISOString()};const {data,error}=await sb.from('autonomous_operating_actions').update({status:'completed',evidence:{...(row.evidence||{}),...evidence},outcome:{status:'completed',external_effect:false},completed_at:evidence.completed_at,updated_at:evidence.completed_at}).eq('id',row.id).eq('status',row.status).select().single();if(error)throw createError({statusCode:409,message:'action_claim_conflict'});return{action:data}}
 throw createError({statusCode:400,message:'unsupported_autonomy_action'})
}
