import {describe,expect,it} from 'vitest'
import {analyzeClauseGenome,compileContractOperations,detectContractConflicts,simulateNegotiationTwin} from './autonomousBusinessFabric'
const contract={id:'contract-1',current_version:2,lifecycle:'signed',category:'employment',jurisdiction:'California',counterparty_name:'Alex Rivera',matter_data:{party_a:'Acme',party_b:'Alex Rivera',role_title:'Designer',start_date:'2026-08-01',compensation:'120000 USD',payment_due:'2026-08-15',notice_period:'30 days'}}
const version={version:2,content_digest:'abc123',content:{clauses:[{id:'services',heading:'Services and Employment',text:'Employee provides design services.'},{id:'fees',heading:'Compensation and Payment',text:'Compensation is paid monthly after invoice.'},{id:'privacy',heading:'Confidentiality and Security',text:'Confidential information and personal data must be secured.'},{id:'term',heading:'Term and Termination',text:'The term renews annually and requires 30 days notice.'},{id:'signature',heading:'Authority',text:'Each authorized signer has authority.'}]}}
describe('contract-to-operations compiler',()=>{
 it('compiles a deterministic cross-domain graph and gates consequential effects',()=>{const a=compileContractOperations({contract,version,mode:'execute_reversible'}),b=compileContractOperations({contract,version,mode:'execute_reversible'});expect(a.compiler_digest).toBe(b.compiler_digest);expect(a.summary.domains).toEqual(expect.arrayContaining(['workforce','finance','tax','security','procurement','crm','renewal','payment','legal']));expect(a.actions.find(x=>x.action_type==='send_payment')?.status).toBe('approval_required');expect(a.actions.find(x=>x.action_type==='create_receivable_schedule')?.status).toBe('ready');expect(new Set(a.actions.map(x=>x.idempotency_key)).size).toBe(a.actions.length)})
 it('never exports raw clause text into the clause genome',()=>{const patterns=analyzeClauseGenome(contract,version);expect(patterns.every((x:{raw_text_exported:boolean})=>x.raw_text_exported===false)).toBe(true);expect(JSON.stringify(patterns)).not.toContain('Employee provides design services')})
 it('simulates operational consequences and checks authority',()=>{const twin=simulateNegotiationTwin(contract,version),conflicts=detectContractConflicts(contract,version);expect(twin.scenarios).toHaveLength(3);expect(twin.affected_operations).toContain('payment');expect(conflicts.status).toBe('clear')})
})
