import {createDecipheriv,createHash,createHmac,timingSafeEqual} from 'node:crypto'
import {serviceClient} from './fleetSupabase'

const stable=(v:any):string=>Array.isArray(v)?`[${v.map(stable).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(',')}}`:JSON.stringify(v)
const digest=(v:any)=>createHash('sha256').update(stable(v)).digest('hex')
export const canReviseExecutionInput=(existing:any,nextDigest:string)=>!existing?.request_digest||existing.request_digest===nextDigest||(existing.state==='failed'&&String(existing.error_code||'').startsWith('missing_provider_input:'))
export const PROVIDER_ALIASES:Record<string,string[]>= {banking:['plaid','stripe'],payroll:['gusto'],hris:['gusto'],esign:['docusign'],tax:['avalara'],facilitator:['openai','anthropic']}
export const expandConnectedProviders=(providers:string[])=>[...new Set(providers.flatMap(p=>[p,...Object.entries(PROVIDER_ALIASES).filter(([,vendors])=>vendors.includes(p)).map(([domain])=>domain)]))]
function decryptProviderSecret(value:string){const raw=process.env.CONNECTOR_VAULT_KEY||'';if(!raw)throw new Error('connector_vault_not_configured');const [iv,tag,body]=value.split('.'),key=createHash('sha256').update(raw).digest(),decipher=createDecipheriv('aes-256-gcm',key,Buffer.from(iv,'base64url'));decipher.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([decipher.update(Buffer.from(body,'base64url')),decipher.final()]).toString('utf8')}
export function decodeCredential(row:any){const raw=decryptProviderSecret(row.access_token_ciphertext);if(row.metadata?.credential_type==='credential_bundle')return JSON.parse(raw);return{api_key:raw,access_token:raw}}
const required=(input:any,fields:string[])=>{const missing=fields.filter(k=>input?.[k]===undefined||input?.[k]===null||input?.[k]==='');if(missing.length)throw new Error(`missing_provider_input:${missing.join(',')}`)}
const objectValue=(value:any)=>typeof value==='string'?JSON.parse(value):value
const form=(value:Record<string,any>)=>{const out=new URLSearchParams();for(const [k,v] of Object.entries(value))if(v!==undefined&&v!==null)out.set(k,String(v));return out}

export function buildProviderRequest(provider:string,operation:string,input:any,credential:any,idempotencyKey:string){
 if(provider==='stripe'){
  const headers={authorization:`Bearer ${credential.api_key}`,'idempotency-key':idempotencyKey}
  if(operation==='send_payment'){const p=input.stripe_payout||input;required(p,['amount','currency']);return{url:'https://api.stripe.com/v1/payouts',method:'POST',headers,body:form({amount:p.amount,currency:p.currency,description:p.description,method:p.method,destination:p.destination}),finality:'webhook',refPath:'id'}}
  if(operation==='issue_credit'){const p=input.refund||input;required(p,['payment_intent']);return{url:'https://api.stripe.com/v1/refunds',method:'POST',headers,body:form({payment_intent:p.payment_intent,amount:p.amount,reason:p.reason}),finality:'webhook',refPath:'id'}}
  if(operation==='prepare_invoice'){required(input,['customer']);return{url:'https://api.stripe.com/v1/invoices',method:'POST',headers,body:form({customer:input.customer,description:input.description,auto_advance:false}),finality:'read_after_write',refPath:'id'}}
 }
 if(provider==='docusign'&&['issue_contract','sign_contract','send_renewal_notice'].includes(operation)){required(credential,['access_token','account_id','base_url']);required(input,['envelope']);const base=String(credential.base_url).replace(/\/$/,'');if(!/^https:\/\/(demo\.)?docusign\.net$/i.test(base))throw new Error('invalid_docusign_base_url');return{url:`${base}/restapi/v2.1/accounts/${encodeURIComponent(credential.account_id)}/envelopes`,method:'POST',headers:{authorization:`Bearer ${credential.access_token}`},body:{...objectValue(input.envelope),status:'sent'},finality:'webhook',refPath:'envelopeId'}}
 if(provider==='gusto'){
  const base=String(credential.base_url||'');if(!['https://api.gusto-demo.com','https://api.gusto.com'].includes(base))throw new Error('invalid_gusto_base_url');const headers={authorization:`Bearer ${credential.access_token}`}
  if(operation==='prepare_employee_record'){required(input,['employee']);return{url:`${base}/v1/companies/${encodeURIComponent(credential.company_id)}/employees`,method:'POST',headers,body:objectValue(input.employee),finality:'read_after_write',refPath:'uuid'}}
  if(operation==='prepare_payroll_run'){required(input,['payroll_id','payroll']);return{url:`${base}/v1/companies/${encodeURIComponent(credential.company_id)}/payrolls/${encodeURIComponent(input.payroll_id)}`,method:'PUT',headers,body:objectValue(input.payroll),finality:'read_after_write',refPath:'payroll_uuid'}}
  if(operation==='submit_payroll'){required(input,['payroll_id']);return{url:`${base}/v1/companies/${encodeURIComponent(credential.company_id)}/payrolls/${encodeURIComponent(input.payroll_id)}/submit`,method:'PUT',headers,body:{},finality:'read_after_write',refPath:'payroll_uuid'}}
 }
 if(provider==='avalara'&&['prepare_tax_return','reconcile_tax_base'].includes(operation)){const base=String(credential.base_url||'');if(!['https://sandbox-rest.avatax.com','https://rest.avatax.com'].includes(base))throw new Error('invalid_avalara_base_url');required(input,['transaction']);return{url:`${base}/api/v2/companies/${encodeURIComponent(credential.company_code)}/transactions/create`,method:'POST',headers:{authorization:`Basic ${Buffer.from(`${credential.account_id}:${credential.license_key}`).toString('base64')}`},body:{...objectValue(input.transaction),commit:false},finality:'read_after_write',refPath:'id'}}
 throw new Error(provider==='avalara'&&operation==='file_tax_return'?'statutory_filing_provider_or_professional_required':'unsupported_provider_operation')
}

async function call(request:any){return await $fetch<any>(request.url,{method:request.method,headers:{accept:'application/json','content-type':request.body instanceof URLSearchParams?'application/x-www-form-urlencoded':'application/json',...request.headers},body:request.body,timeout:45000})}
async function plaidTransfer(operation:string,input:any,c:any,key:string){if(operation!=='send_payment')throw new Error('unsupported_provider_operation');required(input,['access_token','account_id','amount','legal_name']);const base=c.environment==='production'?'https://production.plaid.com':'https://sandbox.plaid.com';const common={client_id:c.client_id,secret:c.secret};const authorization:any=await $fetch(`${base}/transfer/authorization/create`,{method:'POST',body:{...common,access_token:input.access_token,account_id:input.account_id,type:input.type||'credit',network:input.network||'ach',amount:String(input.amount),ach_class:input.ach_class||'ccd',user:{legal_name:input.legal_name,email_address:input.email_address},idempotency_key:key.slice(0,50)},timeout:45000});if(authorization?.authorization?.decision!=='approved')throw new Error(`plaid_transfer_${authorization?.authorization?.decision||'not_approved'}`);return await $fetch<any>(`${base}/transfer/create`,{method:'POST',body:{...common,access_token:input.access_token,account_id:input.account_id,authorization_id:authorization.authorization.id,description:String(input.description||'PAYMENT').slice(0,10),metadata:{saga_step:input.step_id||''}},timeout:45000})}

async function facilitate(account:any,operation:string,input:any,key:string){const c=decodeCredential(account);if(account.provider!=='openai')throw new Error('facilitator_unavailable');const schema={type:'object',additionalProperties:false,properties:{summary:{type:'string'},evidence:{type:'array',items:{type:'string'}},exceptions:{type:'array',items:{type:'string'}},recommended_input:{type:'object',additionalProperties:true}},required:['summary','evidence','exceptions','recommended_input']};return await $fetch<any>('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${c.api_key}`,'idempotency-key':key},body:{model:'gpt-5.6',store:false,input:`Prepare non-binding operational work for ${operation}. Never claim execution, legal/tax correctness, signature, filing, payroll submission, or money movement. Return evidence gaps and exceptions. Input: ${JSON.stringify(input).slice(0,12000)}`,text:{format:{type:'json_schema',name:'business_facilitation',strict:true,schema}}},timeout:45000})}

export async function executeProviderStep(body:any){
 const sb=serviceClient();const {data:step}=await sb.from('agentic_business_saga_steps').select('*').eq('id',body.step_id).eq('saga_id',body.saga_id).maybeSingle();if(!step||step.state!=='claimed'||step.idempotency_key!==body.idempotency_key)throw new Error('claimed_step_contract_mismatch')
 const {data:saga}=await sb.from('agentic_business_sagas').select('*').eq('id',step.saga_id).maybeSingle();const {data:agent}=await sb.from('business_function_agents').select('*').eq('id',saga?.agent_id).maybeSingle();if(!saga||!agent)throw new Error('saga_agent_not_found')
 if(step.external_effect){const {data:approval}=await sb.from('approvals').select('status').eq('id',step.approval_id).maybeSingle();const {data:authority}=await sb.from('organizational_authority_credentials').select('id').eq('organization_id',saga.organization_id).eq('status','active').in('subject_ref',[agent.agent_key,`agent:${agent.agent_key}`]).contains('scopes',[step.authority_scope]).lte('valid_from',new Date().toISOString()).or(`valid_until.is.null,valid_until.gt.${new Date().toISOString()}`).limit(1).maybeSingle();if(approval?.status!=='approved'||!authority)throw new Error('approval_and_active_authority_required')}
 const requested=step.external_effect?(PROVIDER_ALIASES[step.connector_provider]||[step.connector_provider]):PROVIDER_ALIASES.facilitator;const {data:accounts}=await sb.from('connector_accounts').select('*').eq('organization_id',saga.organization_id).eq('status','connected').in('provider',requested);const desiredEnvironment=String(step.input?.environment||'sandbox'),account=(accounts||[]).filter((row:any)=>row.environment===desiredEnvironment).sort((a:any,b:any)=>requested.indexOf(a.provider)-requested.indexOf(b.provider))[0];if(!account)throw new Error(`connected_${desiredEnvironment}_provider_required:${requested.join('|')}`)
 const requestDigest=digest({provider:account.provider,operation:step.operation,input:step.input,idempotency_key:step.idempotency_key});const {data:existing}=await sb.from('business_provider_executions').select('*').eq('connector_account_id',account.id).eq('idempotency_key',step.idempotency_key).maybeSingle();if(!canReviseExecutionInput(existing,requestDigest))throw new Error('idempotency_payload_mismatch');if(existing?.state==='verified')return{ok:true,external_ref:existing.external_ref,receipt_digest:existing.receipt_digest,replayed:true}
 const {data:execution,error}=await sb.from('business_provider_executions').upsert({organization_id:saga.organization_id,saga_id:saga.id,step_id:step.id,connector_account_id:account.id,provider:account.provider,operation:step.operation,idempotency_key:step.idempotency_key,request_digest:requestDigest,state:'started'},{onConflict:'connector_account_id,idempotency_key'}).select().single();if(error)throw new Error('provider_execution_ledger_failed')
 try{let response:any,finality='webhook';if(!step.external_effect){response=await facilitate(account,step.operation,step.input,step.idempotency_key);finality='read_after_write'}else if(account.provider==='plaid'){response=await plaidTransfer(step.operation,{...step.input,step_id:step.id},decodeCredential(account),step.idempotency_key)}else{const request=buildProviderRequest(account.provider,step.operation,step.input,decodeCredential(account),step.idempotency_key);response=await call(request);finality=request.finality}const externalRef=String(response?.id||response?.envelopeId||response?.payroll_uuid||response?.transfer?.id||response?.authorization?.id||response?.request_id||response?.output?.[0]?.id||'');if(!externalRef)throw new Error('provider_response_missing_reference');const receiptDigest=digest({execution_id:execution.id,provider:account.provider,external_ref:externalRef,response_status:response?.status||response?.transfer?.status||'accepted'});const pending=finality==='webhook';await sb.from('business_provider_executions').update({state:pending?'provider_pending':'verified',external_ref:externalRef,receipt_digest:receiptDigest,response_meta:{status:response?.status||response?.transfer?.status||'accepted',request_id:response?.request_id||null},verified_at:pending?null:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',execution.id);return{ok:true,external_ref:externalRef,receipt_digest:receiptDigest,pending_finality:pending,provider:account.provider}}
 catch(error:any){await sb.from('business_provider_executions').update({state:'failed',error_code:String(error?.data?.error?.code||error?.message||'provider_error').slice(0,160),updated_at:new Date().toISOString()}).eq('id',execution.id);throw error}
}

export function verifyStripeWebhook(raw:string,signature:string,secret:string,now=Date.now()){const parts=Object.fromEntries(signature.split(',').map(x=>x.split('=',2))) as any;const timestamp=Number(parts.t||0);if(!timestamp||Math.abs(now-timestamp*1000)>300000)return false;const expected=createHmac('sha256',secret).update(`${timestamp}.${raw}`).digest('hex');const a=Buffer.from(expected),b=Buffer.from(parts.v1||'');return a.length===b.length&&timingSafeEqual(a,b)}
export function verifyDocuSignWebhook(raw:string,signature:string,secret:string){const expected=createHmac('sha256',secret).update(raw).digest('base64');const a=Buffer.from(expected),b=Buffer.from(signature||'');return a.length===b.length&&timingSafeEqual(a,b)}

export async function finalizeProviderExecution(execution:any,event:any){const sb=serviceClient(),now=new Date().toISOString();const receiptDigest=digest({previous:execution.receipt_digest,event_id:event.event_id,event_type:event.event_type,payload_digest:event.payload_digest});await sb.from('business_provider_executions').update({state:'verified',receipt_digest:receiptDigest,response_meta:{...(execution.response_meta||{}),final_event:event.event_type},verified_at:now,updated_at:now}).eq('id',execution.id);await sb.from('agentic_business_saga_steps').update({state:'completed',completed_at:now,claimed_by:null,claimed_at:null,evidence:{provider:execution.provider,external_ref:execution.external_ref,receipt_digest:receiptDigest,finality:'verified_provider_event'},updated_at:now}).eq('id',execution.step_id).in('state',['claimed','executing']);const {data:pending}=await sb.from('agentic_business_saga_steps').select('id').eq('saga_id',execution.saga_id).not('state','in','(completed,skipped,compensated)').limit(1);if(!pending?.length)await sb.from('agentic_business_sagas').update({state:'completed',outcome:{status:'completed',provider_finality_verified:true},updated_at:now}).eq('id',execution.saga_id);return receiptDigest}

export async function reconcileProviderExecution(executionId:string){const sb=serviceClient();const {data:execution}=await sb.from('business_provider_executions').select('*').eq('id',executionId).eq('state','provider_pending').maybeSingle();if(!execution)return{status:'not_pending'};const {data:account}=await sb.from('connector_accounts').select('*').eq('id',execution.connector_account_id).eq('status','connected').maybeSingle();if(!account)throw new Error('connected_provider_required');const c=decodeCredential(account);let response:any,status='pending';if(execution.provider==='stripe'){const kind=execution.operation==='issue_credit'?'refunds':'payouts';response=await $fetch<any>(`https://api.stripe.com/v1/${kind}/${encodeURIComponent(execution.external_ref)}`,{headers:{authorization:`Bearer ${c.api_key}`}});status=String(response.status||'pending')}else if(execution.provider==='docusign'){response=await $fetch<any>(`${String(c.base_url).replace(/\/$/,'')}/restapi/v2.1/accounts/${encodeURIComponent(c.account_id)}/envelopes/${encodeURIComponent(execution.external_ref)}`,{headers:{authorization:`Bearer ${c.access_token}`}});status=String(response.status||'pending')}else if(execution.provider==='plaid'){const base=c.environment==='production'?'https://production.plaid.com':'https://sandbox.plaid.com';response=await $fetch<any>(`${base}/transfer/get`,{method:'POST',body:{client_id:c.client_id,secret:c.secret,transfer_id:execution.external_ref}});status=String(response.transfer?.status||'pending')}else return{status:'webhook_required',provider:execution.provider};const terminal=['paid','succeeded','completed','settled','funds_available'].includes(status);const failed=['failed','returned','cancelled','voided','declined'].includes(status);if(terminal){const payloadDigest=digest({provider:execution.provider,external_ref:execution.external_ref,status});await finalizeProviderExecution(execution,{event_id:`poll:${execution.id}:${status}`,event_type:`poll.${status}`,payload_digest:payloadDigest});return{status:'verified',provider_status:status}}if(failed){await sb.from('business_provider_executions').update({state:'failed',error_code:`provider_${status}`,updated_at:new Date().toISOString()}).eq('id',execution.id);await sb.from('agentic_business_saga_steps').update({state:'failed',evidence:{provider:execution.provider,external_ref:execution.external_ref,final_status:status},updated_at:new Date().toISOString()}).eq('id',execution.step_id);await sb.from('agentic_business_sagas').update({state:'failed',outcome:{provider:execution.provider,status},updated_at:new Date().toISOString()}).eq('id',execution.saga_id);return{status:'failed',provider_status:status}}return{status:'pending',provider_status:status}}
