import { createHash, randomUUID } from 'node:crypto'
import { createError } from 'h3'
import { BUSINESS_CAPABILITY_BY_ACTION, type BusinessCapability } from '../../config/businessCapabilities'
import { organizationContext, requireOrgAdmin } from './adaptiveFabric'
import { serviceClient } from './fleetSupabase'
type ActionInput = { action?: string; objective?: string; values?: Record<string, any> }
const CONSEQUENTIAL = new Set(['employee_onboarding', 'nda_draft', 'tax_strategy'])
const ADMIN_ONLY = new Set(['employee_onboarding', 'nda_draft', 'tax_strategy', 'expense_review', 'cash_forecast', 'operating_plan'])
const PROHIBITED_WORKFORCE_FIELDS = ['diagnosis', 'medical_history', 'biometric', 'protected_trait', 'individual_health_score', 'private_message_content']
function bounded(value: unknown, length = 500) { return String(value || '').trim().slice(0, length) }
function stable(value: any): string { if (Array.isArray(value)) return `[${value.map(stable).join(',')}]`; if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(key => `${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`; return JSON.stringify(value) }
function digest(value: unknown) { return createHash('sha256').update(stable(value)).digest('hex') }
function number(value: unknown) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0 }
function rows(result: any) { return result?.error ? [] : (result?.data || []) }
export function compileBusinessAction(input: ActionInput) {
  const action = bounded(input.action, 80); const capability = BUSINESS_CAPABILITY_BY_ACTION[action] as BusinessCapability | undefined
  if (!capability) throw createError({ statusCode: 400, message: 'unsupported_business_action' })
  const values = input.values || {}; const missing = capability.requires.filter(field => !bounded(values[field])); if (missing.length) throw createError({ statusCode: 422, message: `missing_required_fields:${missing.join(',')}` })
  const prohibited = PROHIBITED_WORKFORCE_FIELDS.filter(field => Object.keys(values).map(key => key.toLowerCase()).includes(field)); if (prohibited.length) throw createError({ statusCode: 422, message: `privacy_prohibited_fields:${prohibited.join(',')}` })
  const consequential = CONSEQUENTIAL.has(action); const guardrails = ['Record invocation, effect, outcome, and immutable evidence digest', 'Use least-privilege connector scopes and preserve source provenance', ...(capability.domain === 'workforce' ? ['No covert surveillance, protected-trait inference, or individual health scoring', 'Employee-controlled signals stay private; operational views use minimum-cohort aggregates'] : []), ...(action === 'tax_strategy' ? ['Draft strategy only; validate jurisdiction, dates, eligibility, and evidence with a qualified tax professional before filing'] : []), ...(['nda_draft','employee_onboarding'].includes(action) ? ['Approved clause library only; jurisdiction and authorized legal review required before issuance'] : []), ...(capability.domain === 'creative' ? ['Preserve editable sources, content credentials, license terms, and accessibility-safe alternatives'] : [])]
  return { id: randomUUID(), action, capability, objective: bounded(input.objective || capability.outcome, 1000), state: consequential ? 'approval_required' : action === 'business_health' ? 'completed' : 'planned', consequential, guardrails, values, evidence_digest: digest({ action, objective: input.objective, values, guardrails }) }
}
export async function businessDashboard(user: any) {
  const context = await organizationContext(user); const organizationId = context.membership.organization_id; const sb = serviceClient(); const [runs, people, documents, finances, opportunities, creative, accounts, runtime] = await Promise.all([sb.from('business_action_runs').select('*').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(30), sb.from('workforce_lifecycle_cases').select('*').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(30), sb.from('governed_business_documents').select('*').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(30), sb.from('business_financial_events').select('*').eq('organization_id', organizationId).order('occurred_at', { ascending: false }).limit(1000), sb.from('business_opportunities').select('*').eq('organization_id', organizationId).order('expected_value_usd', { ascending: false }).limit(30), sb.from('creative_production_jobs').select('*').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(30), sb.from('connector_accounts').select('provider,status,scopes').eq('user_id', user.id).eq('status', 'connected'), sb.from('creative_runtime_status').select('*').eq('id', true).maybeSingle()])
  const events = rows(finances); const totals = events.reduce((out: any, event: any) => { const amount = number(event.amount); event.direction === 'inflow' ? out.income += amount : out.expenses += amount; if (event.status === 'attention') out.attention++; return out }, { income: 0, expenses: 0, attention: 0 }); const providers = new Set(rows(accounts).map((item: any) => item.provider)); const liveProviders = new Set(runtime?.data?.providers || [])
  return { organization: context.membership.organization, role: context.membership.role, summary: { ...totals, net: totals.income - totals.expenses, people_in_flight: rows(people).filter((item: any) => !['completed','cancelled'].includes(item.status)).length, actions_waiting: rows(runs).filter((item: any) => item.state === 'approval_required').length }, runs: rows(runs), people: rows(people), documents: rows(documents), finances: events, opportunities: rows(opportunities), creative: rows(creative), studio: { connected: [...providers], runtime: [...liveProviders], checked_at: runtime?.data?.checked_at || null, motion_ready: liveProviders.has('kling'), image_ready: liveProviders.has('bfl') || liveProviders.has('ideogram'), spatial_ready: liveProviders.has('meshy') }, privacy: { workforce_mode: 'consent_and_cohort_only', minimum_cohort: 5, individual_health_scoring: false, protected_trait_inference: false } }
}
export async function executeBusinessAction(user: any, input: ActionInput) {
  const plan = compileBusinessAction(input); const context = await organizationContext(user); const organizationId = context.membership.organization_id; const sb = serviceClient(); if (ADMIN_ONLY.has(plan.action)) requireOrgAdmin(context)
  const inserted = await sb.from('business_action_runs').insert({ id: plan.id, organization_id: organizationId, domain: plan.capability.domain, action: plan.action, objective: plan.objective, risk: plan.capability.risk, state: plan.state, input: plan.values, plan: { outcome: plan.capability.outcome, guardrails: plan.guardrails }, evidence_digest: plan.evidence_digest, created_by: user.id }).select().single(); if (inserted.error) throw createError({ statusCode: 500, message: 'business_action_persistence_failed' }); let artifact: any = null; let approval: any = null
  if (plan.action === 'employee_onboarding') { const result = await sb.rpc('create_governed_employee_onboarding', { p_run_id: plan.id, p_organization_id: organizationId, p_created_by: user.id, p_employee_name: bounded(plan.values.employee_name,160), p_employee_email: bounded(plan.values.employee_email,320), p_role_title: bounded(plan.values.role_title,160), p_jurisdiction: bounded(plan.values.jurisdiction,80), p_start_date: plan.values.start_date || null }); if (result.error) throw createError({ statusCode: 500, message: 'employee_onboarding_creation_failed' }); artifact = result.data }
  else if (plan.action === 'nda_draft') { const result = await sb.from('governed_business_documents').insert({ organization_id: organizationId, action_run_id: plan.id, document_type: 'nda', title: `NDA — ${bounded(plan.values.employee_name,160)}`, counterparty_name: bounded(plan.values.employee_name,160), counterparty_email: bounded(plan.values.employee_email,320), jurisdiction: bounded(plan.values.jurisdiction,80), status: 'legal_review', terms: { template: 'approved_mutual_nda_v1', purpose: bounded(plan.values.purpose || 'employment and confidential business activity'), no_automatic_issuance: true }, created_by: user.id }).select().single(); if (result.error) throw createError({ statusCode: 500, message: 'governed_document_creation_failed' }); artifact = result.data }
  else if (plan.capability.domain === 'creative') { const map: Record<string,string[]> = { creative_motion: ['kling','runway','adobe-firefly','fal'], creative_image: ['bfl','ideogram','adobe-firefly','openai','fal','replicate'], creative_3d: ['meshy','adobe-firefly'] }; const candidates = map[plan.action] || []; const accounts = await sb.from('connector_accounts').select('provider').eq('user_id',user.id).eq('status','connected').in('provider',candidates); const provider = candidates.find(id => (accounts.data || []).some((account: any) => account.provider === id)) || null; const result = await sb.from('creative_production_jobs').insert({ organization_id: organizationId, action_run_id: plan.id, capability: plan.action.replace('creative_',''), brief: bounded(plan.values.brief,5000), selected_provider: provider, provider_candidates: candidates, controls: plan.values.controls || {}, status: provider ? 'ready' : 'connector_required', provenance: { source: 'business_os', evidence_digest: plan.evidence_digest }, created_by: user.id }).select().single(); if (result.error) throw createError({ statusCode: 500, message: 'creative_job_creation_failed' }); artifact = result.data }
  else if (plan.action === 'tax_strategy') { const result = await sb.from('business_opportunities').insert({ organization_id: organizationId, action_run_id: plan.id, domain: 'tax', title: `Tax opportunity review — ${bounded(plan.values.jurisdiction,80)}`, summary: bounded(plan.values.context || plan.objective,2000), confidence: 0, expected_value_usd: 0, state: 'evidence_required', evidence: { jurisdiction: plan.values.jurisdiction, professional_review_required: true, filing_automation_disabled: true }, created_by: user.id }).select().single(); if (result.error) throw createError({ statusCode: 500, message: 'tax_opportunity_creation_failed' }); artifact = result.data }
  if (plan.consequential) { const result = await sb.from('approvals').insert({ project: context.membership.organization?.name || 'Business OS', slug: plan.id, kind: plan.action === 'tax_strategy' ? 'material' : 'legal', title: `${plan.capability.name}: ${plan.objective}`, why: plan.capability.summary, value: plan.capability.outcome, risk: plan.guardrails.join('\n'), alternatives: ['Hold for more evidence', 'Narrow scope', 'Use qualified external review'], detail: `Business OS action ${plan.id}. Authorization permits the bounded next step; it is not execution, issuance, filing, signature, payment, or legal/tax certification.` }).select().single(); if (result.error) throw createError({ statusCode: 500, message: 'business_approval_creation_failed' }); approval = result.data }
  const proof = await sb.from('capability_activation_proofs').upsert({ capability: `business_os:${plan.action}`, invocation_key: `${organizationId}:${plan.id}`, invoked: true, effect: !!artifact || plan.state === 'completed', outcome: artifact ? 'artifact_created' : plan.state, metrics: { domain: plan.capability.domain, state: plan.state, evidence_digest: plan.evidence_digest } }, { onConflict: 'capability,invocation_key' }); if (proof.error) throw createError({ statusCode: 500, message: 'business_activation_proof_failed' })
  return { run: inserted.data, artifact, approval, execution: { approval_required: plan.consequential, guardrails: plan.guardrails, evidence_digest: plan.evidence_digest } }
}
