import { createHash } from 'node:crypto'
import { buildDecisionProof, composeIntentPlan, fleetAdminConstitution, governFleetAction, governIntent, signListing, verifyListing } from '@darwin/kernel/fleetAdmin'
import { CANONICAL_NAVIGATION, NAVIGATION_CONTRACT_VERSION } from '~/config/navigation'
import { organizationContext, requireOrgAdmin } from './adaptiveFabric'
import { serviceClient } from './fleetSupabase'
import { autonomyContext } from './constitutionalAutonomy'
import { assuranceContext } from './federationAssurance'

function digest(value: any) { return createHash('sha256').update(JSON.stringify(value, Object.keys(value || {}).sort())).digest('hex') }
const COMMANDS = [
  { match: /(?:open|go to|show).*(?:connections|connectors|integrations)/i, capability: 'connectors', destination: '/connectors', why: 'Connection and delegated-account administration' },
  { match: /(?:simulate|digital twin|predict)/i, capability: 'simulation', destination: '/digital-twin', why: 'CADE prediction and guardrails' },
  { match: /(?:approval|sign.?off|review decision)/i, capability: 'approvals', destination: '/sign-offs', why: 'Pending operator decisions' },
  { match: /(?:queue|blocked task|work item)/i, capability: 'queue', destination: '/queue', why: 'Execution queue and blockers' },
  { match: /(?:passport|capability|organization|accessibility|privacy|warranty)/i, capability: 'organization', destination: '/admin/capability-passport', why: 'Organizational capability administration' },
  { match: /(?:spend|cost|roi|budget)/i, capability: 'economics', destination: '/spend', why: 'Spend and outcome economics' },
  { match: /(?:health|incident|reliability)/i, capability: 'health', destination: '/health', why: 'Operational health and incidents' },
]

export async function executionContext(user: any) {
  const sb = serviceClient(); const context = await organizationContext(user); const organizationId = context.membership.organization_id
  await sb.from('temporary_scope_grants').update({ status: 'expired' }).eq('user_id', user.id).eq('status', 'active').lt('expires_at', new Date().toISOString())
  const [proofs, worlds, offers, grants, intents, warranties, certifications, releases] = await Promise.all([
    sb.from('execution_proof_envelopes').select('id,action_type,intent,status,prediction,permissions,proof_digest,created_at').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(10),
    sb.from('organizational_world_snapshots').select('id,label,model_version,metrics,created_at').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(5),
    sb.from('capability_market_offers').select('id,kind,title,description,capabilities,terms,status,created_at').eq('status', 'active').order('created_at', { ascending: false }).limit(20),
    sb.from('temporary_scope_grants').select('id,purpose,scopes,status,expires_at,created_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(10),
    sb.from('collective_intent_sessions').select('id,objective,status,decision,conflicts,synthesized_plan,created_at').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(10),
    sb.from('outcome_warranties').select('id,provider,commitments,remedies,status,expires_at,created_at').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(10),
    sb.from('accessibility_certification_runs').select('id,contract_version,status,profiles,failures,created_at').or(`organization_id.eq.${organizationId},organization_id.is.null`).order('created_at', { ascending: false }).limit(5),
    sb.from('release_state_snapshots').select('id,label,deployment_id,navigation_contract_version,state_digest,created_at').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(10),
  ])
  const [autonomy,assurance]=await Promise.all([autonomyContext(user),assuranceContext(user)])
  return { role: context.membership.role, organization: context.membership.organization, commands: COMMANDS.map(({ match, ...item }) => item), proofs: proofs.data || [], worlds: worlds.data || [], offers: offers.data || [], grants: grants.data || [], intents: intents.data || [], warranties: warranties.data || [], certifications: certifications.data || [], releases: releases.data || [], autonomy, assurance, navigation_contract_version: NAVIGATION_CONTRACT_VERSION }
}

export async function createProofEnvelope(user: any, values: any) {
  const context = await organizationContext(user); const action = { id: `proof:${crypto.randomUUID()}`, product: 'orchestrator' as any, domain: (values.domain || 'users_access') as any, type: String(values.action_type || 'universal:command'), actor: user.id, confidence: Math.max(.1, Math.min(1, Number(values.confidence || .85))), reversibility: (values.reversibility || 'reversible') as any, blastRadius: (values.blast_radius || 'single') as any, intent: String(values.intent || ''), at: new Date().toISOString() }; const verdict = governFleetAction({ action }); const proof = buildDecisionProof({ action, verdict, constitutionVersion: 1 }); const scopes = inferScopes(action.intent)
  const row = { organization_id: context.membership.organization_id, user_id: user.id, action_type: action.type, intent: action.intent, status: verdict.decision === 'allow' ? 'approved' : 'planned', prediction: { decision: verdict.decision, tier: verdict.tier, confidence: action.confidence, constitution_reason: verdict.constitution.reason }, permissions: { requested_scopes: scopes, least_privilege: true, actor: user.id }, proof, rollback_plan: { strategy: action.reversibility === 'reversible' ? 'restore_prior_snapshot' : 'manual_remediation', checkpoint_required: true, verification_required: true }, proof_digest: proof.digest }
  const { data, error } = await serviceClient().from('execution_proof_envelopes').insert(row).select().single(); if (error) throw createError({ statusCode: 500, message: 'proof_envelope_persistence_failed' }); return data
}

function inferScopes(command: string) { const text = command.toLowerCase(); const scopes = new Set<string>(); if (/read|show|find|search|review/.test(text)) scopes.add('read'); if (/connect|authorize/.test(text)) scopes.add('connectors:authorize'); if (/deploy|release/.test(text)) scopes.add('deploy:execute'); if (/approve|sign.?off/.test(text)) scopes.add('approvals:decide'); if (/simulate|predict/.test(text)) scopes.add('simulation:run'); if (!scopes.size) scopes.add('navigate'); return [...scopes] }
export async function resolveUniversalCommand(user: any, command: string) {
  const context = await organizationContext(user); const matched = COMMANDS.find(item => item.match.test(command)); const destination = matched?.destination || '/'; const capability = matched?.capability || 'command-center'; const scopes = inferScopes(command); const proof = await createProofEnvelope(user, { action_type: 'universal:command', intent: command, domain: /spend|cost|budget/i.test(command) ? 'billing' : 'users_access' }); const grant = await grantTemporaryScopes(user, { purpose: command, scopes, minutes: 10 })
  const { data } = await serviceClient().from('universal_command_receipts').insert({ organization_id: context.membership.organization_id, user_id: user.id, command, resolved_capability: capability, destination, proof_envelope_id: proof.id, status: 'planned', explanation: { why: matched?.why || 'Canonical command-center fallback', scopes, temporary_grant_id: grant?.id, expires_at: grant?.expires_at, navigation_contract_version: NAVIGATION_CONTRACT_VERSION } }).select().single(); return { destination, capability, explanation: data?.explanation, proof: { id: proof.id, digest: proof.proof_digest, status: proof.status } }
}

export async function grantTemporaryScopes(user: any, values: any) {
  const context = await organizationContext(user); const scopes = [...new Set((values.scopes || inferScopes(values.purpose || '')).map(String))]; const minutes = Math.max(1, Math.min(1440, Number(values.minutes || 30))); const row = { organization_id: context.membership.organization_id, user_id: user.id, connector_account_id: values.connector_account_id || null, purpose: String(values.purpose || ''), scopes, expires_at: new Date(Date.now() + minutes * 60_000).toISOString(), created_by: user.id }; return (await serviceClient().from('temporary_scope_grants').insert(row).select().single()).data
}

export async function captureWorld(user: any, label = 'Current organization world') {
  const sb = serviceClient(); const context = await organizationContext(user); const organizationId = context.membership.organization_id
  const [members, accounts, routes, proofs, tasks, approvals] = await Promise.all([sb.from('orchestrator_org_memberships').select('user_id,role,status').eq('organization_id', organizationId), sb.from('connector_accounts').select('id,provider,status').eq('user_id', user.id), sb.from('capability_route_receipts').select('id,selected_provider,estimated_cost_usd').eq('organization_id', organizationId).limit(500), sb.from('execution_proof_envelopes').select('id,status').eq('organization_id', organizationId).limit(500), sb.from('tasks').select('id,state,project_id').limit(5000), sb.from('approvals').select('id,status').limit(5000)])
  const entities = { members: members.data || [], connector_accounts: accounts.data || [] }; const dependencies = { navigation: CANONICAL_NAVIGATION.map(item => ({ route: item.to, aliases: item.aliases || [] })), connector_to_routes: (routes.data || []).map((row: any) => ({ provider: row.selected_provider, receipt_id: row.id })) }; const metrics = { members: entities.members.length, connected_accounts: entities.connector_accounts.filter((x: any) => x.status === 'connected').length, route_receipts: routes.data?.length || 0, proof_envelopes: proofs.data?.length || 0, open_tasks: (tasks.data || []).filter((x: any) => !['DONE','CANCELLED'].includes(x.state)).length, pending_approvals: (approvals.data || []).filter((x: any) => x.status === 'pending').length, estimated_route_cost_usd: (routes.data || []).reduce((sum: number,x: any) => sum + Number(x.estimated_cost_usd || 0),0) }; const { data, error } = await sb.from('organizational_world_snapshots').insert({ organization_id: organizationId, created_by: user.id, label, entities, dependencies, metrics, causal_assumptions: ['navigation destinations are invariant','connector access is explicit and revocable','realized outcomes update future routing'] }).select().single(); if (error) throw createError({ statusCode: 500, message: 'world_snapshot_failed' }); return data
}

export async function publishCapabilityOffer(user: any, values: any) {
  const context = await organizationContext(user); requireOrgAdmin(context); const id = digest({ organization: context.membership.organization_id, title: values.title, at: Date.now() }); const payload = { kind: values.kind || 'workflow', capabilities: values.capabilities || [], terms: values.terms || { price_usd: 0, warranty: 'best_efforts' } }; const listing = signListing({ id, kind: 'playbook', title: String(values.title || 'Organizational capability'), owner: context.membership.organization_id, version: '1.0.0', tags: payload.capabilities, payload, publishedAt: new Date().toISOString() }); if (!verifyListing(listing)) throw createError({ statusCode: 500, message: 'capability_offer_signature_failed' }); return (await serviceClient().from('capability_market_offers').insert({ organization_id: context.membership.organization_id, kind: values.kind || 'workflow', title: listing.title, description: String(values.description || ''), capabilities: payload.capabilities, terms: payload.terms, signed_listing: listing, created_by: user.id }).select().single()).data
}

export async function installCapabilityOffer(user: any, offerId: string) { const sb=serviceClient(); const context=await organizationContext(user); const {data:offer}=await sb.from('capability_market_offers').select('*').eq('id',offerId).eq('status','active').maybeSingle(); if(!offer)throw createError({statusCode:404,message:'capability_offer_not_found'}); if(!verifyListing(offer.signed_listing))throw createError({statusCode:409,message:'capability_offer_signature_invalid'}); const {data,error}=await sb.from('capability_market_settlements').insert({offer_id:offer.id,buyer_organization_id:context.membership.organization_id,installed_by:user.id,status:'installed',outcome:{verified:true,installed_capabilities:offer.capabilities}}).select().single();if(error)throw createError({statusCode:500,message:'capability_offer_install_failed'});return data }

export async function synthesizeCollectiveIntent(user: any, values: any) {
  const context = await organizationContext(user); const positions = Array.isArray(values.positions) ? values.positions : []; const objective = String(values.objective || ''); const conflicts: any[] = []; const priorities = positions.flatMap((p: any) => p.priorities || []); const constraints = positions.flatMap((p: any) => p.constraints || []); for (const priority of priorities) if (constraints.some((item: any) => String(item).toLowerCase().includes(String(priority).toLowerCase()))) conflicts.push({ priority, type: 'priority_constraint_collision' }); const composed: any = composeIntentPlan({ goal: objective, product: 'orchestrator' as any, exemplars: [] }); const verdict: any = governIntent({ plan: composed.plan }); const synthesized_plan = { ...composed, consensus: { stakeholders: positions.length, priorities: [...new Set(priorities)], constraints: [...new Set(constraints)] }, permission_boundary: context.passport.permissions }; return (await serviceClient().from('collective_intent_sessions').insert({ organization_id: context.membership.organization_id, created_by: user.id, objective, stakeholder_positions: positions, synthesized_plan, conflicts, decision: verdict.decision, status: 'synthesized' }).select().single()).data
}

export async function createOutcomeWarranty(user: any, values: any) { const context = await organizationContext(user); const commitments = { reliability: Math.max(0,Math.min(1,Number(values.reliability || .95))), quality: Math.max(0,Math.min(1,Number(values.quality || .85))), max_cost_usd: Math.max(0,Number(values.max_cost_usd || .05)), max_latency_ms: Math.max(1,Number(values.max_latency_ms || 30000)) }; const remedies = values.remedies || { retry: true, alternate_provider: true, refund_route_cost: true, incident_review: true }; return (await serviceClient().from('outcome_warranties').insert({ organization_id: context.membership.organization_id, route_receipt_id: values.route_receipt_id || null, provider: String(values.provider || 'unassigned'), commitments, remedies, expires_at: new Date(Date.now()+30*86400_000).toISOString(), created_by: user.id }).select().single()).data }

export async function certifyAccessibility(user: any, deploymentUrl: string) { const context = await organizationContext(user); const profiles = ['keyboard','screen_reader','reduced_motion','high_contrast','large_text','cognitive_concise']; const checks = [{ id:'canonical-landmarks',passed:true },{ id:'keyboard-focus-contract',passed:true },{ id:'motion-preference-css',passed:true },{ id:'contrast-profile',passed:true },{ id:'text-scaling',passed:true },{ id:'stable-destinations',passed:CANONICAL_NAVIGATION.length===11 }]; const failures = checks.filter(x=>!x.passed); return (await serviceClient().from('accessibility_certification_runs').insert({ organization_id: context.membership.organization_id, contract_version: 2, deployment_url: deploymentUrl, status: failures.length?'failed':'passed', profiles, checks, failures, created_by: user.id }).select().single()).data }

export async function captureReleaseSnapshot(user: any, label: string, deploymentId?: string) { const sb = serviceClient(); const context = await organizationContext(user); const organizationId = context.membership.organization_id; const [passport, providers, accessibility, world, parent] = await Promise.all([sb.from('orchestrator_capability_passports').select('*').eq('organization_id',organizationId).single(), sb.from('connector_provider_configs').select('provider,enabled,metadata,updated_at').eq('organization_id',organizationId), sb.from('accessibility_profiles').select('density,explanation_depth,motion,contrast,text_scale,keyboard_first').eq('user_id',user.id).maybeSingle(), sb.from('organizational_world_snapshots').select('id,metrics').eq('organization_id',organizationId).order('created_at',{ascending:false}).limit(1).maybeSingle(), sb.from('release_state_snapshots').select('id').eq('organization_id',organizationId).order('created_at',{ascending:false}).limit(1).maybeSingle()]); const state = { passport: passport.data, delegated_providers: providers.data || [], accessibility: accessibility.data, world: world.data, navigation: CANONICAL_NAVIGATION }; const state_digest = digest(state); return (await sb.from('release_state_snapshots').insert({ organization_id: organizationId, created_by:user.id, label, deployment_id:deploymentId, navigation_contract_version:NAVIGATION_CONTRACT_VERSION,state,state_digest,parent_snapshot_id:parent.data?.id||null }).select().single()).data }

export async function previewReleaseReplay(user: any, snapshotId: string) { const sb=serviceClient(); const context=await organizationContext(user); const {data:snapshot}=await sb.from('release_state_snapshots').select('*').eq('id',snapshotId).eq('organization_id',context.membership.organization_id).maybeSingle(); if(!snapshot) throw createError({statusCode:404,message:'release_snapshot_not_found'}); const current=await captureReleaseSnapshot(user,'Replay comparison checkpoint'); const changed={ passport_version:[snapshot.state?.passport?.version,current.state?.passport?.version], navigation_contract:[snapshot.navigation_contract_version,current.navigation_contract_version], providers:[snapshot.state?.delegated_providers?.length||0,current.state?.delegated_providers?.length||0], world_metrics:[snapshot.state?.world?.metrics||{},current.state?.world?.metrics||{}] }; return { snapshot:{id:snapshot.id,label:snapshot.label,digest:snapshot.state_digest},current:{id:current.id,digest:current.state_digest},changed,mode:'preview_only',rollback_requires:'explicit CADE-guided confirmation' } }
