import { createHash } from 'node:crypto'
import { createError } from 'h3'
import { LEGAL_TEMPLATE_BY_KEY, LEGAL_TEMPLATES, type LegalTemplate } from '../../config/legalContracts'
import { organizationContext, requireOrgAdmin } from './adaptiveFabric'
import { serviceClient } from './fleetSupabase'
import { getAppConfig } from './appClients'
import { compileJurisdictionalPolicy } from './jurisdictionalPolicy'

type LegalAction = { action?:string; values?:Record<string,any> }
const bounded=(value:any,length=2000)=>String(value||'').trim().slice(0,length)
const hash=(value:any)=>createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex')
const title=(value:string)=>value.split('_').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ')

function clauseText(clause:string,facts:Record<string,any>){
  const a=bounded(facts.party_a||'Party A',180),b=bounded(facts.party_b||'Party B',180),purpose=bounded(facts.purpose||facts.services||'the stated business purpose',500)
  const shared=`${a} and ${b}`
  const clauses:Record<string,string>={
    relationship:`The parties intend this document to define their relationship for ${purpose}. Classification, authority, and mandatory local rights must be confirmed for the selected jurisdiction.`,
    services:`${b} will perform the services described in the approved scope and change records. Dependencies, acceptance criteria, and excluded work must be stated before signature.`,
    services_and_sows:`Services will be authorized through signed statements of work identifying scope, deliverables, timing, dependencies, fees, acceptance criteria, and change control.`,
    confidentiality:`Each receiving party will protect covered confidential information, use it only for the stated purpose, limit access to authorized recipients, and apply the agreed exclusions, compelled-disclosure process, retention rules, and return or destruction process.`,
    intellectual_property:`Background intellectual property remains with its existing owner. Ownership and permitted use of deliverables, work product, improvements, feedback, data, and third-party materials must be stated expressly and reviewed for the selected jurisdiction.`,
    fees_and_taxes:`Fees, invoice timing, disputed-charge procedure, expenses, currency, withholding, indirect taxes, and payment evidence will follow the completed commercial schedule.`,
    fees:`The completed commercial schedule will state fees, invoice timing, expenses, currency, taxes, and the process for disputed amounts.`,
    data:`The parties will identify data roles, permitted processing, instructions, access, retention, deletion, transfers, subprocessors, security measures, and incident responsibilities in the applicable data schedule.`,
    security:`The responsible party will maintain documented safeguards proportionate to the agreed data and service risk, with notification, cooperation, remediation, and evidence requirements defined in the security schedule.`,
    warranties:`Any warranties, disclaimers, service commitments, remedy hierarchy, and reliance limitations must be explicit, internally consistent, and reviewed for mandatory local law.`,
    indemnity:`Indemnity scope, covered claims, exclusions, defense control, settlement authority, notice, cooperation, and interaction with liability limits must be completed and independently reviewed.`,
    liability:`Liability exclusions, caps, cap bases, carve-outs, mitigation duties, and treatment of indirect or consequential loss must be completed and independently approved.`,
    term_and_termination:`The agreement will state its effective date, initial and renewal terms, termination rights, cure periods, transition assistance, survival, data return, and final-payment consequences.`,
    termination:`Termination grounds, notice, cure, final compensation, return of property, continuing duties, and mandatory local rights must be confirmed before issuance.`,
    disputes:`Governing law, forum, escalation, mediation or arbitration choices, emergency relief, fees, notices, and conflicts with mandatory law require jurisdiction-specific review.`,
    acceptance:`Acceptance criteria, review period, rejection detail, remediation, deemed-acceptance treatment, and dependency effects must be completed in the commercial schedule.`,
    change_control:`No material scope, timing, fee, security, or deliverable change is effective unless captured in the agreed written change-control process.`,
  }
  return clauses[clause]||`${shared} will complete and approve the ${title(clause).toLowerCase()} terms using the attached facts, policy snapshot, negotiation record, and required professional review.`
}

export function generateStructuredDraft(template:LegalTemplate,facts:Record<string,any>,prompt:string){
  const missing=template.fields.filter(field=>!bounded(facts[field]))
  const clauses=template.clauses.map((id,index)=>({id,order:index+1,heading:title(id),text:clauseText(id,facts),status:missing.length?'needs_input':'drafted'}))
  const content={schema_version:1,template_key:template.key,template_name:template.name,prompt:bounded(prompt,4000),facts,missing_fields:missing,clauses,notices:['Drafting assistance only; not a legal opinion.','Bracketed or incomplete business terms must be resolved before approval.','Mandatory law, enforceability, tax, regulatory, and professional-responsibility issues require qualified review where routed.']}
  const rendered=[template.name.toUpperCase(),`Draft for review · ${bounded(facts.jurisdiction||'Jurisdiction not supplied')}`,'',...clauses.flatMap(c=>[`${c.order}. ${c.heading}`,c.text,'']),'DRAFTING NOTICE',...content.notices.map(x=>`• ${x}`)].join('\n')
  return {content,rendered,digest:hash(rendered)}
}

export function analyzeDraft(template:LegalTemplate,content:any,policy:any){
  const missing=content.missing_fields||[]; const findings:any[]=[]
  if(missing.length)findings.push({severity:'blocked',code:'missing_terms',message:`Complete: ${missing.join(', ')}`})
  if(!policy.coverage.complete)findings.push({severity:'blocked',code:'authority_gap',message:'No verified effective-date authority pack covers this matter.'})
  for(const reason of policy.review_reasons||[])findings.push({severity:'attention',code:'professional_review',message:reason})
  for(const clause of content.clauses||[])if(['indemnity','liability','disputes','intellectual_property'].includes(clause.id))findings.push({severity:'attention',code:`risk_${clause.id}`,clause_id:clause.id,message:`Independently review ${clause.heading.toLowerCase()} language and its interaction with the full agreement.`})
  const hive=[
    {seat:'Commercial',focus:'Economics, scope, acceptance, remedies, termination, and operational feasibility'},
    {seat:'Employment',focus:'Classification, mandatory rights, compensation, restrictions, and separation'},
    {seat:'Privacy & security',focus:'Data roles, transfers, security evidence, incidents, retention, and deletion'},
    {seat:'IP',focus:'Background rights, deliverables, licenses, third-party materials, and chain of title'},
    {seat:'Tax & corporate',focus:'Entity authority, withholding, nexus, equity, governance, and approvals'},
    {seat:'Negotiation',focus:'Fallback positions, ambiguity, leverage, market variance, and executable obligations'},
  ].filter(seat=>template.category!=='employment'||seat.seat!=='Commercial')
  const blocked=findings.some(x=>x.severity==='blocked'); return {cade:{status:blocked?'blocked':findings.length?'attention':'clear',score:Math.max(0,1-findings.length*.08),findings},hivemind:{status:blocked?'blocked':'attention',score:blocked ? .35 : .72,findings:hive.map(x=>({...x,severity:'review'}))}}
}

async function policySnapshot(sb:any,organizationId:string,userId:string,jurisdiction:string,domains:string[],facts:any){
  const {data:sources}=await sb.from('legal_policy_sources').select('*').eq('status','verified').eq('jurisdiction',jurisdiction).in('domain',domains)
  const compiled=compileJurisdictionalPolicy({jurisdiction,domains,contract:facts,sources:sources||[]}); const {data,error}=await sb.from('legal_policy_snapshots').upsert({organization_id:organizationId,jurisdiction,domains,as_of:compiled.as_of,compiled_rules:compiled.compiled_rules,evidence:compiled.evidence,professional_review_required:compiled.professional_review_required,review_reasons:compiled.review_reasons,coverage:compiled.coverage,snapshot_digest:compiled.digest,created_by:userId},{onConflict:'organization_id,snapshot_digest'}).select().single(); if(error)throw createError({statusCode:500,message:'policy_snapshot_persistence_failed'}); return {...compiled,id:data.id}
}

async function activation(sb:any,organizationId:string,action:string,key:string,effect:boolean,outcome:string,metrics:any={}){ const {error}=await sb.from('capability_activation_proofs').upsert({capability:`legal_workspace:${action}`,invocation_key:`${organizationId}:${key}`,invoked:true,effect,outcome,metrics},{onConflict:'capability,invocation_key'}); if(error)throw createError({statusCode:500,message:'legal_activation_proof_failed'}) }

export async function legalWorkspace(user:any){
  const context=await organizationContext(user),organizationId=context.membership.organization_id,sb=serviceClient(); const [contracts,obligations,policies]=await Promise.all([sb.from('legal_contracts').select('*,legal_contract_versions(*),legal_contract_reviews(*)').eq('organization_id',organizationId).order('updated_at',{ascending:false}).limit(50),sb.from('legal_obligations').select('*').eq('organization_id',organizationId).neq('status','completed').order('due_at',{ascending:true}).limit(100),sb.from('legal_policy_snapshots').select('*').eq('organization_id',organizationId).order('created_at',{ascending:false}).limit(20)]); const items=contracts.data||[]
  return {role:context.membership.role,templates:LEGAL_TEMPLATES,contracts:items,obligations:obligations.data||[],policies:policies.data||[],summary:{matters:items.length,negotiating:items.filter((x:any)=>['counterparty_review','negotiating'].includes(x.lifecycle)).length,needs_review:items.filter((x:any)=>x.professional_review_required&&!['signed','active','cancelled'].includes(x.lifecycle)).length,obligations_due:(obligations.data||[]).filter((x:any)=>x.due_at&&new Date(x.due_at)<=new Date(Date.now()+30*86400000)).length},smarter:getAppConfig('smarter')}
}

async function smarterExecute(type:string,payload:any){ const config=getAppConfig('smarter'); if(!config.baseUrl)return {ok:false,error:'smarter_not_configured'}; try{ const response=await fetch(`${config.baseUrl}/api/fleet/execute`,{method:'POST',headers:{'content-type':'application/json','x-fleet-secret':process.env.FLEET_SHARED_SECRET||''},body:JSON.stringify({action:{type,...payload}}),signal:AbortSignal.timeout(15000)}); const data:any=await response.json().catch(()=>({})); return {ok:response.ok&&data?.ok!==false,data,status:response.status} }catch(error:any){return {ok:false,error:String(error?.message||error).slice(0,300)}} }

export async function executeLegalAction(user:any,input:LegalAction){
  const action=bounded(input.action,80),values=input.values||{},context=await organizationContext(user),organizationId=context.membership.organization_id,sb=serviceClient()
  if(action==='register_policy_source'){ requireOrgAdmin(context); const jurisdiction=bounded(values.jurisdiction,120),domain=bounded(values.domain,80),sourceTitle=bounded(values.title,300),authorityUrl=bounded(values.authority_url,1000),effectiveFrom=bounded(values.effective_from,10); if(!jurisdiction||!domain||!sourceTitle||!/^https:\/\//.test(authorityUrl)||!/^\d{4}-\d{2}-\d{2}$/.test(effectiveFrom))throw createError({statusCode:422,message:'verified_primary_source_metadata_required'}); const verified=values.verification_attested===true; const source={jurisdiction,domain,title:sourceTitle,authority_url:authorityUrl,effective_from:effectiveFrom,effective_to:values.effective_to||null,status:verified?'verified':'draft',rules:{requirements:Array.isArray(values.requirements)?values.requirements:[]},source_digest:hash({jurisdiction,domain,sourceTitle,authorityUrl,effectiveFrom,requirements:values.requirements||[]}),verified_by:verified?user.id:null,verified_at:verified?new Date().toISOString():null}; const {data,error}=await sb.from('legal_policy_sources').upsert(source,{onConflict:'jurisdiction,domain,title,effective_from'}).select().single(); if(error)throw createError({statusCode:500,message:'policy_source_persistence_failed'}); await activation(sb,organizationId,action,data.id,true,verified?'verified_source_registered':'draft_source_registered',{domain,jurisdiction}); return {source:data} }
  if(action==='compile_policy'){ const jurisdiction=bounded(values.jurisdiction,120); const policy=await policySnapshot(sb,organizationId,user.id,jurisdiction,Array.isArray(values.domains)?values.domains:['commercial'],values); await activation(sb,organizationId,action,policy.digest,true,'snapshot_compiled',{coverage:policy.coverage}); return {policy} }
  if(action==='create_draft'){
    const template=LEGAL_TEMPLATE_BY_KEY[bounded(values.template_key,100)] as LegalTemplate|undefined; if(!template)throw createError({statusCode:400,message:'contract_template_required'}); const facts=values.facts||{}; const jurisdiction=bounded(facts.jurisdiction,120); if(!jurisdiction)throw createError({statusCode:422,message:'jurisdiction_required'}); const domains=[template.category==='employment'?'employment':template.category==='privacy'?'privacy':'commercial',...(template.category==='finance'?['tax']:[])]; const policy=await policySnapshot(sb,organizationId,user.id,jurisdiction,domains,facts); const draft=generateStructuredDraft(template,facts,bounded(values.prompt,4000)); const {data,error}=await sb.rpc('create_legal_contract_draft',{p_organization_id:organizationId,p_created_by:user.id,p_template_key:template.key,p_category:template.category,p_title:bounded(values.title||`${template.name} — ${facts.party_b||'New matter'}`,240),p_jurisdiction:jurisdiction,p_counterparty_name:bounded(facts.party_b,240)||null,p_counterparty_email:bounded(facts.counterparty_email,320)||null,p_risk_level:template.risk,p_policy_snapshot_id:policy.id,p_matter_data:{...facts,prompt:bounded(values.prompt,4000)},p_professional_review_required:policy.professional_review_required||template.risk==='high',p_content:draft.content,p_rendered_text:draft.rendered,p_content_digest:draft.digest}); if(error)throw createError({statusCode:500,message:'contract_draft_creation_failed'}); await activation(sb,organizationId,action,data.id,true,'draft_created',{template:template.key,missing:draft.content.missing_fields.length,policy_digest:policy.digest}); return {contract:data,draft,policy}
  }
  const contractId=bounded(values.contract_id,80); if(!contractId)throw createError({statusCode:422,message:'contract_id_required'}); const {data:contract}=await sb.from('legal_contracts').select('*').eq('id',contractId).eq('organization_id',organizationId).maybeSingle(); if(!contract)throw createError({statusCode:404,message:'contract_not_found'}); const template=LEGAL_TEMPLATE_BY_KEY[contract.template_key] as LegalTemplate
  if(action==='review'){
    const {data:version}=await sb.from('legal_contract_versions').select('*').eq('contract_id',contract.id).eq('version',contract.current_version).single(); const {data:policy}=await sb.from('legal_policy_snapshots').select('*').eq('id',contract.policy_snapshot_id).single(); const analysis=analyzeDraft(template,version.content,policy); await sb.from('legal_contract_reviews').insert([{contract_id:contract.id,version:contract.current_version,reviewer_type:'cade',status:analysis.cade.status,score:analysis.cade.score,findings:analysis.cade.findings,evidence:{policy_snapshot_id:policy.id}},{contract_id:contract.id,version:contract.current_version,reviewer_type:'hivemind',status:analysis.hivemind.status,score:analysis.hivemind.score,findings:analysis.hivemind.findings,evidence:{seats:analysis.hivemind.findings.length}}]); await sb.from('legal_contracts').update({lifecycle:'internal_review',updated_at:new Date().toISOString()}).eq('id',contract.id); await activation(sb,organizationId,action,`${contract.id}:${contract.current_version}`,true,analysis.cade.status,{cade_score:analysis.cade.score,hivemind_score:analysis.hivemind.score}); return {analysis}
  }
  if(action==='redline'){
    const operations=Array.isArray(values.operations)?values.operations.slice(0,50):[]; if(!operations.length)throw createError({statusCode:422,message:'redline_operations_required'}); const {data:version}=await sb.from('legal_contract_versions').select('*').eq('contract_id',contract.id).eq('version',contract.current_version).single(); const content=structuredClone(version.content); for(const op of operations){const clause=(content.clauses||[]).find((x:any)=>x.id===op.clause_id);if(clause&&bounded(op.proposed_text,10000)){clause.text=bounded(op.proposed_text,10000);clause.status='redlined'}} const next=contract.current_version+1; const rendered=[template.name.toUpperCase(),`Version ${next} · negotiation draft`,'',...(content.clauses||[]).flatMap((c:any)=>[`${c.order}. ${c.heading}`,c.text,''])].join('\n'); const inserted=await sb.from('legal_contract_versions').insert({contract_id:contract.id,version:next,source:'redline',content,rendered_text:rendered,change_summary:bounded(values.rationale||`${operations.length} clause changes`,1000),content_digest:hash(rendered),created_by:user.id}); if(inserted.error)throw createError({statusCode:500,message:'redline_version_failed'}); await sb.from('legal_negotiation_events').insert({contract_id:contract.id,from_version:contract.current_version,to_version:next,actor:bounded(values.actor||'internal',100),event_type:'redline',operations,rationale:bounded(values.rationale,2000),created_by:user.id}); await sb.from('legal_contracts').update({current_version:next,lifecycle:'negotiating',updated_at:new Date().toISOString()}).eq('id',contract.id); await activation(sb,organizationId,action,`${contract.id}:${next}`,true,'version_created',{operations:operations.length}); return {version:next}
  }
  if(action==='request_approval'){
    requireOrgAdmin(context); if(contract.lifecycle==='approval_required'||contract.approval_id)throw createError({statusCode:409,message:'approval_already_requested'}); const {data:reviews}=await sb.from('legal_contract_reviews').select('*').eq('contract_id',contract.id).eq('version',contract.current_version); if(!(reviews||[]).some((x:any)=>x.reviewer_type==='cade'))throw createError({statusCode:409,message:'cade_review_required_before_approval'}); if((reviews||[]).some((x:any)=>x.status==='blocked'))throw createError({statusCode:409,message:'blocked_review_findings_must_be_resolved'}); const {data:approval,error}=await sb.from('approvals').insert({project:'Business OS Legal',slug:contract.id,kind:'legal',title:`Approve ${contract.title} v${contract.current_version}`,why:'Authorize this exact version for issuance preparation after required professional review.',value:'A version-pinned, evidence-backed contract package ready for the explicit issuance step.',risk:'Approval is not signature, delivery, legal certification, or agreement by the counterparty.',alternatives:['Request another redline','Obtain additional specialist review','Cancel the matter'],detail:`Contract ${contract.id}; version ${contract.current_version}; jurisdiction ${contract.jurisdiction}. ${contract.professional_review_required?'Qualified jurisdiction-specific review is required.':''}`,approvals_required:contract.risk_level==='high'?2:1}).select().single(); if(error)throw createError({statusCode:500,message:'legal_approval_creation_failed'}); await sb.from('legal_contracts').update({lifecycle:'approval_required',approval_id:approval.id,updated_at:new Date().toISOString()}).eq('id',contract.id); await activation(sb,organizationId,action,`${contract.id}:${contract.current_version}`,true,'approval_requested',{approval_id:approval.id}); return {approval}
  }
  if(action==='sync_smarter'){
    const result=await smarterExecute('legal_contract_sync',{contract_id:contract.id,version:contract.current_version,title:contract.title,jurisdiction:contract.jurisdiction,lifecycle:contract.lifecycle,professional_review_required:contract.professional_review_required}); await sb.from('legal_delivery_events').insert({contract_id:contract.id,event_type:'smarter_sync',status:result.ok?'confirmed':'blocked',provider:'smarter',external_ref:result.data?.id||null,evidence:result,created_by:user.id}); await sb.from('legal_contracts').update({smarter_sync_status:result.ok?'synced':'attention',updated_at:new Date().toISOString()}).eq('id',contract.id); await activation(sb,organizationId,action,`${contract.id}:${contract.current_version}`,result.ok,result.ok?'synced':'blocked',{}); return {sync:result}
  }
  if(action==='issue'){
    requireOrgAdmin(context); if(!['approved','issue_ready'].includes(contract.lifecycle))throw createError({statusCode:409,message:'approved_contract_required_for_issue'}); const recipient=bounded(values.recipient||contract.counterparty_email,320); if(!recipient)throw createError({statusCode:422,message:'recipient_required'}); const {data:version}=await sb.from('legal_contract_versions').select('*').eq('contract_id',contract.id).eq('version',contract.current_version).single(); const result=await smarterExecute('legal_contract_issue',{contract_id:contract.id,version:contract.current_version,title:contract.title,recipient,rendered_text:version.rendered_text,content_digest:version.content_digest,signature_requested:values.signature_requested!==false}); await sb.from('legal_delivery_events').insert({contract_id:contract.id,event_type:'issue',status:result.ok?'sent':'blocked',provider:'smarter',recipient,external_ref:result.data?.id||null,evidence:{...result,content_digest:version.content_digest},created_by:user.id}); if(result.ok)await sb.from('legal_contracts').update({lifecycle:'issued',smarter_sync_status:'synced',updated_at:new Date().toISOString()}).eq('id',contract.id); await activation(sb,organizationId,action,`${contract.id}:${contract.current_version}`,result.ok,result.ok?'issued':'blocked',{recipient_domain:recipient.split('@')[1]||''}); return {delivery:result}
  }
  if(action==='record_signature'){
    requireOrgAdmin(context); const externalRef=bounded(values.external_ref,500); if(!externalRef)throw createError({statusCode:422,message:'signature_evidence_required'}); await sb.from('legal_delivery_events').insert({contract_id:contract.id,event_type:'signature_received',status:'confirmed',provider:bounded(values.provider||'smarter',100),external_ref:externalRef,evidence:{signed_at:values.signed_at||new Date().toISOString(),signers:values.signers||[]},created_by:user.id}); await sb.from('legal_contracts').update({lifecycle:'signed',updated_at:new Date().toISOString()}).eq('id',contract.id); await activation(sb,organizationId,action,externalRef,true,'signature_recorded',{contract_id:contract.id}); return {status:'signed'}
  }
  if(action==='add_obligation'){
    const obligation=bounded(values.obligation,2000); if(!obligation)throw createError({statusCode:422,message:'obligation_required'}); const {data,error}=await sb.from('legal_obligations').insert({organization_id:organizationId,contract_id:contract.id,owner:bounded(values.owner,200)||null,obligation,due_at:values.due_at||null,recurrence:bounded(values.recurrence,100)||null,source_clause:bounded(values.source_clause,100)||null,evidence:{created_from_version:contract.current_version}}).select().single(); if(error)throw createError({statusCode:500,message:'obligation_creation_failed'}); await activation(sb,organizationId,action,data.id,true,'obligation_created',{}); return {obligation:data}
  }
  throw createError({statusCode:400,message:'unsupported_legal_action'})
}
