import{serviceClient}from'./fleetSupabase'
import{intelligenceDigest,requestHsmSignature}from'./providerIntelligence'
import{inferProviderStateMachine,modelCheckSaga,optimizeTreasuryGraph,selectProviderAuctionQuote,semanticMutationIntent,simulateRegulatoryImpact,verifyThresholdAggregateProof}from'./providerSovereigntyCompounding'

export async function appendTransparencyEntry(organizationId:string|null,entryType:string,subject:any,payload:any){const subjectDigest=typeof subject==='string'?subject:intelligenceDigest(subject),payloadDigest=typeof payload==='string'?payload:intelligenceDigest(payload),signed=await requestHsmSignature(intelligenceDigest({entry_type:entryType,subject_digest:subjectDigest,payload_digest:payloadDigest}),'provider-transparency'),{data,error}=await serviceClient().rpc('append_provider_transparency_entry',{p_organization_id:organizationId,p_entry_type:entryType,p_subject_digest:subjectDigest,p_payload_digest:payloadDigest,p_signer_key_id:signed.signing_key_id,p_signature:signed.signature});if(error||!data)throw new Error('transparency_append_failed');return Array.isArray(data)?data[0]:data}

export async function verifyAggregateThreshold(aggregate:any){const keys=JSON.parse(process.env.SECURE_MAPPING_THRESHOLD_KEYS_JSON||'{}'),{data:proof,error}=await serviceClient().from('provider_threshold_aggregate_proofs').select('*').eq('aggregate_digest',aggregate.aggregate_digest).eq('verified',true).maybeSingle();if(error||!proof)throw new Error('threshold_aggregate_proof_required');const verified=verifyThresholdAggregateProof(aggregate,{...proof,signatures:proof.signatures,zk_required:process.env.SECURE_MAPPING_ZK_REQUIRED!=='false'},keys);await appendTransparencyEntry(null,'threshold_aggregate_verified',aggregate.aggregate_digest,verified);return verified}

export async function runLiveProviderAuction(saga:any,step:any,accounts:any[]){const endpoint=process.env.PROVIDER_QUOTE_BROKER_URL;if(!endpoint)return null;const request={contract_version:'provider-quote-auction/v1',organization_id:saga.organization_id,saga_id:saga.id,step_id:step.id,operation:step.operation,input_digest:intelligenceDigest(step.input||{}),accounts:accounts.map(a=>({connector_account_id:a.id,provider:a.provider,credential_ref:a.metadata?.credential_ref||null})),non_mutating:true,authorization_only:true},requestDigest=intelligenceDigest(request),signature=await requestHsmSignature(requestDigest,'provider-quote-auction'),response:any=await $fetch(`${endpoint.replace(/\/$/,'')}/v1/quotes/fanout`,{method:'POST',body:{...request,request_digest:requestDigest,signature:signature.signature,key_id:signature.signing_key_id},timeout:15000}),quotes=Array.isArray(response?.quotes)?response.quotes:[],auction=selectProviderAuctionQuote(quotes,{amount:Number(step.input?.amount||0),max_failure_rate:Number(process.env.PROVIDER_ROUTE_MAX_FAILURE_RATE||.15),max_risk_score:Number(process.env.PROVIDER_ROUTE_MAX_RISK_SCORE||.25)}),{error}=await serviceClient().from('provider_route_auctions').upsert({organization_id:saga.organization_id,saga_id:saga.id,step_id:step.id,request_digest:requestDigest,quotes:auction.quotes,selected_connector_account_id:auction.selected?.connector_account_id||null,selection_digest:auction.selection_digest,quote_count:accounts.length,live_quote_count:quotes.length,status:auction.status,expires_at:auction.selected?.expires_at||null},{onConflict:'step_id,request_digest'});if(error)throw new Error('provider_auction_persistence_failed');if(auction.status!=='selected')throw new Error('no_safe_live_provider_quote');await appendTransparencyEntry(saga.organization_id,'provider_route_auction',auction.selection_digest,{request_digest:requestDigest,selected:auction.selected.connector_account_id});return auction}

export async function createSemanticMutationIntent(execution:any,step:any){const sb=serviceClient(),semantic=semanticMutationIntent(execution.operation,step.input||{},{organization_id:execution.organization_id,organization_scope:execution.organization_id}),{data:existing}=await sb.from('provider_semantic_mutation_intents').select('*').eq('semantic_key',semantic.semantic_key).maybeSingle();if(existing)return{...semantic,signed_intent:existing.signed_intent,row:existing};const signed=await requestHsmSignature(semantic.obligation_digest,'semantic-provider-mutation'),signedIntent={...semantic.intent,obligation_digest:semantic.obligation_digest,signature:signed.signature,key_id:signed.signing_key_id},{data,error}=await sb.from('provider_semantic_mutation_intents').insert({semantic_key:semantic.semantic_key,organization_id:execution.organization_id,saga_id:execution.saga_id,step_id:execution.step_id,operation:execution.operation,obligation_digest:semantic.obligation_digest,signed_intent:signedIntent,state:'claimed'}).select().single();if(error||!data){const{data:raced}=await sb.from('provider_semantic_mutation_intents').select('*').eq('semantic_key',semantic.semantic_key).maybeSingle();if(raced)return{...semantic,signed_intent:raced.signed_intent,row:raced};throw new Error('semantic_mutation_intent_failed')}return{...semantic,signed_intent:signedIntent,row:data}}

export async function commitSemanticMutation(semanticKey:string,provider:string,externalRef:string,receiptDigest:string){const{data,error}=await serviceClient().from('provider_semantic_mutation_intents').update({state:'committed',provider,external_ref:externalRef,receipt_digest:receiptDigest,updated_at:new Date().toISOString()}).eq('semantic_key',semanticKey).in('state',['claimed','committed']).select().single();if(error||!data)throw new Error('semantic_mutation_commit_failed');await appendTransparencyEntry(data.organization_id,'semantic_mutation_committed',semanticKey,{provider,external_ref:externalRef,receipt_digest:receiptDigest});return data}
export async function commitSemanticMutationIfPresent(semanticKey:string,provider:string,externalRef:string,receiptDigest:string){const{data,error}=await serviceClient().from('provider_semantic_mutation_intents').update({state:'committed',provider,external_ref:externalRef,receipt_digest:receiptDigest,updated_at:new Date().toISOString()}).eq('semantic_key',semanticKey).in('state',['claimed','committed']).select().maybeSingle();if(error)throw new Error('semantic_mutation_commit_failed');if(data)await appendTransparencyEntry(data.organization_id,'semantic_mutation_committed',semanticKey,{provider,external_ref:externalRef,receipt_digest:receiptDigest});return data}

export async function inferAndPersistStateMachines(organizationId:string,adapter:any,traces:any[]){const machines=inferProviderStateMachine(adapter.manifest,traces),{error}=await serviceClient().from('provider_inferred_state_machines').insert(machines.map(machine=>({organization_id:organizationId,adapter_id:adapter.id,operation:machine.operation,states:machine.states,transitions:machine.transitions,terminals:machine.terminals,invariants:machine.invariants,coverage:machine.coverage,model_check:machine.model_check,machine_digest:machine.machine_digest,status:machine.status})));if(error)throw new Error('inferred_state_machine_persistence_failed');return machines}

export async function runRegulatoryImpact(organizationId:string,snapshot:any){const sb=serviceClient(),[contracts,employees,events,obligations]=await Promise.all([sb.from('legal_contracts').select('*').eq('organization_id',organizationId).limit(1000),sb.from('workforce_lifecycle_cases').select('*').eq('organization_id',organizationId).limit(1000),sb.from('business_financial_events').select('*').eq('organization_id',organizationId).limit(2000),sb.from('legal_obligations').select('*').eq('organization_id',organizationId).limit(2000)]),resources=[...(contracts.data||[]).map(x=>({type:'contract',id:x.id,data:x})),...(employees.data||[]).map(x=>({type:'employee',id:x.id,data:x})),...(events.data||[]).map(x=>({type:'financial_event',id:x.id,data:x})),...(obligations.data||[]).map(x=>({type:'obligation',id:x.id,data:x}))],impact=simulateRegulatoryImpact(snapshot.rule_manifest||[],resources),{data,error}=await sb.from('provider_regulatory_impact_runs').upsert({organization_id:organizationId,snapshot_id:snapshot.id,impacted_resources:impact.impacted_resources,impact_count:impact.impact_count,risk_summary:impact.risk_summary,simulation_digest:impact.simulation_digest,professional_review_required:true},{onConflict:'snapshot_id,simulation_digest'}).select().single();if(error)throw new Error('regulatory_impact_persistence_failed');return data}

export async function verifyAndPersistSagaModel(saga:any,steps:any[]){const result=modelCheckSaga(steps),{data,error}=await serviceClient().from('provider_saga_model_checks').upsert({organization_id:saga.organization_id,saga_id:saga.id,model_version:result.model_version,explored_states:result.explored_states,invariants:result.invariants,counterexamples:result.counterexamples,model_digest:result.model_digest,status:result.status},{onConflict:'saga_id,model_digest'}).select().single();if(error)throw new Error('saga_model_check_persistence_failed');if(result.status!=='passed')throw new Error(`saga_model_check_failed:${result.counterexamples.map((x:any)=>x.invariant).join(',')}`);return data}

export async function createTreasuryPlan(organizationId:string,userId:string,input:any){const sb=serviceClient(),{data:profiles}=await sb.from('provider_route_profiles').select('*').eq('organization_id',organizationId).in('operation',['send_payment','submit_payroll']),{data:accounts}=await sb.from('connector_accounts').select('id,provider').eq('organization_id',organizationId).eq('status','connected'),rails=(profiles||[]).map(p=>({id:p.connector_account_id,provider:(accounts||[]).find(a=>a.id===p.connector_account_id)?.provider,currency:input.currency||'USD',fee:Number(p.expected_fee_bps||0)*Number(input.typical_amount||1000)/10000,settlement_ms:p.p50_settlement_ms,failure_probability:p.failure_rate})),plan=optimizeTreasuryGraph(Array.isArray(input.obligations)?input.obligations:[],rails,{available_cash:input.available_cash,minimum_reserve:input.minimum_reserve,max_failure_rate:Number(process.env.PROVIDER_ROUTE_MAX_FAILURE_RATE||.15)}),{data,error}=await sb.from('provider_treasury_plans').upsert({organization_id:organizationId,horizon_at:String(input.horizon_at||new Date(Date.now()+7*86400000).toISOString()),currency:String(input.currency||'USD'),obligations:input.obligations||[],rails,schedule:plan.schedule,projected_idle_cash:plan.projected_idle_cash,projected_shortfall:plan.projected_shortfall,expected_cost:plan.expected_cost,approval_actions:plan.approval_actions,plan_digest:plan.plan_digest,state:'proposed',created_by:userId},{onConflict:'organization_id,plan_digest'}).select().single();if(error)throw new Error('treasury_plan_persistence_failed');return data}
