import{serviceClient}from'./fleetSupabase'
import{applyFieldMappings,assignHoldout,estimateCausalEffects,inferFieldMappings,intelligenceDigest,normalizeFinalityEvent,rankProviderAccounts,simulateProviderMutation}from'./providerIntelligence'
import{aggregateFederatedMappings,applyFederatedMappings,counterfactualRoutePlan,evaluateRegulatoryTwinRules,federatedMappingContribution,sequentialCausalAnalysis}from'./providerAutonomy'

const baselineHours:Record<string,number>={send_payment:.5,issue_credit:.4,prepare_invoice:.35,issue_contract:1.5,sign_contract:1,send_renewal_notice:.75,prepare_employee_record:1.25,prepare_payroll_run:3,submit_payroll:1.5,prepare_tax_return:4,reconcile_tax_base:2}

export async function assignProviderExperiment(organizationId:string,sagaId:string,experimentKey='provider-intelligence-v1'){
 const sb=serviceClient(),assignmentUnit=`${organizationId}:${sagaId}:${experimentKey}`,assignment=assignHoldout(assignmentUnit,.1)
 const{data,error}=await sb.from('provider_experiment_assignments').upsert({organization_id:organizationId,saga_id:sagaId,experiment_key:experimentKey,variant:assignment.variant,assignment_unit:assignmentUnit,assignment_digest:assignment.assignment_digest},{onConflict:'saga_id,experiment_key'}).select().single()
 if(error)throw new Error('provider_experiment_assignment_failed');return data
}

export async function prepareProviderExecution(saga:any,step:any,accounts:any[]){
 const sb=serviceClient();let{data:assignment}=await sb.from('provider_experiment_assignments').select('*').eq('saga_id',saga.id).eq('experiment_key','provider-intelligence-v1').maybeSingle()
 if(!assignment)assignment=await assignProviderExperiment(saga.organization_id,saga.id)
 const treatment=assignment.variant==='treatment',pepper=process.env.FEDERATED_MAPPING_PEPPER||'';let effectiveInput=step.input||{},applied:string[]=[]
 if(treatment){
  const{data:mappings}=await sb.from('provider_field_mappings').select('*').eq('organization_id',saga.organization_id).in('provider',accounts.map(account=>account.provider)).eq('operation',step.operation).gte('confidence',.9).gte('support',3)
  const mapped=applyFieldMappings(effectiveInput,mappings||[]);effectiveInput=mapped.input;applied=mapped.applied
  if(pepper){const{data:contributions}=await sb.from('provider_federated_mapping_contributions').select('*').in('provider',accounts.map(account=>account.provider)).eq('operation',step.operation);const federated=applyFederatedMappings(effectiveInput,aggregateFederatedMappings(contributions||[]),pepper);effectiveInput=federated.input;applied.push(...federated.applied)}
 }
 const jurisdiction=String(effectiveInput.jurisdiction||'*');let ranked=accounts.map((account,index)=>({account,score:1-index*.001,profile:null})),profiles:any[]=[]
 if(treatment&&accounts.length){const result=await sb.from('provider_route_profiles').select('*').eq('organization_id',saga.organization_id).eq('operation',step.operation).in('connector_account_id',accounts.map(account=>account.id)).in('jurisdiction',[jurisdiction,'*']);profiles=result.data||[];ranked=rankProviderAccounts(accounts,profiles,step.operation,jurisdiction)}
 const routePlan=counterfactualRoutePlan(accounts,profiles,step.operation,jurisdiction),selected=ranked[0];if(!selected)throw new Error('connected_provider_required')
 const{error:routeError}=await sb.from('provider_counterfactual_routes').upsert({organization_id:saga.organization_id,saga_id:saga.id,step_id:step.id,operation:step.operation,jurisdiction,candidates:routePlan.candidates,selected_connector_account_id:selected.account.id,selection_digest:routePlan.selection_digest,mutation_count:0},{onConflict:'step_id,selection_digest'});if(routeError)throw new Error('counterfactual_route_persistence_failed')
 const twin=simulateProviderMutation(selected.account.provider,step.operation,effectiveInput),{data:rules,error:rulesError}=await sb.from('provider_regulatory_twin_rules').select('*').eq('organization_id',saga.organization_id).eq('status','active').eq('professional_reviewed',true).in('jurisdiction',[jurisdiction,'*']).in('provider',[selected.account.provider,'*']).in('operation',[step.operation,'*']);if(rulesError)throw new Error('regulatory_twin_rules_unavailable');const regulatory=evaluateRegulatoryTwinRules(effectiveInput,rules||[]),checks=[...twin.checks,...regulatory.checks],verdict=twin.verdict==='block'||regulatory.verdict==='block'?'block':twin.verdict==='review'||regulatory.verdict==='review'?'review':'pass',requestDigest=intelligenceDigest({provider:selected.account.provider,operation:step.operation,input:effectiveInput,idempotency_key:step.idempotency_key})
 const{data:twinRun,error}=await sb.from('provider_digital_twin_runs').upsert({organization_id:saga.organization_id,saga_id:saga.id,step_id:step.id,provider:selected.account.provider,operation:step.operation,request_digest:requestDigest,scenario_digest:intelligenceDigest({provider_twin:twin.scenario_digest,regulatory:regulatory.evidence_digest}),verdict,checks,predicted:{...twin.predicted,route_score:selected.score,field_mappings_applied:applied,counterfactual_route_digest:routePlan.selection_digest,regulatory_rule_count:regulatory.checks.length}},{onConflict:'step_id,request_digest'}).select().single()
 if(error)throw new Error('provider_digital_twin_persistence_failed');const failed=checks.filter(check=>!check.passed).map(check=>check.key)
 if(verdict==='block')throw new Error(`digital_twin_block:${failed.join(',')}`);if(String(effectiveInput.environment||'sandbox')==='production'&&verdict==='review')throw new Error(`missing_provider_input:${failed.join(',')}`)
 return{account:selected.account,input:effectiveInput,assignment,twinRun,routeScore:selected.score,fieldMappingsApplied:applied}
}

async function updateRouteProfile(execution:any,success:boolean,latencyMs:number){
 const sb=serviceClient(),jurisdiction=String(execution.response_meta?.jurisdiction||'*'),{data:current}=await sb.from('provider_route_profiles').select('*').eq('connector_account_id',execution.connector_account_id).eq('operation',execution.operation).eq('jurisdiction',jurisdiction).maybeSingle(),n=Number(current?.sample_size||0),sample=n+1,failureRate=((Number(current?.failure_rate||0)*n)+(success?0:1))/sample,p50=n?Math.round((Number(current?.p50_settlement_ms||0)*.8)+(latencyMs*.2)):latencyMs
 await sb.from('provider_route_profiles').upsert({organization_id:execution.organization_id,connector_account_id:execution.connector_account_id,provider:execution.provider,operation:execution.operation,jurisdiction,expected_fee_bps:Number(current?.expected_fee_bps||0),p50_settlement_ms:p50,failure_rate:failureRate,risk_score:Number(current?.risk_score||0),sample_size:sample,updated_at:new Date().toISOString()},{onConflict:'connector_account_id,operation,jurisdiction'})
}

async function persistSequentialAnalysis(organizationId:string){
 const sb=serviceClient(),{data}=await sb.from('provider_outcome_measurements').select('*').eq('organization_id',organizationId).order('measured_at',{ascending:false}).limit(2000),analysis=sequentialCausalAnalysis(data||[])
 await sb.from('provider_sequential_analyses').insert({organization_id:organizationId,experiment_key:'provider-intelligence-v1',analysis_version:analysis.analysis_version,sample_size:analysis.sample_size,information_fraction:analysis.information_fraction,adjusted_effects:analysis.adjusted_effects,alpha_spent:analysis.alpha_spent,decision:analysis.decision,evidence_digest:analysis.evidence_digest})
}

export async function learnFromVerifiedExecution(execution:any){
 const sb=serviceClient(),started=new Date(execution.provider_started_at||execution.created_at).getTime(),latency=Math.max(0,Date.now()-started),{data:step}=await sb.from('agentic_business_saga_steps').select('input').eq('id',execution.step_id).maybeSingle(),input=step?.input||{},pepper=process.env.FEDERATED_MAPPING_PEPPER||''
 for(const inferred of inferFieldMappings(execution.provider,execution.operation,input)){
  const{data:current}=await sb.from('provider_field_mappings').select('*').eq('organization_id',execution.organization_id).eq('provider',execution.provider).eq('operation',execution.operation).eq('source_path',inferred.source_path).eq('target_path',inferred.target_path).maybeSingle(),support=Number(current?.support||0)+1,successes=Number(current?.successes||0)+1,mapping={...inferred,support,successes,confidence:successes/support}
  await sb.from('provider_field_mappings').upsert({organization_id:execution.organization_id,provider:execution.provider,operation:execution.operation,...mapping,last_verified_at:new Date().toISOString()},{onConflict:'organization_id,provider,operation,source_path,target_path'})
  if(pepper){const contribution=federatedMappingContribution(execution.provider,execution.operation,input,mapping,pepper);await sb.from('provider_federated_mapping_contributions').upsert({organization_id:execution.organization_id,...contribution,privacy_epoch:new Date().toISOString().slice(0,10)},{onConflict:'organization_id,provider,operation,schema_fingerprint,source_leaf_hash,target_path,privacy_epoch'})}
 }
 const{data:assignment}=await sb.from('provider_experiment_assignments').select('*').eq('saga_id',execution.saga_id).eq('experiment_key','provider-intelligence-v1').maybeSingle(),providedBaseline=Number(input.baseline_hours),baseline=Math.max(0,Number.isFinite(providedBaseline)&&providedBaseline>0?providedBaseline:baselineHours[execution.operation]??.5),automated=latency/3600000,realized=Number(input.realized_financial_value),value=Number.isFinite(realized)?realized:0
 await sb.from('provider_outcome_measurements').upsert({organization_id:execution.organization_id,saga_id:execution.saga_id,assignment_id:assignment?.id||null,provider:execution.provider,operation:execution.operation,variant:assignment?.variant||'control',automated_hours:automated,baseline_hours:baseline,hours_saved:Math.max(0,baseline-automated),error_count:0,settlement_latency_ms:latency,financial_value:value,currency:String(input.currency||'USD').slice(0,8),non_regressed:true,evidence:{execution_id:execution.id,receipt_digest:execution.receipt_digest,measurement_contract:'provider-outcome/v1',hours_baseline_source:Number.isFinite(providedBaseline)&&providedBaseline>0?'observed_prior_process':'versioned_benchmark',financial_value_source:Number.isFinite(realized)?'realized_input':'unavailable'}},{onConflict:'saga_id,operation'})
 await updateRouteProfile(execution,true,latency);await persistSequentialAnalysis(execution.organization_id)
}

export async function learnFromFailedExecution(execution:any,errorCode:string){
 const sb=serviceClient(),started=new Date(execution.provider_started_at||execution.created_at).getTime(),latency=Math.max(0,Date.now()-started),{data:assignment}=await sb.from('provider_experiment_assignments').select('*').eq('saga_id',execution.saga_id).eq('experiment_key','provider-intelligence-v1').maybeSingle()
 await sb.from('provider_outcome_measurements').upsert({organization_id:execution.organization_id,saga_id:execution.saga_id,assignment_id:assignment?.id||null,provider:execution.provider,operation:execution.operation,variant:assignment?.variant||'control',automated_hours:latency/3600000,baseline_hours:baselineHours[execution.operation]||.5,hours_saved:0,error_count:1,settlement_latency_ms:latency,financial_value:0,non_regressed:false,evidence:{execution_id:execution.id,error_digest:intelligenceDigest(errorCode),measurement_contract:'provider-outcome/v1'}},{onConflict:'saga_id,operation'})
 await updateRouteProfile(execution,false,latency);await persistSequentialAnalysis(execution.organization_id)
}

async function updateSettlementGraph(execution:any,canonicalStatus:string){
 const sb=serviceClient(),{data:prior}=await sb.from('business_provider_executions').select('provider,connector_account_id').eq('saga_id',execution.saga_id).neq('id',execution.id).lt('created_at',execution.created_at).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!prior)return
 const jurisdiction=String(execution.response_meta?.jurisdiction||'*'),{data:current}=await sb.from('provider_settlement_dependencies').select('*').eq('organization_id',execution.organization_id).eq('upstream_provider',prior.provider).eq('downstream_provider',execution.provider).eq('operation',execution.operation).eq('jurisdiction',jurisdiction).maybeSingle(),observations=Number(current?.observations||0)+1,cascadeFailures=Number(current?.cascade_failures||0)+(canonicalStatus==='failed'?1:0)
 const{data:alternate}=await sb.from('provider_route_profiles').select('connector_account_id').eq('organization_id',execution.organization_id).eq('operation',execution.operation).neq('connector_account_id',execution.connector_account_id).order('failure_rate',{ascending:true}).limit(1).maybeSingle()
 await sb.from('provider_settlement_dependencies').upsert({organization_id:execution.organization_id,upstream_provider:prior.provider,downstream_provider:execution.provider,operation:execution.operation,jurisdiction,observations,cascade_failures:cascadeFailures,conditional_failure_rate:cascadeFailures/observations,alternate_connector_account_id:alternate?.connector_account_id||null,updated_at:new Date().toISOString()},{onConflict:'organization_id,upstream_provider,downstream_provider,operation,jurisdiction'})
}

export async function recordFinalityEvent(execution:any,event:any,source:'webhook'|'poll'|'read_after_write'='webhook'){
 const sb=serviceClient(),normalized=normalizeFinalityEvent(execution.provider,event,source),{data,error}=await sb.from('business_provider_finality_events').upsert({organization_id:execution.organization_id,connector_account_id:execution.connector_account_id,execution_id:execution.id,...normalized,verified:true},{onConflict:'connector_account_id,provider_event_id'}).select().single()
 if(error)throw new Error('normalized_finality_persistence_failed');if(['succeeded','failed','cancelled'].includes(normalized.canonical_status))await updateSettlementGraph(execution,normalized.canonical_status);return data
}

export async function providerIntelligenceDashboard(organizationId:string){
 const sb=serviceClient(),q=(table:string,limit=100,order='created_at')=>sb.from(table).select('*').eq('organization_id',organizationId).order(order,{ascending:false}).limit(limit)
 const[mappings,outcomes,twins,adapters,finality,routes,leases,federated,counterfactuals,synthetic,attestations,sequential,dependencies,rules,proofs]=await Promise.all([q('provider_field_mappings'),q('provider_outcome_measurements',500,'measured_at'),q('provider_digital_twin_runs'),q('provider_adapter_manifests',50),q('business_provider_finality_events'),q('provider_route_profiles',100,'updated_at'),q('provider_credential_grants',50),q('provider_federated_mapping_contributions'),q('provider_counterfactual_routes'),q('provider_synthetic_sandbox_runs'),q('provider_workload_attestations'),q('provider_sequential_analyses'),q('provider_settlement_dependencies',100,'updated_at'),q('provider_regulatory_twin_rules'),q('provider_adapter_capability_proofs')]),rows=(result:any)=>result.error?[]:result.data||[],outcomeRows=rows(outcomes),latestSequential=rows(sequential)[0]||sequentialCausalAnalysis(outcomeRows)
 return{mappings:rows(mappings),outcomes:outcomeRows,twins:rows(twins),adapters:rows(adapters),finality:rows(finality),routes:rows(routes),leases:rows(leases),federated:rows(federated),counterfactuals:rows(counterfactuals),synthetic:rows(synthetic),attestations:rows(attestations),sequential:latestSequential,dependencies:rows(dependencies),regulatory_rules:rows(rules),capability_proofs:rows(proofs),causal:estimateCausalEffects(outcomeRows),summary:{learned_mappings:rows(mappings).filter((item:any)=>item.support>=3&&item.confidence>=.9).length,federated_contributions:rows(federated).length,twin_blocks:rows(twins).filter((item:any)=>item.verdict==='block').length,active_adapters:rows(adapters).filter((item:any)=>item.status==='active').length,verified_finality:rows(finality).filter((item:any)=>item.verified).length,active_leases:rows(leases).filter((item:any)=>item.status==='active'&&new Date(item.expires_at)>new Date()).length,verified_attestations:rows(attestations).filter((item:any)=>item.verified).length,proofed_adapters:rows(proofs).filter((item:any)=>item.verified).length,active_regulatory_rules:rows(rules).filter((item:any)=>item.status==='active').length}}
}
