import{createDecipheriv,generateKeyPairSync,privateDecrypt,sign}from'node:crypto'
import{describe,expect,it}from'vitest'
import{canonicalJson,intelligenceDigest}from'./providerIntelligence'
import{diffAuthorityRules,forecastSettlementLiquidity,fuzzProviderLifecycle,globalMutationKey,safeContextualBandit,sealMappingContribution,validateWasmModule,verifyAuthorityManifest,verifySecureMappingAggregate,verifyTeeAttestation}from'./providerSovereignty'

const ed=generateKeyPairSync('ed25519'),publicPem=ed.publicKey.export({type:'spki',format:'pem'}).toString()
const signed=(value:any)=>sign(null,Buffer.from(canonicalJson(value)),ed.privateKey).toString('base64url')

describe('provider sovereignty contracts',()=>{
 it('seals mapping contributions so the control plane cannot inspect them',()=>{const rsa=generateKeyPairSync('rsa',{modulusLength:2048}),sealed=sealMappingContribution({provider:'stripe',operation:'send_payment',schema_fingerprint:'schema',source_leaf_hash:'leaf',target_path:'amount',value_type:'number',support:9,confidence:.99,contribution_digest:'digest'},rsa.publicKey.export({type:'spki',format:'pem'}).toString(),'aggregate-key-1'),envelope=JSON.parse(Buffer.from(sealed.envelope_ciphertext,'base64url').toString()),key=privateDecrypt({key:rsa.privateKey,oaepHash:'sha256'},Buffer.from(envelope.wrapped_key,'base64url')),decipher=createDecipheriv('aes-256-gcm',key,Buffer.from(envelope.iv,'base64url'));decipher.setAuthTag(Buffer.from(envelope.tag,'base64url'));const plain=Buffer.concat([decipher.update(Buffer.from(envelope.ciphertext,'base64url')),decipher.final()]).toString();expect(sealed.envelope_ciphertext).not.toContain('stripe');expect(JSON.parse(plain).provider).toBe('stripe')})
 it('accepts only digest-bound, signed, k-anonymous aggregates',()=>{const core={contract_version:'secure-mapping-aggregate/v1',provider:'stripe',operation:'send_payment',privacy_epoch:'2026-07-16',schema_fingerprint:'schema',source_leaf_hash:'leaf',target_path:'amount',value_type:'number',organization_count:6,support:12,confidence:.97},aggregate={...core,aggregate_digest:intelligenceDigest(core),aggregator_key_id:'agg-1'},row={...aggregate,attestation:signed(aggregate)};expect(verifySecureMappingAggregate(row,publicPem).verified).toBe(true);expect(()=>verifySecureMappingAggregate({...row,support:4},publicPem)).toThrow('secure_aggregate_threshold_not_met')})
 it('validates a state-free WASM execute module',()=>{const bytes=Uint8Array.from([0,97,115,109,1,0,0,0,1,4,1,96,0,0,3,2,1,0,7,11,1,7,101,120,101,99,117,116,101,0,0,10,4,1,2,0,11]);expect(validateWasmModule(bytes,{wasm_imports:[]}).exports).toContainEqual({name:'execute',kind:'function'})})
 it('routes only across safe candidates and logs propensity',()=>{const accounts=[{id:'a',provider:'stripe'},{id:'b',provider:'plaid'}],profiles=[{connector_account_id:'a',operation:'send_payment',jurisdiction:'*',failure_rate:.01,risk_score:.05,sample_size:100},{connector_account_id:'b',operation:'send_payment',jurisdiction:'*',failure_rate:.8,risk_score:.9,sample_size:100}],decision=safeContextualBandit(accounts,profiles,{operation:'send_payment',jurisdiction:'*',step_id:'s'},{exploration_rate:.2});expect(decision.selected_connector_account_id).toBe('a');expect(decision.propensity).toBeGreaterThan(0)})
 it('fuzzes full provider lifecycle paths without invariant violations',()=>{for(const operation of ['send_payment','submit_payroll','sign_contract','prepare_tax_return'])expect(fuzzProviderLifecycle('provider',operation,'seed',250).status).toBe('passed')})
 it('verifies nonce-bound TEE evidence',()=>{const claims={contract_version:'credential-tee-attestation/v1',platform:'nitro',measurement:'sha384:trusted',nonce:'nonce',lease_id:'lease',issued_at:new Date().toISOString(),expires_at:new Date(Date.now()+60000).toISOString(),key_id:'tee-1'},attestation={...claims,signature:signed(claims)};expect(verifyTeeAttestation(attestation,publicPem,'nonce',['sha384:trusted']).verified).toBe(true)})
 it('ingests signed primary authority and creates review proposals',()=>{const manifest={contract_version:'regulatory-authority/v1',jurisdiction:'US-CA',effective_at:new Date().toISOString(),key_id:'ca-1',rules:[{rule_key:'notice',invariant:{operator:'required'},source_uri:'https://ca.gov/rule'}]},verified=verifyAuthorityManifest({...manifest,signature:signed(manifest)},publicPem);expect(verified.verified).toBe(true);expect(diffAuthorityRules([] as any[],verified.rules)).toHaveLength(1)})
 it('clears the same business mutation across providers with one global key',()=>{expect(globalMutationKey('stripe','send_payment','stable-key')).toBe(globalMutationKey('plaid','send_payment','stable-key'))})
 it('forecasts stressed liquidity from unsettled provider work',()=>{const forecast=forecastSettlementLiquidity([{state:'provider_pending',response_meta:{amount:1000,currency:'USD',failure_rate:.1}}],{now:Date.UTC(2026,6,16),available_liquidity:500});expect(forecast.stressed_outflow).toBeGreaterThan(1000);expect(forecast.shortfall).toBeGreaterThan(0)})
})
