import test from'node:test'
import assert from'node:assert/strict'
import{generateKeyPairSync,sign}from'node:crypto'
import{canonicalJson}from'./providerIntelligence'
import{buildObligationGraph,computeLiquidityNetting,designChaosMarket,generateSagaTla,assignCausalTreasuryWindow,compileProviderEvidence,verifyClearingConsensus,verifyFormalReceipt}from'./providerNetworkExecution'
test('obligation graph blocks semantic duplicates',()=>{const graph=buildObligationGraph([{id:'a',organization_id:'o',payee_id:'p',amount:10,currency:'USD',due_at:'2027-01-01',invoice_number:'1'},{id:'b',organization_id:'o',payee_id:'p',amount:10,currency:'USD',due_at:'2027-01-01',invoice_number:'1'}]);assert.equal(graph.duplicate_clusters.length,1);assert.equal(graph.duplicate_clusters[0].disposition,'block_duplicate_execution')})
test('liquidity netting reduces settlement without executing',()=>{const r=computeLiquidityNetting([{participant_id:'a',currency:'USD',payable:100,receivable:40},{participant_id:'b',currency:'USD',payable:40,receivable:100}]);assert.equal(r.gross_notional,140);assert.equal(r.net_settlement_notional,60);assert.equal(r.state,'approval_required')})
test('chaos market is sandbox and reversible only',()=>{const r=designChaosMarket([{provider:'a',operation:'pay',environment:'production',reversible:true},{provider:'b',operation:'pay',environment:'sandbox',reversible:true}]);assert.equal(r.experiments.length,1);assert.equal(r.experiments[0].production_mutation,false)})
test('formal model and causal assignment are deterministic',()=>{assert.equal(generateSagaTla({id:'s'},[{id:'x',step_index:0}]).model_digest,generateSagaTla({id:'s'},[{id:'x',step_index:0}]).model_digest);assert.deepEqual(assignCausalTreasuryWindow('a','x'),assignCausalTreasuryWindow('a','x'))})
test('provider compiler requires executable evidence',()=>{const r=compileProviderEvidence({provider:'p',version:'1',openapi:{},webhooks:{},sandbox_traces:[]});assert.equal(r.proof_ready,true)})
test('clearing consensus requires distinct signed institutions and regions',()=>{const keyring:Record<string,string>={},votes=[['bank-a','us-east'],['bank-b','us-west'],['bank-c','eu']].map(([institution_id,region],i)=>{const{privateKey,publicKey}=generateKeyPairSync('ed25519'),key_id=`k${i}`,claims={contract_version:'provider-clearing-vote/v1',round_digest:'r',obligation_digest:'o',decision:'accept',institution_id,region,key_id};keyring[key_id]=publicKey.export({type:'spki',format:'pem'}).toString();return{...claims,signature:sign(null,Buffer.from(canonicalJson(claims)),privateKey).toString('base64url')}}),certificate=verifyClearingConsensus({obligation_digest:'o',round_digest:'r'},votes,keyring,3);assert.equal(certificate.institutions.length,3);assert.equal(certificate.regions.length,3)})
test('formal verification accepts only a signed passing external receipt',()=>{const{privateKey,publicKey}=generateKeyPairSync('ed25519'),model={model_digest:'m'},claims={contract_version:'formal-verifier-receipt/v1',model_digest:'m',engine:'apalache',engine_version:'1',status:'passed',states_explored:42,counterexample_digest:null,issued_at:'2026-07-17T00:00:00Z',key_id:'formal'},receipt={...claims,signature:sign(null,Buffer.from(canonicalJson(claims)),privateKey).toString('base64url')};assert.equal(verifyFormalReceipt(model,receipt,{formal:publicKey.export({type:'spki',format:'pem'}).toString()}).verified,true)})
