import{createPublicKey,verify as verifySignature}from'node:crypto'
import{canonicalJson,intelligenceDigest}from'./providerIntelligence'

const signed=(claims:any,signature:string,pem:string)=>verifySignature(null,Buffer.from(canonicalJson(claims)),createPublicKey(pem),Buffer.from(signature,'base64url'))

export function verifyClearingConsensus(intent:any,votes:any[],keyring:Record<string,string>,minimum=3){const digest=String(intent.obligation_digest||''),roundDigest=String(intent.round_digest||''),seenInstitutions=new Set<string>(),regions=new Set<string>(),valid:any[]=[];if(!roundDigest)throw new Error('clearing_consensus_round_digest_required');for(const vote of votes){const institution=String(vote.institution_id||''),keyId=String(vote.key_id||''),pem=keyring[keyId],claims={contract_version:'provider-clearing-vote/v1',round_digest:vote.round_digest,obligation_digest:digest,decision:vote.decision,institution_id:institution,region:vote.region,key_id:keyId};if(!pem||vote.round_digest!==roundDigest||!institution||seenInstitutions.has(institution)||vote.decision!=='accept'||!signed(claims,String(vote.signature||''),pem))continue;seenInstitutions.add(institution);regions.add(String(vote.region||''));valid.push({...claims,vote_digest:intelligenceDigest(claims)})}if(valid.length<minimum)throw new Error('clearing_consensus_quorum_not_met');if(regions.size<2)throw new Error('clearing_consensus_region_diversity_required');const validVotes=valid.sort((a,b)=>a.institution_id.localeCompare(b.institution_id));return{contract_version:'provider-clearing-certificate/v1',round_digest:roundDigest,obligation_digest:digest,quorum:minimum,institutions:[...seenInstitutions].sort(),regions:[...regions].filter(Boolean).sort(),valid_votes:validVotes,certificate_digest:intelligenceDigest({round_digest:roundDigest,obligation_digest:digest,votes:validVotes})}}

export function verifyThresholdCeremony(ceremony:any,attestations:any[],keyring:Record<string,string>){const threshold=Math.max(2,Number(ceremony.threshold||0)),regions=new Set<string>(),custodians=new Set<string>(),valid:any[]=[];for(const a of attestations){const custodian=String(a.custodian_id||''),keyId=String(a.key_id||''),pem=keyring[keyId],claims={contract_version:'threshold-ceremony-attestation/v1',ceremony_digest:ceremony.ceremony_digest,public_key_digest:ceremony.public_key_digest,measurement:a.measurement,region:a.region,custodian_id:custodian,key_id:keyId};if(!pem||!custodian||custodians.has(custodian)||!a.measurement||!signed(claims,String(a.signature||''),pem))continue;custodians.add(custodian);regions.add(String(a.region||''));valid.push({...claims,attestation_digest:intelligenceDigest(claims)})}if(valid.length<threshold)throw new Error('threshold_ceremony_quorum_not_met');if(regions.size<Math.min(3,threshold))throw new Error('threshold_ceremony_geo_separation_required');const validAttestations=valid.sort((a,b)=>a.custodian_id.localeCompare(b.custodian_id));return{verified:true,threshold,attested_custodians:[...custodians].sort(),regions:[...regions].filter(Boolean).sort(),valid_attestations:validAttestations,transcript_digest:intelligenceDigest({ceremony_digest:ceremony.ceremony_digest,attestations:validAttestations})}}

export function generateSagaTla(saga:any,steps:any[]){const ordered=[...steps].sort((a,b)=>Number(a.step_index??a.step_order)-Number(b.step_index??b.step_order)),name=(s:any)=>String(s.id).replace(/[^A-Za-z0-9_]/g,'_'),names=ordered.map(name),external=ordered.filter((s:any)=>s.external_effect===true).map(name),approved=ordered.filter((s:any)=>s.approval_required===true||Boolean(s.approval_id)||!s.external_effect).map(name),authorized=ordered.filter((s:any)=>!s.external_effect||Boolean(s.authority_scope)).map(name),set=(xs:string[])=>xs.length?`{${xs.map(x=>`\"${x}\"`).join(', ')}}`:'{}',moduleName=`Saga_${String(saga.id).replace(/[^A-Za-z0-9_]/g,'_')}`,source=`---- MODULE ${moduleName} ----\nEXTENDS Naturals, Sequences\nCONSTANT Steps, External, Approved, Authorized\nVARIABLE pc\nInit == pc = 0\nNext == /\\ pc < Len(Steps) /\\ pc' = pc + 1\nApprovalSafety == External \\subseteq Approved\nAuthoritySafety == External \\subseteq Authorized\nSpec == Init /\\ [][Next]_pc\n====`,config=`CONSTANT Steps = <<${names.map(x=>`\"${x}\"`).join(', ')}>>\nCONSTANT External = ${set(external)}\nCONSTANT Approved = ${set(approved)}\nCONSTANT Authorized = ${set(authorized)}\nINVARIANT ApprovalSafety\nINVARIANT AuthoritySafety`;return{module_name:moduleName,source,config,model_digest:intelligenceDigest({moduleName,source,config})}}

export function verifyFormalReceipt(model:any,receipt:any,keyring:Record<string,string>){const keyId=String(receipt?.key_id||''),pem=keyring[keyId],claims={contract_version:'formal-verifier-receipt/v1',model_digest:model.model_digest,engine:receipt?.engine,engine_version:receipt?.engine_version,status:receipt?.status,states_explored:receipt?.states_explored,counterexample_digest:receipt?.counterexample_digest||null,issued_at:receipt?.issued_at,key_id:keyId};if(!pem||!['apalache','tlc'].includes(String(receipt?.engine))||receipt?.status!=='passed'||Number(receipt?.states_explored)<1||!signed(claims,String(receipt?.signature||''),pem))throw new Error('formal_verifier_receipt_invalid');return{verified:true,...claims,receipt_digest:intelligenceDigest(claims)}}

export function verifyPrivateOptimizationReceipt(request:any,receipt:any,keyring:Record<string,string>){if(request.plaintext||request.positions||request.obligations)throw new Error('private_optimizer_plaintext_forbidden');const keyId=String(receipt?.key_id||''),pem=keyring[keyId],claims={contract_version:'private-optimization-receipt/v1',request_digest:intelligenceDigest(request),ciphertext_digest:request.ciphertext_digest,result_ciphertext_digest:receipt?.result_ciphertext_digest,proof_digest:receipt?.proof_digest,scheme:receipt?.scheme,verified:receipt?.verified,key_id:keyId};if(!pem||receipt?.verified!==true||!['ckks','bfv','bgv','tfhe'].includes(String(receipt?.scheme).toLowerCase())||!signed(claims,String(receipt?.signature||''),pem))throw new Error('private_optimization_receipt_invalid');return{...claims,receipt_digest:intelligenceDigest(claims)}}

export function assignCausalTreasuryWindow(subjectKey:string,experimentKey:string,holdout=.1){const bucket=parseInt(intelligenceDigest({subjectKey,experimentKey}).slice(0,8),16)/0xffffffff,arm=bucket<Math.max(0,Math.min(.5,holdout))?'holdout':'optimized';return{contract_version:'causal-treasury-assignment/v1',subject_key:subjectKey,experiment_key:experimentKey,arm,bucket:Number(bucket.toFixed(8)),assignment_digest:intelligenceDigest({subjectKey,experimentKey,arm})}}

const norm=(v:any)=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ')
export function buildObligationGraph(records:any[]){const nodes=records.map((r:any)=>{const identity={organization:r.organization_id||'',counterparty:norm(r.counterparty_id||r.payee_id||r.employee_id),amount:Number(r.amount||0).toFixed(2),currency:norm(r.currency||'usd'),due:norm(r.due_at||r.effective_date||r.period),purpose:norm(r.invoice_number||r.contract_id||r.tax_form||r.description)};return{id:String(r.id),kind:String(r.kind||r.type||'obligation'),identity,fingerprint:intelligenceDigest(identity)}}),groups=new Map<string,any[]>();for(const node of nodes)(groups.get(node.fingerprint)||groups.set(node.fingerprint,[]).get(node.fingerprint)!).push(node);const duplicate_clusters=[...groups.entries()].filter(([,xs])=>xs.length>1).map(([fingerprint,xs])=>({fingerprint,node_ids:xs.map(x=>x.id).sort(),confidence:1,disposition:'block_duplicate_execution'})),edges=duplicate_clusters.flatMap(c=>c.node_ids.slice(1).map(id=>({from:c.node_ids[0],to:id,type:'semantic_duplicate',fingerprint:c.fingerprint})));return{nodes,edges,duplicate_clusters,graph_digest:intelligenceDigest({nodes,edges})}}

export function computeLiquidityNetting(positions:any[]){const totals=new Map<string,number>();for(const p of positions){const currency=String(p.currency||'USD').toUpperCase(),key=`${String(p.participant_id)}:${currency}`;totals.set(key,(totals.get(key)||0)+Number(p.receivable||0)-Number(p.payable||0))}const net_positions=[...totals].map(([key,amount])=>{const[participant_id,currency]=key.split(':');return{participant_id,currency,net_amount:Number(amount.toFixed(2))}}).sort((a,b)=>a.currency.localeCompare(b.currency)||a.participant_id.localeCompare(b.participant_id)),byCurrency=new Map<string,number>();for(const p of net_positions)byCurrency.set(p.currency,(byCurrency.get(p.currency)||0)+p.net_amount);const imbalances=[...byCurrency].filter(([,v])=>Math.abs(v)>.01);if(imbalances.length)throw new Error('liquidity_netting_unbalanced');const gross=positions.reduce((n,p)=>n+Number(p.payable||0),0),residual=net_positions.filter(x=>x.net_amount<0).reduce((n,x)=>n-x.net_amount,0),result={contract_version:'liquidity-netting-round/v1',net_positions,gross_notional:Number(gross.toFixed(2)),net_settlement_notional:Number(residual.toFixed(2)),saved_notional:Number(Math.max(0,gross-residual).toFixed(2)),state:'approval_required'};return{...result,round_digest:intelligenceDigest(result)}}

export function designChaosMarket(capabilities:any[],budget:any={}){const maxExperiments=Math.min(20,Math.max(1,Number(budget.max_experiments||5))),sandbox=capabilities.filter((x:any)=>x.environment==='sandbox'&&x.reversible===true).slice(0,maxExperiments),experiments=sandbox.map((x:any,i:number)=>({id:`chaos-${i+1}`,provider:x.provider,operation:x.operation,fault:['timeout','duplicate_webhook','out_of_order_webhook','rate_limit'][i%4],blast_radius:1,production_mutation:false,success_contract:['no_duplicate_effect','terminal_finality','bounded_retry']}));return{experiments,rejected:capabilities.length-sandbox.length,market_digest:intelligenceDigest({experiments,budget})}}

export function verifyAuthorityRulePackage(pkg:any,keyring:Record<string,string>,now=Date.now()){const keyId=String(pkg.key_id||''),pem=keyring[keyId],claims={contract_version:'authority-rule-package/v1',authority_source_id:pkg.authority_source_id,jurisdiction:pkg.jurisdiction,package_version:pkg.package_version,effective_at:pkg.effective_at,expires_at:pkg.expires_at||null,rules_digest:intelligenceDigest(pkg.rules||[]),key_id:keyId};if(!pem||!pkg.jurisdiction||!pkg.package_version||!Array.isArray(pkg.rules)||!pkg.rules.length||!signed(claims,String(pkg.signature||''),pem))throw new Error('authority_rule_package_invalid');if(pkg.expires_at&&new Date(pkg.expires_at).getTime()<=now)throw new Error('authority_rule_package_expired');const bad=pkg.rules.find((r:any)=>!r.rule_key||!r.domain||!r.invariant?.operator);if(bad)throw new Error('authority_rule_schema_invalid');return{verified:true,claims,package_digest:intelligenceDigest(claims),verification_digest:intelligenceDigest({claims,verified:true})}}

export function compileProviderEvidence(input:any){const sources=['openapi','webhooks','sdk','docs','sandbox_traces'].filter(k=>input[k]!==undefined&&input[k]!==null),missing=['openapi','webhooks','sandbox_traces'].filter(k=>input[k]===undefined||input[k]===null),artifacts=sources.map(kind=>({kind,digest:intelligenceDigest(input[kind])}));return{sources,artifacts,missing_required:missing,proof_ready:missing.length===0,compiler_digest:intelligenceDigest({artifacts,provider:input.provider,version:input.version})}}
