import{generateKeyPairSync,sign}from'node:crypto'
import{describe,expect,it}from'vitest'
import{applyFieldMappings,assignHoldout,canonicalJson,compileOpenApiAdapter,estimateCausalEffects,inferFieldMappings,intelligenceDigest,normalizeFinalityEvent,rankProviderAccounts,runSandboxConformance,signAdapterForTest,simulateProviderMutation,verifyCredentialLease}from'./providerIntelligence'

const spec={openapi:'3.1.0',info:{title:'Sandbox',version:'1'},servers:[{url:'https://api.gusto-demo.com'}],components:{securitySchemes:{bearer:{type:'http',scheme:'bearer'}}},paths:{'/v1/payrolls/{id}':{put:{operationId:'updatePayroll',responses:{'200':{description:'ok'}}}}}}
describe('provider intelligence mesh',()=>{
 it('learns only schema paths and activates proven mappings',()=>{const inferred=inferFieldMappings('stripe','send_payment',{payment:{total:42},currency_code:'usd'});expect(inferred).toEqual(expect.arrayContaining([expect.objectContaining({source_path:'payment.total',target_path:'amount'}),expect.objectContaining({target_path:'currency'})]));const applied=applyFieldMappings({payment:{total:42}},[{source_path:'payment.total',target_path:'amount',confidence:.95,support:3}]);expect(applied.input.amount).toBe(42);expect(applyFieldMappings({payment:{total:42}},[{source_path:'payment.total',target_path:'amount',confidence:.95,support:2}]).input.amount).toBeUndefined()})
 it('assigns stable randomized holdouts near the requested rate',()=>{expect(assignHoldout('same')).toEqual(assignHoldout('same'));const controls=Array.from({length:1000},(_,i)=>assignHoldout(`saga-${i}`)).filter(x=>x.variant==='control').length;expect(controls).toBeGreaterThan(70);expect(controls).toBeLessThan(130)})
 it('computes causal confidence bounds and requires real sample sizes',()=>{const rows=[...Array.from({length:40},()=>({variant:'treatment',hours_saved:4,error_count:0,settlement_latency_ms:100,financial_value:20})),...Array.from({length:20},()=>({variant:'control',hours_saved:1,error_count:0,settlement_latency_ms:200,financial_value:0}))],effect=estimateCausalEffects(rows);expect(effect.effects.hours_saved.effect).toBe(3);expect(effect.effects.settlement_latency_ms.effect).toBe(-100);expect(effect.promotion_ready).toBe(true)})
 it('compiles a host-pinned signed OpenAPI adapter',()=>{const compiled=compileOpenApiAdapter(spec,{provider:'gusto',version:'1',allowedOrigins:['https://api.gusto-demo.com']});expect(compiled.manifest.operations[0].operation_id).toBe('updatePayroll');expect(compiled.manifest.auth[0].scheme).toBe('bearer');expect(signAdapterForTest(compiled.digest,'test').signature).toBeTruthy();expect(()=>compileOpenApiAdapter({...spec,servers:[{url:'https://evil.test'}]},{provider:'gusto',version:'1',allowedOrigins:['https://api.gusto-demo.com']})).toThrow('adapter_server_not_allowlisted')})
 it('runs sandbox conformance and refuses non-2xx success definitions',async()=>{const manifest=compileOpenApiAdapter(spec,{provider:'gusto',version:'1',allowedOrigins:['https://api.gusto-demo.com']}).manifest;const result=await runSandboxConformance(manifest,[{operation_id:'updatePayroll',path_params:{id:'p1'},expected_statuses:[200]}],async request=>({status:request.url.includes('/p1')?200:500}));expect(result.status).toBe('passed');const invalid=await runSandboxConformance(manifest,[{operation_id:'updatePayroll',expected_statuses:[401]}],async()=>({status:401}));expect(invalid.status).toBe('failed')})
 it('blocks unsafe mutations in the digital twin before provider calls',()=>{expect(simulateProviderMutation('stripe','send_payment',{amount:-1,currency:'usd'}).verdict).toBe('block');expect(simulateProviderMutation('docusign','issue_contract',{envelope:{recipients:{signers:[{email:'a@example.com'}]}}}).verdict).toBe('pass')})
 it('routes toward lower observed failure, latency, cost and risk',()=>{const accounts=[{id:'slow'},{id:'fast'}],profiles=[{connector_account_id:'slow',operation:'send_payment',jurisdiction:'*',expected_fee_bps:100,p50_settlement_ms:500000,failure_rate:.2,risk_score:.3},{connector_account_id:'fast',operation:'send_payment',jurisdiction:'*',expected_fee_bps:5,p50_settlement_ms:1000,failure_rate:.01,risk_score:.05}];expect(rankProviderAccounts(accounts,profiles,'send_payment')[0].account.id).toBe('fast')})
 it('normalizes different provider events into one finality contract',()=>{const event=normalizeFinalityEvent('docusign',{id:'evt-1',envelopeId:'env-1',envelopeStatus:'completed'});expect(event).toMatchObject({provider_event_id:'evt-1',external_ref:'env-1',canonical_status:'succeeded',source:'webhook'})})
 it('verifies a short-lived broker lease signed by an asymmetric key',()=>{const{privateKey,publicKey}=generateKeyPairSync('ed25519'),credential={access_token:'temporary'},base={lease_id:'lease-1',credential_ref:'hsm://gusto/a',credential_digest:intelligenceDigest(credential),expires_at:new Date(Date.now()+300000).toISOString(),nonce:'n',key_id:'key-1'},signature=sign(null,Buffer.from(canonicalJson(base)),privateKey).toString('base64url'),verified=verifyCredentialLease({...base,credential,signature},publicKey.export({type:'spki',format:'pem'}).toString(),'n');expect(verified.credential.access_token).toBe('temporary')})
})
