import{generateKeyPairSync,sign}from'node:crypto'
import{describe,expect,it}from'vitest'
import{canonicalJson,intelligenceDigest}from'./providerIntelligence'
import{inferProviderStateMachine,modelCheckSaga,optimizeTreasuryGraph,selectProviderAuctionQuote,semanticMutationIntent,simulateRegulatoryImpact,verifyThresholdAggregateProof}from'./providerSovereigntyCompounding'

describe('compounding provider sovereignty',()=>{
 it('requires an independently verifiable threshold quorum',()=>{const keys=Array.from({length:3},()=>generateKeyPairSync('ed25519')),aggregate={aggregate_digest:'aggregate'},quorum=2,transcript=intelligenceDigest({aggregate_digest:'aggregate',signer_key_ids:['k0','k1'],quorum}),signatures=keys.slice(0,2).map((key,index)=>{const key_id=`k${index}`,payload={contract_version:'threshold-aggregate-share/v1',aggregate_digest:'aggregate',transcript_digest:transcript,key_id};return{key_id,signature:sign(null,Buffer.from(canonicalJson(payload)),key.privateKey).toString('base64url')}}),keyring=Object.fromEntries(keys.map((key,index)=>[`k${index}`,key.publicKey.export({type:'spki',format:'pem'}).toString()]));expect(verifyThresholdAggregateProof(aggregate,{quorum,transcript_digest:transcript,signatures,zk_required:false},keyring).valid_signers).toHaveLength(2);expect(()=>verifyThresholdAggregateProof(aggregate,{quorum:3,transcript_digest:transcript,signatures},keyring)).toThrow('threshold_aggregate_quorum_not_met')})
 it('creates semantic identities stable across provider rails',()=>{const a=semanticMutationIntent('send_payment',{payer_id:'org',payee_id:'vendor',amount:100,currency:'usd',invoice_id:'inv-1'},{organization_id:'org'}),b=semanticMutationIntent('send_payment',{payer_id:'org',payee_id:'vendor',amount:100,currency:'usd',invoice_id:'inv-1'},{organization_id:'org'});expect(a.semantic_key).toBe(b.semantic_key)})
 it('selects only live non-mutating safe auction quotes',()=>{const future=new Date(Date.now()+60000).toISOString(),result=selectProviderAuctionQuote([{connector_account_id:'cheap-risky',fee:1,settlement_ms:1,failure_probability:.8,risk_score:.9,expires_at:future,non_mutating:true,authorization_only:true},{connector_account_id:'safe',fee:2,settlement_ms:1000,failure_probability:.01,risk_score:.02,expires_at:future,non_mutating:true,authorization_only:true}],{amount:100});expect(result.selected.connector_account_id).toBe('safe')})
 it('infers and model-checks state machines from traces',()=>{const machines=inferProviderStateMachine({operations:[{operation_id:'pay'}]},[{operation:'pay',from_state:'created',to_state:'pending'},{operation:'pay',from_state:'pending',to_state:'succeeded'},{operation:'pay',from_state:'pending',to_state:'failed'}]);expect(machines[0].status).toBe('verified');expect(machines[0].terminals).toEqual(['failed','succeeded'])})
 it('optimizes treasury scheduling while preserving reserve',()=>{const plan=optimizeTreasuryGraph([{id:'bill',amount:400,currency:'USD',due_at:new Date(Date.now()+86400000).toISOString()}],[{id:'rail',currency:'USD',fee:1,settlement_ms:1000,failure_probability:.01}],{available_cash:1000,minimum_reserve:500});expect(plan.schedule[0].state).toBe('scheduled');expect(plan.projected_idle_cash).toBe(100)})
 it('simulates rule impact without activating the rule',()=>{const impact=simulateRegulatoryImpact([{rule_key:'email',resource_type:'employee',severity:'block',invariant:{path:'email',operator:'required'}}],[{type:'employee',id:'e1',data:{email:''}}]);expect(impact.impact_count).toBe(1);expect(impact.professional_review_required).toBe(true)})
 it('rejects sagas that bypass approval or authority',()=>{const good=modelCheckSaga([{id:'one',step_index:0,idempotency_key:'a',external_effect:true,approval_id:'approval',authority_scope:'payments.submit',state:'claimed',reversible:false}]),bad=modelCheckSaga([{id:'one',step_index:0,idempotency_key:'a',external_effect:true,state:'ready',reversible:false}]);expect(good.status).toBe('passed');expect(bad.status).toBe('failed')})
})
