import{createHmac}from'node:crypto'
import{canonicalJson,intelligenceDigest,scoreProviderRoute}from'./providerIntelligence'

const leaf=(path:string)=>path.split('.').pop()!.replace(/[^a-z0-9]/gi,'_').toLowerCase()
const flatten=(value:any,prefix='',depth=0):Array<{path:string;value:any}>=>{if(depth>6||value===null||value===undefined)return[];if(Array.isArray(value))return[{path:prefix,value}];if(typeof value!=='object')return[{path:prefix,value}];return Object.entries(value).flatMap(([key,item])=>flatten(item,prefix?`${prefix}.${key}`:key,depth+1))}
const fieldHash=(name:string,pepper:string)=>createHmac('sha256',pepper).update(name).digest('hex')
export function schemaFingerprint(input:any){const shape=flatten(input).map(item=>`${item.path.replace(/[^.]+$/,'*')}:${Array.isArray(item.value)?'array':typeof item.value}`).sort();return intelligenceDigest(shape)}
export function federatedMappingContribution(provider:string,operation:string,input:any,mapping:any,pepper:string){if(!pepper||pepper.length<16)throw new Error('federated_mapping_pepper_required');const source=flatten(input).find(item=>item.path===mapping.source_path);if(!source)throw new Error('mapping_source_not_present');return{provider,operation,schema_fingerprint:schemaFingerprint(input),source_leaf_hash:fieldHash(leaf(mapping.source_path),pepper),target_path:String(mapping.target_path),value_type:Array.isArray(source.value)?'array':typeof source.value,support:Number(mapping.support||1),confidence:Number(mapping.confidence||1),contribution_digest:intelligenceDigest({provider,operation,schema_fingerprint:schemaFingerprint(input),source_leaf_hash:fieldHash(leaf(mapping.source_path),pepper),target_path:mapping.target_path,value_type:Array.isArray(source.value)?'array':typeof source.value})}}
export function aggregateFederatedMappings(rows:any[],minimumOrganizations=5){const groups=new Map<string,any[]>();for(const row of rows){const key=[row.provider,row.operation,row.schema_fingerprint,row.source_leaf_hash,row.target_path,row.value_type].join(':');groups.set(key,[...(groups.get(key)||[]),row])}return[...groups.values()].flatMap(group=>{const organizations=new Set(group.map(row=>row.organization_id)),support=group.reduce((sum,row)=>sum+Number(row.support||0),0),confidence=group.reduce((sum,row)=>sum+Number(row.confidence||0)*Number(row.support||0),0)/Math.max(1,support);return organizations.size>=minimumOrganizations&&support>=minimumOrganizations&&confidence>=.9?[{provider:group[0].provider,operation:group[0].operation,schema_fingerprint:group[0].schema_fingerprint,source_leaf_hash:group[0].source_leaf_hash,target_path:group[0].target_path,value_type:group[0].value_type,organization_count:organizations.size,support,confidence:Number(confidence.toFixed(4)),privacy_contract:'schema-only-k-anonymous/v1'}]:[]})}
export function applyFederatedMappings(input:any,mappings:any[],pepper:string){const result=structuredClone(input||{}),items=flatten(result),applied:string[]=[];for(const mapping of mappings){if(mapping.organization_count<5||mapping.confidence<.9)continue;const found=items.find(item=>fieldHash(leaf(item.path),pepper)===mapping.source_leaf_hash);if(!found)continue;const keys=String(mapping.target_path).split('.');let current=result;for(const key of keys.slice(0,-1))current=current[key]??={};if(current[keys.at(-1)!]===undefined){current[keys.at(-1)!]=found.value;applied.push(`federated:${mapping.target_path}`)}}return{input:result,applied}}

function sampleForSchema(schema:any,mode:'valid'|'minimum'|'maximum'='valid'):any{if(!schema)return{};if(schema.enum?.length)return schema.enum[0];if(schema.type==='object'||schema.properties){const out:any={};for(const key of schema.required||[])out[key]=sampleForSchema(schema.properties?.[key]||{},mode);return out}if(schema.type==='array')return[sampleForSchema(schema.items||{},mode)];if(schema.type==='integer'||schema.type==='number')return mode==='maximum'?(schema.maximum??100):mode==='minimum'?(schema.minimum??0):(schema.minimum??1);if(schema.type==='boolean')return true;if(schema.format==='email')return'conformance@example.invalid';if(schema.format==='date')return'2030-01-01';if(schema.format==='date-time')return'2030-01-01T00:00:00.000Z';return String(schema.minLength? 'x'.repeat(schema.minLength):'conformance')}
function validateSchema(value:any,schema:any,path='$'):string[]{if(!schema)return[];const errors:string[]=[];if(schema.type==='object'||schema.properties){if(!value||typeof value!=='object'||Array.isArray(value))return[`${path}:object_required`];for(const key of schema.required||[])if(value[key]===undefined)errors.push(`${path}.${key}:required`);for(const[key,child]of Object.entries<any>(schema.properties||{}))if(value[key]!==undefined)errors.push(...validateSchema(value[key],child,`${path}.${key}`))}else if(schema.type==='array'&&!Array.isArray(value))errors.push(`${path}:array_required`);else if(schema.type==='string'&&typeof value!=='string')errors.push(`${path}:string_required`);else if(['number','integer'].includes(schema.type)&&!Number.isFinite(Number(value)))errors.push(`${path}:number_required`);if(schema.enum&&!schema.enum.includes(value))errors.push(`${path}:enum`);if(typeof value==='number'&&schema.minimum!==undefined&&value<schema.minimum)errors.push(`${path}:minimum`);if(typeof value==='number'&&schema.maximum!==undefined&&value>schema.maximum)errors.push(`${path}:maximum`);return errors}
export function generateSyntheticConformanceCases(manifest:any,limit=100){const cases:any[]=[];for(const operation of manifest.operations||[]){const schema=operation.request_schema||{type:'object',properties:{}};for(const mode of ['valid','minimum','maximum']as const)cases.push({operation_id:operation.operation_id,name:`${operation.operation_id}:${mode}`,body:sampleForSchema(schema,mode),expected_valid:true,schema});for(const required of (schema.required||[]).slice(0,10)){const body=sampleForSchema(schema);delete body[required];cases.push({operation_id:operation.operation_id,name:`${operation.operation_id}:missing:${required}`,body,expected_valid:false,schema})}}return cases.slice(0,Math.max(1,Math.min(500,limit)))}
export function runSyntheticSchemaConformance(manifest:any,limit=100){const cases=generateSyntheticConformanceCases(manifest,limit),tests=cases.map(test=>{const errors=validateSchema(test.body,test.schema),passed=test.expected_valid?errors.length===0:errors.length>0;return{name:test.name,operation_id:test.operation_id,expected_valid:test.expected_valid,passed,error_codes:errors}});const operations=new Set(cases.map(item=>item.operation_id));return{status:tests.every(test=>test.passed)?'passed':'failed',case_count:tests.length,passed:tests.filter(test=>test.passed).length,failed:tests.filter(test=>!test.passed).length,coverage:{operations:operations.size,required_field_negatives:cases.filter(item=>!item.expected_valid).length,boundary_cases:cases.filter(item=>item.expected_valid).length},tests,evidence_digest:intelligenceDigest(tests)}}

export function buildAdapterCapabilityProof(manifest:any){const origins=[...new Set((manifest.servers||[]).map((server:string)=>new URL(server).origin))].sort(),methods=[...new Set((manifest.operations||[]).map((operation:any)=>String(operation.method).toUpperCase()))].sort(),operations=(manifest.operations||[]).map((operation:any)=>String(operation.operation_id)).sort(),dataPaths=[...new Set((manifest.operations||[]).flatMap((operation:any)=>(operation.parameters||[]).map((parameter:any)=>String(parameter.name))))].sort();const proof={proof_version:'adapter-capability/v1',manifest_digest:intelligenceDigest(manifest),declared_origins:origins,declared_methods:methods,declared_operations:operations,declared_data_paths:dataPaths,network_default_deny:true,filesystem_default_deny:true,subprocess_default_deny:true};return{proof,proof_digest:intelligenceDigest(proof)}}
export function verifyAdapterCapabilityProof(manifest:any,proof:any){const expected=buildAdapterCapabilityProof(manifest);if(proof.proof_version!=='adapter-capability/v1'||proof.manifest_digest!==expected.proof.manifest_digest)throw new Error('adapter_capability_manifest_mismatch');for(const key of ['declared_origins','declared_methods','declared_operations','declared_data_paths'])if(canonicalJson(proof[key]||[])!==canonicalJson((expected.proof as any)[key]))throw new Error(`adapter_capability_${key}_mismatch`);if(!proof.network_default_deny||!proof.filesystem_default_deny||!proof.subprocess_default_deny)throw new Error('adapter_capability_default_deny_required');return{verified:true,proof_digest:intelligenceDigest(proof)}}

export function counterfactualRoutePlan(accounts:any[],profiles:any[],operation:string,jurisdiction='*'){const candidates=accounts.map(account=>{const profile=profiles.find(item=>item.connector_account_id===account.id&&item.operation===operation&&(item.jurisdiction===jurisdiction||item.jurisdiction==='*'))||{expected_fee_bps:0,p50_settlement_ms:0,failure_rate:.05,risk_score:.1,sample_size:0};return{connector_account_id:account.id,provider:account.provider,score:scoreProviderRoute(profile),expected_fee_bps:Number(profile.expected_fee_bps||0),p50_settlement_ms:Number(profile.p50_settlement_ms||0),failure_rate:Number(profile.failure_rate||0),risk_score:Number(profile.risk_score||0),sample_size:Number(profile.sample_size||0),mutation_count:0}}).sort((a,b)=>b.score-a.score);return{candidates,selected_connector_account_id:candidates[0]?.connector_account_id||null,mutation_count:0,selection_digest:intelligenceDigest({operation,jurisdiction,candidates})}}

const valueAt=(input:any,path:string)=>path.split('.').reduce((current,key)=>current?.[key],input)
export function evaluateRegulatoryTwinRules(input:any,rules:any[],at=new Date()){const checks=rules.filter(rule=>rule.status==='active'&&new Date(`${rule.effective_from}T00:00:00Z`)<=at&&(!rule.effective_until||new Date(`${rule.effective_until}T23:59:59Z`)>=at)).map(rule=>{const invariant=rule.invariant||{},value=valueAt(input,String(invariant.path||''));let passed=false;if(invariant.operator==='required')passed=value!==undefined&&value!==null&&value!=='';else if(invariant.operator==='equals')passed=value===invariant.value;else if(invariant.operator==='one_of')passed=Array.isArray(invariant.values)&&invariant.values.includes(value);else if(invariant.operator==='maximum')passed=Number.isFinite(Number(value))&&Number(value)<=Number(invariant.value);else if(invariant.operator==='minimum')passed=Number.isFinite(Number(value))&&Number(value)>=Number(invariant.value);else if(invariant.operator==='date_not_past')passed=!!value&&new Date(value)>=at;return{key:`regulatory:${rule.rule_key}`,passed,severity:rule.severity,source_uri:rule.source_uri,source_digest:rule.source_digest,professional_reviewed:!!rule.professional_reviewed}});return{checks,verdict:checks.some(check=>!check.passed&&check.severity==='block')?'block':checks.some(check=>!check.passed)?'review':'pass',evidence_digest:intelligenceDigest(checks)}}

const mean=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0
const covariance=(x:number[],y:number[])=>{const mx=mean(x),my=mean(y);return x.length>1?x.reduce((sum,value,index)=>sum+(value-mx)*(y[index]-my),0)/(x.length-1):0}
const variance=(values:number[])=>covariance(values,values)
export function sequentialCausalAnalysis(rows:any[],maximumSample=1000){const treatment=rows.filter(row=>row.variant==='treatment'),control=rows.filter(row=>row.variant==='control'),all=[...treatment,...control],baseline=all.map(row=>Number(row.baseline_hours||0)),outcome=all.map(row=>Number(row.hours_saved||0)),theta=variance(baseline)>0?covariance(outcome,baseline)/variance(baseline):0,baselineMean=mean(baseline),adjust=(row:any)=>Number(row.hours_saved||0)-theta*(Number(row.baseline_hours||0)-baselineMean),tv=treatment.map(adjust),cv=control.map(adjust),effect=mean(tv)-mean(cv),se=Math.sqrt(variance(tv)/Math.max(1,tv.length)+variance(cv)/Math.max(1,cv.length)),informationFraction=Math.min(1,rows.length/Math.max(1,maximumSample)),alphaSpent=.05*Math.sqrt(informationFraction),boundary=1.96/Math.max(.25,Math.sqrt(alphaSpent/.05)),z=se?effect/se:effect>0?Infinity:effect<0?-Infinity:0,decision=treatment.length>=20&&control.length>=10?(z>boundary?'promote':z< -boundary?'stop_harm':'continue'):'continue';const result={analysis_version:'provider-sequential/v1',sample_size:rows.length,information_fraction:Number(informationFraction.toFixed(6)),alpha_spent:Number(alphaSpent.toFixed(6)),adjusted_effects:{hours_saved:{effect,se,z,theta,lower_95:effect-1.96*se,upper_95:effect+1.96*se}},decision};return{...result,evidence_digest:intelligenceDigest(result)}}

export function settlementCascadePlan(edges:any[],failedProvider:string,operation:string,jurisdiction='*'){const relevant=edges.filter(edge=>edge.upstream_provider===failedProvider&&edge.operation===operation&&(edge.jurisdiction===jurisdiction||edge.jurisdiction==='*')).sort((a,b)=>Number(b.conditional_failure_rate)-Number(a.conditional_failure_rate)),affected=relevant.filter(edge=>Number(edge.conditional_failure_rate)>=.2).map(edge=>({provider:edge.downstream_provider,conditional_failure_rate:Number(edge.conditional_failure_rate),alternate_connector_account_id:edge.alternate_connector_account_id||null}));return{failed_provider:failedProvider,operation,jurisdiction,affected,preposition_alternates:affected.filter(item=>item.alternate_connector_account_id),risk_digest:intelligenceDigest(affected)}}

export function parseWorkloadIdentityClaims(token:string,expectedAudience:string,allowedIssuers:string[],now=Date.now()){const parts=String(token||'').split('.');if(parts.length!==3)throw new Error('workload_identity_jwt_required');let claims:any;try{claims=JSON.parse(Buffer.from(parts[1],'base64url').toString('utf8'))}catch{throw new Error('workload_identity_claims_invalid')}const exp=Number(claims.exp||0)*1000,iat=Number(claims.iat||0)*1000,aud=Array.isArray(claims.aud)?claims.aud:[claims.aud];if(!allowedIssuers.includes(String(claims.iss||''))||!aud.includes(expectedAudience)||!claims.sub||exp<=now||exp-now>15*60*1000||iat>now+30000)throw new Error('workload_identity_claims_rejected');return{issuer:String(claims.iss),subject_hash:intelligenceDigest(String(claims.sub)),audience:expectedAudience,token_id_hash:claims.jti?intelligenceDigest(String(claims.jti)):null,expires_at:new Date(exp).toISOString()}}
