import {createHash,createHmac,createPublicKey,randomUUID,verify as verifySignature} from 'node:crypto'

export const canonicalJson=(value:any):string=>Array.isArray(value)?`[${value.map(canonicalJson).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`:JSON.stringify(value)
export const intelligenceDigest=(value:any)=>createHash('sha256').update(canonicalJson(value)).digest('hex')

const canonicalFields:Record<string,string[]>={
 'stripe:send_payment':['amount','currency','description'], 'stripe:issue_credit':['payment_intent','amount','reason'],
 'plaid:send_payment':['access_token','account_id','amount','legal_name','email_address','description'],
 'gusto:prepare_employee_record':['employee'], 'gusto:prepare_payroll_run':['payroll_id','payroll'], 'gusto:submit_payroll':['payroll_id'],
 'docusign:issue_contract':['envelope'], 'docusign:sign_contract':['envelope'], 'docusign:send_renewal_notice':['envelope'],
 'avalara:prepare_tax_return':['transaction'], 'avalara:reconcile_tax_base':['transaction'],
}
const aliases:Record<string,string[]>={amount:['total','value','payment_amount','gross_amount'],currency:['currency_code','iso_currency'],description:['memo','note'],payment_intent:['payment_id','charge_id'],legal_name:['name','account_name'],email_address:['email'],payroll_id:['payroll_uuid'],employee:['worker','employee_record'],payroll:['payroll_data'],envelope:['envelope_definition'],transaction:['tax_transaction']}
const leaf=(path:string)=>path.split('.').pop()!.replace(/[^a-z0-9]/gi,'_').toLowerCase()
function paths(value:any,prefix='',depth=0):Array<{path:string;value:any}>{if(depth>5||value===null||value===undefined)return[];if(Array.isArray(value))return value.length?[{path:prefix,value}]:[];if(typeof value!=='object')return[{path:prefix,value}];return Object.entries(value).flatMap(([key,item])=>paths(item,prefix?`${prefix}.${key}`:key,depth+1))}
export function inferFieldMappings(provider:string,operation:string,input:any){const targets=canonicalFields[`${provider}:${operation}`]||[];const candidates=paths(input);return targets.flatMap(target=>{const accepted=new Set([target,...(aliases[target]||[])]);const found=candidates.find(candidate=>accepted.has(leaf(candidate.path)));return found?[{source_path:found.path,target_path:target,value_type:Array.isArray(found.value)?'array':found.value===null?'null':typeof found.value,confidence:leaf(found.path)===target?1:.94}]:[]})}
const getPath=(value:any,path:string)=>path.split('.').reduce((current,key)=>current?.[key],value)
const setPath=(value:any,path:string,next:any)=>{const keys=path.split('.');let current=value;for(const key of keys.slice(0,-1))current=current[key]??={};current[keys.at(-1)!]=next}
export function applyFieldMappings(input:any,mappings:any[]){const result=structuredClone(input||{}),applied:string[]=[];for(const mapping of mappings){if(Number(mapping.confidence)<.9||Number(mapping.support)<3||getPath(result,mapping.target_path)!==undefined)continue;const value=getPath(result,mapping.source_path);if(value===undefined)continue;setPath(result,mapping.target_path,value);applied.push(`${mapping.source_path}->${mapping.target_path}`)}return{input:result,applied}}

export function assignHoldout(assignmentUnit:string,controlRate=.1){const bucket=parseInt(intelligenceDigest(assignmentUnit).slice(0,12),16)/0xffffffffffff;return{variant:bucket<controlRate?'control':'treatment',bucket,assignment_digest:intelligenceDigest({assignmentUnit,controlRate})}}
const mean=(values:number[])=>values.length?values.reduce((sum,value)=>sum+value,0)/values.length:0
const variance=(values:number[],average:number)=>values.length>1?values.reduce((sum,value)=>sum+(value-average)**2,0)/(values.length-1):0
export function estimateCausalEffects(rows:any[]){const metrics=['hours_saved','error_count','settlement_latency_ms','financial_value'];const treatment=rows.filter(row=>row.variant==='treatment'),control=rows.filter(row=>row.variant==='control');const effects:any={};for(const metric of metrics){const t=treatment.map(row=>Number(row[metric]||0)),c=control.map(row=>Number(row[metric]||0)),tm=mean(t),cm=mean(c),effect=tm-cm,se=Math.sqrt(variance(t,tm)/Math.max(1,t.length)+variance(c,cm)/Math.max(1,c.length));effects[metric]={treatment_mean:tm,control_mean:cm,effect,lower_95:effect-1.96*se,upper_95:effect+1.96*se}}return{treatment_n:treatment.length,control_n:control.length,effects,promotion_ready:treatment.length>=30&&control.length>=10&&effects.hours_saved.lower_95>0&&effects.error_count.upper_95<=0&&effects.financial_value.lower_95>=0}}

export function compileOpenApiAdapter(spec:any,options:{provider:string;version:string;allowedOrigins:string[];operationIds?:string[]}){if(!String(spec?.openapi||'').startsWith('3.'))throw new Error('openapi_v3_required');const servers=(spec.servers||[]).map((item:any)=>String(item.url||'').replace(/\/$/,''));if(!servers.length||servers.some((url:string)=>!options.allowedOrigins.includes(new URL(url).origin)))throw new Error('adapter_server_not_allowlisted');const selected=new Set(options.operationIds||[]),operations:any[]=[];for(const [path,item] of Object.entries<any>(spec.paths||{}))for(const method of ['get','post','put','patch','delete']){const operation=item?.[method];if(!operation?.operationId||selected.size&&!selected.has(operation.operationId))continue;if(!path.startsWith('/')||path.includes('..'))throw new Error('invalid_adapter_path');operations.push({operation_id:operation.operationId,method:method.toUpperCase(),path,parameters:operation.parameters||[],request_schema:operation.requestBody?.content?.['application/json']?.schema||null,response_schemas:Object.fromEntries(Object.entries<any>(operation.responses||{}).map(([status,response])=>[status,response?.content?.['application/json']?.schema||null]))})}if(!operations.length)throw new Error('adapter_operations_required');const auth:any[]=[];for(const [key,scheme] of Object.entries<any>(spec.components?.securitySchemes||{})){if(scheme.type==='http'&&['bearer','basic'].includes(String(scheme.scheme).toLowerCase()))auth.push({key,type:'http',scheme:String(scheme.scheme).toLowerCase()});else if(scheme.type==='apiKey'&&scheme.in==='header')auth.push({key,type:'apiKey',in:'header',name:String(scheme.name)})}const manifest:any={schema:'provider-adapter/v1',provider:options.provider,version:options.version,environment:'sandbox',servers,auth,operations:operations.sort((a,b)=>a.operation_id.localeCompare(b.operation_id)),spec_digest:intelligenceDigest(spec)};return{manifest,digest:intelligenceDigest(manifest)}}
export function signAdapterForTest(digest:string,key:string,keyId='test-only'){return{signature:createHmac('sha256',key).update(digest).digest('base64url'),signing_key_id:keyId}}
export async function requestHsmSignature(digest:string,purpose='provider-adapter'){const url=process.env.CONNECTOR_HSM_SIGNER_URL,key=process.env.CONNECTOR_HSM_SIGNER_TOKEN;if(!url||!key)throw new Error('hsm_signer_not_configured');const response:any=await $fetch(`${url.replace(/\/$/,'')}/v1/sign`,{method:'POST',headers:{authorization:`Bearer ${key}`},body:{digest,purpose,algorithm:'Ed25519'},timeout:15000});if(!response?.signature||!response?.key_id)throw new Error('invalid_hsm_signature_response');return{signature:String(response.signature),signing_key_id:String(response.key_id)}}
export async function runSandboxConformance(manifest:any,tests:any[],executor:(request:any)=>Promise<any>){if(!manifest?.servers?.length||manifest.environment!=='sandbox')throw new Error('sandbox_adapter_required');const operations=new Map((manifest.operations||[]).map((operation:any)=>[operation.operation_id,operation]));const results=[];for(const test of tests.slice(0,100)){const operation:any=operations.get(test.operation_id);if(!operation){results.push({name:test.name||test.operation_id,passed:false,error:'operation_not_in_manifest'});continue}const url=new URL(String(operation.path).replace(/\{([^}]+)\}/g,(_:string,key:string)=>encodeURIComponent(String(test.path_params?.[key]||`conformance-${key}`))),manifest.servers[0]).toString();try{const response=await executor({url,method:operation.method,body:test.body,headers:{'x-orchestrator-conformance':'true'}});const status=Number(response?.status||200),allowed=(test.expected_statuses||[200,201,202,204]).map(Number).filter((code:number)=>code>=200&&code<300),passed=allowed.includes(status);results.push({name:test.name||test.operation_id,passed,status})}catch(error:any){results.push({name:test.name||test.operation_id,passed:false,error:String(error?.message||'sandbox_request_failed').slice(0,120)})}}return{status:results.length>0&&results.every(result=>result.passed)?'passed':'failed',passed:results.filter(result=>result.passed).length,failed:results.length?results.filter(result=>!result.passed).length:1,tests:results.length?results:[{name:'live_sandbox_case_required',passed:false,error:'live_sandbox_case_required'}],evidence_digest:intelligenceDigest(results.length?results:['live_sandbox_case_required'])}}

export function simulateProviderMutation(provider:string,operation:string,input:any){const checks:Array<{key:string;passed:boolean;severity:'block'|'review'}>=[];const add=(key:string,passed:boolean,severity:'block'|'review'='block')=>checks.push({key,passed,severity});add('request_present',!!input&&typeof input==='object');if(['stripe','plaid'].includes(provider)&&operation==='send_payment'){add('positive_finite_amount',Number.isFinite(Number(input?.amount||input?.stripe_payout?.amount))&&Number(input?.amount||input?.stripe_payout?.amount)>0);add('currency_present',!!String(input?.currency||input?.stripe_payout?.currency||''));add('counterparty_evidence',!!(input?.account_id||input?.destination||input?.stripe_payout?.destination||input?.counterparty_evidence),'review')}if(provider==='gusto'&&operation.includes('payroll')){add('payroll_identifier_present',!!String(input?.payroll_id||''));add('pay_date_not_stale',!input?.pay_date||new Date(input.pay_date).getTime()>=Date.now()-86400000)}if(provider==='docusign')add('envelope_has_recipients',Array.isArray(input?.envelope?.recipients?.signers)&&input.envelope.recipients.signers.length>0);if(provider==='avalara'){const tx=input?.transaction;add('transaction_lines_present',Array.isArray(tx?.lines)&&tx.lines.length>0);add('jurisdiction_evidence',!!(tx?.addresses||input?.jurisdiction),'review')}const blocked=checks.some(check=>!check.passed&&check.severity==='block'),review=checks.some(check=>!check.passed&&check.severity==='review');return{verdict:blocked?'block':review?'review':'pass',checks,predicted:{external_call:false,provider,operation,estimated_mutation_count:1},scenario_digest:intelligenceDigest({provider,operation,input_digest:intelligenceDigest(input),checks})}}

export function scoreProviderRoute(profile:any,weights:any={cost:.25,latency:.2,reliability:.35,risk:.2}){const cost=Math.min(1,Math.max(0,Number(profile.expected_fee_bps||0)/500)),latency=Math.min(1,Math.max(0,Number(profile.p50_settlement_ms||0)/(7*86400000))),failure=Math.min(1,Math.max(0,Number(profile.failure_rate||0))),risk=Math.min(1,Math.max(0,Number(profile.risk_score||0)));return Number((1-(cost*weights.cost+latency*weights.latency+failure*weights.reliability+risk*weights.risk)).toFixed(6))}
export function rankProviderAccounts(accounts:any[],profiles:any[],operation:string,jurisdiction='*'){return accounts.map(account=>{const profile=profiles.find(item=>item.connector_account_id===account.id&&item.operation===operation&&(item.jurisdiction===jurisdiction||item.jurisdiction==='*'))||{connector_account_id:account.id,expected_fee_bps:0,p50_settlement_ms:0,failure_rate:.05,risk_score:.1,sample_size:0};return{account,profile,score:scoreProviderRoute(profile)}}).sort((a,b)=>b.score-a.score)}

const statusMaps:Record<string,Record<string,string>>={stripe:{paid:'succeeded',succeeded:'succeeded',failed:'failed',canceled:'cancelled',pending:'pending',in_transit:'pending'},docusign:{completed:'succeeded',delivered:'pending',sent:'pending',declined:'failed',voided:'cancelled'},plaid:{settled:'succeeded',funds_available:'succeeded',posted:'pending',pending:'pending',failed:'failed',returned:'failed',cancelled:'cancelled'},gusto:{processed:'succeeded',submitted:'pending',failed:'failed'},avalara:{saved:'succeeded',committed:'succeeded',cancelled:'cancelled'}}
export function normalizeFinalityEvent(provider:string,event:any,source:'webhook'|'poll'|'read_after_write'='webhook'){const rawStatus=String(event.status||event.data?.object?.status||event.transfer?.status||event.envelopeStatus||'unknown').toLowerCase(),canonical_status=statusMaps[provider]?.[rawStatus]||(['succeeded','failed','cancelled','pending','accepted'].includes(rawStatus)?rawStatus:'unknown');const external_ref=String(event.external_ref||event.data?.object?.id||event.transfer?.id||event.envelopeId||event.id||'');const provider_event_id=String(event.provider_event_id||event.event_id||event.id||`${source}:${external_ref}:${rawStatus}`);return{contract_version:'provider-finality/v1',provider,provider_event_id,external_ref,canonical_status,event_type:String(event.event_type||event.type||`${provider}.${rawStatus}`),occurred_at:event.created?new Date(Number(event.created)*1000).toISOString():event.occurred_at||null,payload_digest:intelligenceDigest(event),source,normalized:{raw_status:rawStatus,terminal:['succeeded','failed','cancelled'].includes(canonical_status)}}}

export function verifyCredentialLease(response:any,publicKeyPem:string,expectedNonce:string){const expires=new Date(response?.expires_at||0).getTime(),ttl=expires-Date.now();if(!response?.credential||!response?.lease_id||response?.nonce!==expectedNonce||ttl<=0||ttl>15*60*1000)throw new Error('invalid_credential_lease');const credential_digest=intelligenceDigest(response.credential);if(credential_digest!==response.credential_digest)throw new Error('credential_lease_digest_mismatch');const signed=canonicalJson({lease_id:response.lease_id,credential_ref:response.credential_ref,credential_digest,expires_at:response.expires_at,nonce:response.nonce,key_id:response.key_id});const ok=verifySignature(null,Buffer.from(signed),createPublicKey(publicKeyPem),Buffer.from(String(response.signature||''),'base64url'));if(!ok)throw new Error('credential_lease_signature_invalid');return{credential:response.credential,lease_id:String(response.lease_id),credential_ref:String(response.credential_ref),credential_digest,expires_at:String(response.expires_at),broker_key_id:String(response.key_id)}}
export async function leaseCredential(account:any){const url=process.env.CONNECTOR_CREDENTIAL_BROKER_URL,publicKey=process.env.CONNECTOR_CREDENTIAL_BROKER_PUBLIC_KEY;if(!url||!publicKey)throw new Error('credential_broker_not_configured');const audience=process.env.CONNECTOR_WORKLOAD_IDENTITY_AUDIENCE||'provider-credential-broker',issuers=(process.env.CONNECTOR_WORKLOAD_IDENTITY_ISSUERS||'').split(',').map(x=>x.trim()).filter(Boolean),file=process.env.CONNECTOR_WORKLOAD_IDENTITY_TOKEN_FILE;let subjectToken=process.env.CONNECTOR_WORKLOAD_IDENTITY_TOKEN||'';if(!subjectToken&&file){const fs=(process as any).getBuiltinModule?.('fs');if(!fs)throw new Error('workload_identity_token_file_unsupported');subjectToken=String(fs.readFileSync(file,'utf8')).trim()}let identity:any=null,headers:Record<string,string>={};if(subjectToken){const{parseWorkloadIdentityClaims}=await import('./providerAutonomy');identity=parseWorkloadIdentityClaims(subjectToken,audience,issuers);headers['x-workload-identity']=subjectToken}else if(process.env.CONNECTOR_ALLOW_LEGACY_BROKER_TOKEN==='true'&&process.env.CONNECTOR_CREDENTIAL_BROKER_TOKEN)headers.authorization=`Bearer ${process.env.CONNECTOR_CREDENTIAL_BROKER_TOKEN}`;else throw new Error('workload_identity_not_configured');const nonce=intelligenceDigest({account:account.id,at:Date.now(),random:randomUUID()});const response:any=await $fetch(`${url.replace(/\/$/,'')}/v1/credentials/lease`,{method:'POST',headers,body:{credential_ref:account.metadata?.credential_ref,provider:account.provider,audience:account.token_audience,scopes:account.scopes,max_ttl_seconds:900,nonce,workload_identity_audience:audience},timeout:15000}),lease=verifyCredentialLease(response,publicKey.replaceAll('\\n','\n'),nonce);return{...lease,workload_identity:identity}}
