import{randomUUID}from'node:crypto'
import{serviceClient}from'./fleetSupabase'
import{applyFederatedMappings,federatedMappingContribution}from'./providerAutonomy'
import{forecastSettlementLiquidity,globalMutationKey,safeContextualBandit,sealMappingContribution,verifySecureMappingAggregate}from'./providerSovereignty'
import{intelligenceDigest,requestHsmSignature}from'./providerIntelligence'

export async function contributeSecureMapping(organizationId:string,provider:string,operation:string,input:any,mapping:any){const encryptionKey=(process.env.SECURE_MAPPING_AGGREGATOR_PUBLIC_KEY||'').replaceAll('\\n','\n'),keyId=process.env.SECURE_MAPPING_AGGREGATOR_KEY_ID||'',pepper=process.env.FEDERATED_MAPPING_PEPPER||'';if(!encryptionKey||!keyId||!pepper)return{status:'disabled'};const contribution={...federatedMappingContribution(provider,operation,input,mapping,pepper),privacy_epoch:new Date().toISOString().slice(0,10)},sealed=sealMappingContribution(contribution,encryptionKey,keyId),{error}=await serviceClient().from('provider_secure_mapping_envelopes').upsert({organization_id:organizationId,provider,operation,...sealed},{onConflict:'organization_id,envelope_digest'});if(error)throw new Error('secure_mapping_envelope_persistence_failed');return{status:'sealed',envelope_digest:sealed.envelope_digest}}
export async function applySecureFederatedMappings(input:any,provider:string[],operation:string){const pepper=process.env.FEDERATED_MAPPING_PEPPER||'',attestationKey=(process.env.SECURE_MAPPING_AGGREGATOR_ATTESTATION_KEY||'').replaceAll('\\n','\n');if(!pepper||!attestationKey)return{input,applied:[]};const{data,error}=await serviceClient().from('provider_secure_mapping_aggregates').select('*').in('provider',provider).eq('operation',operation).gte('privacy_epoch',new Date(Date.now()-31*86400000).toISOString().slice(0,10));if(error)throw new Error('secure_mapping_aggregates_unavailable');const verified=(data||[]).map(row=>verifySecureMappingAggregate(row,attestationKey));return applyFederatedMappings(input,verified,pepper)}

export async function chooseSafeBanditRoute(saga:any,step:any,accounts:any[],profiles:any[],jurisdiction:string){const decision=safeContextualBandit(accounts,profiles,{organization_id:saga.organization_id,saga_id:saga.id,step_id:step.id,operation:step.operation,jurisdiction,amount_bucket:Math.ceil(Number(step.input?.amount||0)/1000),currency:String(step.input?.currency||'USD')},{max_failure_rate:Number(process.env.PROVIDER_ROUTE_MAX_FAILURE_RATE||.15),max_risk_score:Number(process.env.PROVIDER_ROUTE_MAX_RISK_SCORE||.25),exploration_rate:Number(process.env.PROVIDER_ROUTE_EXPLORATION_RATE||.05)}),{error}=await serviceClient().from('provider_bandit_decisions').upsert({organization_id:saga.organization_id,saga_id:saga.id,step_id:step.id,policy_version:decision.policy_version,context_digest:decision.context_digest,candidates:decision.candidates,selected_connector_account_id:decision.selected_connector_account_id,propensity:decision.propensity,exploration:decision.exploration,safety_constraints:decision.safety_constraints},{onConflict:'step_id,policy_version'});if(error)throw new Error('provider_bandit_decision_persistence_failed');return decision}
export async function claimAtomicRoute(saga:any,step:any,connectorAccountId:string,selectionDigest:string){const owner=`web:${process.pid}:${randomUUID()}`,{data,error}=await serviceClient().rpc('claim_provider_route',{p_organization_id:saga.organization_id,p_saga_id:saga.id,p_step_id:step.id,p_selection_digest:selectionDigest,p_connector_account_id:connectorAccountId,p_claim_owner:owner});if(error||!data)throw new Error(error?.message==='route_already_claimed'?'route_already_claimed':'atomic_route_claim_failed');return Array.isArray(data)?data[0]:data}
export async function settleAtomicRoute(stepId:string,claimOwner:string,state:'committed'|'failed'){const{data,error}=await serviceClient().from('provider_atomic_route_claims').update({state,committed_at:state==='committed'?new Date().toISOString():null}).eq('step_id',stepId).eq('claim_owner',claimOwner).select().single();if(error||!data)throw new Error('atomic_route_settlement_failed');return data}

export async function claimGlobalMutation(execution:any,idempotencyKey:string){const key=globalMutationKey(execution.provider,execution.operation,idempotencyKey),owner=`${execution.id}:${randomUUID()}`,{data,error}=await serviceClient().rpc('claim_global_provider_mutation',{p_global_key:key,p_provider:execution.provider,p_operation:execution.operation,p_organization_id:execution.organization_id,p_execution_id:execution.id,p_owner_token:owner,p_lease_seconds:180});if(error||!data)throw new Error(error?.message==='global_mutation_in_progress'?'global_mutation_in_progress':'global_mutation_claim_failed');const row=Array.isArray(data)?data[0]:data;return{key,owner,row,replayed:row.state==='committed'}}
export async function commitGlobalMutation(key:string,owner:string,externalRef:string,receiptDigest:string){const{data,error}=await serviceClient().rpc('commit_global_provider_mutation',{p_global_key:key,p_owner_token:owner,p_external_ref:externalRef,p_receipt_digest:receiptDigest});if(error||!data)throw new Error('global_mutation_commit_failed');return Array.isArray(data)?data[0]:data}

export async function refreshLiquidityForecast(organizationId:string,currency='USD',jurisdiction='*'){const sb=serviceClient(),{data:executions,error}=await sb.from('business_provider_executions').select('state,response_meta,created_at').eq('organization_id',organizationId).in('state',['started','provider_pending']).limit(1000);if(error)throw new Error('liquidity_execution_evidence_unavailable');const forecast=forecastSettlementLiquidity(executions||[],{currency,jurisdiction}),{error:insertError}=await sb.from('provider_liquidity_forecasts').upsert({organization_id:organizationId,...forecast},{onConflict:'organization_id,currency,jurisdiction,horizon_at'});if(insertError)throw new Error('liquidity_forecast_persistence_failed');return forecast}

export async function executeAttestedWasmAdapter(account:any,operation:string,input:any,idempotencyKey:string){const moduleId=String(account.metadata?.wasm_module_id||'');if(!moduleId)return null;if(account.metadata?.credential_type!=='hsm_ref')throw new Error('wasm_adapter_requires_brokered_credential');const endpoint=process.env.WASM_ADAPTER_SANDBOX_URL;if(!endpoint)throw new Error('attested_wasm_sandbox_not_configured');const{data:module,error}=await serviceClient().from('provider_wasm_modules').select('*').eq('id',moduleId).eq('organization_id',account.organization_id).eq('status','active').maybeSingle();if(error||!module)throw new Error('active_wasm_module_required');const request={contract_version:'wasm-provider-execution/v1',module_ref:module.sandbox_module_ref,module_digest:module.module_digest,provider:account.provider,operation,input,idempotency_key:idempotencyKey,credential_ref:account.metadata.credential_ref},requestDigest=intelligenceDigest(request),signature=await requestHsmSignature(requestDigest,'wasm-provider-execution'),response:any=await $fetch(`${endpoint.replace(/\/$/,'')}/v1/execute`,{method:'POST',body:{...request,request_digest:requestDigest,signature:signature.signature,key_id:signature.signing_key_id},timeout:45000});if(!response?.external_ref||response?.request_digest!==requestDigest||!response?.receipt_digest)throw new Error('wasm_execution_receipt_invalid');return{id:String(response.external_ref),status:String(response.status||'accepted'),request_id:String(response.request_id||''),sandbox_receipt_digest:String(response.receipt_digest)}}
