import{describe,expect,it}from'vitest'
import{aggregateFederatedMappings,applyFederatedMappings,buildAdapterCapabilityProof,counterfactualRoutePlan,evaluateRegulatoryTwinRules,federatedMappingContribution,generateSyntheticConformanceCases,parseWorkloadIdentityClaims,runSyntheticSchemaConformance,sequentialCausalAnalysis,settlementCascadePlan,verifyAdapterCapabilityProof}from'./providerAutonomy'

const manifest={schema:'provider-adapter/v1',servers:['https://sandbox.example.com'],operations:[{operation_id:'createPayment',method:'POST',path:'/payments',parameters:[{name:'idempotency-key'}],request_schema:{type:'object',required:['amount','currency'],properties:{amount:{type:'number',minimum:1,maximum:10000},currency:{type:'string',enum:['USD']}}}}]}
describe('provider autonomy mesh',()=>{
 it('federates only k-anonymous schema signals without raw paths or values',()=>{const pepper='a-long-private-pepper',input={payment:{total:42}},base=federatedMappingContribution('stripe','send_payment',input,{source_path:'payment.total',target_path:'amount',support:1,confidence:1},pepper),rows=Array.from({length:5},(_,i)=>({...base,organization_id:`org-${i}`})),aggregated=aggregateFederatedMappings(rows);expect(aggregated).toHaveLength(1);expect(base).not.toHaveProperty('source_path');expect(base).not.toHaveProperty('value');expect(applyFederatedMappings(input,aggregated,pepper).input.amount).toBe(42);expect(aggregateFederatedMappings(rows.slice(0,4))).toHaveLength(0)})
 it('generates positive, boundary, and negative synthetic schema cases',()=>{const cases=generateSyntheticConformanceCases(manifest);expect(cases.some(item=>!item.expected_valid)).toBe(true);const result=runSyntheticSchemaConformance(manifest);expect(result.status).toBe('passed');expect(result.coverage.required_field_negatives).toBe(2)})
 it('requires exact default-deny adapter capabilities',()=>{const built=buildAdapterCapabilityProof(manifest);expect(verifyAdapterCapabilityProof(manifest,built.proof).verified).toBe(true);expect(()=>verifyAdapterCapabilityProof(manifest,{...built.proof,network_default_deny:false})).toThrow('default_deny_required')})
 it('compares all routes without mutating and selects the best observed rail',()=>{const accounts=[{id:'a',provider:'slow'},{id:'b',provider:'fast'}],profiles=[{connector_account_id:'a',operation:'send_payment',jurisdiction:'*',failure_rate:.4,risk_score:.3,p50_settlement_ms:500000,expected_fee_bps:100},{connector_account_id:'b',operation:'send_payment',jurisdiction:'*',failure_rate:.01,risk_score:.01,p50_settlement_ms:1000,expected_fee_bps:5}],plan=counterfactualRoutePlan(accounts,profiles,'send_payment');expect(plan.selected_connector_account_id).toBe('b');expect(plan.mutation_count).toBe(0);expect(plan.candidates.every(item=>item.mutation_count===0)).toBe(true)})
 it('enforces effective, professionally sourced regulatory invariants',()=>{const rules=[{rule_key:'payment-cap',status:'active',effective_from:'2025-01-01',invariant:{path:'amount',operator:'maximum',value:100},severity:'block',source_uri:'https://authority.example/rule',source_digest:'d',professional_reviewed:true}],result=evaluateRegulatoryTwinRules({amount:101},rules,new Date('2026-01-01'));expect(result.verdict).toBe('block');expect(result.checks[0].source_uri).toContain('authority.example')})
 it('uses baseline adjustment and alpha spending for sequential decisions',()=>{const rows=[...Array.from({length:30},(_,i)=>({variant:'treatment',hours_saved:5,baseline_hours:i%3})),...Array.from({length:15},(_,i)=>({variant:'control',hours_saved:1,baseline_hours:i%3}))],analysis=sequentialCausalAnalysis(rows,100);expect(analysis.decision).toBe('promote');expect(analysis.alpha_spent).toBeLessThan(.05);expect(analysis.adjusted_effects.hours_saved.effect).toBeGreaterThan(3)})
 it('prepositions alternates only for elevated settlement cascades',()=>{const plan=settlementCascadePlan([{upstream_provider:'bank',downstream_provider:'payroll',operation:'submit_payroll',jurisdiction:'*',conditional_failure_rate:.5,alternate_connector_account_id:'backup'}],'bank','submit_payroll');expect(plan.preposition_alternates[0].alternate_connector_account_id).toBe('backup')})
 it('accepts only short-lived allowlisted workload identity claims',()=>{const now=Date.now(),claims={iss:'https://issuer.example',sub:'workload:orchestrator',aud:'provider-credential-broker',iat:Math.floor(now/1000),exp:Math.floor((now+300000)/1000),jti:'one'},token=`${Buffer.from('{}').toString('base64url')}.${Buffer.from(JSON.stringify(claims)).toString('base64url')}.signature`,parsed=parseWorkloadIdentityClaims(token,'provider-credential-broker',['https://issuer.example'],now);expect(parsed.subject_hash).not.toContain('orchestrator');expect(()=>parseWorkloadIdentityClaims(token,'wrong',['https://issuer.example'],now)).toThrow('claims_rejected')})
})
