import { createHash, randomBytes } from 'node:crypto'
import { serviceClient } from './fleetSupabase'

const hash = (v: any) => createHash('sha256').update(typeof v === 'string' ? v : JSON.stringify(v)).digest('hex')
const clamp = (n: number, a = 0, b = 100) => Math.max(a, Math.min(b, n))
const text = (v: any, n = 240) => String(v || '').trim().slice(0, n)

export function verifyZkEnvelope(input: any) {
  const verifier = input.verifier || {}; const result = input.verification_result || {}
  const active = verifier.status === 'active' && Boolean(verifier.audit_manifest?.approved) && Boolean(verifier.verifier_digest)
  const binding = result.verifier_digest === verifier.verifier_digest && result.proof_digest === input.proof_digest && result.predicate === input.predicate
  const valid = active && binding && result.valid === true && result.public_inputs_digest === hash(input.public_inputs || {})
  return { verification_result: { valid, verifier_active: active, binding_valid: binding, verifier_digest: verifier.verifier_digest, public_inputs_digest: hash(input.public_inputs || {}), failure: valid ? null : !active ? 'verifier_not_active_or_audited' : !binding ? 'proof_or_verifier_binding_invalid' : 'cryptographic_verification_failed' }, verified_at: new Date().toISOString(), status: valid ? 'valid' : 'invalid' }
}

export function prepareAtomicRegulatoryTransaction(input: any) {
  const steps = (input.steps || []).slice(0, 100); const preconditions = (input.preconditions || []).slice(0, 100).map((p: any) => ({ ...p, satisfied: p.satisfied === true && (!p.expires_at || new Date(p.expires_at).getTime() > Date.now()) })); const missing = preconditions.filter((p: any) => !p.satisfied)
  const compensation = [...steps].reverse().map((s: any) => ({ step: s.key, action: s.compensate || 'restore_previous_state', preauthorized: Boolean(s.compensation_preauthorized) }))
  return { steps, preconditions, compensation_plan: compensation, evidence_plan: steps.map((s: any) => ({ step: s.key, required_receipts: s.required_receipts || ['execution','policy'] })), authorization_result: { allowed: !missing.length, missing: missing.map((p: any) => p.key), atomicity: 'all_steps_or_compensate' }, execution_receipts: [], failed_step: null, status: missing.length ? 'held' : 'authorized' }
}

export function derivePurposeConsent(input: any) {
  const parent = input.parent || null; const requestedPurposes = input.purposes || []; const requestedActions = input.allowed_actions || []
  const purposes = parent ? requestedPurposes.filter((x: string) => (parent.purposes || []).includes(x)) : requestedPurposes
  const actions = parent ? requestedActions.filter((x: string) => (parent.allowed_actions || []).includes(x)) : requestedActions
  const parentExpiry = parent?.expires_at ? new Date(parent.expires_at).getTime() : Infinity; const requestedExpiry = new Date(input.expires_at).getTime(); const expiresAt = new Date(Math.min(parentExpiry, requestedExpiry)).toISOString()
  return { purposes, allowed_actions: actions, inherited_from: parent?.id || null, attenuation: { purposes_removed: requestedPurposes.filter((x: string) => !purposes.includes(x)), actions_removed: requestedActions.filter((x: string) => !actions.includes(x)), cannot_expand_parent: Boolean(parent) }, expires_at: expiresAt, status: purposes.length && actions.length && expiresAt > new Date().toISOString() ? 'active' : 'expired' }
}

export function evaluateProofChallenge(input: any) {
  const checks = { stale: Boolean(input.expires_at && new Date(input.expires_at).getTime() <= Date.now()), replayed: Boolean(input.nonce_reused), inconsistent: Boolean(input.expected_subject && input.actual_subject !== input.expected_subject), insufficient: (input.required_claims || []).some((x: string) => !(input.present_claims || []).includes(x)), invalid_signature: input.signature_valid === false }
  const findings = Object.entries(checks).filter(([, found]) => found).map(([type]) => ({ type, validated: true })); const severity = checks.invalid_signature || checks.replayed ? 'critical' : findings.length ? 'high' : 'none'; const reward = findings.length ? Math.min(Number(input.max_reward_cents || 100_000), findings.length * Number(input.reward_per_finding_cents || 10_000)) : 0
  return { challenge_types: Object.keys(checks), findings, severity, stake: input.stake || {}, resolution: { proof_status: findings.length ? 'suspend_and_reverify' : 'challenge_rejected', human_review_required: severity === 'critical' }, reward_cents: reward, status: findings.length ? 'validated' : 'rejected' }
}

export function attributeRegulatoryLiability(input: any) {
  const contributors = (input.contributors || []).slice(0, 50); const weighted = contributors.map((c: any) => ({ ...c, raw_weight: Math.max(0, Number(c.causal_weight || 0)) * Math.max(0, Math.min(1, Number(c.evidence_confidence || 0))) })); const total = weighted.reduce((s: number, c: any) => s + c.raw_weight, 0)
  const allocation = weighted.map((c: any) => ({ contributor_ref: c.ref, contributor_type: c.type, share: total ? Number((c.raw_weight / total).toFixed(4)) : 0, allocated_cost_cents: total ? Math.round(Number(input.remediation_cost_cents || 0) * c.raw_weight / total) : 0 }))
  return { contributors, causal_chain: input.causal_chain || [], allocation, remediation_cost_cents: Number(input.remediation_cost_cents || 0), recoverable_cost_cents: allocation.filter((x: any) => contributors.find((c: any) => c.ref === x.contributor_ref)?.contractually_recoverable).reduce((s: number, x: any) => s + x.allocated_cost_cents, 0), uncertainty: { unallocated_share: total ? 0 : 1, requires_contract_and_legal_review: true }, status: 'modeled' }
}

export function compileRegulatoryUnitEconomics(input: any) {
  const volume = Math.max(0, Number(input.monthly_volume || 0)); const price = Math.max(0, Number(input.revenue_per_unit_cents || 0)); const variable = Math.max(0, Number(input.variable_cost_per_unit_cents || 0)); const fixed = Math.max(0, Number(input.fixed_regulatory_cost_cents || 0)); const supervision = Math.max(0, Number(input.supervision_cost_per_unit_cents || 0)); const reporting = Math.max(0, Number(input.reporting_cost_per_unit_cents || 0)); const contributionPerUnit = price - variable - supervision - reporting; const contribution = contributionPerUnit * volume - fixed; const breakEven = contributionPerUnit > 0 ? Math.ceil(fixed / contributionPerUnit) : null
  return { volume_assumptions: { monthly_volume: volume }, revenue_model: { revenue_per_unit_cents: price, monthly_revenue_cents: volume * price }, regulatory_costs: { fixed_cents: fixed, supervision_per_unit_cents: supervision, reporting_per_unit_cents: reporting, monthly_total_cents: fixed + volume * (supervision + reporting) }, contribution_model: { contribution_per_unit_cents: contributionPerUnit, monthly_contribution_cents: contribution, margin_pct: price ? Number((contributionPerUnit / price * 100).toFixed(2)) : 0 }, break_even: { monthly_units: breakEven }, sensitivity: [-.25,0,.25].map(delta => ({ volume_change: delta, monthly_contribution_cents: Math.round(contributionPerUnit * volume * (1 + delta) - fixed) })), recommendation: contribution > 0 ? 'economically_viable_subject_to_authority' : breakEven ? 'increase_volume_or_restructure_costs' : 'restructure_pricing_or_route', status: 'modeled' }
}

export function prepareCustomerRemedy(input: any) {
  const customers = (input.customers || []).slice(0, 10_000); const rules = input.eligibility_rules || []; const eligible = customers.filter((c: any) => rules.every((r: any) => r.type === 'minimum_loss' ? Number(c.loss_cents || 0) >= Number(r.value || 0) : r.type === 'event' ? (c.events || []).includes(r.value) : true)); const calculations = eligible.map((c: any) => ({ subject_token: c.subject_token, principal_cents: Number(c.loss_cents || 0), interest_cents: Math.round(Number(c.loss_cents || 0) * Number(input.interest_rate || 0)), consequential_cents: Number(c.approved_consequential_cents || 0), proposed_total_cents: Math.round(Number(c.loss_cents || 0) * (1 + Number(input.interest_rate || 0)) + Number(c.approved_consequential_cents || 0)) }))
  return { affected_cohort: { evaluated: customers.length, eligible: eligible.length, tokenized_subjects_only: true }, eligibility_rules: rules, calculations, total_proposed_cents: calculations.reduce((s: number, x: any) => s + x.proposed_total_cents, 0), evidence_manifest: input.evidence_manifest || [], notification_plan: [{ stage: 'draft', external_send_requires_approval: true }, { stage: 'delivery', channel_preferences_required: true }], execution_controls: { payments_require_approval: true, admissions_require_legal_approval: true, idempotency_required: true, reconciliation_required: true }, status: 'prepared' }
}

export function scoreCapacityReliability(input: any) {
  const reserved = Math.max(0, Number(input.reserved_minutes || 0)); const delivered = Math.max(0, Number(input.delivered_minutes || 0)); const fulfillment = reserved ? Math.min(1, delivered / reserved) : 1; const response = clamp(100 - Number(input.response_minutes || 0) / Math.max(1, Number(input.response_slo_minutes || 60)) * 50); const quality = clamp(Number(input.quality_score || 0)); const exam = clamp(Number(input.examination_score || quality)); const reliability = Number((fulfillment * 40 + response * .2 + quality * .25 + exam * .15).toFixed(2))
  return { reserved_minutes: reserved, delivered_minutes: delivered, response_minutes: Number(input.response_minutes || 0), quality_score: quality, examination_outcomes: input.examination_outcomes || [], reliability_score: reliability, pricing_adjustment: { multiplier: Number(clamp(1 + (85 - reliability) / 100, .7, 1.5).toFixed(3)), reason: reliability < 70 ? 'reliability_discount_or_additional_assurance' : reliability > 95 ? 'verified_reliability_premium' : 'standard' }, status: reliability < 60 ? 'watch' : 'current' }
}

export async function saveAtomicAssuranceAction(organizationId: string, action: string, values: any) {
  const sb = serviceClient(); const insert = async (table: string, row: any) => { const { data, error } = await sb.from(table).insert(row).select().single(); if (error) throw createError({ statusCode: 500, message: error.message }); return data }
  if (action === 'register_zk_verifier') return insert('regulatory_zk_verifier_registry', { organization_id: organizationId, circuit_key: text(values.circuit_key), circuit_version: text(values.circuit_version, 80), proof_system: text(values.proof_system, 80), verifier_ref: text(values.verifier_ref), verifier_digest: text(values.verifier_digest, 128), supported_predicates: values.supported_predicates || [], trusted_setup_manifest: values.trusted_setup_manifest || {}, audit_manifest: values.audit_manifest || {}, status: values.status === 'active' && values.audit_manifest?.approved ? 'active' : 'shadow' })
  if (action === 'verify_zk_proof') { const { data: verifier } = await sb.from('regulatory_zk_verifier_registry').select('*').eq('organization_id', organizationId).eq('id', values.verifier_registry_id).single(); const result = verifyZkEnvelope({ ...values, verifier }); return insert('regulatory_zk_proof_envelopes', { organization_id: organizationId, verifier_registry_id: values.verifier_registry_id, subject_ref: text(values.subject_ref), predicate: text(values.predicate), public_inputs: values.public_inputs || {}, proof_blob_ref: text(values.proof_blob_ref, 500), proof_digest: text(values.proof_digest, 128), expires_at: values.expires_at, envelope_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }), ...result }) }
  if (action === 'atomic_transaction') { const result = prepareAtomicRegulatoryTransaction(values); return insert('regulatory_atomic_transactions', { organization_id: organizationId, transaction_ref: text(values.transaction_ref), ...result, atomicity_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'purpose_consent') { let parent = null; if (values.inherited_from) { const response = await sb.from('regulatory_consent_graph_edges').select('*').eq('organization_id', organizationId).eq('id', values.inherited_from).single(); parent = response.data } const result = derivePurposeConsent({ ...values, parent }); return insert('regulatory_consent_graph_edges', { organization_id: organizationId, grantor_ref: text(values.grantor_ref), grantee_ref: text(values.grantee_ref), resource_ref: text(values.resource_ref), edge_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }), ...result }) }
  if (action === 'proof_challenge') { const result = evaluateProofChallenge(values); return insert('regulatory_proof_challenges', { organization_id: organizationId, proof_ref: text(values.proof_ref), challenger_ref: text(values.challenger_ref), ...result, challenge_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'liability_attribution') { const result = attributeRegulatoryLiability(values); return insert('regulatory_liability_attribution', { organization_id: organizationId, outcome_ref: text(values.outcome_ref), ...result, attribution_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'unit_economics') { const result = compileRegulatoryUnitEconomics(values); return insert('regulatory_unit_economics', { organization_id: organizationId, product_ref: text(values.product_ref), jurisdiction: text(values.jurisdiction, 80), authority_route: text(values.authority_route), ...result, economics_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'customer_remedy') { const result = prepareCustomerRemedy(values); return insert('regulatory_customer_remedies', { organization_id: organizationId, incident_ref: text(values.incident_ref), ...result, remedy_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'capacity_performance') { const result = scoreCapacityReliability(values); return insert('regulatory_capacity_performance', { organization_id: organizationId, provider_ref: text(values.provider_ref), capability: text(values.capability), jurisdiction: text(values.jurisdiction, 80), ...result, performance_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  throw createError({ statusCode: 400, message: 'unknown_atomic_assurance_action' })
}

export async function atomicAssuranceCockpit(organizationId: string) {
  const sb = serviceClient(); const names = ['regulatory_zk_verifier_registry','regulatory_zk_proof_envelopes','regulatory_atomic_transactions','regulatory_consent_graph_edges','regulatory_proof_challenges','regulatory_liability_attribution','regulatory_unit_economics','regulatory_customer_remedies','regulatory_capacity_performance']; const results = await Promise.all(names.map(name => sb.from(name).select('*').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(30))); const [verifiers, proofs, transactions, consent, challenges, liability, economics, remedies, capacity] = results.map(x => x.data || [])
  return { zk_verifiers: verifiers, zk_proofs: proofs, atomic_transactions: transactions, consent_edges: consent, proof_challenges: challenges, liability_attribution: liability, unit_economics: economics, customer_remedies: remedies, capacity_performance: capacity, summary: { valid_zk_proofs: proofs.filter((x: any) => x.status === 'valid' && new Date(x.expires_at).getTime() > Date.now()).length, held_atomic_transactions: transactions.filter((x: any) => x.status === 'held').length, active_consent_edges: consent.filter((x: any) => x.status === 'active' && !x.revoked_at && new Date(x.expires_at).getTime() > Date.now()).length, validated_proof_challenges: challenges.filter((x: any) => x.status === 'validated').length, attributed_remediation_cents: liability.reduce((s: number, x: any) => s + Number(x.remediation_cost_cents || 0), 0), proposed_remedies_cents: remedies.reduce((s: number, x: any) => s + Number(x.total_proposed_cents || 0), 0), average_capacity_reliability: capacity.length ? Math.round(capacity.reduce((s: number, x: any) => s + Number(x.reliability_score || 0), 0) / capacity.length) : null } }
}
