import { createHash, randomBytes } from 'node:crypto'
import { serviceClient } from './fleetSupabase'

const clamp = (n: number, a = 0, b = 100) => Math.max(a, Math.min(b, n))
const hash = (v: any) => createHash('sha256').update(typeof v === 'string' ? v : JSON.stringify(v, Object.keys(v || {}).sort())).digest('hex')
const bounded = (v: any, n = 240) => String(v || '').trim().slice(0, n)

export function buildPrivacyPassport(input: any) {
  const claims = (input.claims || []).slice(0, 100).map((claim: any) => { const salt = claim.salt || randomBytes(16).toString('hex'); return { key: claim.key, commitment: hash(`${claim.key}:${JSON.stringify(claim.value)}:${salt}`), issuer_ref: claim.issuer_ref || 'madeus-verified', verified_at: claim.verified_at || new Date().toISOString(), expires_at: claim.expires_at || input.expires_at, disclosure: claim.disclose ? { key: claim.key, value: claim.value, salt, verification: 'recompute_commitment' } : null } })
  const disclosed = claims.filter((x: any) => x.disclosure).map((x: any) => x.disclosure)
  return { claim_commitments: claims.map(({ disclosure, ...claim }: any) => claim), disclosed_proofs: disclosed, verifier_policy: { purpose: input.purpose, allowed_verifiers: input.allowed_verifiers || [], minimum_freshness_days: input.minimum_freshness_days || 30 }, evidence_retention: { raw_evidence_copied: false, commitments_only: true, revoke_supported: true }, passport_root: hash(claims.map((x: any) => x.commitment).sort().join(':')), status: 'valid' }
}

export function coordinateTransactionAuthority(input: any) {
  const requirements = (input.requirements || []).slice(0, 100); const proofs = input.proofs || {}
  const checks = requirements.map((r: any) => ({ key: r.key, type: r.type || 'authority', valid: Boolean(proofs[r.key]?.valid) && (!proofs[r.key]?.expires_at || new Date(proofs[r.key].expires_at).getTime() > Date.now()), proof_ref: proofs[r.key]?.ref || null }))
  const missing = checks.filter((x: any) => !x.valid).map((x: any) => ({ key: x.key, type: x.type }))
  const route = missing.length && input.fallback_route ? [{ mode: 'lawful_fallback', route: input.fallback_route }] : [{ mode: 'requested', route: input.requested_route || 'direct' }]
  const decision = missing.length ? (input.fallback_route ? 'reroute' : 'hold') : 'allow'
  return { authority_checks: checks.filter((x: any) => x.type === 'authority'), agreement_checks: checks.filter((x: any) => x.type === 'agreement'), limit_checks: checks.filter((x: any) => x.type === 'limit'), routing_plan: route, missing_requirements: missing, decision, status: decision === 'allow' ? 'allowed' : decision === 'reroute' ? 'rerouted' : 'held' }
}

export function matchRegulatoryCounterparty(input: any) {
  const candidates = (input.candidates || []).slice(0, 100).map((c: any) => { const capacity = clamp(Number(c.capacity_fit || 0)); const authority = c.authority_valid === false ? 0 : clamp(Number(c.authority_score || 0)); const risk = clamp(100 - Number(c.risk_score || 0)); const economics = clamp(100 - Number(c.price_score || 0)); return { ...c, match_score: Math.round(authority * .35 + capacity * .3 + risk * .2 + economics * .15), eligible: c.consent_available !== false && c.authority_valid !== false } }).sort((a: any, b: any) => Number(b.eligible) - Number(a.eligible) || b.match_score - a.match_score)
  const winner = candidates.find((x: any) => x.eligible) || null
  return { candidates, recommended_match: winner ? { candidate_ref: winner.key, match_score: winner.match_score, requires_affirmative_introduction: true } : null, economics: winner ? { monthly_cents: Number(winner.monthly_cents || 0), setup_cents: Number(winner.setup_cents || 0) } : {}, conflicts: candidates.filter((x: any) => Number(x.conflict_score || 0) > 25).map((x: any) => ({ candidate_ref: x.key, conflict_score: x.conflict_score })), status: winner ? 'permission_required' : 'modeled' }
}

export function reconcileProviderSwarm(input: any) {
  const assessments = (input.provider_assessments || []).slice(0, 20).map((x: any) => ({ provider: x.provider, recommendation: x.recommendation, confidence: Math.max(0, Math.min(1, Number(x.confidence || 0))), material_gaps: x.material_gaps || [], evidence_digest: x.evidence_digest }))
  const votes: Record<string, number> = {}; assessments.forEach((x: any) => { votes[x.recommendation] = (votes[x.recommendation] || 0) + x.confidence })
  const ranked = Object.entries(votes).sort((a, b) => b[1] - a[1]); const recommendation = ranked[0]?.[0] || 'hold'; const total = assessments.reduce((s: number, x: any) => s + x.confidence, 0); const consensus = total ? Number(((ranked[0]?.[1] || 0) / total).toFixed(2)) : 0
  const dissent = assessments.filter((x: any) => x.recommendation !== recommendation); const gaps = [...new Set(assessments.flatMap((x: any) => x.material_gaps))]
  return { provider_assessments: assessments, consensus: { recommendation, confidence: consensus }, dissent, material_gaps: gaps, human_review_required: gaps.length > 0 || consensus < .75 || dissent.some((x: any) => x.confidence >= .8), routing_manifest: assessments.map((x: any) => ({ provider: x.provider, bounded_only: true, evidence_digest: x.evidence_digest })), status: gaps.length || consensus < .75 ? 'human_review' : 'evaluated' }
}

export function estimateCausalRegulatoryEffect(input: any) {
  const treated = (input.treated_outcomes || []).map(Number); const comparison = (input.comparison_outcomes || []).map(Number); const avg = (x: number[]) => x.length ? x.reduce((s, n) => s + n, 0) / x.length : 0; const effect = avg(treated) - avg(comparison); const sample = Math.min(treated.length, comparison.length); const confidence = Number(Math.min(.95, .35 + sample * .04 - (input.confounders || []).length * .05).toFixed(2))
  return { treated_outcomes: treated, comparison_outcomes: comparison, estimated_effect: { absolute: Number(effect.toFixed(3)), treated_mean: Number(avg(treated).toFixed(3)), comparison_mean: Number(avg(comparison).toFixed(3)), causal_claim_allowed: confidence >= .75 && (input.confounders || []).length === 0 }, confounders: input.confounders || [], transfer_conditions: input.transfer_conditions || ['same_activity','similar_jurisdiction','comparable_customer_segment'], confidence, status: confidence >= .75 ? 'quasi_experimental' : 'observational' }
}

export function simulateCustomerOutcomes(input: any) {
  const segments = (input.segments || []).slice(0, 50); const scenarios = (input.scenarios || []).slice(0, 50)
  const evaluated = scenarios.flatMap((scenario: any) => segments.map((segment: any) => ({ scenario: scenario.key, segment: segment.key, approval_rate: clamp(Number(scenario.approval_rate || 0) + Number(segment.adjustment || 0)), cost_cents: Number(scenario.cost_cents || 0), error_rate: clamp(Number(scenario.error_rate || 0) + Number(segment.error_adjustment || 0)), access_score: clamp(Number(scenario.access_score || 0) + Number(segment.access_adjustment || 0)) })))
  const approval = evaluated.map(x => x.approval_rate); const access = evaluated.map(x => x.access_score); const disparity = Math.max(0, ...approval) - Math.min(100, ...approval); const accessGap = Math.max(0, ...access) - Math.min(100, ...access)
  const disparities = [disparity > Number(input.max_approval_disparity || 15) && { metric: 'approval_rate', gap: disparity }, accessGap > Number(input.max_access_disparity || 15) && { metric: 'access_score', gap: accessGap }].filter(Boolean)
  const harms = evaluated.filter(x => x.error_rate > Number(input.max_error_rate || 5)).map(x => ({ scenario: x.scenario, segment: x.segment, harm: 'error_rate_above_threshold', value: x.error_rate }))
  return { segments, scenarios: evaluated, outcome_metrics: { approval_disparity: disparity, access_disparity: accessGap, evaluated_cells: evaluated.length }, disparity_findings: disparities, harm_findings: harms, mitigations: [...(disparities.length ? ['adjust_eligibility_or_pricing_and_retest'] : []), ...(harms.length ? ['improve_error_controls_and_add_human_fallback'] : [])], launch_recommendation: disparities.length || harms.length ? 'hold_for_mitigation' : 'eligible_for_shadow_launch', status: disparities.length || harms.length ? 'review' : 'shadow' }
}

export function createRuntimeComplianceReceipt(input: any) {
  const inputs = hash(input.policy_inputs || {}); const decision = hash(input.decision || {}); const receipt = hash([input.transaction_ref, input.authority_ref, input.agreement_ref, input.model_ref, input.approval_ref, input.fallback_ref, inputs, decision, input.receipt_chain_prev].join(':'))
  return { policy_inputs_digest: inputs, decision_digest: decision, receipt_chain_prev: input.receipt_chain_prev || null, receipt_digest: receipt, verification_manifest: { algorithm: 'sha256', chain_bound: Boolean(input.receipt_chain_prev), required_refs_present: ['authority_ref','agreement_ref'].filter(key => Boolean(input[key])) }, status: 'valid' }
}

export function forecastSupervisoryCapacity(input: any) {
  const periods = (input.periods || []).slice(0, 36).map((x: any) => { const demand = Number(x.expected_cases || 0) * Number(x.minutes_per_case || 0); const supply = Number(x.available_minutes || 0); return { period: x.period, demand_minutes: demand, supply_minutes: supply, shortage_minutes: Math.max(0, demand - supply), confidence: Number(x.confidence || .6) } })
  const shortages = periods.filter((x: any) => x.shortage_minutes > 0); const options = (input.reservation_options || []).map((x: any) => ({ ...x, coverage_ratio: shortages.reduce((s: number, p: any) => s + Math.min(p.shortage_minutes, Number(x.minutes || 0)), 0) / Math.max(1, shortages.reduce((s: number, p: any) => s + p.shortage_minutes, 0)) })).sort((a: any, b: any) => b.coverage_ratio - a.coverage_ratio || Number(a.cost_cents || 0) - Number(b.cost_cents || 0))
  return { forecast: { periods, total_shortage_minutes: shortages.reduce((s: number, x: any) => s + x.shortage_minutes, 0) }, shortage_windows: shortages, reservation_options: options, recommended_reservation: options[0] || null, risk_transfer_terms: { type: 'operational_capacity_reservation', financial_derivative: false, insurance: false }, approval_requirements: ['budget_owner','provider_consent','agreement_execution'], status: options.length ? 'permission_required' : 'forecast' }
}

export async function saveProofMarketAction(organizationId: string, action: string, values: any) {
  const sb = serviceClient(); const insert = async (table: string, row: any) => { const { data, error } = await sb.from(table).insert(row).select().single(); if (error) throw createError({ statusCode: 500, message: error.message }); return data }; const expires = values.expires_at || new Date(Date.now() + 24 * 3600e3).toISOString()
  if (action === 'privacy_passport') { const result = buildPrivacyPassport({ ...values, expires_at: expires }); return insert('regulatory_privacy_passports', { organization_id: organizationId, subject_ref: bounded(values.subject_ref), ...result, expires_at: expires, passport_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'coordinate_transaction') { const result = coordinateTransactionAuthority(values); return insert('regulatory_transaction_authorizations', { organization_id: organizationId, transaction_ref: bounded(values.transaction_ref), parties: values.parties || [], jurisdictions: values.jurisdictions || [], activities: values.activities || [], ...result, receipt_digest: hash({ organizationId, values, result, nonce: randomBytes(4).toString('hex') }), expires_at: expires }) }
  if (action === 'counterparty_order') { const result = matchRegulatoryCounterparty(values); return insert('regulatory_counterparty_orders', { organization_id: organizationId, order_type: bounded(values.order_type), capability: bounded(values.capability), jurisdictions: values.jurisdictions || [], requested_capacity: values.requested_capacity || {}, risk_profile: values.risk_profile || {}, consent_policy: values.consent_policy || { affirmative: true }, ...result, order_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'provider_swarm') { const result = reconcileProviderSwarm(values); return insert('regulatory_swarm_escalations', { organization_id: organizationId, subject_ref: bounded(values.subject_ref), bounded_packet: values.bounded_packet || {}, ...result, escalation_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'causal_memory') { const result = estimateCausalRegulatoryEffect(values); return insert('regulatory_causal_memory', { organization_id: organizationId, intervention_key: bounded(values.intervention_key), context_signature: hash(values.context || {}), ...result, memory_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'customer_outcome_twin') { const result = simulateCustomerOutcomes(values); return insert('regulatory_customer_outcome_twins', { organization_id: organizationId, feature_ref: bounded(values.feature_ref), ...result, twin_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  if (action === 'runtime_receipt') { const result = createRuntimeComplianceReceipt(values); return insert('regulatory_runtime_receipts', { organization_id: organizationId, transaction_ref: bounded(values.transaction_ref), authority_ref: values.authority_ref || null, agreement_ref: values.agreement_ref || null, model_ref: values.model_ref || null, approval_ref: values.approval_ref || null, fallback_ref: values.fallback_ref || null, ...result, expires_at: expires }) }
  if (action === 'capacity_reservation') { const result = forecastSupervisoryCapacity(values); return insert('regulatory_capacity_reservations', { organization_id: organizationId, capability: bounded(values.capability), jurisdiction: bounded(values.jurisdiction), ...result, reservation_digest: hash({ organizationId, values, nonce: randomBytes(4).toString('hex') }) }) }
  throw createError({ statusCode: 400, message: 'unknown_regulatory_proof_market_action' })
}

export async function proofMarketCockpit(organizationId: string) {
  const sb = serviceClient(); const names = ['regulatory_privacy_passports','regulatory_transaction_authorizations','regulatory_counterparty_orders','regulatory_swarm_escalations','regulatory_causal_memory','regulatory_customer_outcome_twins','regulatory_runtime_receipts','regulatory_capacity_reservations']; const results = await Promise.all(names.map(name => sb.from(name).select('*').eq('organization_id', organizationId).order('created_at', { ascending: false }).limit(30))); const [passports, transactions, orders, swarms, memories, twins, receipts, capacity] = results.map(x => x.data || [])
  return { passports, transactions, counterparty_orders: orders, provider_swarms: swarms, causal_memory: memories, customer_outcome_twins: twins, runtime_receipts: receipts, capacity_reservations: capacity, summary: { valid_passports: passports.filter((x: any) => x.status === 'valid' && new Date(x.expires_at).getTime() > Date.now()).length, held_transactions: transactions.filter((x: any) => x.status === 'held').length, permissioned_matches: orders.filter((x: any) => x.status === 'permission_required').length, swarm_human_escalations: swarms.filter((x: any) => x.human_review_required).length, reusable_causal_memories: memories.filter((x: any) => x.estimated_effect?.causal_claim_allowed).length, outcome_holds: twins.filter((x: any) => x.launch_recommendation === 'hold_for_mitigation').length, valid_runtime_receipts: receipts.filter((x: any) => x.status === 'valid' && new Date(x.expires_at).getTime() > Date.now()).length, capacity_shortage_minutes: capacity.reduce((s: number, x: any) => s + Number(x.forecast?.total_shortage_minutes || 0), 0) } }
}
