import{describe,expect,it}from'vitest'
import{FUNCTIONAL_AGENTS,compileExecutivePolicyIR,counterfactualNegotiationValue,planBusinessSaga,reconcileBusinessEvidence,simulateEntityJurisdictions}from'./virtualExecutiveTeam'
describe('virtual executive team',()=>{
 it('provisions every critical business function under deny-by-default policy',()=>{expect(FUNCTIONAL_AGENTS.map(x=>x.domain)).toEqual(expect.arrayContaining(['hr','payroll','banking','tax','legal','compliance','accounting','security','procurement','revenue','risk','operations']));const p=compileExecutivePolicyIR({mode:'exception_only',jurisdictions:['US-CA'],approval_amount:10000});expect(p.ast.default_effect).toBe('deny');expect(p.ast.rules.find(x=>x.id==='external_effect')?.effect).toContain('credential');expect(p.ast.tests).toHaveLength(4)})
 it('creates deterministic compensated sagas and gates every external effect',()=>{const values={period_end:'2026-07-31',pay_date:'2026-08-01',jurisdiction:'US-CA'},a:any=planBusinessSaga('payroll_run',values,['payroll','banking'],'policy'),b:any=planBusinessSaga('payroll_run',values,['payroll','banking'],'policy');expect(a.idempotency_key).toBe(b.idempotency_key);expect(a.steps.filter((x:any)=>x.external_effect).length).toBeGreaterThan(0);expect(a.steps.filter((x:any)=>x.reversible).every((x:any)=>x.compensation_operation)).toBe(true)})
 it('asks only for missing minimum input',()=>{const plan:any=planBusinessSaga('tax_filing',{jurisdiction:'US-CA'},[],'policy');expect(plan.needs_input).toBe(true);expect(plan.missing).toEqual(['tax_type','period'])})
 it('reconciles evidence and surfaces near-term exceptions',()=>{const due=new Date(Date.now()+86400000).toISOString();const result=reconcileBusinessEvidence({obligations:[{id:'o1',status:'open',due_at:due,contract_id:'c1'}],actions:[{status:'completed',action_type:'monitor',payload:{contract_id:'c1'}}],financial:[],receipts:[]});expect(result.exceptions).toHaveLength(1);expect(result.matches).toHaveLength(1)})
 it('keeps structural and negotiation simulations explicitly assumption-bound',()=>{const structure=simulateEntityJurisdictions({objective:'Expand',jurisdictions:['US-DE'],entity_types:['single_entity'],revenue:100000});expect(structure.professional_review_required).toBe(true);expect(structure.scored_outcomes[0].not_legal_or_tax_advice).toBe(true);const value=counterfactualNegotiationValue({annual_value:100000,margin:.5,churn_risk:.1,dispute_risk:.05,operational_cost:5000});expect(value.scenarios).toHaveLength(4);expect(value.requires_observed_outcomes).toBe(true)})
})
