/**
 * Tool definitions for Apparently — Gaming RegTech.
 * 10 tools covering licensing, legal review, compliance, disclosure, and intel.
 */
import type { ToolDefinition } from '../types.js';

export const APPARENTLY_TOOLS: ToolDefinition[] = [
  { name: 'apparently.licensing.determine_requirements', description: 'Determine which gaming licenses are required for a product/service across specified US states. Returns required license types, estimated costs, timeline, risk assessment per jurisdiction.', inputSchema: { type: 'object', properties: { product_description: { type: 'string', description: 'Description of the product or service' }, states: { type: 'array', description: 'US states to check', items: { type: 'string' } }, revenue_model: { type: 'string', description: 'Revenue model type' }, entity_structure: { type: 'string', description: 'Corporate entity structure' } }, required: ['product_description'] }, proxyTo: { method: 'POST', path: '/api/licensing/scope-determination' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'apparently.licensing.multi_jurisdiction_plan', description: 'Generate a multi-state filing strategy with optimal sequencing, reciprocity opportunities, and minimum-work pathways.', inputSchema: { type: 'object', properties: { product_description: { type: 'string' }, target_states: { type: 'array', items: { type: 'string' } }, held_licenses: { type: 'array', items: { type: 'string' } }, budget_usd: { type: 'number', minimum: 0 } }, required: ['product_description', 'target_states'] }, proxyTo: { method: 'POST', path: '/api/licensing/multi-jurisdiction-plan' }, costProfile: 'ai-heavy', pricingCents: 10000 },
  { name: 'apparently.licensing.tier_fit', description: 'Recommend the lowest defensible licensing tier per state based on revenue model.', inputSchema: { type: 'object', properties: { product_description: { type: 'string' }, revenue_model: { type: 'string' }, states: { type: 'array', items: { type: 'string' } } }, required: ['product_description', 'revenue_model'] }, proxyTo: { method: 'POST', path: '/api/licensing/tier-fit' }, costProfile: 'ai-heavy', pricingCents: 2500 },
  { name: 'apparently.licensing.reciprocity', description: 'Given currently held licenses, identify jurisdictions likely to grant expedited reciprocity.', inputSchema: { type: 'object', properties: { held_licenses: { type: 'array', items: { type: 'object', properties: { state: { type: 'string' }, license_type: { type: 'string' } } } } }, required: ['held_licenses'] }, proxyTo: { method: 'POST', path: '/api/licensing/reciprocity/suggest' }, costProfile: 'ai-light', pricingCents: 1000 },
  { name: 'apparently.legal.review_opinion', description: 'Run a full 6-pass AI legal review: extraction, specialist bots, compliance, citation verification, adversarial CADE review, consensus synthesis.', inputSchema: { type: 'object', properties: { question: { type: 'string', description: 'Legal question to analyze' }, jurisdiction: { type: 'string' }, vertical: { type: 'string', enum: ['gaming', 'sweepstakes', 'fantasy-sports', 'igaming', 'sports-betting'] } }, required: ['question'] }, proxyTo: { method: 'POST', path: '/api/legal-opinions/review-orchestrated' }, costProfile: 'ai-heavy', pricingCents: 25000 },
  { name: 'apparently.legal.verify_citations', description: 'Verify all legal citations against public primary sources (eCFR, CourtListener, LegiScan). Flags hallucinated citations.', inputSchema: { type: 'object', properties: { text: { type: 'string', description: 'Text containing legal citations to verify' } }, required: ['text'] }, proxyTo: { method: 'POST', path: '/api/legal-opinions/verify-citations' }, costProfile: 'ai-light', pricingCents: 1500 },
  { name: 'apparently.compliance.sweepstakes_check', description: 'Check a promotional offer for legal compliance across all 50 US states. Returns per-state legality, required disclosures, registration requirements.', inputSchema: { type: 'object', properties: { promotion_description: { type: 'string' }, states: { type: 'array', items: { type: 'string' } }, prize_value_usd: { type: 'number', minimum: 0 }, entry_mechanism: { type: 'string', enum: ['no-purchase', 'purchase-required', 'amoe'] } }, required: ['promotion_description'] }, proxyTo: { method: 'POST', path: '/api/rewards/gaming/provision' }, costProfile: 'ai-heavy', pricingCents: 3000 },
  { name: 'apparently.compliance.what_if', description: 'Simulate a regulatory scenario (ownership restructure, new product, jurisdiction entry) against existing compliance posture.', inputSchema: { type: 'object', properties: { scenario: { type: 'string', description: 'Scenario to simulate' }, current_licenses: { type: 'array', items: { type: 'object' } } }, required: ['scenario'] }, proxyTo: { method: 'POST', path: '/api/whatif/simulate' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'apparently.disclosure.control_graph', description: 'Resolve a corporate control graph from cap table data for gaming regulatory disclosure.', inputSchema: { type: 'object', properties: { entities: { type: 'array', description: 'Corporate entities with ownership relationships', items: { type: 'object', properties: { name: { type: 'string' }, type: { type: 'string' }, ownership_pct: { type: 'number' }, parent: { type: 'string' } } } } }, required: ['entities'] }, proxyTo: { method: 'POST', path: '/api/disclosure/control-graph' }, costProfile: 'pure-logic', pricingCents: 500 },
  { name: 'apparently.intel.recommend_jurisdictions', description: 'AI jurisdiction recommender: rank all US gaming jurisdictions by opportunity, risk, cost, and timeline for your product.', inputSchema: { type: 'object', properties: { product_description: { type: 'string' }, business_model: { type: 'string' }, budget_usd: { type: 'number', minimum: 0 } }, required: ['product_description'] }, proxyTo: { method: 'POST', path: '/api/smart-intake/recommend-jurisdictions' }, costProfile: 'ai-heavy', pricingCents: 5000 },
];
