/**
 * Tool definitions for Apparently -- Gaming RegTech.
 * 10 tools covering licensing, legal, compliance, disclosure, and regulator intelligence.
 */
import type { ToolDefinition } from '../types.js';

export const APPARENTLY_TOOLS: ToolDefinition[] = [
  { name: 'apparently.licensing.determine_requirements', description: 'Determine licensing requirements for a gaming operation in one or more jurisdictions. Returns required license types, application fees, timelines, and key conditions.', inputSchema: { type: 'object', properties: { jurisdictions: { type: 'array', description: 'List of jurisdiction codes', items: { type: 'string' } }, activityType: { type: 'string', description: 'Type of gaming activity', enum: ['casino','sports-betting','igaming','poker','lottery','fantasy-sports','sweepstakes'] }, entityType: { type: 'string', description: 'Type of business entity', enum: ['operator','supplier','manufacturer','platform-provider','affiliate'] }, revenueEstimate: { type: 'number', description: 'Estimated annual GGR in USD', minimum: 0 } }, required: ['jurisdictions','activityType','entityType'] }, proxyTo: { method: 'POST', path: '/api/licensing/requirements' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'apparently.licensing.multi_jurisdiction_plan', description: 'Generate a phased multi-jurisdiction licensing strategy. Prioritizes by market size, regulatory complexity, and reciprocity.', inputSchema: { type: 'object', properties: { targetJurisdictions: { type: 'array', description: 'Target jurisdiction codes', items: { type: 'string' } }, activityType: { type: 'string', enum: ['casino','sports-betting','igaming','poker','lottery','fantasy-sports','sweepstakes'] }, budget: { type: 'number', description: 'Total licensing budget USD', minimum: 0 }, timelineMonths: { type: 'number', minimum: 1, maximum: 60 }, existingLicenses: { type: 'array', items: { type: 'string' } } }, required: ['targetJurisdictions','activityType'] }, proxyTo: { method: 'POST', path: '/api/licensing/multi-jurisdiction-plan' }, costProfile: 'ai-heavy', pricingCents: 10000 },
  { name: 'apparently.licensing.tier_fit', description: 'Evaluate which licensing tier (full, provisional, temporary) best fits the applicant profile.', inputSchema: { type: 'object', properties: { jurisdiction: { type: 'string' }, activityType: { type: 'string', enum: ['casino','sports-betting','igaming','poker','lottery','fantasy-sports','sweepstakes'] }, urgency: { type: 'string', enum: ['standard','expedited','emergency'] }, applicantProfile: { type: 'object', properties: { yearsInBusiness: { type: 'number' }, existingLicenseCount: { type: 'number' }, complianceHistory: { type: 'string', enum: ['clean','minor-issues','major-issues'] } } } }, required: ['jurisdiction','activityType'] }, proxyTo: { method: 'POST', path: '/api/licensing/tier-fit' }, costProfile: 'ai-light', pricingCents: 2500 },
  { name: 'apparently.licensing.reciprocity', description: 'Check reciprocity and mutual recognition agreements between jurisdictions.', inputSchema: { type: 'object', properties: { sourceJurisdiction: { type: 'string' }, targetJurisdiction: { type: 'string' }, licenseType: { type: 'string' } }, required: ['sourceJurisdiction','targetJurisdiction'] }, proxyTo: { method: 'GET', path: '/api/licensing/reciprocity' }, costProfile: 'pure-logic', pricingCents: 1000 },
  { name: 'apparently.legal.review_opinion', description: 'Generate a legal opinion review on a gaming regulatory matter with confidence levels.', inputSchema: { type: 'object', properties: { jurisdiction: { type: 'string' }, question: { type: 'string' }, context: { type: 'string' }, activityType: { type: 'string', enum: ['casino','sports-betting','igaming','poker','lottery','fantasy-sports','sweepstakes'] }, includeRegulatorySentiment: { type: 'boolean', default: true } }, required: ['jurisdiction','question'] }, proxyTo: { method: 'POST', path: '/api/legal/opinion' }, costProfile: 'ai-heavy', pricingCents: 25000 },
  { name: 'apparently.legal.verify_citations', description: 'Verify legal citations against the regulatory corpus.', inputSchema: { type: 'object', properties: { citations: { type: 'array', items: { type: 'string' } }, jurisdiction: { type: 'string' }, documentType: { type: 'string', enum: ['legal-opinion','compliance-report','application','disclosure','regulatory-filing'] } }, required: ['citations','jurisdiction'] }, proxyTo: { method: 'POST', path: '/api/legal/verify-citations' }, costProfile: 'ai-light', pricingCents: 1500 },
  { name: 'apparently.compliance.sweepstakes_check', description: 'Analyze a promotional mechanic for sweepstakes law compliance.', inputSchema: { type: 'object', properties: { jurisdiction: { type: 'string' }, mechanic: { type: 'object', properties: { entryMethod: { type: 'string' }, prizeType: { type: 'string' }, prizeValue: { type: 'number' }, hasAlternateEntry: { type: 'boolean' }, virtualCurrency: { type: 'boolean' }, duration: { type: 'string' } } } }, required: ['jurisdiction','mechanic'] }, proxyTo: { method: 'POST', path: '/api/compliance/sweepstakes-check' }, costProfile: 'ai-heavy', pricingCents: 3000 },
  { name: 'apparently.compliance.what_if', description: 'Run a what-if scenario analysis for a proposed change to gaming operations.', inputSchema: { type: 'object', properties: { scenario: { type: 'string' }, affectedJurisdictions: { type: 'array', items: { type: 'string' } }, changeType: { type: 'string', enum: ['product-feature','payment-method','marketing','territory-expansion','technology','personnel'] }, currentCompliance: { type: 'string', enum: ['compliant','pending-review','conditional'] } }, required: ['scenario','affectedJurisdictions','changeType'] }, proxyTo: { method: 'POST', path: '/api/compliance/what-if' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'apparently.disclosure.control_graph', description: 'Generate a disclosure control graph showing entity relationships and beneficial ownership chains.', inputSchema: { type: 'object', properties: { entityId: { type: 'string' }, jurisdiction: { type: 'string' }, depth: { type: 'number', minimum: 1, maximum: 10, default: 3 }, includeIndividuals: { type: 'boolean', default: true } }, required: ['entityId','jurisdiction'] }, proxyTo: { method: 'GET', path: '/api/disclosure/control-graph' }, costProfile: 'pure-logic', pricingCents: 500 },
  { name: 'apparently.intel.recommend_jurisdictions', description: 'Recommend optimal jurisdictions for market entry based on regulatory environment and market size.', inputSchema: { type: 'object', properties: { activityType: { type: 'string', enum: ['casino','sports-betting','igaming','poker','lottery','fantasy-sports','sweepstakes'] }, priorities: { type: 'array', items: { type: 'string', enum: ['market-size','tax-rate','speed-to-market','regulatory-stability','reciprocity','cost'] } }, excludeJurisdictions: { type: 'array', items: { type: 'string' } }, maxResults: { type: 'number', minimum: 1, maximum: 25, default: 10 } }, required: ['activityType'] }, proxyTo: { method: 'POST', path: '/api/intel/recommend-jurisdictions' }, costProfile: 'ai-heavy', pricingCents: 5000 },
];
