/**
 * Tool definitions for Pareto 2080 — Personal Finance.
 * 12 tools covering retirement, tax, portfolio, treasury, and sweeps.
 */
import type { ToolDefinition } from '../types.js';

export const PARETO_TOOLS: ToolDefinition[] = [
  { name: 'pareto.retirement.monte_carlo', description: 'Run probabilistic retirement simulation with P10/P50/P90 outcomes, success probability, and retirement-day exchange rate.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' }, scenarioOverrides: { type: 'object', description: 'Optional overrides for income, expenses, returns, inflation' } }, required: ['userId'] }, proxyTo: { method: 'GET', path: '/api/personal/retirement/montecarlo' }, costProfile: 'pure-logic', pricingCents: 100 },
  { name: 'pareto.retirement.social_security', description: 'Calculate Social Security benefits by claim age (62-70), breakeven analysis, spousal benefits, taxation, and optimal claiming strategy.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'GET', path: '/api/personal/retirement/social-security' }, costProfile: 'pure-logic', pricingCents: 50 },
  { name: 'pareto.retirement.decumulation', description: 'Tax-aware withdrawal sequencing across traditional/Roth/taxable accounts. Roth conversion ladder, over-saving detection, RMD planning.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'GET', path: '/api/personal/retirement/decumulation' }, costProfile: 'pure-logic', pricingCents: 100 },
  { name: 'pareto.tax.deduction_optimizer', description: 'Compare standard vs itemized deductions with caps, rerouting, above-the-line steering, bunching strategies, and charitable optimization.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'POST', path: '/api/finance/deductions' }, costProfile: 'pure-logic', pricingCents: 50 },
  { name: 'pareto.tax.entity_routing', description: 'Route each expense to the optimal tax entity (personal/business). QBI deduction optimization, combined plan.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'POST', path: '/api/finance/tax-optimizer' }, costProfile: 'pure-logic', pricingCents: 100 },
  { name: 'pareto.portfolio.optimize', description: 'Liability-driven asset allocation, glidepath, tax-loss harvesting, rebalancing triggers, and asset location across account types.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'POST', path: '/api/finance/portfolio-optimize' }, costProfile: 'pure-logic', pricingCents: 200 },
  { name: 'pareto.portfolio.recommendations', description: 'AI-scored investment recommendations. Ranks across 7 dimensions: CAGR, Sortino, diversification, net CAGR, expense ratio, momentum, drawdown.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' }, amount: { type: 'number', description: 'Deposit amount in USD' } }, required: ['userId'] }, proxyTo: { method: 'GET', path: '/api/investments/recommendations' }, costProfile: 'ai-light', pricingCents: 300 },
  { name: 'pareto.finance.opportunities', description: 'Unified opportunity scanner: unclaimed money, optimization gaps, tax savings, benefit windows, actionable improvements ranked by value.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'GET', path: '/api/personal/opportunities' }, costProfile: 'pure-logic', pricingCents: 100 },
  { name: 'pareto.finance.allocator', description: 'Unified-loop allocator: invest vs spend-now vs save-for-later across all goals. Luxury frontier slider.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'POST', path: '/api/finance/allocator/proposal' }, costProfile: 'pure-logic', pricingCents: 100 },
  { name: 'pareto.treasury.briefing', description: 'Personal treasury briefing: deposit bonus rotation, JIT liquidity, yield optimization, counterfactual analysis.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'GET', path: '/api/personal/treasury' }, costProfile: 'pure-logic', pricingCents: 100 },
  { name: 'pareto.sweeps.equity_comp', description: 'Equity compensation optimizer: ESPP discount, RSU vest withholding gap, ISO AMT analysis, 83(b) election decision.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'GET', path: '/api/personal/sweeps/equity-comp' }, costProfile: 'pure-logic', pricingCents: 100 },
  { name: 'pareto.sweeps.subscription_savings', description: 'AI-ranked subscription savings sweep: detect recurring charges, cancellation/downgrade/negotiation opportunities.', inputSchema: { type: 'object', properties: { userId: { type: 'string', description: 'User ID' } }, required: ['userId'] }, proxyTo: { method: 'POST', path: '/api/finance/sweep-proposal' }, costProfile: 'ai-light', pricingCents: 200 },
];
