/**
 * Tool definitions for Smarter -- Legal Ops.
 * 12 tools covering war room, contract analysis, research, intel, and drafting.
 */
import type { ToolDefinition } from '../types.js';

export const SMARTER_TOOLS: ToolDefinition[] = [
  { name: 'smarter.warroom.copilot', description: 'AI war room copilot for active litigation. Analyzes case posture, surfaces relevant precedent, and suggests strategic moves.', inputSchema: { type: 'object', properties: { matterId: { type: 'string' }, query: { type: 'string' }, caseType: { type: 'string', enum: ['litigation','arbitration','regulatory','transaction','ip-dispute','employment'] }, jurisdiction: { type: 'string' }, documents: { type: 'array', items: { type: 'string' } } }, required: ['matterId','query'] }, proxyTo: { method: 'POST', path: '/api/warroom/copilot' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'smarter.warroom.frontier', description: 'Identify the legal frontier -- novel arguments, untested theories, and emerging trends.', inputSchema: { type: 'object', properties: { matterId: { type: 'string' }, legalIssues: { type: 'array', items: { type: 'string' } }, jurisdiction: { type: 'string' }, riskAppetite: { type: 'string', enum: ['conservative','moderate','aggressive'] } }, required: ['matterId','legalIssues'] }, proxyTo: { method: 'POST', path: '/api/warroom/frontier' }, costProfile: 'ai-heavy', pricingCents: 3000 },
  { name: 'smarter.warroom.draft_clause', description: 'Draft a contract clause with multiple variants and risk commentary.', inputSchema: { type: 'object', properties: { matterId: { type: 'string' }, clauseType: { type: 'string', enum: ['indemnification','limitation-of-liability','termination','non-compete','confidentiality','ip-assignment','governing-law','arbitration','force-majeure','representations','custom'] }, context: { type: 'string' }, partyRole: { type: 'string', enum: ['drafter-favorable','balanced','counterparty-favorable'] }, governingLaw: { type: 'string' } }, required: ['clauseType','context'] }, proxyTo: { method: 'POST', path: '/api/warroom/draft-clause' }, costProfile: 'ai-heavy', pricingCents: 2000 },
  { name: 'smarter.contract.extract_obligations', description: 'Extract all obligations, deadlines, and deliverables from a contract.', inputSchema: { type: 'object', properties: { documentId: { type: 'string' }, contractText: { type: 'string' }, partyName: { type: 'string' }, includeConditional: { type: 'boolean', default: true } } }, proxyTo: { method: 'POST', path: '/api/contract/extract-obligations' }, costProfile: 'ai-heavy', pricingCents: 2000 },
  { name: 'smarter.contract.extract_positions', description: 'Extract negotiating positions from a contract draft.', inputSchema: { type: 'object', properties: { documentId: { type: 'string' }, contractText: { type: 'string' }, priorVersionId: { type: 'string' } } }, proxyTo: { method: 'POST', path: '/api/contract/extract-positions' }, costProfile: 'ai-heavy', pricingCents: 1500 },
  { name: 'smarter.contract.suggest_clause', description: 'Suggest an improved clause with risk analysis and alternatives.', inputSchema: { type: 'object', properties: { existingClause: { type: 'string' }, contractType: { type: 'string', enum: ['saas','services','license','employment','nda','partnership','loan','lease'] }, objective: { type: 'string' }, governingLaw: { type: 'string' } }, required: ['existingClause','objective'] }, proxyTo: { method: 'POST', path: '/api/contract/suggest-clause' }, costProfile: 'ai-heavy', pricingCents: 1000 },
  { name: 'smarter.research.dossier', description: 'Generate a research dossier on a legal topic synthesizing case law, statutes, and regulatory actions.', inputSchema: { type: 'object', properties: { topic: { type: 'string' }, jurisdiction: { type: 'string' }, depth: { type: 'string', enum: ['quick','standard','comprehensive'], default: 'standard' }, focusAreas: { type: 'array', items: { type: 'string' } }, dateRange: { type: 'object', properties: { from: { type: 'string' }, to: { type: 'string' } } } }, required: ['topic'] }, proxyTo: { method: 'POST', path: '/api/research/dossier' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'smarter.research.verify_citations', description: 'Verify legal citations for accuracy including case names, reporter volumes, and holdings.', inputSchema: { type: 'object', properties: { citations: { type: 'array', items: { type: 'object', properties: { citation: { type: 'string' }, proposition: { type: 'string' } }, required: ['citation'] } }, jurisdiction: { type: 'string' } }, required: ['citations'] }, proxyTo: { method: 'POST', path: '/api/research/verify-citations' }, costProfile: 'ai-light', pricingCents: 1000 },
  { name: 'smarter.intel.counterparty', description: 'Build a counterparty intelligence profile with litigation history and negotiation patterns.', inputSchema: { type: 'object', properties: { entityName: { type: 'string' }, entityType: { type: 'string', enum: ['corporation','llc','partnership','individual','government-agency'] }, jurisdiction: { type: 'string' }, focusAreas: { type: 'array', items: { type: 'string', enum: ['litigation-history','regulatory-actions','financial-health','negotiation-patterns','key-personnel'] } } }, required: ['entityName'] }, proxyTo: { method: 'POST', path: '/api/intel/counterparty' }, costProfile: 'ai-heavy', pricingCents: 2000 },
  { name: 'smarter.intel.deal', description: 'Analyze a deal structure for legal risks, tax implications, and structural optimizations.', inputSchema: { type: 'object', properties: { dealType: { type: 'string', enum: ['ma','joint-venture','licensing','financing','real-estate','ip-transfer','restructuring'] }, dealSummary: { type: 'string' }, dealValue: { type: 'number', minimum: 0 }, jurisdictions: { type: 'array', items: { type: 'string' } }, parties: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, role: { type: 'string', enum: ['buyer','seller','investor','target','partner'] } } } } }, required: ['dealType','dealSummary'] }, proxyTo: { method: 'POST', path: '/api/intel/deal' }, costProfile: 'ai-heavy', pricingCents: 3000 },
  { name: 'smarter.draft.engagement_letter', description: 'Draft an engagement letter covering scope, fees, conflicts, and termination.', inputSchema: { type: 'object', properties: { clientName: { type: 'string' }, matterType: { type: 'string', enum: ['litigation','transaction','advisory','regulatory','ip','employment'] }, feeArrangement: { type: 'string', enum: ['hourly','flat-fee','contingency','hybrid','retainer'] }, scope: { type: 'string' }, jurisdiction: { type: 'string' }, conflictCheck: { type: 'boolean', default: false } }, required: ['clientName','matterType','scope'] }, proxyTo: { method: 'POST', path: '/api/draft/engagement-letter' }, costProfile: 'ai-heavy', pricingCents: 2000 },
  { name: 'smarter.draft.presend_review', description: 'Pre-send review of outgoing legal communications for privilege leaks and tone.', inputSchema: { type: 'object', properties: { content: { type: 'string' }, communicationType: { type: 'string', enum: ['email','letter','brief','motion','settlement-offer','demand-letter'] }, recipient: { type: 'string' }, matterId: { type: 'string' }, checkPrivilege: { type: 'boolean', default: true } }, required: ['content','communicationType'] }, proxyTo: { method: 'POST', path: '/api/draft/presend-review' }, costProfile: 'ai-light', pricingCents: 500 },
];
