/**
 * Tool definitions for Smarter — Legal Ops & Negotiation Intelligence.
 * 12 tools covering war room, contracts, research, intel, and drafting.
 */
import type { ToolDefinition } from '../types.js';

export const SMARTER_TOOLS: ToolDefinition[] = [
  { name: 'smarter.warroom.copilot', description: 'Full AI negotiation copilot session. Analyzes counterparty positions, suggests strategies, drafts responses, provides real-time guidance.', inputSchema: { type: 'object', properties: { dealId: { type: 'string', description: 'Deal/negotiation ID' }, context: { type: 'string', description: 'Current negotiation context or counterparty message' }, mode: { type: 'string', enum: ['analyze', 'respond', 'strategize'], description: 'Copilot mode' } }, required: ['dealId', 'context'] }, proxyTo: { method: 'POST', path: '/api/warroom/copilot' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'smarter.warroom.frontier', description: 'Compute the negotiation frontier: best/worst/likely outcomes across all open terms. Identifies trades and concession packages.', inputSchema: { type: 'object', properties: { dealId: { type: 'string', description: 'Deal ID' } }, required: ['dealId'] }, proxyTo: { method: 'POST', path: '/api/warroom/frontier' }, costProfile: 'ai-heavy', pricingCents: 3000 },
  { name: 'smarter.warroom.draft_clause', description: 'Draft or redline a contract clause with jurisdiction-aware language, fallback positions, and annotations.', inputSchema: { type: 'object', properties: { clauseType: { type: 'string', description: 'Type of clause' }, jurisdiction: { type: 'string', description: 'Governing jurisdiction' }, position: { type: 'string', enum: ['aggressive', 'balanced', 'conservative'], description: 'Drafting posture' }, context: { type: 'string', description: 'Deal context' } }, required: ['clauseType'] }, proxyTo: { method: 'POST', path: '/api/warroom/draft-clause' }, costProfile: 'ai-heavy', pricingCents: 2000 },
  { name: 'smarter.contract.extract_obligations', description: 'Extract all obligations, deadlines, and compliance requirements from a contract. Returns structured obligation graph.', inputSchema: { type: 'object', properties: { documentId: { type: 'string', description: 'Document ID' }, format: { type: 'string', enum: ['summary', 'detailed', 'calendar'], description: 'Output format' } }, required: ['documentId'] }, proxyTo: { method: 'POST', path: '/api/contracts/extract-obligations' }, costProfile: 'ai-heavy', pricingCents: 2000 },
  { name: 'smarter.contract.extract_positions', description: 'Analyze a contract for each party negotiating position on key terms. Identifies leverage points and market-standard deviations.', inputSchema: { type: 'object', properties: { documentId: { type: 'string', description: 'Document ID' }, contractType: { type: 'string', description: 'Contract type for benchmarking' } }, required: ['documentId'] }, proxyTo: { method: 'POST', path: '/api/contracts/extract-positions' }, costProfile: 'ai-heavy', pricingCents: 1500 },
  { name: 'smarter.contract.suggest_clause', description: 'Suggest optimal clause language from precedent corpus. Includes market-standard benchmarks and jurisdiction variants.', inputSchema: { type: 'object', properties: { clauseType: { type: 'string', description: 'Type of clause' }, contractType: { type: 'string', description: 'Overall contract type' }, jurisdiction: { type: 'string', description: 'Governing law' } }, required: ['clauseType'] }, proxyTo: { method: 'POST', path: '/api/contracts/suggest-clause' }, costProfile: 'ai-light', pricingCents: 1000 },
  { name: 'smarter.research.dossier', description: 'Comprehensive research dossier on a counterparty, entity, or legal topic. Pulls from corpus, public records, and AI analysis.', inputSchema: { type: 'object', properties: { subject: { type: 'string', description: 'Research subject' }, depth: { type: 'string', enum: ['quick', 'standard', 'deep'], description: 'Research depth' }, focus: { type: 'string', description: 'Aspects to emphasize' } }, required: ['subject'] }, proxyTo: { method: 'POST', path: '/api/research/dossier' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'smarter.research.verify_citations', description: 'Verify legal citations against the corpus. Checks existence, validity, supersession, and relevance.', inputSchema: { type: 'object', properties: { citations: { type: 'array', items: { type: 'string' }, description: 'Citation strings to verify' } }, required: ['citations'] }, proxyTo: { method: 'POST', path: '/api/research/verify-citations' }, costProfile: 'ai-light', pricingCents: 1000 },
  { name: 'smarter.intel.counterparty', description: 'Counterparty intelligence: negotiation history, known positions, organizational pressure points, predicted strategy.', inputSchema: { type: 'object', properties: { counterpartyName: { type: 'string', description: 'Counterparty organization name' }, dealContext: { type: 'string', description: 'Current deal context' } }, required: ['counterpartyName'] }, proxyTo: { method: 'POST', path: '/api/intel/counterparty' }, costProfile: 'ai-heavy', pricingCents: 2000 },
  { name: 'smarter.intel.deal', description: 'Full deal intelligence: market benchmarks, comparable transactions, risk assessment, recommended parameters.', inputSchema: { type: 'object', properties: { dealType: { type: 'string', description: 'Type of deal' }, industry: { type: 'string', description: 'Industry vertical' }, value: { type: 'number', description: 'Approximate deal value USD' } }, required: ['dealType'] }, proxyTo: { method: 'POST', path: '/api/intel/deal' }, costProfile: 'ai-heavy', pricingCents: 3000 },
  { name: 'smarter.draft.engagement_letter', description: 'Generate professional engagement letter with scope, fees, deliverables, and standard terms.', inputSchema: { type: 'object', properties: { clientName: { type: 'string', description: 'Client name' }, matterType: { type: 'string', description: 'Type of legal matter' }, jurisdiction: { type: 'string', description: 'Jurisdiction' }, feeStructure: { type: 'string', enum: ['hourly', 'fixed', 'contingency', 'hybrid'], description: 'Fee arrangement' } }, required: ['clientName', 'matterType'] }, proxyTo: { method: 'POST', path: '/api/drafts/engagement-letter' }, costProfile: 'ai-heavy', pricingCents: 2000 },
  { name: 'smarter.draft.presend_review', description: 'Pre-send review of any outgoing document. Checks legal risk, tone, missing disclosures, strategic alignment.', inputSchema: { type: 'object', properties: { content: { type: 'string', description: 'Document content to review' }, recipientType: { type: 'string', enum: ['client', 'counterparty', 'court', 'regulator'], description: 'Recipient category' } }, required: ['content'] }, proxyTo: { method: 'POST', path: '/api/drafts/presend-review' }, costProfile: 'ai-light', pricingCents: 500 },
];
