/**
 * Tool definitions for Tomorrow — OTC Derivatives Intelligence.
 * 10 tools covering pricing, risk, regulatory, structuring, and market intel.
 */
import type { ToolDefinition } from '../types.js';

export const TOMORROW_TOOLS: ToolDefinition[] = [
  { name: 'tomorrow.pricing.vanilla', description: 'Price vanilla OTC derivatives (swaps, forwards, options) with full Greeks, margin requirements, and counterparty exposure.', inputSchema: { type: 'object', properties: { instrumentType: { type: 'string', enum: ['swap', 'forward', 'option', 'swaption'], description: 'Derivative type' }, underlier: { type: 'string', description: 'Underlying asset or rate' }, notional: { type: 'number', description: 'Notional amount' }, tenor: { type: 'string', description: 'Contract tenor (e.g., 5Y, 18M)' }, direction: { type: 'string', enum: ['pay', 'receive', 'buy', 'sell'] } }, required: ['instrumentType', 'underlier', 'notional'] }, proxyTo: { method: 'POST', path: '/api/pricing/vanilla' }, costProfile: 'ai-light', pricingCents: 500 },
  { name: 'tomorrow.pricing.exotic', description: 'Price exotic/structured OTC derivatives with Monte Carlo simulation, barrier analysis, and path-dependent features.', inputSchema: { type: 'object', properties: { structure: { type: 'object', description: 'Structured product definition' }, simulationPaths: { type: 'number', description: 'Number of MC paths (default 10000)' } }, required: ['structure'] }, proxyTo: { method: 'POST', path: '/api/pricing/exotic' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'tomorrow.risk.portfolio_var', description: 'Calculate portfolio VaR, CVaR, stress scenarios, and concentration risk across all OTC positions.', inputSchema: { type: 'object', properties: { portfolioId: { type: 'string', description: 'Portfolio identifier' }, confidence: { type: 'number', description: 'VaR confidence level (default 0.99)' }, horizon: { type: 'string', description: 'Risk horizon (1D, 10D, etc.)' } }, required: ['portfolioId'] }, proxyTo: { method: 'POST', path: '/api/risk/portfolio-var' }, costProfile: 'pure-logic', pricingCents: 1000 },
  { name: 'tomorrow.risk.counterparty', description: 'Counterparty credit risk analysis: PFE, CVA/DVA, wrong-way risk, netting set optimization, and collateral adequacy.', inputSchema: { type: 'object', properties: { counterpartyId: { type: 'string', description: 'Counterparty identifier' }, nettingSetId: { type: 'string', description: 'Optional netting set filter' } }, required: ['counterpartyId'] }, proxyTo: { method: 'POST', path: '/api/risk/counterparty' }, costProfile: 'ai-light', pricingCents: 2000 },
  { name: 'tomorrow.regulatory.margin_calc', description: 'Calculate initial and variation margin under UMR/ISDA SIMM. Includes eligible collateral optimization and margin call forecasting.', inputSchema: { type: 'object', properties: { portfolioId: { type: 'string', description: 'Portfolio identifier' }, regime: { type: 'string', enum: ['ISDA-SIMM', 'grid', 'both'], description: 'Margin calculation methodology' } }, required: ['portfolioId'] }, proxyTo: { method: 'POST', path: '/api/regulatory/margin' }, costProfile: 'pure-logic', pricingCents: 1000 },
  { name: 'tomorrow.regulatory.reporting', description: 'Generate regulatory reports: EMIR/CFTC trade reporting, SFTR, MiFID II best execution, and FRTB capital charges.', inputSchema: { type: 'object', properties: { reportType: { type: 'string', enum: ['EMIR', 'CFTC', 'SFTR', 'MiFID-II', 'FRTB'], description: 'Report type' }, portfolioId: { type: 'string' }, asOfDate: { type: 'string', description: 'Report date (YYYY-MM-DD)' } }, required: ['reportType'] }, proxyTo: { method: 'POST', path: '/api/regulatory/reporting' }, costProfile: 'ai-light', pricingCents: 3000 },
  { name: 'tomorrow.structuring.optimize', description: 'AI-assisted trade structuring: optimize payoff profile, minimize margin/capital, suggest hedging overlays.', inputSchema: { type: 'object', properties: { objective: { type: 'string', description: 'What the client wants to achieve' }, constraints: { type: 'object', description: 'Budget, risk limits, regulatory constraints' }, existingPositions: { type: 'array', description: 'Current portfolio for basis/netting optimization' } }, required: ['objective'] }, proxyTo: { method: 'POST', path: '/api/structuring/optimize' }, costProfile: 'ai-heavy', pricingCents: 10000 },
  { name: 'tomorrow.market.curves', description: 'Fetch and interpolate live market curves: yield curves, vol surfaces, credit spreads, basis curves.', inputSchema: { type: 'object', properties: { curveType: { type: 'string', enum: ['yield', 'vol-surface', 'credit-spread', 'basis', 'fx-forward'], description: 'Curve type' }, currency: { type: 'string', description: 'Currency (USD, EUR, etc.)' }, asOfDate: { type: 'string', description: 'Valuation date' } }, required: ['curveType'] }, proxyTo: { method: 'GET', path: '/api/market/curves' }, costProfile: 'external-api', pricingCents: 500 },
  { name: 'tomorrow.market.intel', description: 'AI market intelligence: flow analysis, dealer positioning, upcoming events impact, and trade idea generation.', inputSchema: { type: 'object', properties: { assetClass: { type: 'string', enum: ['rates', 'fx', 'credit', 'equity', 'commodity'], description: 'Asset class focus' }, query: { type: 'string', description: 'Specific market question or topic' } }, required: ['assetClass'] }, proxyTo: { method: 'POST', path: '/api/market/intel' }, costProfile: 'ai-heavy', pricingCents: 5000 },
  { name: 'tomorrow.lifecycle.events', description: 'Query upcoming lifecycle events: fixings, resets, expirations, exercises, margin calls, and settlement dates.', inputSchema: { type: 'object', properties: { portfolioId: { type: 'string' }, dateRange: { type: 'string', description: 'Date range (e.g., 7D, 30D, 90D)' }, eventTypes: { type: 'array', items: { type: 'string' }, description: 'Filter by event type' } }, required: ['portfolioId'] }, proxyTo: { method: 'GET', path: '/api/lifecycle/events' }, costProfile: 'pure-logic', pricingCents: 200 },
];
