#!/usr/bin/env bash
# GENERATED by scripts/reconcile-evidence.mjs --preserve-plan. Do not hand-edit.
#
# Pushes every local-only branch tip to a PRESERVED ref on origin so it survives
# this machine. `refs/preserved/*` is not `refs/heads/*`, so none of these become
# branches: the merge train, CI and Vercel enumerate branches and will not see them.
#
#   ./preserve-local-only.sh            # dry run, prints what it would push
#   APPLY=1 ./preserve-local-only.sh    # actually pushes
#
# Idempotent: re-running pushes the same sha to the same ref, which is a no-op.
set -euo pipefail

APPLY="${APPLY:-0}"
REMOTE="${REMOTE:-origin}"

push() {
  local sha="$1" ref="$2"
  if [ "$APPLY" = "1" ]; then
    git push "$REMOTE" "$sha:$ref"
  else
    echo "would push $sha -> $ref"
  fi
}

# 18 tip(s) with no remote copy.
push fcef8e0665f9b7d79cc9f4e72734dc169e24badd refs/preserved/_rb   # 2 unique commit(s)
push e48843cde658ce584e75dcaeff31fa87bfd4f05b refs/preserved/agent/chatgpt-local-reconcile-beethoven-215fba971ab9   # 4 unique commit(s)
push 37a6932a8bf6b9182517d8e8405f8521fc8e5fc7 refs/preserved/agent/copyfix-beethoven-07180848-slice-3-public-landing-founder-navigation-copy-clean-140991   # 1 unique commit(s)
push 0a175f15699b96e2d4cf27d3499dc74b83c97ec8 refs/preserved/agent/dropbox-beethoven-fleet-immune-system-throughput-accelerators-operat-3-speed-triage-routing-accelerators-p0   # 14 unique commit(s)
push 358297faa18ff03172ac9f7240ce981e825e13bb refs/preserved/agent/dropbox-hisanta-mastery-engine-grandma-rail-family-slice-2-clean-129448   # 1 unique commit(s)
push 8aedeab59d0995649b4d1e1fef1ae7be82322071 refs/preserved/agent/dropbox-mission-complete-merge-and-deploy-the-full-backlog-to-vercel-bulk-integrate-shelf   # 25 unique commit(s)
push 574f409a15bde6497d1c8a24432be3a12e7df6d1 refs/preserved/agent/dropbox-mission-complete-merge-and-deploy-the-full-backlog-to-vercel-governor-ram-floor   # 26 unique commit(s)
push 2fdf1dc3567fc32714b23a489e320df76a34fb91 refs/preserved/agent/dropbox-mission-complete-merge-and-deploy-the-full-backlog-to-vercel-keepalive-single-supervisor   # 24 unique commit(s)
push e1e3a7a2235b55fa3ea2bdd1b5147259316e1a06 refs/preserved/agent/dropbox-recover-the-lease-night-stash-work-branch-hotfix-stash-rescu-group-2   # 11 unique commit(s)
push ae4f5f7d64f7653921c3f195f0f15310f6046ffe refs/preserved/agent/dropbox-recover-the-lease-night-stash-work-branch-hotfix-stash-rescu-group-4   # 16 unique commit(s)
push fbec1e7cd20bbccf7d7cf303720086a188b97f82 refs/preserved/agent/dropbox-recover-the-lease-night-stash-work-branch-hotfix-stash-rescu-group-5   # 15 unique commit(s)
push 41283e21fa6b81a6b3966f24d1a37accd010c3aa refs/preserved/agent/improve-missing-branch-auto-creator-slice-3-adapt-auto-branch-patch-r2   # 1 unique commit(s)
push dc65c5428c7ca2d3de8d2cf017ced6fa513e438c refs/preserved/agent/improve-missing-branch-auto-creator-slice-3-locate-decomposition-event-handler-a-clean-152441   # 1 unique commit(s)
push a9e98fc3c705ebcb705617f1111c1396230ef915 refs/preserved/agent/improve-value-aware-test-routing-early-exit-r-slice-3-fix-broken-tests-clean-151469   # 1 unique commit(s)
push 0abf5b6d4c52bfc741172e9aae160743cc5bc2e3 refs/preserved/backlog-batch-illuminati-1d1b027   # 3 unique commit(s)
push 6d77311f95e2fe2172425395372f54eaecfbf932 refs/preserved/fix-release-train-manifest-import-20260807   # 1 unique commit(s)
push 609c9b2afa584795f60c624f163f042a4116ce1b refs/preserved/verify/cowork-batch1   # 12 unique commit(s)
push f1aeea3f2bde8e845520d5d9ad48b89611d63868 refs/preserved/verify/solo3   # 3 unique commit(s)

echo "18 tip(s) handled. Nothing was deleted, reset or moved."
