<script setup lang="ts">
definePageMeta({layout:'default'})
const supabase=useSupabaseClient<any>(),data=ref<any>(),loading=ref(true),busy=ref(false),error=ref(''),message=ref(''),selectedContract=ref(''),mode=ref('exception_only'),domain=ref('all')
const domains=['all','workforce','finance','tax','security','procurement','crm','renewal','payment','legal']
const actions=computed(()=>(data.value?.actions||[]).filter((x:any)=>domain.value==='all'||x.domain===domain.value))
const selected=computed(()=>data.value?.contracts?.find((x:any)=>x.id===selectedContract.value))
const tone=(state:string)=>['completed','ready','active'].includes(state)?'bg-emerald-50 text-emerald-700':['approval_required','planned','draft'].includes(state)?'bg-amber-50 text-amber-700':['blocked','failed'].includes(state)?'bg-red-50 text-red-700':'bg-gray-100 text-gray-600'
const label=(value:string)=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())
async function authed<T>(url:string,options:any={}){const{data:{session}}=await supabase.auth.getSession();return $fetch<T>(url,{...options,headers:{...(options.headers||{}),...(session?.access_token?{authorization:`Bearer ${session.access_token}`}:{})}})}
async function load(){loading.value=true;error.value='';try{data.value=await authed('/api/business/autonomy');if(!selectedContract.value)selectedContract.value=data.value.contracts.find((x:any)=>['signed','active'].includes(x.lifecycle))?.id||data.value.contracts[0]?.id||''}catch(e:any){error.value=e?.data?.message||e?.message||'Autonomous operations could not load.'}finally{loading.value=false}}
async function act(action:string,values:any={}){busy.value=true;error.value='';message.value='';try{const result:any=await authed('/api/business/autonomy/action',{method:'POST',body:{action,values}});message.value=action==='compile_operations'?`${result.compiled.summary.total} operations compiled across ${result.compiled.summary.domains.length} control domains. External effects remain authority-gated.`:`${label(action)} completed with evidence.`;await load();return result}catch(e:any){error.value=e?.data?.message||e?.message||'The action could not be completed.'}finally{busy.value=false}}
async function compile(){await act('compile_operations',{contract_id:selectedContract.value,mode:mode.value})}
onMounted(load)
</script>
<template><main class="min-h-full bg-[#f7f8f5] text-[#171817]">
 <header class="border-b bg-[radial-gradient(circle_at_82%_14%,#dbeafe,transparent_28%),radial-gradient(circle_at_65%_70%,#ede9fe,transparent_25%),linear-gradient(145deg,#fff,#eef1ea)]"><div class="mx-auto max-w-[1320px] px-6 py-12"><div class="flex items-center justify-between"><NuxtLink to="/business" class="text-[10px] text-gray-500">← Business OS</NuxtLink><span class="rounded-full border bg-white/70 px-3 py-1 text-[9px] text-indigo-700">Contract → operations compiler v1</span></div><div class="mt-8 grid gap-8 lg:grid-cols-[1fr_380px]"><div><span class="text-[10px] font-bold uppercase tracking-[.16em] text-indigo-700">Autonomous business fabric</span><h1 class="mt-3 text-5xl font-semibold tracking-[-.055em] md:text-7xl">The agreement becomes<br><em class="not-italic text-gray-500">the operating system.</em></h1><p class="mt-5 max-w-3xl text-sm leading-7 text-gray-600">Signed clauses compile into idempotent workforce, finance, tax, security, procurement, CRM, renewal, payment, and legal action graphs. Madeus completes reversible internal work and surfaces only true authority exceptions.</p></div><aside class="rounded-2xl border bg-gray-950 p-5 text-white"><span class="text-[9px] uppercase tracking-wider text-indigo-300">Department-light, control-rich</span><h2 class="mt-2 text-xl font-semibold">Autonomy without silent authority.</h2><p class="mt-2 text-[10px] leading-5 text-gray-400">Payments, filings, signatures, termination, compensation, bank changes, notices, and privileged access cannot cross the boundary without the authorized accountable role.</p><div class="mt-4 grid grid-cols-2 gap-2 text-[9px]"><span class="rounded-lg bg-gray-900 p-2">✓ Idempotent</span><span class="rounded-lg bg-gray-900 p-2">✓ Matter-scoped</span><span class="rounded-lg bg-gray-900 p-2">✓ Proof-carrying</span><span class="rounded-lg bg-gray-900 p-2">✓ Exception-only</span></div></aside></div></div></header>
 <div class="mx-auto max-w-[1320px] space-y-8 px-6 py-8"><p v-if="error" role="alert" class="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{{error}}</p><p v-if="message" role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-700">{{message}}</p>
 <section v-if="data" class="grid overflow-hidden rounded-2xl border bg-white sm:grid-cols-2 lg:grid-cols-5"><article v-for="x in [{l:'Workflows',v:data.summary.workflows},{l:'Safe actions ready',v:data.summary.ready},{l:'Authority exceptions',v:data.summary.exceptions},{l:'Completed',v:data.summary.completed},{l:'External effects gated',v:data.summary.external_gated}]" :key="x.l" class="border-b p-5 sm:border-r lg:border-b-0"><span class="text-[8px] uppercase tracking-wider text-gray-400">{{x.l}}</span><b class="mt-2 block text-3xl">{{x.v}}</b></article></section>
 <section class="grid gap-5 lg:grid-cols-[420px_minmax(0,1fr)]"><aside class="space-y-4"><form class="rounded-2xl border bg-white p-5" @submit.prevent="compile"><span class="text-[9px] font-bold uppercase tracking-wider text-indigo-700">Compile signed intent</span><h2 class="mt-2 text-2xl font-semibold">Contract → executable graph</h2><p class="mt-2 text-[10px] leading-5 text-gray-500">Compilation is deterministic and repeat-safe. A new contract version produces a new graph; re-running the same version does not duplicate actions.</p><label class="mt-5 block text-[9px] font-semibold">Agreement<select v-model="selectedContract" required class="mt-1 w-full rounded-lg border p-2 text-xs"><option value="">Choose a contract</option><option v-for="c in data?.contracts||[]" :key="c.id" :value="c.id">{{c.title}} · v{{c.current_version}} · {{label(c.lifecycle)}}</option></select></label><label class="mt-3 block text-[9px] font-semibold">Autonomy posture<select v-model="mode" class="mt-1 w-full rounded-lg border p-2 text-xs"><option value="observe">Observe only</option><option value="prepare">Prepare all work</option><option value="execute_reversible">Execute reversible internal work</option><option value="exception_only">Exception-only operations</option></select></label><div v-if="selected" class="mt-3 rounded-xl bg-gray-50 p-3 text-[9px] leading-4 text-gray-600"><b>{{selected.counterparty_name||'No counterparty recorded'}}</b><br>{{selected.jurisdiction}} · {{label(selected.lifecycle)}}<p v-if="!['signed','active'].includes(selected.lifecycle)" class="mt-2 text-amber-700">Operational execution requires a signed or active contract. Use the negotiation twin before signature.</p></div><button :disabled="busy||!selectedContract||!['signed','active'].includes(selected?.lifecycle)" class="mt-4 w-full rounded-lg bg-gray-950 px-4 py-3 text-[10px] font-semibold text-white disabled:opacity-40">{{busy?'Compiling…':'Compile and activate controls'}}</button><div class="mt-2 grid grid-cols-3 gap-2"><button type="button" :disabled="busy||!selectedContract" class="rounded-lg border p-2 text-[8px]" @click="act('simulate_negotiation',{contract_id:selectedContract})">Run twin</button><button type="button" :disabled="busy||!selectedContract" class="rounded-lg border p-2 text-[8px]" @click="act('check_conflicts',{contract_id:selectedContract})">Conflicts</button><button type="button" :disabled="busy||!selectedContract" class="rounded-lg border p-2 text-[8px]" @click="act('learn_clause_genome',{contract_id:selectedContract})">Learn pattern</button></div></form>
 <section class="rounded-2xl border bg-indigo-950 p-5 text-white"><span class="text-[9px] uppercase text-indigo-300">Information barrier</span><h3 class="mt-2 font-semibold">Minimum necessary disclosure</h3><p class="mt-2 text-[9px] leading-4 text-indigo-200/70">Operations receive structured obligations, dates, amounts, and controls—not the privileged matter. Clause learning is tenant-scoped and exports structural features, never raw text.</p></section></aside>
 <article class="overflow-hidden rounded-2xl border bg-white"><header class="flex flex-col gap-4 border-b p-5 sm:flex-row sm:items-end sm:justify-between"><div><span class="text-[9px] font-bold uppercase tracking-wider text-indigo-700">Operating action graph</span><h2 class="mt-1 text-2xl font-semibold">Only exceptions need a person.</h2></div><select v-model="domain" class="rounded-lg border px-3 py-2 text-[9px]"><option v-for="x in domains" :key="x" :value="x">{{label(x)}}</option></select></header><div v-if="loading" class="p-16 text-center text-xs text-gray-400">Loading the control plane…</div><div v-else-if="!actions.length" class="p-16 text-center text-xs text-gray-400">Compile a signed agreement to create its operating graph.</div><div v-else class="divide-y"><section v-for="item in actions" :key="item.id" class="grid gap-3 p-4 md:grid-cols-[36px_1fr_auto]"><i class="grid h-9 w-9 place-items-center rounded-lg bg-indigo-50 text-[10px] not-italic text-indigo-700">{{item.domain.slice(0,2).toUpperCase()}}</i><div><div class="flex flex-wrap items-center gap-2"><b class="text-[11px]">{{item.title}}</b><span class="rounded-full px-2 py-1 text-[8px]" :class="tone(item.status)">{{label(item.status)}}</span><span v-if="item.external_effect" class="rounded-full bg-red-50 px-2 py-1 text-[8px] text-red-700">external effect</span></div><p class="mt-1 text-[9px] text-gray-500">{{label(item.domain)}} · {{label(item.action_type)}} · {{item.owner_role}}</p><span class="mt-2 block font-mono text-[7px] text-gray-300">{{item.idempotency_key.slice(0,22)}}…</span></div><button v-if="item.status==='ready'&&!item.external_effect" :disabled="busy" class="self-center rounded-lg border px-3 py-2 text-[8px]" @click="act('execute_safe_action',{action_id:item.id})">Execute safely</button><span v-else class="self-center text-[8px] text-gray-400">{{item.status==='approval_required'?'Await authority':'Tracked automatically'}}</span></section></div></article></section>
 <section class="grid gap-4 md:grid-cols-3"><article class="rounded-2xl border bg-white p-5"><span class="text-[9px] uppercase text-gray-400">Negotiation twin</span><h3 class="mt-2 font-semibold">Simulate downstream cost before agreeing.</h3><p class="mt-2 text-[9px] leading-4 text-gray-500">Compares action count, exceptions, missing facts, early termination, and counterparty-favorable scenarios.</p><b class="mt-4 block text-2xl">{{data?.twins?.length||0}}</b></article><article class="rounded-2xl border bg-white p-5"><span class="text-[9px] uppercase text-gray-400">Portfolio conflict graph</span><h3 class="mt-2 font-semibold">Identity, authority, law, and collision checks.</h3><p class="mt-2 text-[9px] leading-4 text-gray-500">Normalized entities and signer authority checks run without pooling privileged contract text.</p><b class="mt-4 block text-2xl">{{data?.conflicts?.length||0}}</b></article><article class="rounded-2xl border bg-white p-5"><span class="text-[9px] uppercase text-gray-400">Execution finality</span><h3 class="mt-2 font-semibold">One proof set for every binding event.</h3><p class="mt-2 text-[9px] leading-4 text-gray-500">Identity, authority, signature, delivery, timestamp, archive, payment, and filing receipts share content digests.</p><b class="mt-4 block text-2xl">{{data?.finality?.filter((x:any)=>x.status==='verified').length||0}}</b></article></section>
 </div></main></template>
