<script setup lang="ts">
definePageMeta({layout:'default'})
const supabase=useSupabaseClient<any>(),data=ref<any>(),loading=ref(true),busy=ref(false),error=ref(''),message=ref(''),search=ref(''),category=ref('all'),drafting=ref<any>(),matter=ref<any>()
const form=reactive({title:'',prompt:'Draft a balanced, operationally clear agreement. Surface missing terms and avoid invented facts.',facts:{} as Record<string,any>})
const redline=reactive({clause_id:'',proposed_text:'',rationale:''}),issue=reactive({recipient:'',signature_requested:true}),policy=reactive({jurisdiction:'',domains:['commercial']})
const categories=['all','employment','commercial','corporate','privacy','finance','ip']
const templates=computed(()=>(data.value?.templates||[]).filter((x:any)=>(category.value==='all'||x.category===category.value)&&(!search.value||`${x.name} ${x.summary}`.toLowerCase().includes(search.value.toLowerCase()))))
const currentVersion=computed(()=>matter.value?.legal_contract_versions?.find((x:any)=>x.version===matter.value.current_version))
const reviews=computed(()=>matter.value?.legal_contract_reviews?.filter((x:any)=>x.version===matter.value.current_version)||[])
const tone=(state:string)=>['signed','active','approved','clear','synced'].includes(state)?'bg-emerald-50 text-emerald-700':['blocked','failed','attention','cancelled'].includes(state)?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700'
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())
async function authed<T>(url:string,options:any={}){const{data:{session}}=await supabase.auth.getSession();return $fetch<T>(url,{...options,headers:{...(options.headers||{}),...(session?.access_token?{authorization:`Bearer ${session.access_token}`}:{})}})}
async function load(){loading.value=true;error.value='';try{data.value=await authed('/api/legal');if(matter.value)matter.value=data.value.contracts.find((x:any)=>x.id===matter.value.id)||matter.value}catch(e:any){error.value=e?.data?.message||e?.message||'Legal workspace could not load.'}finally{loading.value=false}}
function start(template:any){drafting.value=template;form.title='';form.facts={};for(const field of template.fields)form.facts[field]='';message.value='';error.value=''}
async function act(action:string,values:any={}){busy.value=true;error.value='';message.value='';try{const result:any=await authed('/api/legal/action',{method:'POST',body:{action,values}});message.value=action==='create_draft'?'Draft created with a version-pinned policy snapshot. Run CADE + Hivemind review next.':action==='issue'?(result.delivery?.ok?'Issued through Smarter with delivery evidence.':'Issuance blocked safely; configure or repair the Smarter bridge.'):`${label(action)} completed and receipted.`;if(action==='create_draft'){drafting.value=undefined;matter.value=result.contract}if(action==='redline'){redline.proposed_text='';redline.rationale=''}await load();return result}catch(e:any){error.value=e?.data?.message||e?.message||'Action could not be completed.'}finally{busy.value=false}}
async function createDraft(){await act('create_draft',{template_key:drafting.value.key,title:form.title,prompt:form.prompt,facts:{...form.facts}})}
async function compilePolicy(){await act('compile_policy',{jurisdiction:policy.jurisdiction,domains:policy.domains})}
onMounted(load)
</script>

<template><main class="min-h-full bg-[#fafbf9] text-[#171817]">
  <header class="border-b bg-[radial-gradient(circle_at_80%_10%,#ede9fe,transparent_30%),linear-gradient(145deg,#fff,#f4f5f1)]">
    <div class="mx-auto max-w-[1280px] px-6 py-12">
      <div class="flex items-center justify-between"><NuxtLink to="/business" class="text-[10px] text-gray-500">← Business OS</NuxtLink><NuxtLink to="/business/autonomy" class="rounded-full border bg-white/70 px-3 py-1.5 text-[9px] text-indigo-700">Contract → operations</NuxtLink></div>
      <div class="mt-7 grid gap-8 lg:grid-cols-[1fr_340px]"><div><span class="text-[10px] font-bold uppercase tracking-[.16em] text-indigo-700">CADE Legal · Hivemind review · Smarter delivery</span><h1 class="mt-3 text-5xl font-semibold tracking-[-.05em] md:text-7xl">Contracts at operating speed.<br><em class="not-italic text-gray-500">Evidence at legal depth.</em></h1><p class="mt-5 max-w-3xl text-sm leading-7 text-gray-600">Find the right agreement, fill it with natural-language business terms, pin the applicable policy snapshot, negotiate exact versions, and issue only the document that was approved.</p></div>
      <aside class="rounded-2xl border bg-white/80 p-5"><span class="text-[9px] uppercase text-gray-400">Safety contract</span><b class="mt-2 block">Fast drafting is not legal certainty.</b><p class="mt-2 text-[10px] leading-5 text-gray-500">Madeus exposes missing authority coverage, unresolved terms, and required professional review. It never represents generated material as “bulletproof.”</p><div class="mt-4 flex items-center gap-2 text-[9px]"><i class="h-2 w-2 rounded-full" :class="data?.smarter?.configured?'bg-emerald-500':'bg-amber-500'"/><span>Smarter {{data?.smarter?.configured?'delivery connected':'bridge needs configuration'}}</span></div></aside></div>
    </div>
  </header>
  <div class="mx-auto max-w-[1280px] space-y-10 px-6 py-8">
    <p v-if="error" role="alert" class="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">{{error}}</p><p v-if="message" role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-700">{{message}}</p>
    <section v-if="data" class="grid overflow-hidden rounded-2xl border bg-white sm:grid-cols-2 lg:grid-cols-4"><article v-for="x in [{l:'Matters',v:data.summary.matters},{l:'Negotiating',v:data.summary.negotiating},{l:'Needs review',v:data.summary.needs_review},{l:'Due in 30 days',v:data.summary.obligations_due}]" :key="x.l" class="border-b p-5 sm:border-r lg:border-b-0"><span class="text-[9px] uppercase text-gray-400">{{x.l}}</span><b class="mt-2 block text-3xl">{{x.v}}</b></article></section>
    <section class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><div class="rounded-2xl border bg-white p-5"><header class="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><span class="text-[10px] font-bold uppercase tracking-[.14em] text-indigo-700">Agreement library</span><h2 class="mt-1 text-2xl font-semibold">Start from the business outcome</h2></div><input v-model="search" class="rounded-lg border px-3 py-2 text-xs" placeholder="Search 20 agreement types"></header><div class="mt-4 flex gap-2 overflow-x-auto pb-2"><button v-for="x in categories" :key="x" class="rounded-full border px-3 py-1.5 text-[9px]" :class="category===x?'bg-gray-950 text-white':''" @click="category=x">{{label(x)}}</button></div><div v-if="loading" class="p-12 text-center text-xs text-gray-400">Loading contract intelligence…</div><div v-else class="mt-3 grid gap-3 md:grid-cols-2"><article v-for="template in templates" :key="template.key" class="flex min-h-48 flex-col rounded-xl border p-4"><div class="flex justify-between"><span class="text-[8px] uppercase text-indigo-700">{{template.category}}</span><span class="rounded-full bg-amber-50 px-2 py-1 text-[8px] text-amber-700">{{template.risk}} risk</span></div><h3 class="mt-4 text-base font-semibold">{{template.name}}</h3><p class="mt-1 text-[10px] leading-4 text-gray-500">{{template.summary}}</p><button class="mt-auto rounded-lg bg-gray-950 px-3 py-2 text-[10px] text-white" @click="start(template)">Draft from prompt →</button></article></div></div>
    <aside class="space-y-4"><section class="rounded-2xl border bg-gray-950 p-5 text-white"><span class="text-[9px] uppercase tracking-wider text-indigo-300">Effective-date compiler</span><h2 class="mt-2 text-xl font-semibold">Compile before relying.</h2><p class="mt-2 text-[10px] leading-4 text-gray-400">Creates an immutable jurisdiction, domain, authority, effective-date, coverage, and review-routing snapshot.</p><input v-model="policy.jurisdiction" class="mt-4 w-full rounded-lg border border-gray-700 bg-gray-900 p-2 text-xs" placeholder="Jurisdiction"><select v-model="policy.domains[0]" class="mt-2 w-full rounded-lg border border-gray-700 bg-gray-900 p-2 text-xs"><option>commercial</option><option>employment</option><option>privacy</option><option>tax</option><option>corporate</option></select><button :disabled="busy||!policy.jurisdiction" class="mt-3 w-full rounded-lg bg-white px-3 py-2 text-[10px] text-gray-950 disabled:opacity-40" @click="compilePolicy">Compile policy snapshot</button></section>
    <section class="rounded-2xl border bg-white p-5"><span class="text-[9px] uppercase text-gray-400">Open matters</span><div v-if="!data?.contracts?.length" class="py-8 text-center text-[10px] text-gray-400">No matters yet</div><button v-for="item in data?.contracts||[]" :key="item.id" class="mt-2 w-full rounded-lg border p-3 text-left" :class="matter?.id===item.id?'border-indigo-400 bg-indigo-50':''" @click="matter=item"><b class="block text-[10px]">{{item.title}}</b><span class="mt-1 flex justify-between text-[8px] text-gray-500"><em class="not-italic">v{{item.current_version}} · {{item.jurisdiction}}</em><i class="rounded-full px-2 not-italic" :class="tone(item.lifecycle)">{{label(item.lifecycle)}}</i></span></button></section></aside></section>
    <section v-if="matter" class="overflow-hidden rounded-2xl border bg-white"><header class="flex flex-col justify-between gap-4 border-b p-5 md:flex-row md:items-center"><div><span class="text-[9px] uppercase text-indigo-700">{{matter.category}} · {{matter.jurisdiction}} · v{{matter.current_version}}</span><h2 class="mt-1 text-2xl font-semibold">{{matter.title}}</h2><p class="mt-1 text-[9px] text-gray-500">Policy {{matter.policy_snapshot_id?.slice(0,8)}} · {{matter.professional_review_required?'Professional review required':'Standard review route'}}</p></div><div class="flex flex-wrap gap-2"><button :disabled="busy" class="rounded-lg border px-3 py-2 text-[9px]" @click="act('review',{contract_id:matter.id})">Run CADE + Hivemind</button><button :disabled="busy" class="rounded-lg border px-3 py-2 text-[9px]" @click="act('sync_smarter',{contract_id:matter.id})">Sync Smarter</button><button :disabled="busy" class="rounded-lg bg-gray-950 px-3 py-2 text-[9px] text-white" @click="act('request_approval',{contract_id:matter.id})">Request approval</button></div></header>
      <div class="grid lg:grid-cols-[minmax(0,1fr)_380px]"><article class="border-b p-6 lg:border-b-0 lg:border-r"><div class="flex justify-between"><h3 class="text-xs font-semibold">Current document</h3><span class="text-[8px] text-gray-400">Digest {{currentVersion?.content_digest?.slice(0,12)}}…</span></div><pre class="mt-4 max-h-[640px] whitespace-pre-wrap font-sans text-[11px] leading-6 text-gray-700">{{currentVersion?.rendered_text}}</pre></article><aside class="space-y-5 p-5"><section><h3 class="text-xs font-semibold">Review panel</h3><div v-if="!reviews.length" class="mt-2 rounded-lg bg-gray-50 p-3 text-[9px] text-gray-500">Run the panel on this exact version.</div><article v-for="review in reviews" :key="review.id" class="mt-2 rounded-lg border p-3"><div class="flex justify-between text-[9px]"><b>{{label(review.reviewer_type)}}</b><span :class="tone(review.status)">{{label(review.status)}} · {{Math.round(review.score*100)}}%</span></div><p class="mt-2 text-[8px] text-gray-500">{{review.findings?.length||0}} findings</p></article></section>
      <section><h3 class="text-xs font-semibold">Create exact redline</h3><select v-model="redline.clause_id" class="mt-2 w-full rounded-lg border p-2 text-[10px]"><option value="">Choose clause</option><option v-for="clause in currentVersion?.content?.clauses||[]" :key="clause.id" :value="clause.id">{{clause.heading}}</option></select><textarea v-model="redline.proposed_text" rows="5" class="mt-2 w-full rounded-lg border p-2 text-[10px]" placeholder="Replacement clause text"/><input v-model="redline.rationale" class="mt-2 w-full rounded-lg border p-2 text-[10px]" placeholder="Negotiation rationale"><button :disabled="busy||!redline.clause_id||!redline.proposed_text" class="mt-2 w-full rounded-lg border px-3 py-2 text-[9px] disabled:opacity-40" @click="act('redline',{contract_id:matter.id,operations:[{clause_id:redline.clause_id,proposed_text:redline.proposed_text}],rationale:redline.rationale})">Create new version</button></section>
      <section class="rounded-xl bg-amber-50 p-4"><h3 class="text-xs font-semibold text-amber-900">Issue approved version</h3><input v-model="issue.recipient" type="email" class="mt-2 w-full rounded-lg border border-amber-200 p-2 text-[10px]" :placeholder="matter.counterparty_email||'Recipient email'"><label class="mt-2 flex gap-2 text-[9px] text-amber-900"><input v-model="issue.signature_requested" type="checkbox">Request signature through Smarter</label><button :disabled="busy||!['approved','issue_ready'].includes(matter.lifecycle)" class="mt-3 w-full rounded-lg bg-amber-900 px-3 py-2 text-[9px] text-white disabled:opacity-40" @click="act('issue',{contract_id:matter.id,...issue})">Issue exact approved version</button><p class="mt-2 text-[8px] text-amber-800">Disabled until the approval card is complete. Approval is not delivery or signature.</p></section></aside></div>
    </section>
  </div>
  <Teleport to="body"><div v-if="drafting" class="fixed inset-0 z-[200] grid place-items-center overflow-y-auto bg-gray-950/70 p-4" @mousedown.self="!busy&&(drafting=undefined)"><form class="max-h-[94vh] w-full max-w-3xl overflow-auto rounded-2xl bg-white" @submit.prevent="createDraft"><header class="flex justify-between border-b p-5"><div><span class="text-[9px] uppercase text-indigo-700">{{drafting.category}} · prompted drafting</span><h2 class="mt-1 text-2xl font-semibold">{{drafting.name}}</h2><p class="mt-1 text-[10px] text-gray-500">{{drafting.summary}}</p></div><button type="button" class="text-2xl text-gray-400" @click="drafting=undefined">×</button></header><div class="grid gap-3 p-5 sm:grid-cols-2"><label class="sm:col-span-2 text-[9px] font-semibold">Matter title<input v-model="form.title" class="mt-1 w-full rounded-lg border p-2 text-xs" :placeholder="drafting.name"></label><label v-for="field in drafting.fields" :key="field" class="text-[9px] font-semibold">{{label(field)}}<textarea v-if="['services','purpose'].includes(field)" v-model="form.facts[field]" rows="2" required class="mt-1 w-full rounded-lg border p-2 text-xs"/><input v-else v-model="form.facts[field]" required class="mt-1 w-full rounded-lg border p-2 text-xs"></label><label class="sm:col-span-2 text-[9px] font-semibold">Drafting prompt<textarea v-model="form.prompt" rows="4" required class="mt-1 w-full rounded-lg border p-2 text-xs"/></label><aside class="sm:col-span-2 rounded-xl bg-indigo-50 p-3 text-[9px] leading-4 text-indigo-900">The first version is deliberately review-ready, not signature-ready. Missing facts block CADE clearance; missing verified authority coverage forces professional review.</aside></div><footer class="flex justify-end gap-2 border-t p-4"><button type="button" class="rounded-lg border px-4 py-2 text-[10px]" @click="drafting=undefined">Cancel</button><button :disabled="busy" class="rounded-lg bg-gray-950 px-4 py-2 text-[10px] text-white">{{busy?'Compiling…':'Create governed draft'}}</button></footer></form></div></Teleport>
</main></template>
