#!/usr/bin/env python3
"""
gen_env_example.py — derive `.env.example` from the environment variables the code
actually reads.

WHY. The runner is configured almost entirely through environment variables — over a
thousand `os.environ` reads across `runner/` — and there was no `.env.example` at all.
Every knob was discoverable only by grepping, and `.gitignore` matched `.env*`, so even
if someone wrote one it would not have been trackable. That is the concrete configuration
gap this task fixes; the file is GENERATED rather than hand-written because a hand-written
one drifts the moment a knob is added, and a stale config template is worse than none.

WHAT IT FINDS. Static AST analysis, so a var is only reported if it is genuinely read:
    os.environ.get("NAME")            -> optional, no default
    os.environ.get("NAME", "value")   -> optional, default recorded
    os.environ["NAME"]                -> REQUIRED (raises when unset)
    os.getenv("NAME"[, "value"])      -> same as .get

Test modules are excluded: their fixtures (`ORCH_TESTKEY`, `ORCH_BOOL`, …) are not
configuration and would drown the real knobs.

Usage:
    python3 scripts/gen_env_example.py                 # write .env.example
    python3 scripts/gen_env_example.py --check         # exit 1 if it has drifted
    python3 scripts/gen_env_example.py --stdout

`--check` is the point of generating it: run it in CI and a new knob without a template
entry becomes a failing check rather than an undocumented setting.
"""
import argparse
import ast
import collections
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_OUT = os.path.join(REPO_ROOT, ".env.example")
SCAN_DIRS = ("runner", "tools", "scripts")

#: Names that are process/OS environment, not configuration for this project.
SYSTEM_VARS = {
    "PATH", "HOME", "USER", "SHELL", "PWD", "TMPDIR", "LANG", "LC_ALL", "TERM",
    "PYTHONPATH", "VIRTUAL_ENV", "CI", "GITHUB_ACTIONS", "NODE_ENV",
}

#: Vars whose value is a credential. The template lists the NAME with an empty value and
#: a warning; it must never carry a real secret, and `.env.example` is committed.
SECRET_MARKERS = ("KEY", "TOKEN", "SECRET", "PASSWORD", "CREDENTIAL", "DSN", "PAT")

HEADER = """\
# .env.example — generated by scripts/gen_env_example.py. DO NOT EDIT BY HAND.
#
# Regenerate:  python3 scripts/gen_env_example.py
# Check drift: python3 scripts/gen_env_example.py --check
#
# Copy to .env and fill in the values you need. Every variable below is read somewhere
# under runner/, tools/ or scripts/. Variables marked REQUIRED are read with
# os.environ[...] and will raise if unset; everything else has a default and may be
# omitted. Secret-looking variables are listed with an EMPTY value on purpose — this file
# is committed, so it must never contain a real credential.
"""


def is_secret(name):
    """True when the variable name looks like it holds a credential."""
    upper = str(name or "").upper()
    return any(marker in upper for marker in SECRET_MARKERS)


def _is_constant_name(name):
    """True for UPPER_SNAKE_CASE — the convention that means "this does not change"."""
    return bool(name) and name.upper() == name and name.strip("_") != ""


def _module_constants(tree):
    """{NAME: literal node} for module-level `NAME = <literal>` constants.

    Deliberately narrow, because the cost of being wrong here is a template that
    documents a default the code does not use — worse than documenting none:

      * module scope only, single Name target, literal value;
      * UPPER_SNAKE_CASE only, so an ordinary variable (`d = "x"`) is left alone.
        A lowercase name carries no promise of staying put;
      * assigned EXACTLY ONCE anywhere in the module. A name rebound in a branch,
        a loop or a function is not resolvable by reading top-level statements, and
        a second binding this scan cannot see is exactly how it would lie.
    """
    assignment_count = collections.Counter()
    for node in ast.walk(tree):
        targets = []
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, (ast.AugAssign, ast.AnnAssign)):
            targets = [node.target]
        for target in targets:
            if isinstance(target, ast.Name):
                assignment_count[target.id] += 1

    constants = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if (isinstance(target, ast.Name) and isinstance(node.value, ast.Constant)
                and _is_constant_name(target.id)
                and assignment_count[target.id] == 1):
            constants[target.id] = node.value
    return constants


def _literal(node, constants=None):
    """Render a default-value AST node as a string, or None when it is not a literal.

    Non-literal defaults (a computed expression, a call) are deliberately reported as
    "no literal default" rather than guessed at — a template that invents a default is
    a template that lies.

    A bare module-level CONSTANT is the one exception, and it is not an exception to
    that principle: resolving TEST_GATE_TIMEOUT_DEFAULT to the 3600 assigned two
    screens up is exact, not a guess — it is the same value the code will use. The
    exception earns its keep because the codebase is actively moving defaults OUT of
    `os.environ.get(NAME, "3600")` and into named constants: convention-lint's
    MAGIC_NUMBERS rule pushes every author that way. Without this, each such
    improvement silently blanked the knob's documented default in .env.example, which
    is where an operator goes to find out what a knob does when unset. Three had
    already gone that way (TASK_TIMEOUT, ORCH_TEST_GATE_TIMEOUT,
    MERGE_TRAIN_TEST_TIMEOUT) before this was noticed.

    `str(CONSTANT)` is resolved too, because a string-typed knob whose default lives
    in an int constant is written exactly that way.
    """
    if isinstance(node, ast.Call) and len(node.args) == 1:
        func = node.func
        if isinstance(func, ast.Name) and func.id == "str":
            return _literal(node.args[0], constants)
    if isinstance(node, ast.Name) and constants and node.id in constants:
        return _literal(constants[node.id], constants)
    if isinstance(node, ast.Constant):
        if node.value is None:
            return ""
        if isinstance(node.value, bool):
            return "true" if node.value else "false"
        return str(node.value)
    return None


def scan_source(source, filename=""):
    """Return {name: {"required": bool, "defaults": set, "files": set}} for one module."""
    found = {}
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return found
    constants = _module_constants(tree)

    def record(name, required, default):
        if not name or name in SYSTEM_VARS:
            return
        entry = found.setdefault(name, {"required": False, "defaults": set(), "files": set()})
        entry["required"] = entry["required"] or required
        if default is not None:
            entry["defaults"].add(default)
        if filename:
            entry["files"].add(filename)

    for node in ast.walk(tree):
        # os.environ["NAME"] — required
        if isinstance(node, ast.Subscript):
            target = node.value
            if (isinstance(target, ast.Attribute) and target.attr == "environ"
                    and isinstance(node.slice, ast.Constant)
                    and isinstance(node.slice.value, str)):
                record(node.slice.value, True, None)
            continue

        if not isinstance(node, ast.Call) or not node.args:
            continue
        func = node.func
        name_node = node.args[0]
        if not (isinstance(name_node, ast.Constant) and isinstance(name_node.value, str)):
            continue
        default = _literal(node.args[1], constants) if len(node.args) > 1 else None

        # os.environ.get("NAME", default)
        if (isinstance(func, ast.Attribute) and func.attr == "get"
                and isinstance(func.value, ast.Attribute) and func.value.attr == "environ"):
            record(name_node.value, False, default)
        # os.getenv("NAME", default)
        elif isinstance(func, ast.Attribute) and func.attr == "getenv":
            record(name_node.value, False, default)

    return found


def _merge(into, other):
    for name, entry in other.items():
        target = into.setdefault(name, {"required": False, "defaults": set(), "files": set()})
        target["required"] = target["required"] or entry["required"]
        target["defaults"] |= entry["defaults"]
        target["files"] |= entry["files"]


def is_test_path(path):
    parts = path.replace("\\", "/").split("/")
    return any(p in ("tests", "test") for p in parts) or os.path.basename(path).startswith("test_")


def scan_repo(root=REPO_ROOT, scan_dirs=SCAN_DIRS):
    """Scan the repository. Returns the merged variable map."""
    variables = {}
    for directory in scan_dirs:
        base = os.path.join(root, directory)
        if not os.path.isdir(base):
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames
                           if d not in ("__pycache__", "node_modules", "tests", "test")]
            for filename in filenames:
                if not filename.endswith(".py"):
                    continue
                path = os.path.join(dirpath, filename)
                if is_test_path(os.path.relpath(path, root)):
                    continue
                try:
                    with open(path, encoding="utf-8", errors="replace") as handle:
                        source = handle.read()
                except OSError:
                    continue
                _merge(variables, scan_source(source, os.path.relpath(path, root)))
    return variables


def render(variables):
    """Render the template. Deterministic: same repo state, byte-identical output."""
    required = sorted(n for n, e in variables.items() if e["required"])
    optional = sorted(n for n, e in variables.items() if not e["required"])

    lines = [HEADER, ""]

    lines.append(f"# ---- REQUIRED ({len(required)}) "
                 "-- read with os.environ[...]; unset means a raise ----")
    lines.append("")
    for name in required:
        lines.extend(_render_one(name, variables[name]))
    if not required:
        lines.append("# (none)")
        lines.append("")

    lines.append(f"# ---- OPTIONAL ({len(optional)}) "
                 "-- defaults shown; omit to accept them ----")
    lines.append("")
    for name in optional:
        lines.extend(_render_one(name, variables[name]))

    return "\n".join(lines).rstrip("\n") + "\n"


def _render_one(name, entry):
    lines = []
    files = sorted(entry["files"])[:2]
    if files:
        lines.append(f"# read in: {', '.join(files)}")
    if is_secret(name):
        lines.append("# SECRET — leave empty here; set the real value in .env only")
        lines.append(f"{name}=")
    else:
        defaults = sorted(d for d in entry["defaults"] if d != "")
        if len(defaults) == 1:
            lines.append(f"{name}={defaults[0]}")
        elif len(defaults) > 1:
            # More than one default for one name is a real inconsistency worth surfacing
            # rather than silently picking a winner.
            lines.append(f"# NOTE: differing defaults in the tree: {', '.join(defaults)}")
            lines.append(f"{name}={defaults[0]}")
        else:
            lines.append(f"{name}=")
    lines.append("")
    return lines


def main(argv=None):
    parser = argparse.ArgumentParser(prog="gen_env_example")
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if the committed file has drifted from the code")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args(argv)

    content = render(scan_repo())

    if args.stdout:
        sys.stdout.write(content)
        return 0

    if args.check:
        try:
            with open(args.out, encoding="utf-8") as handle:
                current = handle.read()
        except OSError:
            print(f"gen_env_example: {args.out} is missing; run "
                  f"`python3 scripts/gen_env_example.py`")
            return 1
        if current != content:
            print(f"gen_env_example: {args.out} has DRIFTED from the code; run "
                  f"`python3 scripts/gen_env_example.py`")
            return 1
        print(f"gen_env_example: {args.out} is up to date")
        return 0

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"gen_env_example: wrote {args.out} "
          f"({content.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
