#!/usr/bin/env python3
"""
lockfile.py - Generate and verify requirements.lock against the installed set.

requirements.txt pins nothing (`python-dotenv`, `prometheus-client`) or pins a
floor (`requests>=2.28`), so two machines in the fleet resolving the same file a
week apart get different environments and nothing notices. This freezes the
resolved versions into requirements.lock and gives CI a check that fails when
the installed set drifts from the lock.

Usage:
    python3 scripts/lockfile.py generate        # write requirements.lock
    python3 scripts/lockfile.py verify          # exit 1 on drift
    python3 scripts/lockfile.py verify --quiet

Fail-soft by convention: the library functions return data/False rather than
raising; only the CLI turns a failure into a non-zero exit code.
"""
from __future__ import annotations

import argparse
import logging
import os
import re
import sys

logger = logging.getLogger(__name__)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REQUIREMENTS = os.path.join(REPO_ROOT, "requirements.txt")
LOCKFILE = os.path.join(REPO_ROOT, "requirements.lock")

HEADER = (
    "# requirements.lock - generated by scripts/lockfile.py; do not hand-edit.\n"
    "# Exact resolved versions for the direct requirements in requirements.txt\n"
    "# plus their transitive dependencies. Regenerate after any dependency\n"
    "# change:  python3 scripts/lockfile.py generate\n"
)

# Strip extras, markers, and any version specifier to get the bare project name.
_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def canonical(name: str) -> str:
    """PEP 503 normalized project name; '' for unusable input."""
    try:
        return re.sub(r"[-_.]+", "-", str(name or "").strip()).lower()
    except Exception as exc:
        logger.warning("lockfile: uncanonicalizable name %r (%s)", name, exc)
        return ""


def parse_requirements(path: str = None) -> list:
    """Return the direct requirement names declared in requirements.txt.

    Comments, blank lines, -r/-e/--flag lines and environment markers are
    skipped. Returns [] when the file is missing or unreadable.
    """
    path = path or REQUIREMENTS
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            raw = fh.read()
    except FileNotFoundError:
        logger.warning("lockfile: %s not found; treating as no direct requirements", path)
        return []
    except Exception as exc:
        logger.warning("lockfile: cannot read %s (%s); treating as empty", path, exc)
        return []

    names = []
    for line in raw.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or line.startswith("-"):
            continue
        line = line.split(";", 1)[0].strip()          # drop env markers
        match = _NAME.match(line)
        if match:
            name = canonical(match.group(1))
            if name and name not in names:
                names.append(name)
    return names


def parse_lock(path: str = None) -> dict:
    """Return {canonical_name: version} from requirements.lock; {} if absent."""
    path = path or LOCKFILE
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            raw = fh.read()
    except FileNotFoundError:
        return {}
    except Exception as exc:
        logger.warning("lockfile: cannot read %s (%s); treating as empty", path, exc)
        return {}

    pinned = {}
    for line in raw.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or "==" not in line:
            continue
        name, _, version = line.partition("==")
        name = canonical(name)
        version = version.strip()
        if name and version:
            pinned[name] = version
    return pinned


def installed_versions(names) -> dict:
    """Resolve {canonical_name: installed_version} for ``names``.

    A name that is not installed maps to None rather than raising, so callers
    can report the whole gap in one pass instead of dying on the first miss.
    """
    import importlib.metadata as md

    out = {}
    for name in names or []:
        key = canonical(name)
        if not key:
            continue
        try:
            out[key] = md.version(key)
        except Exception:
            out[key] = None
    return out


def _transitive(names) -> list:
    """Direct names plus their declared runtime dependencies, canonicalized."""
    import importlib.metadata as md

    seen = []
    queue = [canonical(n) for n in (names or []) if canonical(n)]
    while queue:
        name = queue.pop(0)
        if name in seen:
            continue
        seen.append(name)
        try:
            requires = md.requires(name) or []
        except Exception:
            continue
        for spec in requires:
            head, _, marker = spec.partition(";")
            # Optional-extra dependencies (`foo; extra == "test"`) are not part
            # of the runtime closure. Including them is what dragged the whole
            # sphinx/pytest/tox dev stack of every upstream package into the
            # lock as "not installed".
            if "extra" in marker and "==" in marker:
                continue
            spec = head.strip()
            if not spec:
                continue
            match = _NAME.match(spec)
            if not match:
                continue
            dep = canonical(match.group(1))
            if dep and dep not in seen:
                queue.append(dep)
    return sorted(seen)


def render(pinned: dict) -> str:
    """Render a lock file body from {name: version}, sorted for a stable diff."""
    lines = [HEADER]
    for name in sorted(pinned):
        version = pinned[name]
        if version:
            lines.append(f"{name}=={version}\n")
    return "".join(lines)


def generate(requirements_path: str = None, lock_path: str = None) -> dict:
    """Write requirements.lock from the currently installed set.

    Returns the {name: version} mapping that was written ({} on failure).
    """
    lock_path = lock_path or LOCKFILE
    direct = parse_requirements(requirements_path)
    resolved = installed_versions(_transitive(direct))
    pinned = {k: v for k, v in resolved.items() if v}
    missing = sorted(k for k, v in resolved.items() if not v)
    if missing:
        logger.warning("lockfile: not installed, omitted from lock: %s", ", ".join(missing))
    try:
        with open(lock_path, "w", encoding="utf-8") as fh:
            fh.write(render(pinned))
    except Exception as exc:
        logger.warning("lockfile: cannot write %s (%s)", lock_path, exc)
        return {}
    return pinned


def verify(requirements_path: str = None, lock_path: str = None) -> tuple:
    """Check the lock against requirements.txt and the installed set.

    Returns ``(ok, problems)``. ``problems`` is a list of human-readable
    strings; ``ok`` is True only when it is empty.
    """
    direct = parse_requirements(requirements_path)
    locked = parse_lock(lock_path)
    problems = []

    if not locked:
        problems.append("requirements.lock is missing or empty; run: "
                        "python3 scripts/lockfile.py generate")
        return False, problems

    for name in direct:
        if name not in locked:
            problems.append(f"{name}: declared in requirements.txt but not pinned in the lock")

    for name, version in sorted(locked.items()):
        actual = installed_versions([name]).get(name)
        if actual is None:
            problems.append(f"{name}: pinned at {version} but not installed")
        elif actual != version:
            problems.append(f"{name}: lock pins {version} but {actual} is installed")

    return (not problems), problems


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("command", choices=["generate", "verify"])
    parser.add_argument("--requirements", default=None)
    parser.add_argument("--lock", default=None)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.WARNING, format="%(message)s")

    if args.command == "generate":
        pinned = generate(args.requirements, args.lock)
        if not pinned:
            print("lockfile: nothing pinned", file=sys.stderr)
            return 1
        if not args.quiet:
            print(f"lockfile: pinned {len(pinned)} package(s) -> {args.lock or LOCKFILE}")
        return 0

    ok, problems = verify(args.requirements, args.lock)
    if ok:
        if not args.quiet:
            print("lockfile: installed set matches requirements.lock")
        return 0
    for problem in problems:
        print(f"lockfile: {problem}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
