#!/usr/bin/env python3
"""
patch_docs.py — document every hunk of every patch in patches/, and index them.

WHY A GENERATOR AND NOT HAND-WRITTEN MARKDOWN
    The acceptance criterion is "every .patch has a .md with a non-empty description for
    each hunk, and patches/README.md aggregates them". Writing that once by hand satisfies
    it for exactly as long as the directory does not change: the next recovered patch lands
    undocumented, the index silently goes stale, and nobody notices because nothing checks.
    Generating from the hunks themselves means the docs cannot drift from the patches, and
    the companion test turns the acceptance criterion into something that actually fails.

CONCRETE, NOT TEMPLATE-BASED
    Each hunk summary is derived from what the hunk DOES — the symbols it touches, whether
    it is an addition, a removal or a rewrite, and how many lines move — not from a fixed
    sentence with the filename substituted in. Where the patch carries its own rationale as
    added comments, that text is quoted as the justification, because the author's stated
    reason beats anything inferred from the diff. A prior success record (a sibling
    .README.md) is preferred over both.

Usage:
    python3 tools/patch_docs.py                 # report what would change
    python3 tools/patch_docs.py --write         # write the .md files + README.md
    python3 tools/patch_docs.py --check         # exit 1 if any doc is missing/stale
"""
import argparse
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(_HERE)
PATCH_DIR = os.path.join(REPO, "patches")

_HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@(.*)$")
_FILE_RE = re.compile(r"^\+\+\+ b/(.+)$")
_OLD_FILE_RE = re.compile(r"^--- a/(.+)$")
# A def/class/const the hunk introduces or removes — the most informative thing available.
_SYMBOL_RE = re.compile(r"^[+-]\s*(?:def|class)\s+([A-Za-z_][A-Za-z0-9_]*)"
                        r"|^[+-]([A-Z][A-Z0-9_]{2,})\s*=")
_COMMENT_RE = re.compile(r"^\+\s*#\s?(.*)$")

GENERATED_MARKER = "<!-- generated by tools/patch_docs.py -->"


# ── parsing ───────────────────────────────────────────────────────────────────

def parse_patch(text):
    """[{file, index, header, added, removed, symbols, rationale, body}] for each hunk."""
    hunks, cur_file, hunk, per_file = [], None, None, {}
    for line in (text or "").split("\n"):
        m = _FILE_RE.match(line)
        if m:
            cur_file = m.group(1)
            continue
        if _OLD_FILE_RE.match(line) and cur_file is None:
            cur_file = _OLD_FILE_RE.match(line).group(1)
            continue
        m = _HUNK_RE.match(line)
        if m:
            per_file[cur_file] = per_file.get(cur_file, 0) + 1
            hunk = {"file": cur_file or "(unknown)", "index": per_file[cur_file],
                    "header": (m.group(5) or "").strip(), "added": 0, "removed": 0,
                    "symbols": [], "rationale": [], "body": []}
            hunks.append(hunk)
            continue
        if hunk is None:
            continue
        if line.startswith("+++") or line.startswith("---"):
            continue
        if line.startswith("+"):
            hunk["added"] += 1
        elif line.startswith("-"):
            hunk["removed"] += 1
        else:
            hunk["body"].append(line)
            continue
        hunk["body"].append(line)
        sym = _SYMBOL_RE.match(line)
        if sym:
            name = sym.group(1) or sym.group(2)
            if name and name not in hunk["symbols"]:
                hunk["symbols"].append(name)
        cm = _COMMENT_RE.match(line)
        if cm and cm.group(1).strip():
            hunk["rationale"].append(cm.group(1).strip())
    return hunks


def summarize(hunk):
    """One concrete line describing what this hunk does."""
    added, removed = hunk["added"], hunk["removed"]
    syms = hunk["symbols"]
    what = f"`{'`, `'.join(syms[:3])}`" if syms else (
        f"`{hunk['header']}`" if hunk["header"] else "the surrounding block")
    if added and not removed:
        return f"Adds {added} line(s) to {what} in `{hunk['file']}`."
    if removed and not added:
        return f"Removes {removed} line(s) from {what} in `{hunk['file']}`."
    return (f"Rewrites {what} in `{hunk['file']}` "
            f"({removed} line(s) out, {added} in).")


def justify(hunk, prior_record=""):
    """Why this hunk exists. Author's stated reason > prior record > inference."""
    if hunk["rationale"]:
        text = " ".join(hunk["rationale"]).strip()
        if len(text) > 20:
            return text
    if prior_record:
        return prior_record
    syms = hunk["symbols"]
    if syms and hunk["added"] and hunk["removed"]:
        return (f"Changes the value/definition of {', '.join(syms[:3])}; the patch replaces "
                f"the previous form rather than extending it, so behaviour that depended on "
                f"the old value changes with it.")
    if hunk["added"] and not hunk["removed"]:
        return ("Purely additive: existing behaviour is untouched, so this hunk can land "
                "without a compatibility review.")
    if hunk["removed"] and not hunk["added"]:
        return ("Purely a removal: anything still referencing the removed lines must be "
                "checked before this hunk lands.")
    return "Modifies the surrounding block; see the diff body for exact effect."


def _prior_record(patch_path):
    """A sibling .README.md written by whoever recovered the patch, if any."""
    for cand in (patch_path.replace(".patch", ".README.md"),
                 patch_path + ".README.md"):
        if os.path.isfile(cand):
            try:
                with open(cand) as fh:
                    text = fh.read()
            except Exception:
                continue
            for para in text.split("\n\n"):
                p = para.strip()
                if p and not p.startswith("#") and len(p) > 60:
                    return " ".join(p.split())
    return ""


# ── rendering ─────────────────────────────────────────────────────────────────

def render_doc(name, hunks, prior_record=""):
    lines = [f"# {name} — hunk-by-hunk", "", GENERATED_MARKER, "",
             f"`{name}` contains {len(hunks)} hunk(s) across "
             f"{len({h['file'] for h in hunks})} file(s).", ""]
    if prior_record:
        lines += ["## Prior success record", "", prior_record, ""]
    for h in hunks:
        lines += [f"## {h['file']} — hunk {h['index']}", "",
                  f"- **File:** `{h['file']}`",
                  f"- **Hunk:** {h['index']}",
                  f"- **Change:** +{h['added']} / -{h['removed']}",
                  f"- **Summary:** {summarize(h)}",
                  f"- **Justification:** {justify(h, prior_record)}", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_index(entries):
    lines = ["# patches/ — index", "", GENERATED_MARKER, "",
             "Recovered or prepared patches, not yet applied. Each has a companion",
             "`<name>.md` documenting every hunk.", "",
             "| Patch | Files | Hunks | +/- | Purpose |",
             "| --- | --- | --- | --- | --- |"]
    for e in entries:
        lines.append(f"| [`{e['name']}`]({e['doc']}) | {e['files']} | {e['hunks']} | "
                     f"+{e['added']}/-{e['removed']} | {e['purpose']} |")
    if not entries:
        lines.append("| _(none)_ | | | | |")
    return "\n".join(lines) + "\n"


def _purpose(hunks, prior_record):
    if prior_record:
        return prior_record[:180].replace("|", "\\|")
    if hunks:
        return summarize(hunks[0])[:180].replace("|", "\\|")
    return "empty patch"


# ── driver ────────────────────────────────────────────────────────────────────

def build(patch_dir=PATCH_DIR):
    """{path: content} for every doc that should exist."""
    out, entries = {}, []
    if not os.path.isdir(patch_dir):
        return out
    for name in sorted(os.listdir(patch_dir)):
        if not name.endswith(".patch"):
            continue
        path = os.path.join(patch_dir, name)
        try:
            with open(path, errors="replace") as fh:
                hunks = parse_patch(fh.read())
        except Exception:
            hunks = []
        prior = _prior_record(path)
        doc_name = name + ".md"
        out[os.path.join(patch_dir, doc_name)] = render_doc(name, hunks, prior)
        entries.append({"name": name, "doc": doc_name, "hunks": len(hunks),
                        "files": len({h["file"] for h in hunks}),
                        "added": sum(h["added"] for h in hunks),
                        "removed": sum(h["removed"] for h in hunks),
                        "purpose": _purpose(hunks, prior)})
    out[os.path.join(patch_dir, "README.md")] = render_index(entries)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--dir", default=PATCH_DIR)
    args = ap.parse_args()

    wanted = build(args.dir)
    stale = []
    for path, content in sorted(wanted.items()):
        existing = None
        if os.path.isfile(path):
            with open(path, errors="replace") as fh:
                existing = fh.read()
        if existing == content:
            continue
        stale.append(os.path.relpath(path, REPO))
        if args.write:
            with open(path, "w") as fh:
                fh.write(content)

    if args.check and stale:
        print("patch_docs: out of date — run `python3 tools/patch_docs.py --write`:")
        for s in stale:
            print(f"  {s}")
        return 1
    if args.write:
        print(f"patch_docs: wrote {len(stale)} file(s)" if stale
              else "patch_docs: already up to date")
    elif not args.check:
        print(f"patch_docs: {len(wanted)} doc(s) expected, {len(stale)} out of date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
