#!/usr/bin/env python3
"""Reconcile dirty worktrees, broken worktrees and bridge patch artifacts.

The rescue-ref and branch-tip reconcilers only see work that reached a commit.
Two large classes of ChatGPT/Codex evidence never do:

  dirty_worktree            uncommitted tracked edits and untracked files sitting
                            in a checked-out worktree
  broken_codex_git_worktree a worktree whose working directory or gitdir link is
                            gone, so git can see the registration but not the work
  chatgpt_bridge_artifact   .patch/.diff files parked in the ChatGPT bridge
  codex_output_artifact     dropbox (_applied/_failed), which may or may not have
                            actually landed

This script is READ-ONLY with respect to all of them. It never stashes, cleans,
checks out, prunes, resets or moves anything; a dirty worktree is inspected in
place and left exactly as found. That matters because these are the evidence
sources the recovery contract explicitly forbids destroying.

Classification vocabulary matches tools/reconcile_rescue_refs.py.

Usage:
    python3 tools/reconcile_worktree_evidence.py --base origin/master \
        --fingerprint <audit-sha> --repo /path/to/main/checkout \
        --dropbox ~/Documents/chatgpt-dropbox \
        --out .orch/recovery-ledger-<short>-worktrees.json
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from dataclasses import asdict, dataclass, field

# Strict apply verdict lives in one module so every reconciler agrees on what
# "still applies" means. See tools/recovery_apply_check.py for why
# `git apply --check --3way` is not a usable answer.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from recovery_apply_check import apply_verdict, deletes_live_paths, LANDABLE  # noqa: E402


# Untracked noise that is regenerated by tooling and carries no recoverable
# intent. Matching paths are still enumerated and classified, never silently
# dropped -- they simply resolve to ALREADY_PRESENT/generated.
GENERATED_HINTS = (
    "/__pycache__/", ".pyc", "/node_modules/", "/.pytest_cache/",
    "/.orch/", "/.DS_Store",
)


def git(*args: str, cwd: str = ".", check: bool = False) -> str:
    proc = subprocess.run(
        ("git",) + args, cwd=cwd, capture_output=True, text=True, errors="replace"
    )
    if check and proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)}: {proc.stderr.strip()}")
    return proc.stdout


def git_ok(*args: str, cwd: str = ".") -> bool:
    return subprocess.run(
        ("git",) + args, cwd=cwd, capture_output=True, text=True
    ).returncode == 0


@dataclass
class Item:
    ref: str                      # worktree path or artifact path
    sha: str = ""                 # worktree HEAD, or content hash for artifacts
    subject: str = ""
    created_at: int = 0
    kind: str = ""
    classification: str = "UNKNOWN"
    disposition: str = ""
    files: list = field(default_factory=list)
    evidence: str = ""


# --------------------------------------------------------------------------
# enumeration
# --------------------------------------------------------------------------

def enumerate_worktrees(repo: str) -> "list[tuple[str, str, str]]":
    """(path, head_sha, branch) for every registered worktree. Read-only."""
    out = git("worktree", "list", "--porcelain", cwd=repo)
    entries, cur = [], {}
    for line in out.splitlines():
        if line.startswith("worktree "):
            if cur:
                entries.append(cur)
            cur = {"path": line.split(" ", 1)[1], "head": "", "branch": ""}
        elif line.startswith("HEAD "):
            cur["head"] = line.split(" ", 1)[1]
        elif line.startswith("branch "):
            cur["branch"] = line.split(" ", 1)[1]
    if cur:
        entries.append(cur)
    return [(e["path"], e["head"], e["branch"]) for e in entries]


def enumerate_artifacts(dropbox: str) -> "list[str]":
    """Every patch-like artifact under the bridge dropbox, recursively."""
    found = []
    if not dropbox or not os.path.isdir(dropbox):
        return found
    for root, _dirs, files in os.walk(dropbox):
        for name in files:
            if name.endswith((".patch", ".diff")):
                found.append(os.path.join(root, name))
    return sorted(found)


# --------------------------------------------------------------------------
# shared helpers
# --------------------------------------------------------------------------

def patch_id_of(diff_text: str, cwd: str) -> "str | None":
    if not diff_text.strip():
        return None
    out = subprocess.run(
        ["git", "patch-id", "--stable"], cwd=cwd,
        input=diff_text, capture_output=True, text=True, errors="replace",
    ).stdout
    return out.split()[0] if out.strip() else None


def base_patch_ids(base: str, depth: int, cwd: str) -> "set[str]":
    shas = git("log", "--no-merges", "--pretty=format:%H", "-n", str(depth),
               base, cwd=cwd).split()
    ids: set[str] = set()
    for start in range(0, len(shas), 150):
        diff = subprocess.run(
            ["git", "show", "--no-color", "--patch", "--first-parent"]
            + shas[start : start + 150],
            cwd=cwd, capture_output=True, text=True, errors="replace",
        ).stdout
        out = subprocess.run(
            ["git", "patch-id", "--stable"], cwd=cwd,
            input=diff, capture_output=True, text=True, errors="replace",
        ).stdout
        for line in out.splitlines():
            if line.strip():
                ids.add(line.split()[0])
    return ids


def diff_applies(diff_text: str, base: str = "HEAD", cwd: str = ".") -> bool:
    """True only when the diff lands WITHOUT conflicts (see recovery_apply_check)."""
    return apply_verdict(diff_text, base, cwd) in LANDABLE


def newest_touch(base: str, path: str, cwd: str) -> int:
    out = git("log", "-1", "--format=%ct", base, "--", path, cwd=cwd).strip()
    return int(out) if out.isdigit() else 0


def is_generated(path: str) -> bool:
    p = "/" + path.replace(os.sep, "/")
    return any(h in p for h in GENERATED_HINTS)


def base_blob(base: str, path: str, cwd: str) -> str:
    """Blob sha of `path` in `base`, or "" when the base does not carry it.

    Fail-soft: any git error is reported as "not in base" rather than raising,
    because a missing lookup must never wedge a reconciliation run.
    """
    out = git("rev-parse", "%s:%s" % (base, path.replace(os.sep, "/")), cwd=cwd)
    out = out.strip()
    return out if len(out) == 40 and all(c in "0123456789abcdef" for c in out) else ""


def worktree_blob(root: str, path: str) -> str:
    """Blob sha the untracked working-tree file would hash to (or "")."""
    abs_path = os.path.join(root, path)
    if not os.path.isfile(abs_path):
        return ""
    out = git("hash-object", "--", abs_path, cwd=root).strip()
    return out if len(out) == 40 else ""


def split_untracked_against_base(files: "list[str]", root: str, base: str,
                                 repo: str) -> "tuple[list[str], list[str], list[str]]":
    """Partition untracked paths into (new, identical_to_base, differs_from_base).

    An untracked file is only NEW when the base branch does not carry the path at
    all. A worktree checked out at an older commit reports paths as untracked
    that the default branch has since started tracking; without this check they
    were reported as RECOVERABLE_VALUE and looked like dropped work.
    """
    new, same, differs = [], [], []
    for f in files:
        blob = base_blob(base, f, repo)
        if not blob:
            new.append(f)
        elif blob == worktree_blob(root, f):
            same.append(f)
        else:
            differs.append(f)
    return new, same, differs


# --------------------------------------------------------------------------
# classification
# --------------------------------------------------------------------------

def classify_worktree(item: Item, path: str, head: str, branch: str,
                      base: str, repo: str, known: "set[str]") -> None:
    # A registration whose working directory is gone is broken evidence: the
    # commit may still be reachable, but nothing uncommitted can be recovered.
    if not os.path.isdir(path):
        item.kind = "broken_codex_git_worktree"
        if head and git_ok("merge-base", "--is-ancestor", head, base, cwd=repo):
            item.classification = "ALREADY_PRESENT"
            item.disposition = (
                "worktree directory missing but its HEAD is reachable from "
                f"{base}; nothing uncommitted to recover"
            )
        else:
            item.classification = "CONFLICTED_NEEDS_FOCUSED_TASK"
            item.disposition = (
                "worktree directory missing and HEAD not in base; queue a "
                "focused task to recover from the commit graph, do not prune"
            )
        item.evidence = "path absent: " + path
        return

    item.kind = "dirty_worktree"
    status = git("status", "--porcelain", cwd=path)
    if not status.strip():
        item.classification = "ALREADY_PRESENT"
        item.disposition = "worktree clean; no uncommitted evidence"
        item.evidence = "git status --porcelain empty"
        return

    tracked, untracked = [], []
    for line in status.splitlines():
        if len(line) < 4:
            continue
        code, p = line[:2], line[3:].strip().strip('"')
        (untracked if code == "??" else tracked).append(p)
    item.files = sorted(tracked + untracked)

    real = [f for f in item.files if not is_generated(f)]
    if not real:
        item.classification = "ALREADY_PRESENT"
        item.disposition = (
            f"{len(item.files)} dirty path(s), all tool-generated "
            "(caches/build output); nothing to recover"
        )
        item.evidence = "generated-only working tree"
        return

    # Uncommitted tracked edits are the only part git can diff directly.
    diff_text = git("diff", "HEAD", "--", cwd=path)
    if diff_text.strip():
        pid = patch_id_of(diff_text, path)
        if pid and pid in known:
            item.classification = "ALREADY_PRESENT"
            item.disposition = f"uncommitted diff patch-id {pid[:12]} already in {base}"
            item.evidence = "patch-id=" + pid
            return

    tracked_real = [f for f in tracked if not is_generated(f)]
    if tracked_real and all(
        newest_touch(base, f, repo) > 0
        and newest_touch(base, f, repo) > item.created_at
        for f in tracked_real
    ) and not [f for f in untracked if not is_generated(f)]:
        item.classification = "SUPERSEDED_BY_NEWER"
        item.disposition = (
            f"all {len(tracked_real)} modified path(s) rewritten in {base} after "
            "this worktree was last touched; newest implementation wins"
        )
        item.evidence = "base newer on every modified path"
        return

    # A published branch means the merge train can already see this line of work,
    # but uncommitted edits still are not in it -- so this is only ACTIVE when
    # there is nothing uncommitted beyond generated noise.
    if branch:
        short = branch.replace("refs/heads/", "")
        published = git("ls-remote", "--heads", "origin", short, cwd=repo).strip()
        if published and not diff_text.strip() and not [
            f for f in untracked if not is_generated(f)
        ]:
            item.classification = "ACTIVE_IN_ANOTHER_TASK"
            item.disposition = f"origin/{short} carries this work; leave to that task"
            item.evidence = "ls-remote origin " + short
            return

    if diff_text.strip() and diff_applies(diff_text, base, repo):
        item.classification = "RECOVERABLE_VALUE"
        item.disposition = (
            f"{len(real)} uncommitted path(s); tracked diff applies to base. "
            "Recover via a new isolated worktree + agent branch. Source worktree "
            "left untouched."
        )
        item.evidence = "git apply --check --3way clean"
    elif diff_text.strip():
        item.classification = "CONFLICTED_NEEDS_FOCUSED_TASK"
        item.disposition = (
            "uncommitted tracked diff no longer applies to base; queue a focused "
            "follow-up rather than forcing an overwrite"
        )
        item.evidence = "git apply --check --3way rejected"
    else:
        # Untracked-only. "Untracked" is relative to THIS worktree's checkout,
        # not to the base branch, so a stale worktree reports paths the base has
        # since started tracking. Only paths the base does not carry are new.
        untracked_real = [f for f in untracked if not is_generated(f)]
        new, same, differs = split_untracked_against_base(
            untracked_real, path, base, repo)
        if not new and not differs:
            item.classification = "ALREADY_PRESENT"
            item.disposition = (
                f"{len(same)} untracked path(s) are byte-identical to {base}; "
                "the worktree simply predates the commit that added them"
            )
            item.evidence = "untracked paths match base blobs"
        elif not new:
            item.classification = "CONFLICTED_NEEDS_FOCUSED_TASK"
            item.disposition = (
                f"{len(differs)} untracked path(s) already exist in {base} with "
                "different content; queue a focused follow-up rather than "
                "overwriting the newer tracked version: " + ", ".join(differs[:6])
            )
            item.evidence = "untracked paths diverge from base blobs"
        else:
            item.files = sorted(new + differs)
            item.classification = "RECOVERABLE_VALUE"
            item.disposition = (
                f"{len(new)} untracked new file(s) absent from {base}; "
                "review and land through an agent branch. Source left untouched."
            )
            item.evidence = "untracked-only working tree, %d new vs base" % len(new)


def classify_artifact(item: Item, path: str, base: str, repo: str,
                      known: "set[str]") -> None:
    parent = os.path.basename(os.path.dirname(path))
    item.kind = ("chatgpt_bridge_artifact" if parent != "_failed"
                 else "codex_output_artifact")
    try:
        text = open(path, errors="replace").read()
    except OSError as exc:
        item.classification = "CONFLICTED_NEEDS_FOCUSED_TASK"
        item.disposition = f"artifact unreadable: {exc}"
        item.evidence = "read error"
        return

    item.sha = hashlib.sha256(text.encode(errors="replace")).hexdigest()[:40]
    item.subject = os.path.basename(path)
    item.files = [
        ln.split(" b/", 1)[1].strip()
        for ln in text.splitlines()
        if ln.startswith("diff --git ") and " b/" in ln
    ]

    if not text.strip():
        item.classification = "ALREADY_PRESENT"
        item.disposition = "empty artifact; nothing to recover"
        item.evidence = "zero-length patch"
        return

    pid = patch_id_of(text, repo)
    if pid and pid in known:
        item.classification = "ALREADY_PRESENT"
        item.disposition = f"patch-id {pid[:12]} already in {base}"
        item.evidence = "patch-id=" + pid
        return

    # An artifact the bridge already applied is represented by a commit; if that
    # commit is in base the patch is redundant, otherwise it is still live work.
    if parent == "_applied":
        item.evidence = "bridge marked applied"
        if diff_applies(text, base, repo):
            item.classification = "RECOVERABLE_VALUE"
            item.disposition = (
                "bridge marked this applied, but the patch still applies to "
                f"{base} -- the change never reached the default branch. "
                "Recover through an agent branch."
            )
        else:
            item.classification = "ALREADY_PRESENT"
            item.disposition = (
                "bridge applied it and the patch no longer applies, consistent "
                "with the change already being in base"
            )
        return

    if diff_applies(text, base, repo):
        item.classification = "RECOVERABLE_VALUE"
        item.disposition = (
            "failed bridge artifact whose patch applies cleanly today; recover "
            "through an isolated worktree + agent branch"
        )
        item.evidence = "git apply --check --3way clean"
    else:
        item.classification = "CONFLICTED_NEEDS_FOCUSED_TASK"
        item.disposition = (
            "failed bridge artifact whose patch no longer applies; queue a "
            "focused follow-up rather than forcing an overwrite"
        )
        item.evidence = "git apply --check --3way rejected"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="origin/master")
    ap.add_argument("--fingerprint", required=True)
    ap.add_argument("--repo", default=".", help="main checkout to classify against")
    ap.add_argument("--dropbox", default=os.path.expanduser(
        "~/Documents/chatgpt-dropbox"))
    ap.add_argument("--out", default=".orch/recovery-ledger-worktrees.json")
    ap.add_argument("--depth", type=int, default=1200)
    ap.add_argument("--exclude-path", default="",
                    help="worktree path of the reconciling task itself")
    args = ap.parse_args()

    repo = os.path.abspath(args.repo)
    known = base_patch_ids(args.base, args.depth, repo)

    items: list[Item] = []

    for path, head, branch in enumerate_worktrees(repo):
        if args.exclude_path and os.path.abspath(path) == os.path.abspath(
            args.exclude_path
        ):
            continue
        it = Item(ref=path, sha=head, subject=branch or "(detached)")
        try:
            it.created_at = int(os.path.getmtime(path)) if os.path.isdir(path) else 0
        except OSError:
            it.created_at = 0
        try:
            classify_worktree(it, path, head, branch, args.base, repo, known)
        except Exception as exc:
            it.classification = "CONFLICTED_NEEDS_FOCUSED_TASK"
            it.disposition = "classification error, needs focused task: %s" % exc
            it.evidence = "exception"
        items.append(it)

    for path in enumerate_artifacts(args.dropbox):
        it = Item(ref=path)
        try:
            it.created_at = int(os.path.getmtime(path))
        except OSError:
            it.created_at = 0
        try:
            classify_artifact(it, path, args.base, repo, known)
        except Exception as exc:
            it.classification = "CONFLICTED_NEEDS_FOCUSED_TASK"
            it.disposition = "classification error, needs focused task: %s" % exc
            it.evidence = "exception"
        items.append(it)

    counts: dict = {}
    for it in items:
        counts[it.classification] = counts.get(it.classification, 0) + 1

    ledger = {
        "audit_fingerprint": args.fingerprint,
        "base": args.base,
        "evidence_kind": "worktrees_and_bridge_artifacts",
        "total": len(items),
        "counts": counts,
        "unknown": counts.get("UNKNOWN", 0),
        "items": [asdict(it) for it in items],
    }

    out_dir = os.path.dirname(args.out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w") as fh:
        json.dump(ledger, fh, indent=2, sort_keys=True)

    print(json.dumps({"total": len(items), "counts": counts}, indent=2))
    return 1 if counts.get("UNKNOWN") else 0


if __name__ == "__main__":
    raise SystemExit(main())
