#!/usr/bin/env python3
"""branch_durability.py — never destroy the only copy of committed work.

WHY (2026-08-04, cowork forensic audit)
---------------------------------------
The single largest generator of orchestrator work was `recover-missing-branch-*`: an agent
commits, its branch is destroyed before promotion, and the orchestrator files a NEW task to
redo the work from scratch. 3,332 such tasks — 23.6% of all output — were re-doing work
that had already been done. Worse, the recovery task's own placeholder commit then
self-certified the original as MERGED, so the loop reported success.

Two fixes were already in place: runner._durable_share_branch() pushes agent/<slug> to
origin at commit time, and branch_gc refuses to delete anything it cannot prove is on
origin. Those are live and correct, but they only cover branch_gc. An audit of every
`git branch -D` in runner/ found four more paths that destroy committed work with no
durability check at all:

  * branch_cleanup.cleanup()      — force-deletes "merged", "stale" and "orphaned" branches
                                    classified purely by task state and age. Since 76.6% of
                                    MERGED rows are phantom, "merged" here routinely means
                                    "never shipped", and "orphaned" means "no task row" —
                                    both delete the only copy.
  * git_auto_branch (grace sweep) — deletes branches for terminal-state slugs after a grace
                                    period, again trusting the state that the audit proved
                                    is wrong 3 times in 4.
  * approval_merge (CONFLICT)     — deletes the branch to force a rebuild on fresh base.
  * merge_train._delete_branch    — same redo-on-conflict pattern, and it additionally does
                                    `push origin --delete`, removing the durable copy that
                                    _durable_share_branch had just created.

A merge conflict is not a reason to destroy work; it is a reason to rebase it. The redo
paths legitimately want the BRANCH NAME freed so a clean worktree can be rebuilt — they do
not need the COMMITS gone. So this module archives the tip under refs/archive/ before any
deletion. The name is released, the objects survive, and the work is recoverable by sha
instead of being re-generated by a fresh agent run.

Set ORCH_BRANCH_ARCHIVE=0 to disable archiving (not recommended).
"""
import os
import subprocess
import time

TIMEOUT = 30
ARCHIVE = os.environ.get("ORCH_BRANCH_ARCHIVE", "true").lower() in ("1", "true", "yes", "on")
ARCHIVE_NS = "refs/archive"


def _git(repo, *args, timeout=TIMEOUT):
    try:
        r = subprocess.run(["git", *args], cwd=repo, capture_output=True,
                           encoding="utf-8", errors="replace", timeout=timeout)
        return r.returncode, (r.stdout or "").strip(), (r.stderr or "").strip()
    except Exception as e:
        return -1, "", str(e)


def is_on_origin(repo, branch):
    """True only if origin already holds every commit on *branch*.

    Fail CLOSED: if we cannot prove the work is on origin we return False, and callers
    must then treat the branch as irreplaceable. Mirrors branch_gc._is_on_origin.
    """
    rc, tip, _ = _git(repo, "rev-parse", "--verify", branch)
    if rc != 0 or not tip:
        return False
    rc, _, _ = _git(repo, "rev-parse", "--verify", f"origin/{branch}")
    if rc == 0:
        rc2, out2, _ = _git(repo, "rev-list", "--count", f"origin/{branch}..{branch}")
        if rc2 == 0 and (out2 or "1").strip() == "0":
            return True
    rc3, out3, _ = _git(repo, "branch", "-r", "--contains", tip)
    if rc3 == 0 and any(l.strip().startswith("origin/") for l in (out3 or "").splitlines()):
        return True
    return False


def commits_reachable_elsewhere(repo, ref):
    """True if *ref*'s tip is contained in some OTHER origin ref (i.e. the work landed).

    The honest precondition for deleting a remote branch: its commits must survive the
    deletion. Age is not a proxy for this — an 8-day-old branch that never merged is
    exactly the work most worth keeping.
    """
    rc, tip, _ = _git(repo, "rev-parse", "--verify", ref)
    if rc != 0 or not tip:
        return False
    short = ref.replace("origin/", "", 1)
    rc, out, _ = _git(repo, "branch", "-r", "--contains", tip)
    if rc != 0:
        return False  # fail closed
    for line in (out or "").splitlines():
        name = line.strip()
        if name.startswith("origin/") and name != f"origin/{short}" and name != ref:
            return True
    return False


def archive_branch(repo, branch, reason=""):
    """Copy branch tip to refs/archive/<branch>/<epoch> so the commits survive deletion.

    Refs under refs/archive keep the objects reachable, so `git gc` will not prune them and
    the work can be restored with `git branch <name> <sha>` instead of being re-generated
    by a fresh agent run. Cheap: one ref write, no object copying.
    """
    if not ARCHIVE:
        return None
    rc, tip, _ = _git(repo, "rev-parse", "--verify", branch)
    if rc != 0 or not tip:
        return None
    ref = f"{ARCHIVE_NS}/{branch}/{int(time.time())}"
    rc, _, err = _git(repo, "update-ref", ref, tip)
    if rc != 0:
        print(f"[branch-durability] WARNING could not archive {branch}: {err}")
        return None
    # A local-only archive ref is not durability, it is a note-to-self. Audited 2026-08-06:
    # 93 archive refs existed on this machine and ZERO on origin, so every "archived ..." line
    # in the log was overstating the guarantee — lose the disk, lose the work it claimed to be
    # protecting. Mirror the ref to origin so the objects survive the machine.
    #
    # Best-effort and non-fatal by design: archiving happens on the deletion path, and a push
    # that fails (offline, auth, remote gone) must not stop the local archive from being made
    # or block the caller. The log distinguishes the two outcomes so an operator can tell a
    # genuinely durable archive from a local-only one instead of assuming.
    shared = False
    if os.environ.get("ORCH_SHARE_ARCHIVE_REFS", "true").lower() in ("1", "true", "yes", "on"):
        try:
            rc_p, _, err_p = _git(repo, "push", "origin", f"{ref}:{ref}", timeout=120)
            shared = rc_p == 0
            if not shared:
                print(f"[branch-durability] WARNING archive {ref} is LOCAL-ONLY "
                      f"(push failed: {str(err_p)[-160:]})")
        except Exception as e:
            print(f"[branch-durability] WARNING archive {ref} is LOCAL-ONLY (push error: {e})")
    print(f"[branch-durability] archived {branch} -> {ref} @ {tip[:12]}"
          + (" [on origin]" if shared else " [local-only]")
          + (f" ({reason})" if reason else ""))
    return tip


def try_share(repo, branch):
    """Best-effort push of *branch* to origin so it stops being local-only."""
    if os.environ.get("ORCH_SHARE_AGENT_BRANCHES", "true").lower() not in (
            "1", "true", "yes", "on"):
        return False
    rc, _, _ = _git(repo, "push", "origin", f"{branch}:refs/heads/{branch}", timeout=180)
    return rc == 0


def safe_delete(repo, branch, reason="", delete_remote=False, force=False):
    """Delete *branch* without destroying the only copy of its commits.

    Order of operations:
      1. archive the tip under refs/archive/ (objects survive regardless of what follows)
      2. if the branch is not on origin, try to push it there
      3. delete the local ref
      4. delete the remote ref ONLY when explicitly asked AND the commits are reachable
         from some other origin ref (i.e. they really did land somewhere)

    *force* skips the origin-durability attempt but never skips archiving. Returns a dict
    describing what happened, so callers can log it.
    """
    out = {"branch": branch, "archived": None, "shared": False,
           "local_deleted": False, "remote_deleted": False, "reason": reason}
    rc, tip, _ = _git(repo, "rev-parse", "--verify", branch)
    if rc != 0 or not tip:
        out["error"] = "branch does not exist"
        return out

    out["archived"] = archive_branch(repo, branch, reason)
    durable = is_on_origin(repo, branch)
    if not durable and not force:
        out["shared"] = try_share(repo, branch)
        durable = out["shared"] or is_on_origin(repo, branch)
    out["durable"] = durable

    rc, _, err = _git(repo, "branch", "-D", branch)
    out["local_deleted"] = rc == 0
    if rc != 0:
        out["error"] = err

    if delete_remote:
        # Removing the remote ref removes the durability guarantee, so only do it once the
        # commits are demonstrably reachable from another origin ref.
        rc2, contains, _ = _git(repo, "branch", "-r", "--contains", tip)
        others = [l.strip() for l in (contains or "").splitlines()
                  if l.strip().startswith("origin/")
                  and l.strip() != f"origin/{branch}"]
        if rc2 == 0 and others:
            rc3, _, _ = _git(repo, "push", "origin", "--delete", branch, timeout=180)
            out["remote_deleted"] = rc3 == 0
        else:
            print(f"[branch-durability] KEEPING origin/{branch} — its commits are not "
                  f"reachable from any other origin ref; deleting it would destroy the "
                  f"only durable copy ({reason})")
    return out
