#!/usr/bin/env python3
"""
cx_voi_router.py - Value-of-Information Router.

Find the expert domain with the fewest graded calls / worst Brier score in
committee_scoreboard (highest uncertainty), and — bounded to 1 per run — queue
a small A/B experiment proposal targeting that domain (insert into
improvement_proposals status='proposed', surface='experiment', divergent=false)
so the system deliberately reduces its own uncertainty fastest. Reuses the
hypothesis shape from committees.mine_hypotheses. No schema change.
"""
import os, sys, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import db


def _find_highest_uncertainty_domain():
    """Find the committee domain with fewest graded calls or worst Brier score.
    Returns (committee_name, calls, brier) or None if no data."""
    rows = db.select("committee_scoreboard", {
        "select": "committee,calls,brier,accuracy",
        "entity_type": "eq.committee",
    }) or []
    if not rows:
        return None
    # Score each domain: fewer calls = higher uncertainty; worse Brier = higher uncertainty.
    # Composite: domains with < 5 calls get top priority (insufficient data),
    # then rank by worst Brier score among the rest.
    low_data = [r for r in rows if (r.get("calls") or 0) < 5]
    if low_data:
        worst = min(low_data, key=lambda r: r.get("calls") or 0)
        return worst.get("committee"), worst.get("calls") or 0, worst.get("brier")

    # All domains have >= 5 calls; pick worst Brier (highest = least calibrated)
    with_brier = [r for r in rows if r.get("brier") is not None]
    if not with_brier:
        # Fall back to fewest calls
        worst = min(rows, key=lambda r: r.get("calls") or 0)
        return worst.get("committee"), worst.get("calls") or 0, worst.get("brier")

    worst = max(with_brier, key=lambda r: float(r.get("brier") or 0))
    return worst.get("committee"), worst.get("calls") or 0, worst.get("brier")


def _already_proposed(domain):
    """Check if there's already a pending experiment proposal targeting this domain."""
    existing = db.select("improvement_proposals", {
        "select": "id",
        "surface": "eq.experiment",
        "status": "eq.proposed",
    }) or []
    # Check if any existing proposal title mentions this domain
    for p in (db.select("improvement_proposals", {
        "select": "id,title",
        "surface": "eq.experiment",
        "status": "eq.proposed",
    }) or []):
        if domain and domain.lower() in (p.get("title") or "").lower():
            return True
    return False


def _build_hypothesis(domain, calls, brier):
    """Build a hypothesis in the same shape as committees.mine_hypotheses output."""
    if calls < 5:
        reason = f"only {calls} graded calls — insufficient data to calibrate"
    else:
        reason = f"Brier score {brier:.3f} — worst-calibrated domain" if brier else "poorest calibration"

    # Resolve an app to attach the proposal to (pick the first project)
    projects = db.select("projects", {"select": "name", "limit": "1"}) or []
    app = projects[0]["name"] if projects else "beethoven"

    return {
        "app": app,
        "title": f"VOI experiment: reduce uncertainty in {domain}",
        "hypothesis": (
            f"If we run a targeted A/B experiment in the '{domain}' domain, "
            f"we will improve calibration because {reason}. "
            f"This is the highest-value-of-information domain to test next."
        ),
    }


def run():
    """Main entry point. Bounded to 1 proposal per run."""
    result = _find_highest_uncertainty_domain()
    if not result:
        print("cx_voi_router: no committee_scoreboard data, skipping")
        return {"queued": 0, "reason": "no scoreboard data"}

    domain, calls, brier = result

    if _already_proposed(domain):
        print(f"cx_voi_router: experiment already proposed for '{domain}', skipping")
        return {"queued": 0, "reason": f"already proposed for {domain}"}

    hyp = _build_hypothesis(domain, calls, brier)
    db.insert("improvement_proposals", {
        "app": hyp["app"],
        "surface": "experiment",
        "title": hyp["title"][:200],
        "status": "proposed",
        "divergent": False,
        "proposal": hyp["hypothesis"][:800],
        "rationale": f"Auto-generated by VOI router targeting highest-uncertainty domain ({domain}).",
        "score": 14,
    })
    print(f"cx_voi_router: queued experiment for '{domain}' (calls={calls}, brier={brier})")
    return {"queued": 1, "domain": domain, "calls": calls, "brier": brier}


if __name__ == "__main__":
    run()
