#!/usr/bin/env python3
"""db_probe_forge.py — the probe catalog grows by DEMAND, not by hand.

Every memo argument with strength 'unassessed' is a measurement the fleet wants but no
probe provides. db_link demand lists them; the forge turns each into a PROPOSAL — a
review-ready spec (probe id, dialect SQL sketch, parser contract, fixture-test shape,
evidence kinds, memo argument mapping) committed to docs/db-probe-proposals/ as one draft
PR per argument, deduped by branch. A host-side pass with a local model can fill the TODOs
later; the scaffold itself is deterministic and safe (the SQL sketch ships commented-out,
so nothing half-formed ever runs against a database).

Caps: ORCH_DB_FORGE_MAX_PROPOSALS per run (default 2), dedupe on open PR per argument.
Off by default: ORCH_DB_FORGE=1 enables live PR creation; without it forge_run returns
the specs it would file (plan mode) for db_link/console inspection.
"""
from __future__ import annotations

import base64
import json
import os
import re
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import db  # noqa: E402
import db_steering_contract as C  # noqa: E402

ENABLED = os.environ.get("ORCH_DB_FORGE", "0") == "1"
MAX_PROPOSALS = int(os.environ.get("ORCH_DB_FORGE_MAX_PROPOSALS", "2"))
FLEET_REPO = "kalepasch1/claude-orchestrator"

_IDENT_WORD_RE = re.compile(r"[a-z0-9]+")


def uncovered_arguments():
    """{memo_kind: set(keys)} for arguments with NO mapped evidence anywhere — the demand
    list, deduped across projects. Fail-soft {}."""
    try:
        rows = db.select_all("legal_memo_drafts", {"select": "memo_kind,arguments"}) or []
    except Exception as e:
        print("db_probe_forge: memo read failed: %s" % str(e)[:120])
        return {}
    covered, all_keys = {}, {}
    for m in rows:
        kind = m.get("memo_kind")
        spec = C.MEMO_KINDS.get(kind) or {}
        all_keys.setdefault(kind, set(spec.get("arguments") or {}))
        covered.setdefault(kind, set())
        for a in m.get("arguments") or []:
            if isinstance(a, dict) and a.get("strength") != "unassessed":
                covered[kind].add(a.get("key"))
    out = {}
    for kind, keys in all_keys.items():
        missing = sorted(keys - covered.get(kind, set()))
        if missing:
            out[kind] = missing
    return out


def _probe_id_for(memo_kind, key):
    words = _IDENT_WORD_RE.findall(key.replace("_", " "))[:3]
    return "forge_%s_%s" % (memo_kind.split("_")[0][:8], "_".join(words)[:28])


def spec_for(memo_kind, key):
    """A proposal dict for one uncovered argument. Pure/deterministic."""
    spec = C.MEMO_KINDS.get(memo_kind) or {}
    claim = (spec.get("arguments") or {}).get(key, key)
    kinds = list(spec.get("evidence_kinds") or ["availability"])
    pid = _probe_id_for(memo_kind, key)
    title = "Covers memo argument %s of %s" % (key, memo_kind)
    return {
        "probe_id": pid, "memo_kind": memo_kind, "argument_key": key, "claim": claim,
        "evidence_kinds": kinds, "tier": "cheap", "category": kinds[0] if kinds[0] in C.CATEGORIES else "availability",
        "title": title,
        "sql_sketch": ("-- TODO(host-model): the read-only statement that measures:\n"
                       "--   %s\n" % claim +
                       "-- Constraints: SELECT against catalogs only; no row values; "
                       "limit 500; deterministic ordering; assert_read_only enforced by the adapter."),
        "parser_contract": ("rows -> [make_finding(%r, ...)] ; severity from metrics; "
                            "supports-direction info row is encouraged when the invariant holds" % pid),
        "fixture_test": "test_db_probes.py: run_parse(%r, rows) pins titles/severities/metrics" % pid,
        "safety": "read-only; no PII values; caps like ORCH_DB_PROBE_MAX_ROWS apply",
    }


def proposal_md(spec):
    md = ["# Probe proposal: `%s`" % spec["probe_id"], "",
          "_Demand-driven: memo argument `%s` of `%s` has zero evidence coverage._" % (spec["argument_key"], spec["memo_kind"]),
          "", "Claim to measure: %s" % spec["claim"], "",
          "## Sketch", "", "```sql", spec["sql_sketch"], "```", "",
          "## Parser contract", "", spec["parser_contract"], "",
          "## Fixture test", "", spec["fixture_test"], "",
          "## Registration (db_probes.PROBES)", "",
          ('`_probe("%s", "%s", "%s", "%s", %s, <parser>, "<remediation>")`'
           % (spec["probe_id"], spec["title"], spec["category"], spec["tier"],
              tuple(spec["evidence_kinds"]))), "", "## Safety", "", spec["safety"],
          "", "---", "Generated by db_probe_forge (deterministic scaffold; fill SQL parser TODOs on a host model pass)."]
    return "\n".join(md)


def forge_branch(key):
    return "forge/db-probe-%s" % re.sub(r"[^a-z0-9]+", "-", key.lower())[:40].strip("-")


def file_proposals(gh, specs):
    """One draft PR per argument into the fleet repo. gh = db_remediate._gh (injectable).
    Returns per-spec results; never raises."""
    results = []
    for s in specs:
        branch = forge_branch(s["argument_key"])
        existing = gh("GET", "/repos/%s/pulls?head=%s:%s&state=open&per_page=5" % (FLEET_REPO, FLEET_REPO.split("/")[0], branch))
        if isinstance(existing, list) and existing:
            results.append({"argument_key": s["argument_key"], "ok": True, "skipped": "open PR exists",
                            "pr": existing[0].get("html_url")})
            continue
        meta = gh("GET", "/repos/%s" % FLEET_REPO)
        base = str((meta or {}).get("default_branch") or "master")
        ref = gh("GET", "/repos/%s/git/ref/heads/%s" % (FLEET_REPO, base))
        sha = str((ref or {}).get("object", {}).get("sha") or "")
        if not sha:
            results.append({"argument_key": s["argument_key"], "ok": False, "reason": "base ref unreadable"})
            continue
        made = gh("POST", "/repos/%s/git/refs" % FLEET_REPO, {"ref": "refs/heads/%s" % branch, "sha": sha})
        if (made or {}).get("_http_error") and "already exists" not in str(made.get("_message", "")):
            results.append({"argument_key": s["argument_key"], "ok": False, "reason": "branch failed: %s" % made.get("_message")})
            continue
        path = "docs/db-probe-proposals/%s.md" % s["argument_key"]
        put = gh("PUT", "/repos/%s/contents/%s" % (FLEET_REPO, path), {
            "message": "probe proposal: %s (demand: %s)" % (s["probe_id"], s["argument_key"]),
            "content": base64.b64encode(proposal_md(s).encode()).decode(), "branch": branch,
            "committer": {"name": "kalepasch1", "email": "kalepasch@gmail.com"}})
        if (put or {}).get("_http_error"):
            results.append({"argument_key": s["argument_key"], "ok": False, "reason": "file commit failed: %s" % put.get("_message")})
            continue
        pr = gh("POST", "/repos/%s/pulls" % FLEET_REPO, {
            "title": "probe forge: cover memo argument %s (%s)" % (s["argument_key"], s["memo_kind"]),
            "head": branch, "base": base, "draft": True,
            "body": "Demand-generated probe scaffold. SQL is commented out; complete on a host-model pass, then undraft.\n\nClaim: %s" % s["claim"]})
        results.append({"argument_key": s["argument_key"], "ok": not (pr or {}).get("_http_error"),
                        "pr": (pr or {}).get("html_url") or (pr or {}).get("_message")})
    return results


def forge_run(gh=None, limit=None):
    """Plan or file proposals for the worst demand. {demand, results} — fail-soft.
    `gh` injectable for tests; live path uses db_remediate's authenticated caller."""
    out = {"enabled": ENABLED, "demand": uncovered_arguments(), "results": []}
    flat = [(k, key) for k, keys in out["demand"].items() for key in keys]
    flat = flat[: (limit if limit is not None else MAX_PROPOSALS)]
    specs = [spec_for(k, key) for k, key in flat]
    if not specs:
        out["note"] = "every memo argument has evidence coverage"
        return out
    if not ENABLED:
        out["planned"] = specs
        out["note"] = "plan-only (ORCH_DB_FORGE=0)"
        return out
    if gh is None:
        import db_remediate
        gh = db_remediate._gh
    try:
        out["results"] = file_proposals(gh, specs)
    except Exception as e:
        out["error"] = "%s: %s" % (type(e).__name__, str(e)[:120])
    return out


if __name__ == "__main__":
    print(json.dumps(forge_run(), indent=2, default=str))
