#!/usr/bin/env python3
"""
funding_loop.py - self-funding cost-recovery tracker. Measures the value generated by
the orchestrator (time saved, tasks automated, errors prevented) against its running
cost (API tokens, compute) and surfaces the net ROI so the operator can verify the
system pays for itself.

Reads from cost_ledger (spend) and task outcomes (value delivered). Publishes a
funding_snapshots row each run. Fail-soft: returns defaults on any DB error.
"""
import os, sys, datetime, json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import db

VALUE_PER_TASK_USD = float(os.environ.get("FUNDING_VALUE_PER_TASK", "2.0"))
VALUE_PER_MERGE_USD = float(os.environ.get("FUNDING_VALUE_PER_MERGE", "5.0"))
LOOKBACK_HOURS = int(os.environ.get("FUNDING_LOOKBACK_HOURS", "168"))  # 1 week


def _since():
    return (datetime.datetime.utcnow() - datetime.timedelta(hours=LOOKBACK_HOURS)).isoformat()


def _total_spend() -> float:
    """Sum cost_usd from cost_ledger in the lookback window."""
    try:
        rows = db.select("cost_ledger", {
            "select": "cost_usd", "created_at": f"gte.{_since()}"
        }) or []
        return sum(float(r.get("cost_usd") or 0) for r in rows)
    except Exception:
        return 0.0


def _tasks_completed() -> int:
    try:
        rows = db.select("tasks", {
            "select": "id", "state": "eq.DONE",
            "updated_at": f"gte.{_since()}"
        }) or []
        return len(rows)
    except Exception:
        return 0


def _tasks_merged() -> int:
    try:
        rows = db.select("tasks", {
            "select": "id", "state": "eq.MERGED",
            "updated_at": f"gte.{_since()}"
        }) or []
        return len(rows)
    except Exception:
        return 0


def snapshot() -> dict:
    """Compute current funding-loop snapshot."""
    spend = _total_spend()
    done = _tasks_completed()
    merged = _tasks_merged()
    value = done * VALUE_PER_TASK_USD + merged * VALUE_PER_MERGE_USD
    roi = ((value - spend) / spend * 100) if spend > 0 else 0.0
    return {
        "period_hours": LOOKBACK_HOURS,
        "total_spend_usd": round(spend, 2),
        "tasks_done": done,
        "tasks_merged": merged,
        "estimated_value_usd": round(value, 2),
        "net_usd": round(value - spend, 2),
        "roi_pct": round(roi, 1),
        "self_funding": value >= spend,
    }


def run():
    """Compute and persist a funding snapshot."""
    snap = snapshot()
    try:
        db.insert("funding_snapshots", {
            "period_hours": snap["period_hours"],
            "spend_usd": snap["total_spend_usd"],
            "value_usd": snap["estimated_value_usd"],
            "roi_pct": snap["roi_pct"],
            "self_funding": snap["self_funding"],
        })
    except Exception:
        pass  # fail-soft
    status = "SELF-FUNDING" if snap["self_funding"] else "NEGATIVE"
    print(f"funding_loop: {status} | spend=${snap['total_spend_usd']:.2f} value=${snap['estimated_value_usd']:.2f} ROI={snap['roi_pct']:.0f}%")
    return snap


if __name__ == "__main__":
    print(json.dumps(run(), indent=2))
