#!/usr/bin/env python3
"""
idea_decomposer.py — founder types a one-line idea; system auto-produces a spec,
task DAG (ordered sub-tasks with deps), and acceptance tests, queue-ready in seconds.

Usage (CLI):
  python runner/idea_decomposer.py "add Stripe payment checkout to the app" --project beethoven

Usage (import):
  from idea_decomposer import decompose
  result = decompose("add Stripe payment checkout to the app", project_id="<uuid>")
  # result = {"spec": str, "tasks": [...], "enqueued": int}

Requires: SUPABASE_URL + SUPABASE_SERVICE_KEY (db.py) for enqueue; model inference via model_gateway.
Fail-soft: missing DB / model errors return a result with enqueued=0 but still emit the spec/DAG.
"""
from __future__ import annotations

import json
import os
import re
import sys
from typing import Any, Dict, List, Optional

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import db
import model_gateway
import model_policy

MAX_TASKS = int(os.environ.get("IDEA_DECOMPOSE_MAX_TASKS", "8"))
MAX_IDEA_CHARS = 2000

_SLUG_RE = re.compile(r"[^a-z0-9-]+")

_PLAN_PROMPT = """\
You are a senior software architect. A founder has one line describing their idea.
Produce a concrete build plan as JSON with exactly these fields:
  "spec"  : 2-4 sentence product specification (what it does, who it's for, core value).
  "tasks" : array of 3-{max} task objects, each:
      "title"           : short kebab-case slug (e.g. "add-stripe-checkout-endpoint")
      "prompt"          : full concrete build instruction for a coding agent (files, behaviour, no vague goals)
      "deps"            : array of earlier task titles this task depends on (empty [] for the first task)
      "acceptance_test" : one-sentence pass/fail criterion a reviewer can verify

Rules:
- Order tasks so each dep is listed before the task that needs it (topological order).
- Keep each task completable in a single coding pass with no ambiguity.
- Reply ONLY with the JSON object — no markdown, no prose outside the JSON.

IDEA: {idea}
""".strip()


def _slugify(title: str) -> str:
    return _SLUG_RE.sub("-", title.lower()).strip("-")[:60] or "task"


def _validate_dag(tasks: List[Dict]) -> List[str]:
    """Return list of error strings; empty means the DAG is valid."""
    errors: List[str] = []
    seen: set = set()
    for i, t in enumerate(tasks):
        title = t.get("title", "")
        if not title:
            errors.append(f"task[{i}] missing title")
            continue
        if not t.get("prompt"):
            errors.append(f"task '{title}' missing prompt")
        for dep in (t.get("deps") or []):
            if dep not in seen:
                errors.append(f"task '{title}' has dep '{dep}' that is not defined before it")
        seen.add(title)
    return errors


def _call_model(idea: str) -> Optional[Dict]:
    """Ask a cheap planning model to decompose the idea. Returns parsed dict or None."""
    try:
        prov, model, _ = model_policy.choose("plan", agentic=False)
    except Exception:
        prov, model = "claude", "claude-haiku-4-5-20251001"
    prompt = _PLAN_PROMPT.format(idea=idea[:MAX_IDEA_CHARS], max=MAX_TASKS)
    try:
        result = model_gateway.complete(prov, model, prompt)
        text = (result.get("text") or "").strip()
    except Exception:
        return None
    # extract JSON object (may be wrapped in markdown)
    m = re.search(r"\{.*\}", text, re.S)
    if not m:
        return None
    try:
        return json.loads(m.group(0))
    except (ValueError, TypeError):
        return None


def _enqueue_tasks(tasks: List[Dict], project_id: str, idea_slug: str) -> int:
    """Insert tasks into the DB. Returns count actually inserted; fail-soft on error."""
    inserted = 0
    for i, t in enumerate(tasks):
        slug = f"{idea_slug}-{_slugify(t.get('title', f'part{i+1}'))}"[:80]
        deps_note = ""
        if t.get("deps"):
            dep_slugs = [f"{idea_slug}-{_slugify(d)}" for d in t["deps"]]
            deps_note = f"\nDeps: {', '.join(dep_slugs)}"
        prompt = (
            (t.get("prompt") or "").strip() +
            deps_note +
            f"\n\nAcceptance test: {t.get('acceptance_test', '').strip()}" +
            f"\n\n(Task {i+1}/{len(tasks)} of idea '{idea_slug}', auto-generated by idea_decomposer.)"
        )
        try:
            existing = db.select("tasks", {"select": "id", "slug": f"eq.{slug}", "limit": "1"})
            if existing:
                continue
            db.insert("tasks", {
                "project_id": project_id,
                "slug": slug,
                "kind": "build",
                "state": "QUEUED",
                "prompt": prompt,
                "note": f"idea-decomposer: from '{idea_slug}'",
            })
            inserted += 1
        except Exception:
            pass
    return inserted


def decompose(idea: str, project_id: str = "", enqueue: bool = True) -> Dict[str, Any]:
    """Decompose a one-line idea into spec + task DAG + acceptance tests.

    Returns:
      {
        "spec": str,           product specification
        "tasks": [...],        task DAG (ordered, with deps + acceptance_test per task)
        "errors": [...],       DAG validation errors (empty = valid)
        "enqueued": int,       tasks inserted into the DB (0 if not enqueuing or no project_id)
      }
    """
    idea = (idea or "").strip()
    if not idea:
        return {"spec": "", "tasks": [], "errors": ["idea is empty"], "enqueued": 0}

    data = _call_model(idea)
    if not data or not isinstance(data, dict):
        return {"spec": "", "tasks": [], "errors": ["model returned no parseable JSON"], "enqueued": 0}

    spec = str(data.get("spec") or "").strip()
    raw_tasks = data.get("tasks") or []
    if not isinstance(raw_tasks, list):
        raw_tasks = []

    # normalise task fields
    tasks: List[Dict] = []
    for t in raw_tasks[:MAX_TASKS]:
        if not isinstance(t, dict):
            continue
        tasks.append({
            "title": _slugify(str(t.get("title") or f"task{len(tasks)+1}")),
            "prompt": str(t.get("prompt") or "").strip(),
            "deps": [str(d) for d in (t.get("deps") or []) if d],
            "acceptance_test": str(t.get("acceptance_test") or "").strip(),
        })

    errors = _validate_dag(tasks)

    enqueued = 0
    if enqueue and project_id and not errors:
        idea_slug = _slugify(idea[:40])
        enqueued = _enqueue_tasks(tasks, project_id, idea_slug)

    return {"spec": spec, "tasks": tasks, "errors": errors, "enqueued": enqueued}


def _project_id_by_name(name: str) -> Optional[str]:
    try:
        rows = db.select("projects", {"select": "id,name", "limit": "50"}) or []
        for p in rows:
            if p.get("name") == name:
                return p["id"]
    except Exception:
        pass
    return None


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description="Decompose a one-line idea into a task DAG")
    parser.add_argument("idea", help="One-line idea to decompose")
    parser.add_argument("--project", default="", help="Project name (for enqueue)")
    parser.add_argument("--no-enqueue", action="store_true", help="Print DAG without inserting tasks")
    args = parser.parse_args()

    project_id = ""
    if args.project and not args.no_enqueue:
        project_id = _project_id_by_name(args.project) or ""
        if not project_id:
            print(f"[idea_decomposer] project '{args.project}' not found; printing DAG only.")

    result = decompose(args.idea, project_id=project_id, enqueue=not args.no_enqueue)

    print(f"\n=== SPEC ===\n{result['spec']}\n")
    print(f"=== TASK DAG ({len(result['tasks'])} tasks) ===")
    for i, t in enumerate(result["tasks"]):
        deps = f"  deps: {t['deps']}" if t["deps"] else ""
        print(f"  {i+1}. [{t['title']}]{deps}")
        print(f"     prompt: {t['prompt'][:120]}...")
        print(f"     test:   {t['acceptance_test']}")
    if result["errors"]:
        print(f"\n[WARN] DAG validation errors: {result['errors']}")
    if result["enqueued"]:
        print(f"\n[enqueued] {result['enqueued']} tasks into project '{args.project}'")


if __name__ == "__main__":
    main()
