#!/usr/bin/env python3
"""
intent_compiler.py — Compile mature intents into deterministic scripts (1000X).

When an intent has been replayed 10+ times with 100% success rate, compile
it into a deterministic bash/python script that can be executed without ANY
model call. The script is version-pinned to the repo's current state.

This is the ultimate optimization: zero tokens, zero latency, zero cost.
The model is completely eliminated for patterns that have proven stable.

Compilation stages:
  1. Identify mature intents (10+ replays, 100% merge rate)
  2. Extract the deterministic diff from intent graph
  3. Generate a bash script that: applies diff, runs tests, commits
  4. Store compiled script in controls table
  5. On future matches: run script directly, skip everything

Usage:
    import intent_compiler
    compiled = intent_compiler.get_compiled(task, repo)
    if compiled:
        result = intent_compiler.execute(compiled, repo, task_id)
"""
import os, sys, json, hashlib, subprocess, time, textwrap
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import db

COMPILE_THRESHOLD = int(os.environ.get("ORCH_COMPILE_THRESHOLD", "10"))
COMPILE_MIN_RATE = float(os.environ.get("ORCH_COMPILE_MIN_RATE", "1.0"))  # 100% success required
COMPILED_MAX = int(os.environ.get("ORCH_COMPILED_MAX", "100"))


def _compiled_store():
    try:
        rows = db.select("controls", {"select": "value", "key": "eq.compiled_intents"})
        if rows and rows[0].get("value"):
            v = rows[0]["value"]
            return json.loads(v) if isinstance(v, str) else v
    except Exception:
        pass
    return {}


def _save_compiled(store):
    if len(store) > COMPILED_MAX:
        by_time = sorted(store.items(), key=lambda x: x[1].get("compiled_at", 0))
        store = dict(by_time[-COMPILED_MAX:])
    try:
        db.upsert("controls", {"key": "compiled_intents", "value": json.dumps(store, default=str)})
    except Exception:
        pass


def compile_intent(intent_fp, intent_data, diff_text, files_changed):
    """Compile a mature intent into a deterministic script.

    Args:
        intent_fp: intent fingerprint from intent_graph
        intent_data: the intent dict with success/failure counts
        diff_text: the canonical diff to apply
        files_changed: list of files affected

    Returns: compiled entry dict
    """
    store = _compiled_store()

    script = textwrap.dedent(f"""\
    #!/bin/bash
    # Compiled intent: {intent_fp}
    # Success rate: 100% over {intent_data.get('successes', 0)} runs
    # Files: {', '.join(files_changed[:10])}
    # Auto-generated by intent_compiler — DO NOT EDIT
    set -euo pipefail

    REPO="${{1:-.}}"
    TASK_ID="${{2:-compiled}}"

    cd "$REPO"

    # Apply the proven diff
    git apply --3way <<'DIFF_END'
    {diff_text}
    DIFF_END

    # Verify
    ${{TEST_CMD:-npm test}} || {{ echo "COMPILED SCRIPT FAILED TESTS"; exit 1; }}

    # Commit
    git add -A
    git commit -m "[compiled] $TASK_ID — deterministic intent replay"

    echo "COMPILED_SUCCESS"
    """)

    entry = {
        "intent_fp": intent_fp,
        "script": script,
        "files": files_changed,
        "successes": intent_data.get("successes", 0),
        "compiled_at": time.time(),
        "executions": 0,
        "last_executed": 0,
        "diff_hash": hashlib.sha256(diff_text.encode()).hexdigest()[:16],
    }

    store[intent_fp] = entry
    _save_compiled(store)
    return entry


def get_compiled(task, repo=""):
    """Check if a task matches a compiled intent.

    Returns: compiled entry dict or None
    """
    try:
        import intent_graph
        replay = intent_graph.find_replay(task, repo)
        if not replay:
            return None

        intent_fp = replay.get("intent_fp", "")
        if not intent_fp:
            return None

        store = _compiled_store()
        return store.get(intent_fp)
    except Exception:
        return None


def execute(compiled, repo, task_id=""):
    """Execute a compiled intent script.

    Returns: {success: bool, output: str, cost_usd: 0, tokens: 0}
    """
    script = compiled.get("script", "")
    if not script:
        return {"success": False, "output": "no script", "cost_usd": 0, "tokens": 0}

    try:
        result = subprocess.run(
            ["bash", "-c", script, "--", repo, task_id],
            capture_output=True, text=True, timeout=180,
            env={**os.environ, "CI": "true"}
        )

        success = result.returncode == 0 and "COMPILED_SUCCESS" in result.stdout

        # Update execution count
        store = _compiled_store()
        fp = compiled.get("intent_fp", "")
        if fp in store:
            store[fp]["executions"] = store[fp].get("executions", 0) + 1
            store[fp]["last_executed"] = time.time()
            _save_compiled(store)

        return {
            "success": success,
            "output": result.stdout[-1000:] + result.stderr[-500:],
            "cost_usd": 0,
            "tokens": 0,
            "method": "compiled_intent",
        }

    except subprocess.TimeoutExpired:
        return {"success": False, "output": "timeout", "cost_usd": 0, "tokens": 0}
    except Exception as e:
        return {"success": False, "output": str(e)[:300], "cost_usd": 0, "tokens": 0}


def run():
    """Periodic: scan intent graph for compilable intents."""
    try:
        import intent_graph
        graph = intent_graph._graph()
    except Exception:
        print("[intent-compiler] failed to load intent graph")
        return

    intents = graph.get("intents", {})
    store = _compiled_store()
    compiled_count = 0

    for fp, intent in intents.items():
        # Skip already compiled
        if fp in store:
            continue

        successes = intent.get("successes", 0)
        failures = intent.get("failures", 0)
        total = successes + failures

        if total < COMPILE_THRESHOLD:
            continue

        rate = successes / max(total, 1)
        if rate < COMPILE_MIN_RATE:
            continue

        # Find the canonical diff for this intent
        edges = [e for e in graph.get("edges", [])
                 if e.get("intent_fp") == fp and e.get("merged")]
        if not edges:
            continue

        latest = max(edges, key=lambda e: e.get("timestamp", 0))
        change = graph.get("changes", {}).get(latest.get("change_key", ""), {})
        diff_text = change.get("diff_text", "")
        files = change.get("files", [])

        if not diff_text:
            continue

        compile_intent(fp, intent, diff_text, files)
        compiled_count += 1

    existing = len(store)
    total_executions = sum(e.get("executions", 0) for e in store.values())
    print(f"[intent-compiler] {existing + compiled_count} compiled intents "
          f"({compiled_count} new), {total_executions} total executions")
