#!/usr/bin/env python3
"""
planner.py - plan-then-fan-out. Turns ONE giant master prompt into a DAG of small,
scoped tasks with dependencies, so the orchestrator runs independent work in
parallel and avoids the 150k-650k-token compaction spirals you were hitting.

    python3 app/planner.py "Build the non-custodial settlement engine: ...long prompt..." > tasks.yaml

How: asks a model to decompose the prompt into JSON tasks, each with an explicit
file scope and acceptance test, plus `deps` (slugs that must finish first).
Independent tasks share no files -> safe to run concurrently. Dependent tasks are
ordered. Falls back to a single task if planning fails. Mockable via CLAUDE_BIN.
"""
import os, sys, json, subprocess, re
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import claude_cli

PLAN_MODEL = os.environ.get("PLAN_MODEL", "claude-opus-4-8")

META = """You are a build planner. Decompose the REQUEST below into the smallest set of
independently-shippable tasks. Output ONLY a JSON array. Each item:
{"slug":"kebab-case","prompt":"a SELF-CONTAINED instruction incl. an explicit file
scope and an acceptance test to run","deps":["slugs that must complete first"],
"model_hint":"haiku|sonnet|opus"}
Rules: tasks that touch DIFFERENT files must NOT list each other in deps (so they run
in parallel). Tasks editing the SAME files MUST be chained via deps to prevent merge
conflicts. Keep each prompt small enough to avoid context compaction.
MAXIMIZE PARALLELISM / MINIMIZE DEPTH: produce a WIDE, SHALLOW graph. After the single
"contracts" task, put as many INDEPENDENT sibling tasks as possible at depth 1 (deps just
["contracts"]) so the fleet runs them all at once. Do NOT create long chains A->B->C->D unless
each step genuinely edits the previous step's files; a task should depend ONLY on the minimal set
it truly needs (never add a dep "just to be safe" — that serializes the graph and starves
throughput). Target max dependency depth <= 2 beyond contracts.
CONTRACT-FIRST (required): the FIRST task MUST have slug "contracts" and deps []; it
defines the shared interfaces/types/API signatures/DB schema that the others build
against (and ONLY those - no implementation). EVERY other task MUST list "contracts"
in its deps. This lets parallel branches agree on boundaries up front so they cannot
structurally conflict at merge time.
REQUEST:
"""


def plan(master: str, repo: str = None) -> list:
    spec = ""
    if repo:
        spec_path = os.path.join(repo, "SPEC.md")
        if os.path.isfile(spec_path):
            with open(spec_path) as f:
                spec_content = f.read()[:12000]
            spec = f"\n\n# Project Specification (SPEC.md — every task MUST satisfy these invariants):\n{spec_content}\n\n"
        # OUTCOME-WEIGHTED PLANNING: fold in what ACTUALLY merged before (conventions distilled by
        # learn_from_merges into CLAUDE.md) so the decomposition mirrors past first-pass successes.
        cmd_path = os.path.join(repo, "CLAUDE.md")
        if os.path.isfile(cmd_path):
            try:
                txt = open(cmd_path).read()
                marker = "## Learned from merged work"
                if marker in txt:
                    lesson = txt[txt.index(marker):][:3000]
                    spec += (f"\n\n# What has merged cleanly here before (bias the plan toward these "
                             f"patterns to maximize first-pass merge rate):\n{lesson}\n\n")
            except Exception:
                pass
    try:
        r = claude_cli.run(META + spec + master, PLAN_MODEL,
                           timeout=int(os.environ.get("PLAN_TIMEOUT", "300")))
        m = re.search(r"\[.*\]", r["text"], re.S)
        tasks = json.loads(m.group(0)) if m else []
        assert isinstance(tasks, list) and tasks
    except Exception as e:
        sys.stderr.write(f"[planner] decomposition failed ({e}); using single task\n")
        tasks = [{"slug": "master-task", "prompt": master, "deps": [], "model_hint": "opus"}]
    return tasks


def to_yaml(tasks: list) -> str:
    # dependency-ordered for readability (orchestrator/adaptive_run honors deps separately)
    hint = {"haiku": "claude-haiku-4-5-20251001", "sonnet": "claude-sonnet-4-6", "opus": "claude-opus-4-8"}
    lines = ["# generated by planner.py - review before running\n"]
    for t in tasks:
        lines.append(f"- slug: {t['slug']}")
        lines.append("  base: main")
        if t.get("model_hint"):
            lines.append(f"  model: {hint.get(t['model_hint'], t['model_hint'])}")
        if t.get("deps"):
            lines.append("  deps: [" + ", ".join(t["deps"]) + "]")
        prompt = t["prompt"].replace("\n", "\n    ")
        lines.append("  prompt: |\n    " + prompt)
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("prompt", nargs="?", default="-")
    ap.add_argument("--repo", default=None, help="repo path to read SPEC.md from")
    args = ap.parse_args()
    master = sys.stdin.read() if args.prompt == "-" else args.prompt
    if not master:
        sys.exit("usage: planner.py \"<master prompt>\"  (or - to read stdin)")
    print(to_yaml(plan(master, repo=args.repo)))
