-- Privacy-safe capability sharing, verified-reuse rebates, and bounded autonomous improvement.
create table if not exists public.hivemind_sharing_policies (organization_id uuid primary key references public.orchestrator_organizations(id) on delete cascade, mode text not null default 'network_safe_required' check(mode='network_safe_required'), shared_categories text[] not null default array['capability_patterns','aggregate_benchmarks','verified_outcomes'], prohibited_fields text[] not null default array['source_code','repository','customer_identity','raw_dataset','credentials','secrets','private_prompts','contract_text'], rebate_mode text not null default 'usage_rebate' check(rebate_mode in('usage_rebate','subscription_credit')), updated_at timestamptz not null default now());
create table if not exists public.hivemind_capability_contributions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.orchestrator_organizations(id) on delete cascade, title text not null, problem_class text not null, pattern_summary text not null, prerequisites jsonb not null default '[]', aggregate_outcomes jsonb not null default '{}', verification jsonb not null default '{}', content_digest text not null unique, status text not null default 'candidate' check(status in('candidate','verified','available','paused','withdrawn')), reuse_count int not null default 0 check(reuse_count>=0), verified_value_cents bigint not null default 0 check(verified_value_cents>=0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.hivemind_capability_adoptions (id uuid primary key default gen_random_uuid(), contribution_id uuid not null references public.hivemind_capability_contributions(id) on delete cascade, adopter_organization_id uuid not null references public.orchestrator_organizations(id) on delete cascade, status text not null default 'canary' check(status in('canary','verified','rolled_back','retired')), realized_value_cents bigint not null default 0 check(realized_value_cents>=0), verification jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(contribution_id,adopter_organization_id));
create table if not exists public.hivemind_rebate_ledger (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.orchestrator_organizations(id) on delete cascade, contribution_id uuid references public.hivemind_capability_contributions(id) on delete set null, adoption_id uuid references public.hivemind_capability_adoptions(id) on delete set null, event_type text not null check(event_type in('verified_reuse','quality_bonus','reversal','settlement')), amount_cents bigint not null, credit_mode text not null check(credit_mode in('usage_rebate','subscription_credit')), status text not null default 'accrued' check(status in('accrued','available','settled','reversed')), metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.hivemind_improvement_policies (organization_id uuid primary key references public.orchestrator_organizations(id) on delete cascade, non_material_mode text not null default 'auto_canary' check(non_material_mode in('off','approval','auto_canary')), material_mode text not null default 'off' check(material_mode in('off','approval','auto_canary')), materiality_threshold int not null default 50 check(materiality_threshold between 1 and 100), required_qa jsonb not null default '{"unit":true,"integration":true,"journey":true,"security":true,"rollback":true,"independent":true}', max_canary_percent int not null default 5 check(max_canary_percent between 1 and 25), share_verified_improvements boolean not null default true, updated_at timestamptz not null default now());
create table if not exists public.hivemind_improvement_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.orchestrator_organizations(id) on delete cascade, project_id uuid references public.projects(id) on delete set null, title text not null, objective text not null, materiality_score int not null check(materiality_score between 0 and 100), materiality_factors jsonb not null default '{}', execution_policy jsonb not null default '{}', qa_evidence jsonb not null default '{}', task_id uuid references public.tasks(id) on delete set null, status text not null default 'proposed' check(status in('proposed','approval_required','queued','canary','verified','rolled_back','rejected')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_hivemind_contributions_market on public.hivemind_capability_contributions(status,created_at desc);create index if not exists idx_hivemind_rebates_org_time on public.hivemind_rebate_ledger(organization_id,created_at desc);create index if not exists idx_hivemind_runs_org_time on public.hivemind_improvement_runs(organization_id,created_at desc);
create unique index if not exists idx_hivemind_one_verified_reuse_rebate on public.hivemind_rebate_ledger(adoption_id) where event_type='verified_reuse';
alter table public.hivemind_sharing_policies enable row level security;alter table public.hivemind_capability_contributions enable row level security;alter table public.hivemind_capability_adoptions enable row level security;alter table public.hivemind_rebate_ledger enable row level security;alter table public.hivemind_improvement_policies enable row level security;alter table public.hivemind_improvement_runs enable row level security;
comment on table public.hivemind_capability_contributions is 'Sanitized manifests only; prohibited proprietary artifacts never enter this table.';comment on table public.hivemind_rebate_ledger is 'Auditable credits; billing settlement is a separate controlled operation.';
