-- Proof-carrying control plane for workforce, legal, finance/tax, creative, and operations.
create table if not exists business_action_runs (id uuid primary key default gen_random_uuid(),organization_id uuid not null references orchestrator_organizations(id) on delete cascade,domain text not null check(domain in('workforce','finance','creative','operations')),action text not null,objective text not null,risk text not null check(risk in('low','medium','high')),state text not null check(state in('planned','approval_required','approved','running','completed','blocked','cancelled')),input jsonb not null default '{}',plan jsonb not null default '{}',outcome jsonb,evidence_digest text not null,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists workforce_lifecycle_cases (id uuid primary key default gen_random_uuid(),organization_id uuid not null references orchestrator_organizations(id) on delete cascade,action_run_id uuid references business_action_runs(id) on delete set null,employee_name text not null,employee_email text not null,role_title text not null,jurisdiction text not null,start_date date,status text not null default 'preboarding' check(status in('preboarding','onboarding','active','transitioning','completed','cancelled')),checklist jsonb not null default '[]',consent_policy jsonb not null default '{}',capacity_policy jsonb not null default '{}',created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists governed_business_documents (id uuid primary key default gen_random_uuid(),organization_id uuid not null references orchestrator_organizations(id) on delete cascade,action_run_id uuid references business_action_runs(id) on delete set null,workforce_case_id uuid references workforce_lifecycle_cases(id) on delete set null,document_type text not null check(document_type in('nda','offer','employment','contractor','policy','tax','other')),title text not null,counterparty_name text,counterparty_email text,jurisdiction text,status text not null default 'draft' check(status in('draft','legal_review','approval_required','approved','issued','signed','declined','superseded')),terms jsonb not null default '{}',approval_evidence jsonb not null default '{}',signature_evidence jsonb not null default '{}',created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists business_financial_events (id uuid primary key default gen_random_uuid(),organization_id uuid not null references orchestrator_organizations(id) on delete cascade,external_key text,direction text not null check(direction in('inflow','outflow')),event_type text not null check(event_type in('income','expense','invoice','payment','refund','tax','payroll','transfer')),amount numeric(18,2) not null check(amount>=0),currency text not null default 'USD',category text,occurred_at timestamptz not null,status text not null default 'normalized' check(status in('pending','normalized','attention','approved','settled','void')),counterparty text,business_line text,tax_treatment jsonb not null default '{}',evidence jsonb not null default '{}',source jsonb not null default '{}',created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,external_key));
create table if not exists business_opportunities (id uuid primary key default gen_random_uuid(),organization_id uuid not null references orchestrator_organizations(id) on delete cascade,action_run_id uuid references business_action_runs(id) on delete set null,domain text not null,title text not null,summary text not null,confidence numeric not null default 0 check(confidence between 0 and 1),expected_value_usd numeric(18,2) not null default 0,state text not null default 'discovered' check(state in('discovered','evidence_required','review','approved','executing','realized','rejected','expired')),evidence jsonb not null default '{}',created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists creative_production_jobs (id uuid primary key default gen_random_uuid(),organization_id uuid not null references orchestrator_organizations(id) on delete cascade,action_run_id uuid references business_action_runs(id) on delete set null,capability text not null check(capability in('motion','image','3d')),brief text not null,selected_provider text,provider_candidates text[] not null default '{}',controls jsonb not null default '{}',status text not null default 'draft' check(status in('draft','connector_required','ready','generating','review','approved','published','failed','cancelled')),outputs jsonb not null default '[]',provenance jsonb not null default '{}',created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists business_action_runs_org_state_idx on business_action_runs(organization_id,state,created_at desc); create index if not exists workforce_lifecycle_org_status_idx on workforce_lifecycle_cases(organization_id,status,created_at desc); create index if not exists governed_documents_org_status_idx on governed_business_documents(organization_id,status,created_at desc); create index if not exists financial_events_org_time_idx on business_financial_events(organization_id,occurred_at desc); create index if not exists opportunities_org_value_idx on business_opportunities(organization_id,expected_value_usd desc); create index if not exists creative_jobs_org_status_idx on creative_production_jobs(organization_id,status,created_at desc);
alter table business_action_runs enable row level security; alter table workforce_lifecycle_cases enable row level security; alter table governed_business_documents enable row level security; alter table business_financial_events enable row level security; alter table business_opportunities enable row level security; alter table creative_production_jobs enable row level security;
create or replace function create_governed_employee_onboarding(p_run_id uuid,p_organization_id uuid,p_created_by uuid,p_employee_name text,p_employee_email text,p_role_title text,p_jurisdiction text,p_start_date date default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare v_case workforce_lifecycle_cases; v_document governed_business_documents;
begin
 if not exists(select 1 from business_action_runs where id=p_run_id and organization_id=p_organization_id and action='employee_onboarding') then raise exception 'onboarding_action_run_required'; end if;
 insert into workforce_lifecycle_cases(organization_id,action_run_id,employee_name,employee_email,role_title,jurisdiction,start_date,checklist,consent_policy,capacity_policy,created_by) values(p_organization_id,p_run_id,p_employee_name,p_employee_email,p_role_title,p_jurisdiction,p_start_date,jsonb_build_array(jsonb_build_object('step','identity_and_right-to-work','state','evidence_required'),jsonb_build_object('step','offer_and_nda','state','legal_review'),jsonb_build_object('step','least-privilege_access','state','planned'),jsonb_build_object('step','role-specific_enablement','state','planned'),jsonb_build_object('step','30-60-90_outcomes','state','planned'),jsonb_build_object('step','benefits_and_accommodations','state','employee_controlled')),'{"employee_controlled":true,"minimum_cohort":5,"individual_health_scoring":false,"protected_trait_inference":false}'::jsonb,'{"signals":["declared_capacity","workload_distribution","meeting_load","recovery_time"],"private_content_collection":false,"manager_view":"cohort_and_work_design_only"}'::jsonb,p_created_by) returning * into v_case;
 insert into governed_business_documents(organization_id,action_run_id,workforce_case_id,document_type,title,counterparty_name,counterparty_email,jurisdiction,status,terms,created_by) values(p_organization_id,p_run_id,v_case.id,'nda','Employment NDA — '||p_employee_name,p_employee_name,p_employee_email,p_jurisdiction,'legal_review',jsonb_build_object('template','approved_employment_nda_v1','purpose','employment onboarding','cross_populated',true,'no_automatic_issuance',true),p_created_by) returning * into v_document;
 return jsonb_build_object('workforce_case',to_jsonb(v_case),'nda_draft',to_jsonb(v_document));
end $$;
revoke all on function create_governed_employee_onboarding(uuid,uuid,uuid,text,text,text,text,date) from public; grant execute on function create_governed_employee_onboarding(uuid,uuid,uuid,text,text,text,text,date) to service_role;
comment on table workforce_lifecycle_cases is 'Consent-first workforce coordination; individual health scoring and protected-trait inference are prohibited.';
