-- Recipes are high-level hints for the Claude-in-Chrome browser worker (it reads the page and acts,
-- so it needs intent + URLs + login signals, not brittle CSS selectors). Idempotent upserts.
insert into public.growth_browser_recipe(platform, action, url_template, steps, login_check) values
 ('linkedin_personal','post','https://www.linkedin.com/feed/',
   '[{"do":"click","hint":"Start a post button"},{"do":"type","hint":"post editor textbox","text":"{{body}}"},{"do":"click","hint":"Post button to publish"}]'::jsonb,
   '{"url":"https://www.linkedin.com/feed/","logged_in_hint":"Start a post","logged_out_hint":"Sign in"}'::jsonb),
 ('linkedin_personal','comment','{{target_ref}}',
   '[{"do":"click","hint":"Comment on the target post"},{"do":"type","hint":"comment box","text":"{{text}}"},{"do":"click","hint":"Post comment"}]'::jsonb,
   '{"logged_in_hint":"Start a post"}'::jsonb),
 ('linkedin_personal','like','{{target_ref}}',
   '[{"do":"click","hint":"Like/react button on the target post"}]'::jsonb, '{}'::jsonb),
 ('linkedin_personal','connect','{{target_ref}}',
   '[{"do":"click","hint":"Connect button on the profile"},{"do":"click","hint":"Add a note (optional)"},{"do":"type","hint":"note field","text":"{{text}}"},{"do":"click","hint":"Send invitation"}]'::jsonb,
   '{"logged_in_hint":"My Network"}'::jsonb),
 ('linkedin_personal','follow','{{target_ref}}','[{"do":"click","hint":"Follow button"}]'::jsonb,'{}'::jsonb),
 ('linkedin_company','post','https://www.linkedin.com/company/{{handle}}/admin/',
   '[{"do":"click","hint":"Start a post as the organization"},{"do":"type","hint":"editor","text":"{{body}}"},{"do":"click","hint":"Post"}]'::jsonb,
   '{"logged_in_hint":"Admin view"}'::jsonb),
 ('x','post','https://x.com/compose/post',
   '[{"do":"type","hint":"tweet compose box","text":"{{body}}"},{"do":"click","hint":"Post button"}]'::jsonb,
   '{"url":"https://x.com/home","logged_in_hint":"Post","logged_out_hint":"Sign in"}'::jsonb),
 ('x','thread','https://x.com/compose/post',
   '[{"do":"type","hint":"compose box first tweet","text":"{{body}}"},{"do":"note","hint":"use + to add each subsequent thread part, then Post all"}]'::jsonb,
   '{"logged_in_hint":"Post"}'::jsonb),
 ('x','like','{{target_ref}}','[{"do":"click","hint":"Like heart on the tweet"}]'::jsonb,'{}'::jsonb),
 ('x','comment','{{target_ref}}','[{"do":"click","hint":"Reply"},{"do":"type","hint":"reply box","text":"{{text}}"},{"do":"click","hint":"Reply button"}]'::jsonb,'{}'::jsonb),
 ('x','follow','{{target_ref}}','[{"do":"click","hint":"Follow button on the profile"}]'::jsonb,'{}'::jsonb),
 ('instagram','post','https://www.instagram.com/',
   '[{"do":"click","hint":"New post (+) button"},{"do":"note","hint":"select media, then caption"},{"do":"type","hint":"caption","text":"{{body}}"},{"do":"click","hint":"Share"}]'::jsonb,
   '{"url":"https://www.instagram.com/","logged_in_hint":"Home","logged_out_hint":"Log in"}'::jsonb),
 ('facebook','post','https://www.facebook.com/',
   '[{"do":"click","hint":"What''s on your mind box"},{"do":"type","hint":"post box","text":"{{body}}"},{"do":"click","hint":"Post"}]'::jsonb,
   '{"logged_in_hint":"What''s on your mind","logged_out_hint":"Log in"}'::jsonb),
 ('threads','post','https://www.threads.net/',
   '[{"do":"click","hint":"Start a thread / compose"},{"do":"type","hint":"compose box","text":"{{body}}"},{"do":"click","hint":"Post"}]'::jsonb,
   '{"logged_in_hint":"For you","logged_out_hint":"Log in"}'::jsonb),
 ('youtube','post','https://www.youtube.com/',
   '[{"do":"note","hint":"community post or Shorts upload; drafts prepared, human confirms upload"}]'::jsonb,
   '{"logged_in_hint":"Create","logged_out_hint":"Sign in"}'::jsonb),
 ('tiktok','post','https://www.tiktok.com/upload',
   '[{"do":"note","hint":"upload page; media + caption; human confirms"},{"do":"type","hint":"caption","text":"{{body}}"}]'::jsonb,
   '{"logged_in_hint":"Upload","logged_out_hint":"Log in"}'::jsonb),
 ('reddit','post','https://www.reddit.com/submit',
   '[{"do":"type","hint":"community/subreddit","text":"{{subreddit}}"},{"do":"type","hint":"title","text":"{{title}}"},{"do":"type","hint":"body","text":"{{body}}"},{"do":"click","hint":"Post"}]'::jsonb,
   '{"logged_in_hint":"Create Post","logged_out_hint":"Log In"}'::jsonb),
 ('reddit','comment','{{target_ref}}','[{"do":"click","hint":"Reply"},{"do":"type","hint":"comment box","text":"{{text}}"},{"do":"click","hint":"Comment"}]'::jsonb,'{}'::jsonb),
 ('medium','article','https://medium.com/new-story',
   '[{"do":"type","hint":"title field","text":"{{title}}"},{"do":"type","hint":"body","text":"{{body}}"},{"do":"click","hint":"Publish"},{"do":"click","hint":"Publish now"}]'::jsonb,
   '{"logged_in_hint":"Write","logged_out_hint":"Sign in"}'::jsonb),
 ('substack','newsletter','{{handle}}/publish/post',
   '[{"do":"type","hint":"title","text":"{{title}}"},{"do":"type","hint":"body","text":"{{body}}"},{"do":"note","hint":"Continue → Send/Publish; human confirms send to list"}]'::jsonb,
   '{"logged_in_hint":"New post","logged_out_hint":"Sign in"}'::jsonb)
on conflict (platform, action) do update set url_template=excluded.url_template, steps=excluded.steps, login_check=excluded.login_check, updated_at=now();;
