export type ConnectorKind = 'model-provider' | 'saas-oauth' | 'remote-mcp' | 'internal'
export type ConnectorAuth = 'api-key' | 'oauth2-pkce' | 'mcp-oauth' | 'service-account' | 'none'

export interface ConnectorDefinition {
  id: string
  name: string
  category: string
  kind: ConnectorKind
  auth: ConnectorAuth
  icon: string
  summary: string
  capabilities: string[]
  defaultScopes: string[]
  risk: 'low' | 'medium' | 'high'
  tokenAudience?: string
  supportsIncrementalConsent?: boolean
  documentationUrl?: string
  recommended?: boolean
  tier?: 'core' | 'specialist'
  workflow?: string
}

export const CONNECTORS: ConnectorDefinition[] = [
  { id: 'openai', name: 'OpenAI API', category: 'Models', kind: 'model-provider', auth: 'api-key', icon: '◎', summary: 'Models, Responses, Realtime, built-in tools, service connectors, and remote MCP.', capabilities: ['models', 'responses', 'realtime', 'tools', 'remote-mcp', 'image-generation'], defaultScopes: ['model:invoke'], risk: 'high', tokenAudience: 'api.openai.com', documentationUrl: 'https://platform.openai.com/docs/api-reference/introduction', recommended: true, tier: 'core', workflow: 'Reasoning, image generation, multimodal review, and agent execution' },
  { id: 'anthropic', name: 'Anthropic API', category: 'Models', kind: 'model-provider', auth: 'api-key', icon: 'A', summary: 'Claude models, tool use, prompt caching, and remote MCP connector access.', capabilities: ['models', 'messages', 'tools', 'remote-mcp', 'creative-review'], defaultScopes: ['model:invoke'], risk: 'high', tokenAudience: 'api.anthropic.com', documentationUrl: 'https://docs.anthropic.com/', recommended: true, tier: 'core', workflow: 'Long-context strategy, critique, implementation, and governed tool use' },
  { id: 'google-ai', name: 'Google Gemini API', category: 'Models', kind: 'model-provider', auth: 'api-key', icon: 'G', summary: 'Gemini multimodal reasoning and media-capable model routes for independent generation and review.', capabilities: ['models', 'multimodal', 'creative-review', 'image-generation', 'video-generation'], defaultScopes: ['model:invoke'], risk: 'high', tokenAudience: 'generativelanguage.googleapis.com', documentationUrl: 'https://ai.google.dev/gemini-api/docs', recommended: true, tier: 'core', workflow: 'Independent multimodal generation, critique, and model tournaments' },
  { id: 'figma', name: 'Figma', category: 'Design & prototyping', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: 'F', summary: 'Design files, components, variables, comments, Dev Mode resources, exports, and governed design-system context.', capabilities: ['design-files', 'ui-design', 'components', 'design-systems', 'prototypes', 'comments', 'exports'], defaultScopes: ['current_user:read', 'file_content:read', 'file_comments:read', 'file_dev_resources:read'], risk: 'medium', supportsIncrementalConsent: true, tokenAudience: 'api.figma.com', documentationUrl: 'https://developers.figma.com/docs/rest-api/', recommended: true, tier: 'core', workflow: 'Product design, prototyping, design systems, and developer handoff' },
  { id: 'adobe-firefly', name: 'Adobe Firefly & Creative Cloud APIs', category: 'Image & vector', kind: 'model-provider', auth: 'api-key', icon: 'A', summary: 'Firefly, Photoshop, Illustrator, Express, Lightroom, InDesign, Substance 3D, generative fill, video, and scaled creative production.', capabilities: ['image-generation', 'video-generation', 'generative-fill', 'image-expand', 'upscale', 'graphic-design', 'creative-production', 'vector-generation', '3d-generation'], defaultScopes: ['creative:generate'], risk: 'high', tokenAudience: 'firefly-api.adobe.io', documentationUrl: 'https://developer.adobe.com/firefly-services/docs/', recommended: true, tier: 'core', workflow: 'Commercial creative generation and Creative Cloud production automation' },
  { id: 'replicate', name: 'Replicate', category: 'Generative infrastructure', kind: 'model-provider', auth: 'api-key', icon: 'R', summary: 'Broad hosted model catalog for image, video, audio, restoration, vectorization, and specialist creative workflows.', capabilities: ['image-generation', 'video-generation', 'image-editing', 'upscale', 'restoration', 'vectorization'], defaultScopes: ['model:invoke'], risk: 'high', tokenAudience: 'api.replicate.com', documentationUrl: 'https://replicate.com/docs', recommended: true, tier: 'specialist', workflow: 'Long-tail models, experiments, restoration, and specialist transformations' },
  { id: 'fal', name: 'fal', category: 'Generative infrastructure', kind: 'model-provider', auth: 'api-key', icon: 'ƒ', summary: 'Low-latency generative media inference for images, video, editing, enhancement, and production pipelines.', capabilities: ['image-generation', 'video-generation', 'image-editing', 'upscale', 'creative-production'], defaultScopes: ['model:invoke'], risk: 'high', tokenAudience: 'fal.run', documentationUrl: 'https://docs.fal.ai/', recommended: true, tier: 'core', workflow: 'Fast media inference, model breadth, and scalable creative pipelines' },
  { id: 'runway', name: 'Runway', category: 'Motion, audio & video', kind: 'model-provider', auth: 'api-key', icon: 'R', summary: 'Generative video, image-to-video, motion exploration, and cinematic creative iteration.', capabilities: ['video-generation', 'image-to-video', 'motion-design', 'creative-production'], defaultScopes: ['media:generate'], risk: 'high', tokenAudience: 'api.dev.runwayml.com', documentationUrl: 'https://docs.dev.runwayml.com/', recommended: true, tier: 'core', workflow: 'Generative video, cinematic motion, and image-to-video production' },
  { id: 'stability', name: 'Stability AI', category: 'Image & vector', kind: 'model-provider', auth: 'api-key', icon: 'S', summary: 'Image generation, edit, control, upscale, remove-background, and structured creative transformations.', capabilities: ['image-generation', 'image-editing', 'upscale', 'remove-background', 'graphic-design'], defaultScopes: ['model:invoke'], risk: 'high', tokenAudience: 'api.stability.ai', documentationUrl: 'https://platform.stability.ai/docs/api-reference', recommended: true, tier: 'specialist', workflow: 'Controlled image transformations, background removal, and enhancement' },
  { id: 'canva', name: 'Canva', category: 'Design & prototyping', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: 'C', summary: 'Designs, assets, folders, brand templates, autofill, resize, comments, imports, and exports through Canva Connect APIs.', capabilities: ['graphic-design', 'templates', 'brand-kits', 'assets', 'comments', 'design-imports', 'exports'], defaultScopes: ['asset:read', 'asset:write', 'design:meta:read', 'design:content:read', 'design:content:write', 'folder:read', 'folder:write'], risk: 'medium', supportsIncrementalConsent: true, tokenAudience: 'api.canva.com', documentationUrl: 'https://www.canva.dev/docs/connect/', recommended: true, tier: 'core', workflow: 'Template-driven campaign production and brand-safe derivatives' },
  { id: 'miro', name: 'Miro', category: 'Design & prototyping', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: 'M', summary: 'Boards, diagrams, workshops, research synthesis, journey maps, and collaborative planning artifacts.', capabilities: ['whiteboards', 'journey-maps', 'diagrams', 'research-synthesis', 'workshops', 'prototypes'], defaultScopes: ['boards:read', 'boards:write'], risk: 'medium', supportsIncrementalConsent: true, tokenAudience: 'api.miro.com', documentationUrl: 'https://developers.miro.com/docs/miro-rest-api-introduction', recommended: true, tier: 'core', workflow: 'Discovery, journey mapping, workshops, and collaborative concept development' },
  { id: 'framer', name: 'Framer', category: 'Web production', kind: 'saas-oauth', auth: 'api-key', icon: 'Fr', summary: 'Server-side project updates, CMS synchronization, preview publishing, and production deployment for Framer sites.', capabilities: ['web-design', 'prototypes', 'cms', 'preview-deploy', 'site-publish'], defaultScopes: ['project:write', 'deploy:write'], risk: 'high', tokenAudience: 'framer.com', documentationUrl: 'https://www.framer.com/developers/server-api-introduction', recommended: true, tier: 'core', workflow: 'High-fidelity websites, interactive prototypes, and publishing' },
  { id: 'webflow', name: 'Webflow', category: 'Web production', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: 'W', summary: 'Sites, pages, components, CMS, assets, custom code, comments, localization, analytics, and publishing.', capabilities: ['web-design', 'cms', 'components', 'assets', 'localization', 'site-publish', 'analytics'], defaultScopes: ['sites:read', 'sites:write', 'pages:read', 'pages:write', 'cms:read', 'cms:write', 'assets:read', 'assets:write'], risk: 'high', supportsIncrementalConsent: true, tokenAudience: 'api.webflow.com', documentationUrl: 'https://developers.webflow.com/data/reference/', recommended: true, tier: 'core', workflow: 'Production websites, CMS operations, localization, and publishing' },
  { id: 'recraft', name: 'Recraft', category: 'Image & vector', kind: 'model-provider', auth: 'api-key', icon: 'Rc', summary: 'Production image and vector generation, typography, consistent styles, inpainting, outpainting, and background removal.', capabilities: ['image-generation', 'vector-generation', 'graphic-design', 'image-editing', 'icons', 'illustration'], defaultScopes: ['media:generate'], risk: 'high', tokenAudience: 'external.api.recraft.ai', documentationUrl: 'https://www.recraft.ai/docs/api-reference/endpoints', recommended: true, tier: 'core', workflow: 'Vectors, icons, illustration systems, typography, and production graphics' },
  { id: 'bfl', name: 'Black Forest Labs FLUX', category: 'Image & vector', kind: 'model-provider', auth: 'api-key', icon: 'BF', summary: 'FLUX image generation and editing with multi-reference control, typography, precise color, and photorealistic output.', capabilities: ['image-generation', 'image-editing', 'multi-reference', 'typography', 'photorealism'], defaultScopes: ['media:generate'], risk: 'high', tokenAudience: 'api.bfl.ai', documentationUrl: 'https://docs.bfl.ai/', recommended: true, tier: 'core', workflow: 'High-control image generation, editing, and photorealistic campaign work' },
  { id: 'ideogram', name: 'Ideogram', category: 'Image & vector', kind: 'model-provider', auth: 'api-key', icon: 'I', summary: 'Image generation and editing with strong composition and text rendering for campaign and concept work.', capabilities: ['image-generation', 'image-editing', 'typography', 'graphic-design'], defaultScopes: ['media:generate'], risk: 'high', tokenAudience: 'api.ideogram.ai', documentationUrl: 'https://developer.ideogram.ai/', recommended: true, tier: 'specialist', workflow: 'Typography-heavy campaign concepts, posters, and compositions' },
  { id: 'elevenlabs', name: 'ElevenLabs', category: 'Motion, audio & video', kind: 'model-provider', auth: 'api-key', icon: '11', summary: 'Voice, sound effects, music, dubbing, transcription, and conversational audio for motion and product experiences.', capabilities: ['voice-generation', 'sound-design', 'music-generation', 'dubbing', 'transcription', 'audio-production'], defaultScopes: ['audio:generate'], risk: 'high', tokenAudience: 'api.elevenlabs.io', documentationUrl: 'https://elevenlabs.io/docs/api-reference', recommended: true, tier: 'core', workflow: 'Voiceover, sound design, localization, and conversational experiences' },
  { id: 'heygen', name: 'HeyGen', category: 'Motion, audio & video', kind: 'model-provider', auth: 'api-key', icon: 'H', summary: 'Avatar video, translation, personalized video, templates, and production automation.', capabilities: ['video-generation', 'avatar-video', 'video-translation', 'personalization', 'creative-production'], defaultScopes: ['video:generate'], risk: 'high', tokenAudience: 'api.heygen.com', documentationUrl: 'https://docs.heygen.com/reference', recommended: true, tier: 'specialist', workflow: 'Presenter video, localization, training, and personalized video' },
  { id: 'meshy', name: 'Meshy', category: '3D & spatial', kind: 'model-provider', auth: 'api-key', icon: '3D', summary: 'Text/image-to-3D, texturing, remeshing, rigging, animation, and production export, with an optional MCP server.', capabilities: ['3d-generation', 'texturing', 'remeshing', 'animation', 'spatial-design', '3d-export'], defaultScopes: ['3d:generate'], risk: 'high', tokenAudience: 'api.meshy.ai', documentationUrl: 'https://docs.meshy.ai/en/api', recommended: true, tier: 'core', workflow: 'Product visualization, spatial concepts, game assets, and 3D production' },
  { id: 'cloudinary', name: 'Cloudinary', category: 'Assets & delivery', kind: 'saas-oauth', auth: 'api-key', icon: 'Cl', summary: 'Upload, organize, transform, optimize, moderate, and deliver production image and video assets.', capabilities: ['dam', 'asset-management', 'image-transform', 'video-transform', 'optimization', 'delivery'], defaultScopes: ['assets:read', 'assets:write', 'transform:write'], risk: 'high', tokenAudience: 'api.cloudinary.com', documentationUrl: 'https://cloudinary.com/documentation', recommended: true, tier: 'core', workflow: 'Digital asset management, transformations, optimization, and delivery' },
  { id: 'contentful', name: 'Contentful', category: 'Content & publishing', kind: 'saas-oauth', auth: 'api-key', icon: 'Ct', summary: 'Structured content, assets, localization, previews, releases, and omnichannel publishing through the Content Management API.', capabilities: ['cms', 'content-models', 'assets', 'localization', 'preview', 'publishing'], defaultScopes: ['content:read', 'content:write'], risk: 'high', tokenAudience: 'api.contentful.com', documentationUrl: 'https://www.contentful.com/developers/docs/references/content-management-api/', recommended: true, tier: 'core', workflow: 'Structured content, localization, campaigns, and omnichannel publishing' },
  { id: 'sanity', name: 'Sanity', category: 'Content & publishing', kind: 'saas-oauth', auth: 'api-key', icon: 'S', summary: 'Composable content, structured assets, drafts, workflows, live preview, and programmatic publishing.', capabilities: ['cms', 'content-models', 'assets', 'live-preview', 'localization', 'publishing'], defaultScopes: ['content:read', 'content:write'], risk: 'high', tokenAudience: 'api.sanity.io', documentationUrl: 'https://www.sanity.io/docs/content-lake/http-auth', recommended: true, tier: 'specialist', workflow: 'Composable content, editorial workflows, and real-time product experiences' },
  { id: 'unsplash', name: 'Unsplash', category: 'Assets & delivery', kind: 'saas-oauth', auth: 'api-key', icon: 'U', summary: 'Search and retrieve licensed photography with required attribution and usage tracking.', capabilities: ['stock-photography', 'asset-search', 'image-sourcing'], defaultScopes: ['photos:read'], risk: 'medium', tokenAudience: 'api.unsplash.com', documentationUrl: 'https://unsplash.com/documentation', recommended: true, tier: 'specialist', workflow: 'Rights-aware photography search and art-direction sourcing' },
  { id: 'vercel', name: 'Vercel', category: 'Web production', kind: 'saas-oauth', auth: 'api-key', icon: '▲', summary: 'Projects, deployments, preview URLs, domains, environment configuration, and production promotion.', capabilities: ['preview-deploy', 'site-publish', 'domains', 'web-production', 'deployment-status'], defaultScopes: ['deployments:read', 'deployments:write'], risk: 'high', tokenAudience: 'api.vercel.com', documentationUrl: 'https://vercel.com/docs/rest-api', recommended: true, tier: 'core', workflow: 'Preview deployments, production releases, domains, and deployment evidence' },
  { id: 'chromatic', name: 'Chromatic & Storybook', category: 'Production QA', kind: 'saas-oauth', auth: 'api-key', icon: 'Ch', summary: 'Component review, visual regression testing, interaction tests, accessibility checks, and design-system publishing.', capabilities: ['visual-regression', 'component-review', 'storybook', 'accessibility-qa', 'ui-testing'], defaultScopes: ['builds:write'], risk: 'medium', tokenAudience: 'chromatic.com', documentationUrl: 'https://www.chromatic.com/docs/', recommended: true, tier: 'core', workflow: 'Component QA, visual regression, accessibility, and design-system review' },
  { id: 'google', name: 'Google Workspace', category: 'Productivity', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: 'G', summary: 'Drive, Gmail, Calendar, Docs, Sheets, and account-scoped workspace context.', capabilities: ['drive', 'gmail', 'calendar', 'docs', 'sheets'], defaultScopes: ['openid', 'email', 'profile'], risk: 'high', supportsIncrementalConsent: true },
  { id: 'microsoft', name: 'Microsoft 365', category: 'Productivity', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: 'M', summary: 'Outlook, Calendar, Teams, OneDrive, and SharePoint through Microsoft Graph.', capabilities: ['outlook', 'calendar', 'teams', 'onedrive', 'sharepoint'], defaultScopes: ['openid', 'email', 'profile', 'offline_access'], risk: 'high', supportsIncrementalConsent: true },
  { id: 'github', name: 'GitHub', category: 'Engineering', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: '⌘', summary: 'Repositories, issues, pull requests, actions, code context, and governed design-to-code delivery.', capabilities: ['repositories', 'issues', 'pull-requests', 'actions', 'design-to-code'], defaultScopes: ['read:user'], risk: 'medium', supportsIncrementalConsent: true, documentationUrl: 'https://docs.github.com/en/apps/oauth-apps', recommended: true, tier: 'core', workflow: 'Design-to-code handoff, implementation, review, and release automation' },
  { id: 'slack', name: 'Slack', category: 'Communication', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: 'S', summary: 'Channels, search, messages, and governed communication actions.', capabilities: ['channels', 'search', 'messages'], defaultScopes: [], risk: 'high', supportsIncrementalConsent: true },
  { id: 'atlassian', name: 'Atlassian', category: 'Work', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: '△', summary: 'Jira and Confluence work, knowledge, and planning context.', capabilities: ['jira', 'confluence'], defaultScopes: ['read:me'], risk: 'medium', supportsIncrementalConsent: true },
  { id: 'notion', name: 'Notion', category: 'Knowledge', kind: 'saas-oauth', auth: 'oauth2-pkce', icon: 'N', summary: 'Workspace pages, databases, and operating knowledge.', capabilities: ['pages', 'databases', 'search'], defaultScopes: [], risk: 'medium' },
  { id: 'remote-mcp', name: 'Remote MCP server', category: 'Extensibility', kind: 'remote-mcp', auth: 'mcp-oauth', icon: '↔', summary: 'Discover and authorize standards-based remote MCP tools with resource-bound OAuth.', capabilities: ['tools', 'resources', 'prompts'], defaultScopes: [], risk: 'high', supportsIncrementalConsent: true, documentationUrl: 'https://modelcontextprotocol.io/specification/2025-11-25/basic/authorization' },
]

export const CONNECTOR_BY_ID = Object.fromEntries(CONNECTORS.map(connector => [connector.id, connector]))
