export type DesignCapability = {
  id: string
  name: string
  category: 'Product & UI' | 'Brand & graphics' | 'Image & artwork' | 'Motion & video' | 'Web & spatial' | 'Production & QA'
  icon: string
  summary: string
  outputs: string[]
  capability: string
  connectorIds: string[]
  prompt: string
  controls: Array<'format' | 'ratio' | 'variants' | 'brand' | 'duration' | 'fidelity'>
}

export const DESIGN_CAPABILITIES: DesignCapability[] = [
  { id: 'ui-builder', name: 'Product UI builder', category: 'Product & UI', icon: '▦', summary: 'Turn a product outcome into production-ready screens, flows, components, states, and responsive behavior.', outputs: ['Vue/React UI', 'Figma-ready spec', 'Interaction states'], capability: 'ui-design', connectorIds: ['figma', 'miro', 'openai', 'anthropic', 'google-ai'], prompt: 'Design and implement a complete product UI flow with responsive states, accessibility, and reusable components.', controls: ['fidelity', 'brand', 'variants'] },
  { id: 'prototype', name: 'Prototype & flow studio', category: 'Product & UI', icon: '↳', summary: 'Map journeys, generate interaction prototypes, test edge cases, and hand off implementation-ready behavior.', outputs: ['User flow', 'Clickable prototype', 'Edge-case map'], capability: 'prototypes', connectorIds: ['figma', 'miro', 'framer', 'openai', 'anthropic'], prompt: 'Create a decision-ready user flow and interactive prototype for this outcome, including failure and recovery states.', controls: ['fidelity', 'variants', 'brand'] },
  { id: 'design-system', name: 'Design system architect', category: 'Product & UI', icon: '◫', summary: 'Create or repair tokens, primitives, components, variants, documentation, and code-to-design consistency.', outputs: ['Tokens', 'Components', 'Usage guidance'], capability: 'design-systems', connectorIds: ['figma', 'github', 'anthropic'], prompt: 'Audit and evolve the design system, consolidating tokens and components while preserving product behavior.', controls: ['fidelity', 'brand'] },
  { id: 'brand-builder', name: 'Brand identity builder', category: 'Brand & graphics', icon: '✦', summary: 'Develop a coherent identity system spanning positioning, typography, color, art direction, voice, and applications.', outputs: ['Brand system', 'Creative direction', 'Application kit'], capability: 'graphic-design', connectorIds: ['adobe-firefly', 'figma', 'openai'], prompt: 'Create a distinctive, defensible brand identity system and demonstrate it across the most important product and marketing applications.', controls: ['brand', 'variants', 'format'] },
  { id: 'campaign-builder', name: 'Campaign & layout builder', category: 'Brand & graphics', icon: '▤', summary: 'Generate on-brand social, advertising, editorial, presentation, email, and print compositions as a coordinated set.', outputs: ['Campaign system', 'Channel derivatives', 'Editable layouts'], capability: 'graphic-design', connectorIds: ['adobe-firefly', 'canva', 'figma', 'recraft', 'ideogram'], prompt: 'Build a cohesive campaign system with channel-specific layouts, copy hierarchy, and editable production guidance.', controls: ['format', 'ratio', 'variants', 'brand'] },
  { id: 'logo-explorer', name: 'Logo & mark explorer', category: 'Brand & graphics', icon: '◇', summary: 'Explore concepts, evaluate distinctiveness and scalability, and prepare a controlled identity family—not a random logo grid.', outputs: ['Concept territories', 'Mark family', 'Usage tests'], capability: 'vector-generation', connectorIds: ['recraft', 'adobe-firefly', 'openai', 'figma'], prompt: 'Explore strategically distinct logo territories, explain the rationale, and validate each across scale, color, and application contexts.', controls: ['format', 'variants', 'brand'] },
  { id: 'image-studio', name: 'AI image studio', category: 'Image & artwork', icon: '▧', summary: 'Generate, edit, fill, expand, relight, compose, and upscale imagery with model comparison and provenance-aware outputs.', outputs: ['Source artwork', 'Edit variants', 'Upscaled masters'], capability: 'image-generation', connectorIds: ['adobe-firefly', 'openai', 'google-ai', 'recraft', 'bfl', 'ideogram', 'fal', 'replicate', 'stability'], prompt: 'Generate a production-quality visual matching the art direction, compare suitable image models, and deliver editable variants.', controls: ['format', 'ratio', 'variants', 'brand', 'fidelity'] },
  { id: 'derivative-engine', name: 'Derivative artwork engine', category: 'Image & artwork', icon: '⧉', summary: 'Transform an approved master into channel, locale, aspect-ratio, audience, and seasonal variants with visual QA.', outputs: ['Channel variants', 'Localized art', 'QA contact sheet'], capability: 'creative-production', connectorIds: ['adobe-firefly', 'fal', 'replicate', 'canva'], prompt: 'Create a controlled derivative set from the approved master, preserving brand-critical elements and validating every output.', controls: ['format', 'ratio', 'variants', 'brand'] },
  { id: 'illustration', name: 'Illustration system builder', category: 'Image & artwork', icon: '✎', summary: 'Create a repeatable illustration language, character/object grammar, scene recipes, and a coherent starter library.', outputs: ['Style grammar', 'Illustration library', 'Generation recipes'], capability: 'image-generation', connectorIds: ['adobe-firefly', 'openai', 'stability', 'replicate'], prompt: 'Design a repeatable illustration system with a clear visual grammar and generate a coherent starter library.', controls: ['format', 'ratio', 'variants', 'brand'] },
  { id: 'motion-builder', name: 'Motion design builder', category: 'Motion & video', icon: '▶', summary: 'Design product motion, transitions, explainers, title systems, and brand animation with timing and accessibility controls.', outputs: ['Motion spec', 'Keyframes', 'Implementation plan'], capability: 'motion-design', connectorIds: ['runway', 'adobe-firefly', 'fal', 'figma'], prompt: 'Create a motion system that explains state change, respects accessibility, and includes implementation-ready timing and easing.', controls: ['duration', 'ratio', 'variants', 'brand'] },
  { id: 'video-studio', name: 'Generative video studio', category: 'Motion & video', icon: '◉', summary: 'Develop treatments, storyboards, shots, image-to-video sequences, edits, and channel-ready video derivatives.', outputs: ['Treatment', 'Storyboard', 'Generated shots'], capability: 'video-generation', connectorIds: ['runway', 'adobe-firefly', 'fal', 'replicate'], prompt: 'Produce a concise creative treatment and storyboard, then generate the strongest feasible video assets and derivatives.', controls: ['duration', 'ratio', 'variants', 'brand', 'fidelity'] },
  { id: 'audio-studio', name: 'Voice & sound studio', category: 'Motion & video', icon: '♫', summary: 'Create voiceover, sound effects, music beds, dubbing, transcripts, and accessible audio variants for product and campaign experiences.', outputs: ['Voice masters', 'Sound design', 'Localized audio'], capability: 'audio-production', connectorIds: ['elevenlabs', 'adobe-firefly', 'replicate'], prompt: 'Create a rights-aware audio package with voice, sound, timing, localization, and accessibility variants appropriate to the experience.', controls: ['duration', 'variants', 'brand', 'fidelity'] },
  { id: 'web-builder', name: 'Website & landing-page builder', category: 'Web & spatial', icon: '⌁', summary: 'Design, implement, preview, visually verify, and publish responsive sites with structured content and production deployment evidence.', outputs: ['Working site', 'Preview deployment', 'Editable source'], capability: 'web-design', connectorIds: ['framer', 'webflow', 'github', 'vercel', 'figma'], prompt: 'Design and publish a production-ready responsive website with reusable sections, accessible interactions, editable content, analytics readiness, and verified preview evidence.', controls: ['fidelity', 'brand', 'variants'] },
  { id: 'spatial-studio', name: '3D & spatial studio', category: 'Web & spatial', icon: '⬡', summary: 'Generate, texture, remesh, animate, review, and export production-ready 3D assets for product, web, AR, games, and visualization.', outputs: ['3D source asset', 'Material set', 'Runtime exports'], capability: '3d-generation', connectorIds: ['meshy', 'adobe-firefly'], prompt: 'Create a production-ready 3D asset with clean topology, controlled materials, appropriate LODs, provenance, and exports for the selected runtime.', controls: ['format', 'variants', 'brand', 'fidelity'] },
  { id: 'content-pipeline', name: 'Asset & publishing pipeline', category: 'Production & QA', icon: '⇢', summary: 'Source, approve, transform, localize, organize, and publish assets and structured content across channels with rights and release evidence.', outputs: ['Approved asset set', 'CMS entries', 'Delivery manifest'], capability: 'asset-management', connectorIds: ['cloudinary', 'contentful', 'sanity', 'canva', 'unsplash', 'webflow'], prompt: 'Build a governed asset and content pipeline from sourcing through approval, transformation, localization, publishing, attribution, and rollback.', controls: ['format', 'ratio', 'variants', 'brand'] },
  { id: 'a11y-qa', name: 'Accessibility & visual QA', category: 'Production & QA', icon: '✓', summary: 'Audit contrast, hierarchy, focus, keyboard behavior, responsive layouts, component consistency, and screenshot regressions.', outputs: ['Issue map', 'Verified fixes', 'Regression proof'], capability: 'ui-design', connectorIds: ['github', 'figma', 'anthropic'], prompt: 'Audit and repair accessibility and visual-quality issues, then prove the fixes across representative states and breakpoints.', controls: ['fidelity'] },
  { id: 'creative-review', name: 'Multi-model creative review', category: 'Production & QA', icon: '◈', summary: 'Use archetype simulation and model debate to rank concepts against strategy, clarity, distinctiveness, feasibility, and risk.', outputs: ['Ranked concepts', 'Debate evidence', 'Decision brief'], capability: 'models', connectorIds: ['openai', 'anthropic', 'google-ai'], prompt: 'Run an adversarial multi-model creative review and return a ranked, evidence-backed recommendation with dissent preserved.', controls: ['variants', 'fidelity'] },
]

export const DESIGN_CATEGORIES = ['All', 'Product & UI', 'Brand & graphics', 'Image & artwork', 'Motion & video', 'Web & spatial', 'Production & QA'] as const
