export type LegalTemplate = {
  key: string; category: 'employment'|'commercial'|'corporate'|'privacy'|'finance'|'ip'
  name: string; summary: string; fields: string[]; clauses: string[]; risk: 'medium'|'high'
}

export const LEGAL_TEMPLATES: LegalTemplate[] = [
  { key:'employment_agreement',category:'employment',name:'Employment agreement',summary:'Role, compensation, duties, policies, confidentiality, IP, and separation framework.',fields:['party_a','party_b','role','start_date','compensation','jurisdiction'],clauses:['relationship','duties','compensation','benefits','confidentiality','intellectual_property','termination','disputes'],risk:'high' },
  { key:'offer_letter',category:'employment',name:'Offer letter',summary:'Concise employment offer with conditions and linked policy documents.',fields:['party_a','party_b','role','start_date','compensation','jurisdiction'],clauses:['offer','conditions','compensation','benefits','at_will_or_term','confidentiality_reference','acceptance'],risk:'high' },
  { key:'contractor_agreement',category:'employment',name:'Independent contractor agreement',summary:'Services, classification facts, fees, IP, confidentiality, and termination.',fields:['party_a','party_b','services','fees','term','jurisdiction'],clauses:['services','independent_status','fees','expenses','confidentiality','intellectual_property','warranties','termination'],risk:'high' },
  { key:'nda_mutual',category:'commercial',name:'Mutual NDA',summary:'Two-way confidential information exchange with exclusions and permitted use.',fields:['party_a','party_b','purpose','term','jurisdiction'],clauses:['definition','exclusions','use_and_protection','permitted_disclosure','return_or_destruction','term','remedies'],risk:'medium' },
  { key:'nda_one_way',category:'commercial',name:'One-way NDA',summary:'Unilateral confidential information protection for a bounded purpose.',fields:['party_a','party_b','purpose','term','jurisdiction'],clauses:['definition','exclusions','recipient_duties','required_disclosure','return_or_destruction','term'],risk:'medium' },
  { key:'msa',category:'commercial',name:'Master services agreement',summary:'Reusable commercial framework for statements of work and recurring services.',fields:['party_a','party_b','services','fees','term','jurisdiction'],clauses:['services_and_sows','fees_and_taxes','change_control','acceptance','confidentiality','data_security','intellectual_property','warranties','indemnity','liability','term_and_termination','disputes'],risk:'high' },
  { key:'statement_of_work',category:'commercial',name:'Statement of work',summary:'Deliverables, milestones, assumptions, fees, acceptance, and change control.',fields:['party_a','party_b','services','fees','term'],clauses:['scope','deliverables','timeline','dependencies','fees','acceptance','change_control'],risk:'medium' },
  { key:'saas_agreement',category:'commercial',name:'SaaS subscription agreement',summary:'Hosted service access, acceptable use, support, data, security, and subscription terms.',fields:['party_a','party_b','services','fees','term','jurisdiction'],clauses:['subscription','use_restrictions','accounts','fees','service_levels','data','security','confidentiality','intellectual_property','warranties','liability','term_and_termination'],risk:'high' },
  { key:'software_license',category:'ip',name:'Software license agreement',summary:'License grant, restrictions, ownership, support, audit, and termination.',fields:['party_a','party_b','licensed_material','fees','territory','term','jurisdiction'],clauses:['license_grant','restrictions','ownership','delivery','support','fees','audit','warranties','indemnity','liability','termination'],risk:'high' },
  { key:'ip_assignment',category:'ip',name:'IP assignment',summary:'Identified intellectual-property transfer with further-assurances evidence.',fields:['party_a','party_b','licensed_material','consideration','jurisdiction'],clauses:['assigned_rights','consideration','representations','further_assurances','moral_rights','recordation'],risk:'high' },
  { key:'data_processing_addendum',category:'privacy',name:'Data processing addendum',summary:'Processing instructions, security, subprocessors, rights requests, incidents, and transfers.',fields:['party_a','party_b','services','data_categories','jurisdiction'],clauses:['scope_and_roles','instructions','confidentiality','security','subprocessors','rights_requests','incidents','deletion','audits','transfers'],risk:'high' },
  { key:'vendor_agreement',category:'commercial',name:'Vendor / procurement agreement',summary:'Purchasing, delivery, quality, security, insurance, and supplier obligations.',fields:['party_a','party_b','services','fees','term','jurisdiction'],clauses:['orders','delivery','fees_and_taxes','quality','security','compliance','insurance','indemnity','liability','termination'],risk:'high' },
  { key:'partnership_agreement',category:'corporate',name:'Partnership agreement',summary:'Governance, contributions, economics, authority, transfers, deadlock, and dissolution.',fields:['party_a','party_b','purpose','contributions','economics','jurisdiction'],clauses:['formation','purpose','contributions','allocations','governance','authority','books_and_tax','transfers','deadlock','exit','dissolution'],risk:'high' },
  { key:'joint_venture',category:'corporate',name:'Joint venture agreement',summary:'Shared venture scope, governance, funding, IP, economics, deadlock, and exit.',fields:['party_a','party_b','purpose','contributions','economics','jurisdiction'],clauses:['venture_scope','governance','funding','economics','background_ip','venture_ip','confidentiality','deadlock','exit'],risk:'high' },
  { key:'reseller_distribution',category:'commercial',name:'Reseller / distribution agreement',summary:'Territory, channel rights, pricing, brand use, reporting, and termination.',fields:['party_a','party_b','services','territory','fees','term','jurisdiction'],clauses:['appointment','territory','orders','pricing','marketing','brand','compliance','reporting','warranties','termination'],risk:'high' },
  { key:'referral_agreement',category:'commercial',name:'Referral agreement',summary:'Qualified referrals, attribution, fees, conduct rules, and payment evidence.',fields:['party_a','party_b','services','fees','term','jurisdiction'],clauses:['referrals','qualification','fees','payment','conduct','confidentiality','term_and_termination'],risk:'medium' },
  { key:'founders_agreement',category:'corporate',name:'Founders agreement',summary:'Roles, equity intentions, vesting inputs, IP, decisions, departures, and disputes.',fields:['party_a','party_b','purpose','contributions','economics','jurisdiction'],clauses:['roles','equity_intent','vesting_inputs','intellectual_property','decisions','confidentiality','departure','disputes'],risk:'high' },
  { key:'board_consent',category:'corporate',name:'Board written consent',summary:'Structured approval record with recitals, resolutions, authority, and evidence.',fields:['party_a','purpose','effective_date','jurisdiction'],clauses:['recitals','resolutions','authority','ratification','counterparts'],risk:'high' },
  { key:'promissory_note',category:'finance',name:'Promissory note',summary:'Principal, interest, payment, default, security reference, and governing terms.',fields:['party_a','party_b','principal','interest','term','jurisdiction'],clauses:['promise_to_pay','interest','payments','prepayment','default','remedies','governing_law'],risk:'high' },
  { key:'settlement_release',category:'commercial',name:'Settlement and release',summary:'Dispute resolution, payment, releases, non-admission, confidentiality, and enforcement.',fields:['party_a','party_b','purpose','consideration','jurisdiction'],clauses:['recitals','settlement','release','payment','non_admission','confidentiality','enforcement'],risk:'high' },
]

export const LEGAL_TEMPLATE_BY_KEY = Object.fromEntries(LEGAL_TEMPLATES.map(template => [template.key, template]))
